### ISSUE TITLE
Update other resources listed on visit-users admin page

### ISSUE THREAD

**Issue by markcmiller86** [visit-dav/live-customer-response#1]
If you go to visit-users email list [admin page](https://elist.ornl.gov/mailman/listinfo/visit-users), there is a list of other places to go for help.

This list should probably be updated to include new RTD docs and maybe remove some older items. I think only @hankchilds @brugger1 or @dpugmire have permissions to do that.

**Comment by markcmiller86** [comment]
I am mentioning the customer-response team here with @visit-dav/live-customer-response 

Eddie, let me know if you got an email.

**Comment by rusu24edward** [comment]
> I am mentioning the customer-response team here with @visit-dav/live-customer-response
> 
> Eddie, let me know if you got an email.

Yup! I got an email.
