### ISSUE TITLE
Problem building VisIt on mac OS X Catalina.

### ISSUE THREAD

**Issue by brugger1** [visit-dav/live-customer-response#10]
Dear VisIters,

I’m currently trying and building VisIt on my mac OS X Catalina. I’m using the build_visit script as follows :

./build_visit3_1_1 --parallel --openssl  --mesagl --icet --llvm --mpich

However, the script is crashing when building mesagl libraries, complaining that the llvm shared libraries are not found. It seems however that the llvm libraries where correctly build by the script on previous steps.

Attached to this mail is the logfile of my build.

Any idea is welcome !

Thanks a lot,

Sincerely,

Cyril

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by brugger1** [comment]
Hi Cyril,

I believe we've seen this before. I'll do some research and see if I can find the fix.

Eric

**Comment by brugger1** [comment]
Here is the log file.

[build_visit3_1_1_log.txt](https://github.com/visit-dav/live-customer-response/files/4331305/build_visit3_1_1_log.txt)

**Comment by brugger1** [comment]
I couldn't find anything similar in the issue tracker or in the e-mail list. I looked at the log file and I noticed that the script had been run multiple times. I'm assuming something must have gone wrong to cause that. Can you provide more information on that?

Also, can you show me the contents of the directory below?

/Users/cyrilgeorgy/Documents/Informatique/Visit3.1.1/VisitBuild/third_party/llvm/5.0.0/i386-apple-darwin19_clang/lib

**Comment by griffin28** [comment]
Catalina (10.15) is the latest MacOS and I'm sure there will be build errors since we haven't even looked at building on it. I've just recently been able to update the build scripts to support MacOS 10.14 and won't be looking at Catalina for several months at least.

**Comment by aowen87** [comment]
I've created a ticket in the primary issue tracker to make a note of this problem, and I've mentioned that Kevin plans to work on this build in a few months. Closing the ticket.
