### ISSUE TITLE
Import/launch problem with Python-3.8.3 on Windows 10

### ISSUE THREAD

**Issue by griffin28** [visit-dav/live-customer-response#100]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

Hello,
 
Could you please help me get Visit to work with Python?
 
Transcripts of the error messages when I follow the instructions appear below.
 
Thanks in advance for your help!
 
Regards,
 
--Tarun Mathur
 
 
 
Case-1:
 
```
Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.append("C:\Program Files\LLNL\VisIt 3.1.1\lib\site-packages")
>>> from visit import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\LLNL\VisIt 3.1.1\lib\site-packages\visit\__init__.py", line 29, in <module>
    from frontend import *
ModuleNotFoundError: No module named 'frontend'
```
 
 
Case-2: (adding extra path to the visit folder helps find the ‘frontend’ module, but trips on a syntax problem in the module)
 
```
>>> sys.path.append("C:\Program Files\LLNL\VisIt 3.1.1\lib\site-packages\Visit")
>>> from visit import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\LLNL\VisIt 3.1.1\lib\site-packages\visit\__init__.py", line 29, in <module>
    from frontend import *
  File "C:\Program Files\LLNL\VisIt 3.1.1\lib\site-packages\Visit\frontend.py", line 124
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

**Comment by griffin28** [comment]
Tarun...VisIt is not compatible with Python 3, you will need to use Python 2. @cyrush is currently working on getting VisIt compatible with Python 3.

-Kevin

**Comment by markcmiller86-visit** [comment]
Kevin,

Thanks for the quick response.

I’ll see if I can get permission to have Python 2 installed.

Regards,

--Tarun

**Comment by cyrush** [comment]
Tarun -- VisIt should have its own version of Python, you can access with `visit -nowin -cli`

**Comment by markcmiller86-visit** [comment]
Thanks Cyrus, I’ll check it out.

I’m new to both VisIt and Python.  My goal is to be able to launch VisIt and run a macro/script to automate generation of plots.  I have recorded, modified, and successfully got the macro/script working from within VisIt; looking for a way to get it working from the powershell command line or a Python file.

Regards,

--Tarun

**Comment by cyrush** [comment]
Tarun, in that case, if you have a script, you can save the contents to a file and use:

`visit -nowin -cli -s script.py`

You may need to iterate a bit (making sure our macro process captured opening the database, etc)

**Comment by markcmiller86-visit** [comment]
Cyrus,

That worked great!  No iteration/tweaking necessary.  Thanks so much!

Regards,

--Tarun

**Comment by cyrush** [comment]
Glad that helped!
-Cyrus
