### ISSUE TITLE
surface pressure coefficient

### ISSUE THREAD

**Issue by ag006** [visit-dav/live-customer-response#102]
I am validating a channel flow model where water is flowing past a blunt body. How would I go about plotting the local pressure coefficient along the surface of the body, as in the first slide of the attached powerpoint?  I found how to visualize the surface pressure field as shown in the second slide, but I don’t know how to get this data into a nondimensionalized graph of Cp vs s/D (where Cp is the pressure coefficient, s is the surface coordinate from the nose, and D is the body diameter).   
[Channel Flow Visualization.pptx](https://github.com/visit-dav/live-customer-response/files/4899618/Channel.Flow.Visualization.pptx)

---

**Comment by griffin28** [comment]
@ag006 ...the original responses to this issue are here: https://github.com/visit-dav/live-customer-response/issues/99
