### ISSUE TITLE
Reading Plot3d Function format

### ISSUE THREAD

**Issue by griffin28** [visit-dav/live-customer-response#103]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hello,

  I am trying to read Plot3D function format data in Visit but I could not figure out how. I am not sure whether Visit supports Plot3D function format. However, I have been using Visit to visualize Plot3D Q files for a while now. 

 With regards to this, can anybody help me by answering the following questions. 

  - Does Visit support Plot3d Function format? If so, how does it work? 
  - If it is not supported, is there any way around this? 

  The data format of Plot3d Function format is a simple extension of the Plot3D Q format such that it supports N variables instead of the standard 5 variables supported in Plot3D Q format. 
   Following is an example of a fortran code that writes a Plot3d Function file for reference

```
integer idim(maxgrid)
integer jdim(maxgrid)
integer kdim(maxgrid)
integer ngrid
integer nvar(ngrid)
real f(maxi,maxj,maxk,nvar,ngrid)
write(iunit) ngrid
write(idim(igrid),jdim(igrid),kdim(igrid),nvar(igrid),igrid=1,ngrid)
do igrid=1,ngrid
     write(iunit) (((( f(i,j,k,l,igrid), i = 1, idim ), j = 1, jdim ), k = 1, kdim ), l = 1, nvar )
end do
```

Thanks in advance. 

Best regards,
Rahul Bale

**Comment by griffin28** [comment]
Rahul...the file formats that VisIt supports is [here](https://www.visitusers.org/index.php?title=Detailed_list_of_file_formats_VisIt_supports). Plot3D is on the list. 

Try manually selecting the Plot3D file format as shown below and see if that works for you.

![Picture1](https://user-images.githubusercontent.com/26772741/87177590-c8e8ca80-c290-11ea-8b20-8edc6c1ef483.png)

**Comment by markcmiller86-visit** [comment]
Dear Kevin,

 Thanks very much for the information on the formats supported by VIsit and
for the pointer on how to open Plot3D files on Visit.

 I have been using visit to read Plot3D grid and Q data for over a year. I
am having difficulty opening the Plot3D function files on Visit.

 The format of Plot3D function files is a little different from Plot3D Q
files.
 Is it possible to alter Visit's Plot3D reader to read the Plot3D function
files? If so, a pointer to the explanation or information would be greatly
appreciated.

Thanks,
Rahul

**Comment by griffin28** [comment]
Not sure Rahul...I've created a ticket (https://github.com/visit-dav/visit/issues/4883) to discuss with the VisIt team.

**Comment by markcmiller86-visit** [comment]
Dear Kevin,

 Thanks a ton for raising a ticket on the topic.

 Hope to see the Plot3D function reader in a future version of visit.

Best regards,
Rahul
