### ISSUE TITLE
Visit timeout

### ISSUE THREAD

**Issue by sullan2** [visit-dav/live-customer-response#104]
I am running a python script in Visit via the command line. The script stops running and visit errors out with the message below. Does this mean something in the code is taking longer than 30 minutes to complete? Or is this an an allocation issue? I do not see any other errors besides what is printed below, is there a way to get more details on the error? Thanks for your help!

0: ENGINE exited due to an execution timeout of 30 minutes. (Alarm received)
2: ENGINE exited due to an execution timeout of 30 minutes. (Alarm received)
4: ENGINE exited due to an execution timeout of 30 minutes. (Alarm received)
3: ENGINE exited due to an execution timeout of 30 minutes. (Alarm received)
1: ENGINE exited due to an execution timeout of 30 minutes. (Alarm received)

**Comment by griffin28** [comment]
@sullan2 ...you can increase the execution time to run longer. Use `-exec-timeout 900` with your visit command. 900 represents the number of minutes so adjust accordingly. 

Yes, execution is taking longer than 30 minutes to complete, adding more processors should help if you have more than 5 domains.

To get more details you can also add -debug 5 to generate debug logs.
