### ISSUE TITLE
VisIt 3.1.2, OSX:Mojave. Grant VisIt permission to modify terminal

### ISSUE THREAD

**Issue by markcmiller86** [visit-dav/live-customer-response#111]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

When you execute VisIt 3.1.2 for the first time and open the CLI window a popup window asks for permissions so a osascript can modify the terminal.app.  Does anyone know how to grant those same permissions via the System Preferences?  The reason I'm asking is we have a VisIt user that is unable to open the CLI window, VisIt hangs.  However, if they login as a different user, on the same machine, it works.  I suspect it's a permission issue.

@griffin28 does this sound in any way familiar to you.

**Comment by griffin28** [comment]
@markcmiller86 ...you can do it under the *Privacy* tab in the *Security and Privacy* Settings. This sounds all too familiar and gets even better in the next release! 

![Screen Shot 2020-07-22 at 3 21 38 PM](https://user-images.githubusercontent.com/26772741/88235211-3f8dac80-cc2f-11ea-89ec-da683be0167d.png)

**Comment by markcmiller86** [comment]
Thanks @griffin28! Can't wait for next release ;)

Todd Harman...does this resolve your inquiry?

**Comment by tharman-git** [comment]
Greetings,  
The instructions above worked for me.  Another user in our group that was having issues.  I'll report back if there is still a problem.  
Thanks for the nugget of info.
Todd

**Comment by markcmiller86** [comment]
Ok, thanks for info. Will close this issue then.

**Comment by markcmiller86** [comment]
> When I try to launch a. CLI, the window hangs with the following message: “VisIt. Is waiting for a CLI to launch on localhost”
> If I cancel the message, I see the following: "VisIt could not connect to the new client /Applications/VisIt_3.1.2.app/Contents/Resources/bin/visit.”
> I am running VisIt version 3.1.2 on a MacBook Pro running Mojave (10.14.6). I created a dummy account on my laptop and was able to launch the CLI with no issues when logged in under that account.
> Thanks in advance for any help that you can give me.

@griffin28 I am curious about one thing...the user reports that the app is trying to *modify* something in the `Terminal` app's settings. Specifically...

> for permissions so a osascript can modify the terminal.app

I am wondering...why is VisIt trying to *modify* anything associated with `terminal.app`? Is there any way we can adjust things at our end so that this permissions issue simply *goes away*?

**Comment by markcmiller86** [comment]
Chatted with @griffin28 during this week's telecon...current assessement is that there is nothing VisIt is doing (strange) to somehow exacerbate this. It is all external to VisIt and the fact that VisIt is launching another app.

**Comment by Jspinti** [comment]
I logged out of my account and logged back in to a dummy account on the same machine (MacBook Pro). I was able to launch the client window and "Record" and "Stop" in the "Commands" window. I am unable to do this when logged in as myself. I previously sent the vlog files generated from my own account to Mark. I  am attaching the vlog files that were generated when I logged in under the dummy account.
[Vlog files.zip](https://github.com/visit-dav/live-customer-response/files/5126743/Vlog.files.zip)

**Comment by tharman-git** [comment]
I have compared the vLog files from the two user accounts on the same machine (jspinti vs dummy account) and found  

```
< Reading from the viewer's socket is currently not allowed!
< Error: VisIt could not connect to the new client /Applications/VisIt.app/Contents/Resources/bin/visit.
< signalhandler_exit: SIGINT!
```

The first error is coming from:
src/gui/QvisGUIApplication.C

Do you have any recommendations for debugging this?

**Comment by griffin28** [comment]
@Jspinti  and @tharman-git ...my suggestion is to compare your System Preferences settings in both accounts and make sure they match. In particular the Security & Privacy settings under the Privacy and Firewall tabs. The fact that you can run from one account and not the other points to a configuration issue with your machine.

**Comment by Jspinti** [comment]
I have tried all of the suggestions in the various posts, but the problem hasn't gone away. The Privacy and Firewall tabs are the same between the two accounts and I have "FullDiskAccess" turned on for Terminal. I also have XQuartz installed (I read about xterm issues being one cause of the behavior). Thanks in advance for any further help that you can provide.

**Comment by Jspinti** [comment]
I have found a workaround on one of your user's sites. I run visit from the command line (visit -cli). Then I open the gui (OpenGUI()). From there, I can open the command window and can record commands or run python code. I'm still not sure why the more direct method just hangs, but I'm happy to have something working.

**Comment by brugger1** [comment]
Thanks a lot for updating us on your workaround!

**Comment by Jspinti** [comment]
With help from our IT person, I was able to solve the original problem. In the "Terminal->Preferences->General->New windows open with," the "Command" option was selected and the pathname had some garbage in it. When I switched the selection to "Default login shell," the problem was solved.
