### ISSUE TITLE
Catalina update mds crashes on open

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#112]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hi,

Ever since updating my Mac to Catalina, I am unable to use VisIt.
Every time I try to navigate to a different directory after I click “open,” I receive the following error message:

“The MetaData server running on localhost could not get the file list for the current directory.”

Is there a workaround to this issue?

Sincerely,
Enoch Jo

**Comment by rusu24edward** [comment]
Hi Enoch,

Can you provide me with some more information about your system? What version of Visit are you using? How did you install Visit?

Thanks,
Eddie

**Comment by rusu24edward** [comment]
Enoch,

This is a [known issue](https://github.com/visit-dav/live-customer-response/issues/29#issuecomment-610030278) for Catalina users visit-dav/visit#12122. The workaround is to run Visit from the command line: /Applications/VisIt.app/Contents/Resources/bin/visit

**Comment by rusu24edward** [comment]
Can you give this a try and let me know if it works for you?

**Comment by markcmiller86-visit** [comment]
Hi,

Thank you. Your proposed solution worked!

I downloaded the most recent Visit .dmg from the website.
I was also wondering if compiling Visit from the source code will give me any significant performance benefits on a late 2013 Macbook Pro?

Sincerely,
Enoch Jo

**Comment by rusu24edward** [comment]
Hi Enoch,

Glad to hear that solution worked for you! I'm not sure that you will see any performance benefit by building from source. Maybe if you have specialized hardware, but if it's just a consumer macbook then I wouldn't think so. Pinging @griffin28 who is our mac expert and he might have more insight on that.

If you have access to a remote HPC machine, such as a dedicated workstation or an AWS instance, you can [run Visit in client-server mode](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/tutorials/RemoteUsage.html#using-client-server) to take advantage of the HPC resources and get some serious performance increase.

Eddie

**Comment by markcmiller86-visit** [comment]
Hi,

Sorry to bother you further, but could you perhaps point me towards a resource to how to run Visit in client-server mode if the HPC machine presets are not pre-installed in Visit?

Sincerely,
Enoch Jo

**Comment by rusu24edward** [comment]
It's no bother, I'm glad you asked! Here is a resource for how to [create your own host profiles in Visit](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/ClientServer/Host_Profiles.html?highlight=host). Let me know if this is unclear or if you would like more information.

Eddie

**Comment by griffin28** [comment]
@rusu24edward ...I concur with your assessment. The performance increase will come from running in parallel as opposed to compiling source. I doubt you will notice any performance increase between the dmg and compiling the source.
