### ISSUE TITLE
Spheral dataset pseudocolor nodal databasese cannot be compared different number of domains

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#115]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Mary is attempting to plot as pseudocolor with data from a spheral simulation. It appears that her dataset (and perhaps all spheral datasets) separates cell-centered data and node-centerd data into two variables. For example, The variable x loads as CELLS/x and POINTS/x. When she tries to plot pseudocolor of POINTS/x, she receives this error: `databases cannot be compared because different number of domains`.

She is running 3.1.2 on RZ in serial. She sees the same error message on earlier versions of Visit.

**Comment by rusu24edward** [comment]
CMFE did not work because the meshes have a different number of domains. Seems like this is common problem with spheral datasets because she said it happens all the time. Created a [ticket](https://github.com/visit-dav/visit/issues/4934) to track this.

**Comment by markcmiller86** [comment]
Hmmm...I would think a *position* based (as opposed to *connectivity* based) CMFE would work across differing numbers of domains. Did the user try a `pos_cmfe()`?
