### ISSUE TITLE
Elevate operator with VTU

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#116]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hi, 
I am trying to apply the elevate operator on a 2D plot that I've created for my project. I am saving the data in VTU format. The data is cell centered (zonal) and when I apply the operator, it gives me a 3D plot with disconnected cells (screenshot included for your reference). I would like for visit to perform some kind of interpolation and create an elevate plot with cells connected to each other. Please let me know if that is possible.

Also, when I try to switch between Nodal and Zonal centering in Pseudocolor Attributes, the Nodal centering doesn't seem to work. I am attaching the VTU file for your reference. Kindly help me out and let me know if I am doing something wrong here.

Regards,
Shashwat

**Comment by rusu24edward** [comment]
![visit0000](https://user-images.githubusercontent.com/18565891/88946586-48d8d380-d244-11ea-86cd-15c583b61d49.png)

**Comment by rusu24edward** [comment]
[sol-028.vtu.txt](https://github.com/visit-dav/live-customer-response/files/5002455/sol-028.vtu.txt)

**Comment by rusu24edward** [comment]
Hi Shashwat,

Sorry for your trouble with the elevate operator. I agree, it would be nice to have a smooth surface. The disconnected visualization is a [known issue](https://github.com/visit-dav/visit/issues/475) with the elevate operator. I've tried this with other datasets that also have unstructured meshes, but the interpolation seems to work fine there, so it is not immediately clear to me what the issue is here; this will need further investigation.

To consider some temporary workarounds, can you tell me what version of Visit you are using?

Eddie

**Comment by rusu24edward** [comment]
Hi Shashwat,

I looked deeper at your vtk file, and I noticed that you have some ~6000 cells and exactly 4x as many points. Each cell enumerates its own unique points, as opposed to sharing points, which is causing the disconnection you're seeing. These duplicate points can be merged together when you load the data within Visit's preferences:

Options -> Preferences -> Database -> Automatically remove duplicate nodes from full disconnected unstructured grids.
After selecting this option, then open your file.

I tried this on your dataset and it resolved the issue. Can you give this a try and let me know if it works?

Eddie

**Comment by markcmiller86-visit** [comment]
Hey Edward,
That is exactly what I needed. I removed the duplicate nodes and now it
works as expected. Thanks for the great help.

Regards,
Shashwat

**Comment by rusu24edward** [comment]
Glad to hear that it worked!
