### ISSUE TITLE
Visit GUI with Python

### ISSUE THREAD

**Issue by pj097** [visit-dav/live-customer-response#118]
When launching Visit via Python, is it possible to have the GUI? 

I have tried AddArgument("-gui"). However, all this gives is a blank visit window and the rest of the script is ignored. 

If not, can Customize > Toolbars > Operators be activated via Python? 

Apologies if I have missed this in the manual.

Many thanks,
Pedro

**Comment by markcmiller86** [comment]
You want `OpenGUI()`. I was going to send you a link to where that function is documented in our [user manual](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/index.html) but I couldn't find it so filed [this issue](https://github.com/visit-dav/visit/issues/4944)
