### ISSUE TITLE
Index Select together with Reflect

### ISSUE THREAD

**Issue by vsisl** [visit-dav/live-customer-response#119]
Dear VisIt Community,

I have a question regarding the use of Index Select operator on a plot which has a Reflect operator applied on it.

In the screenshot below, I plot a Pseudocolor plot of a component modelled in 1/4-symmetry (window 1) and the same plot with the Reflect operator applied to reconstruct the remaining three quarters of the plot (window 2). 

In window 2, I also apply the Index Select operator to select a particular range in the Y direction. 

![image](https://user-images.githubusercontent.com/28457179/89439961-3e8a6e00-d74b-11ea-9109-c683200897cc.png)

VisIt applies the Index Select operator on both sides of the mirrored geometry (as highlighted with arrows in the figure). 

**Is there a way to apply the selection only to one side of the geometry so that the selection is not mirrored?** 

I tried to swap the order of Index Select and Reflect operators in the main panel but this has no effect.

Thank you for your help!

**Comment by brugger1** [comment]
Hi,

Yes. You would need to do this with 2 plots. The first thing would be to uncheck the "Apply operators to all plots" checkbox on the main control panel. When it is not selected, any new operators you add will only be added to the active plots.

![Apply_operators_to_all_plots](https://user-images.githubusercontent.com/1102718/89447083-48d84800-d70a-11ea-9a9f-2c35b3e56a53.png)

The workflow would be something like this:

1) Create the first plot.
2) Apply the index select operator
3) Create the second plot
4) Apply the reflect operator, only adding the reflected portion.

That will give you the first plot index selected and the second plot reflected by not index selected.

**Comment by vsisl** [comment]
Thank you @brugger1. That works!

**Comment by brugger1** [comment]
Awesome! Glad to help.
