### ISSUE TITLE
Disappearing surfaces

### ISSUE THREAD

**Issue by bblakeley** [visit-dav/live-customer-response#120]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

I am running into an odd bug with the pseudocolor plots in visit. I can generate the plot just fine, but when I select the 'nodal' option from the plot attributes, I get some artifacting from what I assume are processor boundaries that does not seem to be present in the initial image. I have tried re-opening the file, but that ends up removing half of the surfaces of the domain. The image on the opposite face no longer has the artifacting, but the surface I was attempting to visualize has completely disappeared.
 
I have attached some images of the issue. The first is the initial pseudocolor plot with the original centering. Next is the artifacting around processor boundaries after selecting the nodal centering option. Finally, I show what happens when I re-open the file while the nodal centering option is selected. Any assistance would be greatly appreciated!

Brandon
![visit0021](https://user-images.githubusercontent.com/29437326/89557126-32dc8d00-d7c7-11ea-8c9d-f887b2e84529.png)
![visit0022](https://user-images.githubusercontent.com/29437326/89557136-35d77d80-d7c7-11ea-9d6b-bd72c12f8452.png)
![visit0023](https://user-images.githubusercontent.com/29437326/89557140-37a14100-d7c7-11ea-966d-1b8b94625f93.png)

**Comment by griffin28** [comment]
@bblakeley ...the disappearing surfaces is a known issue and should be fixed in the next release by this ticket (https://github.com/visit-dav/visit/issues/4680).

**Comment by bblakeley** [comment]
Perfect, I will await the next release. Thanks for your time.

**Comment by griffin28** [comment]
I believe the artifacts are a result of zones being incorrectly discarded and identified as external to the problem domain. Can you attach your dataset as a tar.gz file and I can verify with the fix in place?

**Comment by bblakeley** [comment]
Hello, I'm sorry it took me so long to get back to you. I did some investigation on my end, and it appears that I was using a deprecated version of the visit output files from miranda. When I visualize the fields with the supported visit output, everything works just fine. As such, it's doesn't seem necessary to waste your time making sure the deprecated output files work in the new visit.

Sorry to bother you!

**Comment by griffin28** [comment]
No problem @bblakeley. Thanks for the update!
