### ISSUE TITLE
Unwanted layering of volume plots

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#121]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hi,

I have 2 volume plots, and depending on which plot is the first plot determines which plot is viewed at all camera angles in the foreground, even if it is behind something in physical space that is fully opaque.

I was wondering if there is a way to turn this effect off or some sort of workaround? I want to view the physical domain as it is, not have it "stacked" on top / not view behind something that may be obscuring the foreground plot. I want both of them to be treated as if they were both on the same layer.

Is this possible?

This isn't a problem when plotting isosurfaces, only when doing volume plots (or at least that's my experience).

Context: My data is separated into two sets of files (a yin-yang grid), so I load in one file - do a plot - then read in the second file - do a rotation on the mesh - and do a plot of the same variable. Although both grids - at a file level - have the same mesh, they are offset from each other by 2 subsequent rotations in physical space.

Thanks,

Michael

**Comment by rusu24edward** [comment]
Hi Michael,

Sorry for your trouble with the volume plot. I have duplicated your issue and am looking into a workaround now. You mentioned isovolumes, and I've been playing around with these as well. Can you help me understand why you want to use a volume plot over an isovolume?

Thanks,
Eddie

**Comment by rusu24edward** [comment]
Images that demonstrate this issue:
Good volume:
![good_volume](https://user-images.githubusercontent.com/18565891/89819152-cb447b80-daff-11ea-905b-7dceea74f034.png)

Good isovolume:
![good_isovolume](https://user-images.githubusercontent.com/18565891/89819201-df887880-daff-11ea-8725-41c3ecd0faac.png)

Bad volume:
![bad_volume](https://user-images.githubusercontent.com/18565891/89819222-e616f000-daff-11ea-8e16-014ac69272f7.png)

Still good isovolume:
![still_good_isovolume](https://user-images.githubusercontent.com/18565891/89819236-eb743a80-daff-11ea-9630-07e2d74b6f4b.png)

**Comment by markcmiller86-visit** [comment]
Hi Eddie -

Thanks for the response.

I work with core-collapse supernovae and it's nice to highlight the
internal structure of the explosion while still showing the overall
progression of the shock front (via a movie), which means controlling the
opacities of the colors is of utmost importance. The volume plot allows us
to have simple/direct control over the opacities via the transfer function
editor, and produces higher quality images than I seem to be able to make
with pseudocolor plots paired with isosurface/isovolume operators. A large
portion of the decision boils down to it being "prettier" in a movie
setting rather than a single still-image setting where pseudocolor plots
would still be viable options.

**Comment by biagas** [comment]
When we use other volume renderer options (ray-casting, slivr, ospray), we don't allow multiple volume plots, probably for the same reason being experienced here.  Perhaps the same rule needs to be applied for the default renderer.

At any rate, can a different plot be used for the fully-opaque portion?

**Comment by rusu24edward** [comment]
Hi Michael,

Thanks for the further explanation. From what I've seen, it doesn't look like we have done much with multiple volume plots, and as Kathleen noted some of our volume-renderers will display a warning sign indicating that they are incompatible with multiple volumes. I've created [this issue](https://github.com/visit-dav/visit/issues/4955) in our system for the team to discuss some solutions because this seems like it would be a nice feature to have.

As a workaround, I can think of three potential paths forward. One is to play with the opacity of isovolumes to try to accomplish the same task. The opacity settings in pseudocolor are not as fully-featured as volume, but you may still be able to achieve what you want. Here's an example image:
![Screen Shot 2020-08-10 at 4 42 26 PM](https://user-images.githubusercontent.com/18565891/89841934-145cf580-db29-11ea-8021-220220f89020.png)

My second thought is to clip the shock front with a threshold operator to reveal the internal structure of the explosion, something like this:
![gallery_00-1](https://user-images.githubusercontent.com/18565891/89842035-56863700-db29-11ea-9b10-68e94351ae1e.jpg)
I've seen this approach several times before, and it might be useful to you.

Lastly, you may be able to use a [CMFE](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/Quantitative/Expressions.html?highlight=cmfe#comparison-expressions) along with a clever expression to combine the two variables into one and thus render a single volume. I'm not an expert in CMFE's, but I image that if your mesh is symmetric under your rotation transformations, you would still see good data resolution.

Understanding your specific case better would also be beneficial. If you are able to show me over a Webex/Zoom connection, then I can setup a meeting. If you're not able to do that, then perhaps you can email me the data along with steps to reproduce.

Hope this helps!
Eddie

**Comment by markcmiller86-visit** [comment]
Thanks for the options, Eddie. I'm going to try all of these and see how
they look. I too was curious about somehow making a magic CMFE, but have
yet to dive down that rabbit hole. I probably will venture down that path
soon, just to see if it's possible, but I've never rotated data outside of
the transform operator, so I will probably have to create an expression for
that before/during the CMFE.

And yes I am able to live plot over Zoom - that would be easiest since the
data is about 50 GB and on a remote machine.

Thanks again,

Michael

**Comment by rusu24edward** [comment]
Hi Michael,

After discussing with @cyrush, I think the way forward is to try to trick VisIt into thinking that your two databases are just two domains of the same database. You can do this with [grouping into a `my_database.visit` file](http://visitusers.org/index.php?title=.visit_file). Then you can create an expression to combine the variables you care about into one variable and volume plot that variable. I believe you may be able to do a volume plot with Deferred Expressions (see [here](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/Operators/OperatorTypes/DeferExpression_operator.html) and [here](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/tutorials/Aneurysm.html#creating-a-vector-expression-and-using-the-deferexpression-operator)) to accomplish what you want.

Eddie

**Comment by rusu24edward** [comment]
I iterated with Michael offline and am adding the details here:

We have to be a little hackish and use export database. Load in your variable, perform the transformation, and then export the database. Make sure you have all the same variables on both files. You can can distinguish variables from one another with expressions.

After exporting the databases, create a .visit file according to the instructions above to combine the files together.
Then load the .visit file and you'll see the two meshes loaded in as multiple domains. This allows you to use the volume plot on a single variable on both meshes. You will have to be a bit clever with creating your expressions to combine the relevant variables together into one.

Eddie
