### ISSUE TITLE
Using expressions to integrate a variable

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#122]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Clayton Withers is a summer student. He's trying to use VisIt to integrate the data in his simulation. He's writing an expression that calculates the integrand (the "inside" of the integral), which he can visualize with a plot, but is struggling to find how to sum up all the values in the simulation domain.

**Comment by rusu24edward** [comment]
_Clayton further followed up with:_ 
Hello all,
 
I am trying to perform an integration in visit, but having trouble.
 
I am able to take my simulation data, and then write a visit expression to calculate the integrand that I want to evaluate. After doing this, I am able to visualize that visit expression’s results. At this point, I want to sum all the data points up/carry out an integration of the data over the entire simulation domain, but cannot figure out how to do so. The resultant value should be a single integral value for each simulation time step.
 
One route that I have thought of could be to export the values of the calculated visit expression/integrand into an excel or .dat file, and transfer that over to MATLAB and carry out the sum/integral there, but I cannot figure out how to do this exportation either.
 
As of now, I am only carrying out 2D simulations that have x and z values, and the y dimension is kept at a constant depth (if this changes the approach).
 
The integral is along the lines of integral{(4 * variable1 * variable2 * variable3)}dv
 
Any help is appreciated,
Thank you,
Clayton Withers

**Comment by rusu24edward** [comment]
Hi Clayton,

It sounds like what you want is a [Query](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/tutorials/Data_Analysis.html#queries) or [Query over time](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/tutorials/Data_Analysis.html#queries-over-time). You'll probably want to use the Variable Sum Query.

Can you give follow these tutorials and let me know if this helps?
Eddie

**Comment by cyrush** [comment]
"Weighted Variable Sum" will also mult by per-element volume. You can also use `Variable Sum` with an expression that includes the volume calc.

**Comment by rusu24edward** [comment]
Hello all,
 
I have created some 2D line plots by doing a variable sum query over time. Each curve that I add onto the plot window is annotated with the variable name. I want to delete this from the plot, but when I go to       
Controls->Annotation->Objects->Annotation objects and try to select the object I want to hide/delete (Legend:Curve – ‘Variable Name’), the hide/show and delete option grays out and I cannot delete them.
 
If I add my own annotation in the same window, then I can hide/show or delete them with no issue. Just not these ones that autogenerate with the curve. Each curve I add to the plot window has several of these annotations that follow along the curve.
 
Is there any way to delete these?
 
Thank you,
Clayton Withers
