### ISSUE TITLE
Removing variable name "annotations" in curve plots

### ISSUE THREAD

**Issue by markcmiller86** [visit-dav/live-customer-response#123]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

I have created some 2D line plots by doing a variable sum query over time. Each curve that I add onto the plot window is annotated with the variable name. I want to delete this from the plot, but when I go to       
Controls->Annotation->Objects->Annotation objects and try to select the object I want to hide/delete (Legend:Curve – ‘Variable Name’), the hide/show and delete option grays out and I cannot delete them.
 
If I add my own annotation in the same window, then I can hide/show or delete them with no issue. Just not these ones that autogenerate with the curve. Each curve I add to the plot window has several of these annotations that follow along the curve.
 
Is there any way to delete these?

**Comment by markcmiller86** [comment]
This is controlled through the [Curve plot attributes object itself](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/Plots/PlotTypes/CurvePlot.html?highlight=curve%20plot%20attributes#showing-curve-labels). Uncheck the `Labels` option and they should go away.

**Comment by markcmiller86** [comment]
Oh, and if you want that behavior to be the default each time a new curve plot is added. Then, use VisIt's feature to make those the [default attributes](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/Preferences/Setting_default_values.html?highlight=Default%20plot%20attributes#setting-default-values) or for the CLI, use [`SetDefaultPlotOptions()`](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/cli_manual/functions.html?highlight=SetDefaultPlotOptions#setdefaultplotoptions) method.

**Comment by rusu24edward** [comment]
I iterated with Clayton offline. Just adding this here for completion.

![Screen Shot 2020-08-10 at 5 43 58 PM](https://user-images.githubusercontent.com/18565891/89844779-73266d00-db31-11ea-9171-e811ed5092ab.png)
