### ISSUE TITLE
 Visit install on CentOS Linux release 7.8.2003

### ISSUE THREAD

**Issue by biagas** [visit-dav/live-customer-response#125]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hello All,

I am trying to install Visit on a machine with CentOS Linux release 7.8.2003.

I tried to install both the visit3_1_2.linux-x86_64-centos8  and visit3_1_2.linux-x86_64-rhel7 executables but neither worked. I assume because by distro or release did not match. So now I am trying to build Visit from source using

 ./build_visit3_1_2 --makeflags -j12 --optional --tarball visit3.1.2.tar.gz

But I get the error

 $./build_visit3_1_2 --makeflags -j12 --optional --tarball visit3.1.2.tar.gz

Processing bsd license.
executing group optional
[build_visit invocation arguments] --makeflags -j12 --optional --tarball visit3.1.2.tar.gz
g++ version 4.8.5
checkogl.cpp:1:19: fatal error: GL/gl.h: No such file or directory
#include <GL/gl.h>
                                  ^
compilation terminated.
failed to compile checkogl.cpp

 Does anyone have any thoughts on what might be going wrong? The options don’t really seem to matter, I get the same error with ./build_visit3_1_2

 Thanks,
John

**Comment by biagas** [comment]
What errors did you see when you tried to run the centos8 and rhel7 versions?

Based on the error from the build_visit script, it looks like OpenGL isn't installed on your system, or isn't installed in the usual locations.  You can add ``--skip-opengl-context-check`` to your build_visit arguments, and it won't perform the check.  It tests if your OpenGL version is sufficient for VisIt.  Without the check, you should probably also add ``--llvm --mesagl``.

**Comment by markcmiller86-visit** [comment]
Thanks for the help

For the rhel7 install (it installed without error) but when I run visit I get
/usr/local/visit2/3.1.2/linux-x86_64/bin/gui: error while loading shared libraries: libGLU.so.1: cannot open shared object file: No such file or directory

For the centos8 install (it installed without error) but when I run visit I get
/usr/local/visit/bin/../current/linux-x86_64/bin/python: /lib64/libc.so.6: version `GLIBC_2.2\
8' not found (required by /usr/local/visit/bin/../current/linux-x86_64/lib/libpython2.7.so.1.\
0)

Its possible I need to install OpenGL, its new machine.
-John

From: Kathleen Biagas via visit-users <visit-users@elist.ornl.gov>
Reply-To: visit-dav/live-customer-response <reply@reply.github.com>, VisIt software users community <visit-users@elist.ornl.gov>
Date: Friday, August 14, 2020 at 2:33 PM
To: visit-dav/live-customer-response <live-customer-response@noreply.github.com>
Cc: Kathleen Biagas <notifications@github.com>, Subscribed <subscribed@noreply.github.com>
Subject: [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] Visit install on CentOS Linux release 7.8.2003 (#125)


What errors did you see when you tried to run the centos8 and rhel7 versions?

Based on the error from the build_visit script, it looks like OpenGL isn't installed on your system, or isn't installed in the usual locations. You can add --skip-opengl-context-check to your build_visit arguments, and it won't perform the check. It tests if your OpenGL version is sufficient for VisIt. Without the check, you should probably also add --llvm --mesagl.

**Comment by aowen87** [comment]
Hi John,

You should be able to use the following command to determine if you have opengl installed: glxinfo | grep "OpenGL version"
Does that return anything for you? If not, you probably don’t have OpenGl installed.

If you don’t want to install OpenGl, you might want to try downloading one of our releases that comes with mesa: https://github.com/visit-dav/visit/releases/download/v3.1.2/visit3_1_2.linux-x86_64-rhel7-wmesa.tar.gz

Let us know if these options don’t work for you.

Best,
Alister

**Comment by markcmiller86-visit** [comment]
It works!
I installed openGL and the RHEL7 version works. Thank so much.
-John

From: Alister via visit-users <visit-users@elist.ornl.gov>
Reply-To: visit-dav/live-customer-response <reply@reply.github.com>, VisIt software users community <visit-users@elist.ornl.gov>
Date: Friday, August 14, 2020 at 3:19 PM
To: visit-dav/live-customer-response <live-customer-response@noreply.github.com>
Cc: Alister <notifications@github.com>, Comment <comment@noreply.github.com>, markcmiller86-visit <visit-users@ornl.gov>
Subject: [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] Visit install on CentOS Linux release 7.8.2003 (#125)

Hi John,

You should be able to use the following command to determine if you have opengl installed: glxinfo | grep "OpenGL version"
Does that return anything for you? If not, you probably don’t have OpenGl installed.

If you don’t want to install OpenGl, you might want to try downloading one of our releases that comes with mesa: https://github.com/visit-dav/visit/releases/download/v3.1.2/visit3_1_2.linux-x86_64-rhel7-wmesa.tar.gz<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_visit-2Ddav_visit_releases_download_v3.1.2_visit3-5F1-5F2.linux-2Dx86-5F64-2Drhel7-2Dwmesa.tar.gz&d=DwQFaQ&c=S1d2Gs1Y1NQV8Lx35_Qi5FnTH2uYWyh_OhOS94IqYCo&r=u6orZNokQI2NS1xXzi2stYb6tAFuLZTtVRAyVMECDPY&m=k1SPh_PLuV3r01vULcV5hJDhBl7aJTXmejCxDIVUgfk&s=fmyKZ306dtZLEmHYu0J2FC23KZ7s-Frcv9buWTfmMoA&e=>

Let us know if these options don’t work for you.

Best,
Alister

**Comment by aowen87** [comment]
Great! I’m glad you got things working.

Best,
Alister
