### ISSUE TITLE
Ospray Pixie

### ISSUE THREAD

**Issue by griffin28** [visit-dav/live-customer-response#126]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

Hello,

With visit 3.0.2, using Pixie file and Ospray volume rendering, the subdomain boundary between each processor can be seen,
depending on the slab direction when opening a pixie file.

Below are images corresponding to a zoom in on the first part of a longer domain.

On this [image](https://notus-cfd.org/wp-content/uploads/2020/08/visit_X_slab_ospray_28p_0000.png) (X slabs, -np 28), rendering is fine

On this [image](https://notus-cfd.org/wp-content/uploads/2020/08/visit_Y_slab_ospray_28p_0000.png) (Y slabs, -np 28), you will see some horizontal lines

On [this one](https://notus-cfd.org/wp-content/uploads/2020/08/visit_Z_slab_ospray_28p_0000.png) (Z slabs), you will see vertical lines

For Z slabs :

On [this image](https://notus-cfd.org/wp-content/uploads/2020/08/visit_ospray_28p_0000.png) (-np 28), you will see 5 zones

On [this one](https://notus-cfd.org/wp-content/uploads/2020/08/visit_osparay_14p_0000.png) (-np 14), the number of zones is divided by 2 

On [this one](https://notus-cfd.org/wp-content/uploads/2020/08/visit_ospray_4p_0000.png) (-np 4), everything is fine (the part of domain shown is contained into 1 processor)

With Z slab at least, I have tried other volume rendering methods that run fine.

I can go on with X slabs but I wanted to let you know for Y and Z slabs. Moreover, for Z slabs,
I would not have expected these lines in this plane, but visible with a top point of view (slabs perpendicular to Z axis ?)

Thanks, best regards

Stéphane

**Comment by griffin28** [comment]
Thanks for reporting Stéphane, are you able to share your data? If so, can you attach it to this GitHub issue as a tar.gz? In the meantime, I'll do some research on my end and see if I can find the issue.

**Comment by markcmiller86** [comment]
If you cannot attach to this issue, [here](https://visit-dav.github.io/largedata/help/using-for-uploads.html) are some other options for getting us data.

**Comment by glockner** [comment]
Enclosed a small file. Problem occurs whatever slabs direction. The good news is that if volume rendering option "Smooth Data" is used, it works fine!
[poiseuille_rayleigh_benard_3D_00000600.h5.gz](https://github.com/visit-dav/live-customer-response/files/5105631/poiseuille_rayleigh_benard_3D_00000600.h5.gz)

**Comment by griffin28** [comment]
Thanks...glad you have a work-around. I'm wondering if that's the expected behavior @aowen87 ...to do interpolation between domains only if **Smooth Data** is selected?

@glockner...can you also add a screen shot of your **Volume plot attributes** window so I can see and copy your settings. Also, your dataset has only one block, I believe the lines are due to multiple blocks being processed. I'm unable to reproduce with the dataset you've attached. I am using a newer VisIt (3.1.2) I will try with the version you have but I don't think that's the issue.

**Comment by glockner** [comment]
Enclosed screenshots (8 cores, No lighting, attenuation=69%)
You can see as many subdomains as used cores.

![Capture d’écran de 2020-08-21 01-05-23](https://user-images.githubusercontent.com/69991391/90834870-84e6ec00-e34b-11ea-9dcb-57c03f4b9260.png)
![Capture d’écran de 2020-08-21 01-08-29](https://user-images.githubusercontent.com/69991391/90834873-857f8280-e34b-11ea-8e07-f4af0ba902a0.png)
