### ISSUE TITLE
Generating movie failed

### ISSUE THREAD

**Issue by biagas** [visit-dav/live-customer-response#127]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hi:

Hello! I am trying to use visit3.0.1 to generate a movie. I use Tecplot format and set  Option - Preferences - treat all databases as time-varying. I am in the client-server mode. The connection to the server has no problem. I can open and view the data correctly. But when I try to save the data into movie Visit crashes. My settings in Save movie wizard are:

Movie type - new simple movie
choose format  - MPEG + Use current window size + scale = 1
choose length - keep everything as default
choose filename - set the output directory, name: Movie

E-mail - no
choose method - now, use the current allocated processors. 

Visit generates several figures in the output directory and then crashes. 

The error I got is:
Running: gui3.0.1
Running: viewer3.0.1 -geometry 2112x1914+1551+164 -borders 26,4,4,4 -shift 0,0 -preshift 4,26 -defer -host 127.0.0.1 -port 5600
Running: mdserver3.0.1 -host 127.0.0.1 -port 5601
shiqihe@137.122.85.123's password: 
Running: vcl3.0.1 -dir /home/shiqihe/local/visit3_0_1/install -idle-timeout 480 -threads 8 -noloopback -sshtunneling -host localhost -port 15925
Running: mdserver3.0.1 -dir /home/shiqihe/local/visit3_0_1/install -idle-timeout 480 -threads 8 -noloopback -sshtunneling -host localhost -port 14954
Running: engine_ser3.0.1 -dir /home/shiqihe/local/visit3_0_1/install -idle-timeout 480 -threads 8 -noloopback -sshtunneling -host localhost -port 13510
Running: xterm -geometry 120x40 -title "VisIt cli3.0.1" -e "/home/shiqi/Downloads/visit3_0_1/install/3.0.1/../bin/visit -cli -v 3.0.1 -reverse_launch -host 127.0.0.1 -port 5600 -key fda3b1ac4f05807929f7"
VisIt's viewer exited abnormally! Aborting the Graphical User Interface. VisIt's developers may be reached via the visit-users mailing list.  Please see:
        https://wci.llnl.gov/simulation/computer-codes/visit/faqs/faq01

The database I am using is relatively large and it causes Visit to render pretty slow. I wonder if that could be one of the reasons. 

Moreover, I would like to ask if there is a way to let Visit only output the windows, like what it does to generate a movie: first saves all the windows figures and then combines them into a movie. If there is an option to just output all the figures? 

Thank you very much, 

Shiqi He

**Comment by biagas** [comment]
Including Mahesh Natarajan's response:

Regarding your last question - "If there is an option to just output all the figures?" - Yes. In the choose format, you can choose PNG images for eg. There are other options there as well - JPEG, TIFF etc. 
When the database is large it is probably better to generate a python script to output an image of a frame using Controls -> Command -> Record to record your actions, and then put a for loop around it, and run the python script in the background in the terminal without opening the GUI in the following way - path/to/visit/bin/visit -nowin -cli -s <script.py> (See http://visitusers.org/index.php?title=VisIt-tutorial-Python-scripting)

**Comment by biagas** [comment]
Which OS is your local client and your remote?
The crash could be related to very large data. What types of plots/operator combinations are you using?
Does VisIt also crash if you simply step through time without saving images or using the Movie wizard?


Adding to Mahesh suggestion, here's more documentation on [movie making with python](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/tutorials/MakingMovies.html#encoding-the-movie-with-a-python-script)
It describes using the Commands Window from the GUI, but the python code demonstrated can be used directly from the CLI.

**Comment by markcmiller86-visit** [comment]
Hi Kathleen:

Thanks for your reply.

My local OS is Ubuntu 18.04.5 LTS, and my remote OS is Ubuntu 18.04.3 LTS.

I am using "Add - mesh - mesh" and "Add - Pseudocolor - variable" then
"Draw". It's serious of time-dependent data.

I tried again, the Visit also crashes if I only step through the time
without saving images.

I will try to use Python to generate the movie.

Thank you,
Shiqi He

**Comment by markcmiller86-visit** [comment]
Hi Kathleen:

I am trying to use Python script to generate a movie as you suggested. I
first recorded the GUI actions to a python script like the tutorial shows:
here <http://visitusers.org/index.php?title=VisIt-tutorial-Python-scripting>.
Here is the script I got:

OpenDatabase("localhost:/home/shiqi/Documents/thesis/DG_wave_c/outputs/output*.dat
database", 0)

AddPlot("Mesh", "mesh", 1, 1)

AddPlot("Pseudocolor", "PORDER", 1, 1)

PseudocolorAtts = PseudocolorAttributes()

PseudocolorAtts.scaling = PseudocolorAtts.Linear # Linear, Log, Skew

PseudocolorAtts.skewFactor = 1

PseudocolorAtts.limitsMode = PseudocolorAtts.OriginalData # OriginalData,
CurrentPlot

PseudocolorAtts.minFlag = 1

PseudocolorAtts.min = 6

PseudocolorAtts.useBelowMinColor = 0

PseudocolorAtts.belowMinColor = (0, 0, 0, 255)

PseudocolorAtts.maxFlag = 1

PseudocolorAtts.max = 16

PseudocolorAtts.useAboveMaxColor = 0

PseudocolorAtts.aboveMaxColor = (0, 0, 0, 255)

PseudocolorAtts.centering = PseudocolorAtts.Natural # Natural, Nodal, Zonal

PseudocolorAtts.colorTableName = "Oranges"

PseudocolorAtts.invertColorTable = 0

PseudocolorAtts.opacityType = PseudocolorAtts.Constant # ColorTable,
FullyOpaque, Constant, Ramp, VariableRange

PseudocolorAtts.opacityVariable = ""

PseudocolorAtts.opacity = 1

PseudocolorAtts.opacityVarMin = 0

PseudocolorAtts.opacityVarMax = 1

PseudocolorAtts.opacityVarMinFlag = 0

PseudocolorAtts.opacityVarMaxFlag = 0

PseudocolorAtts.pointSize = 0.05

PseudocolorAtts.pointType = PseudocolorAtts.Point # Box, Axis, Icosahedron,
Octahedron, Tetrahedron, SphereGeometry, Point, Sphere

PseudocolorAtts.pointSizeVarEnabled = 0

PseudocolorAtts.pointSizeVar = "default"

PseudocolorAtts.pointSizePixels = 2

PseudocolorAtts.lineType = PseudocolorAtts.Line # Line, Tube, Ribbon

PseudocolorAtts.lineWidth = 0

PseudocolorAtts.tubeResolution = 10

PseudocolorAtts.tubeRadiusSizeType = PseudocolorAtts.FractionOfBBox #
Absolute, FractionOfBBox

PseudocolorAtts.tubeRadiusAbsolute = 0.125

PseudocolorAtts.tubeRadiusBBox = 0.005

PseudocolorAtts.tubeRadiusVarEnabled = 0

PseudocolorAtts.tubeRadiusVar = ""

PseudocolorAtts.tubeRadiusVarRatio = 10

PseudocolorAtts.tailStyle = PseudocolorAtts.None # None, Spheres, Cones

PseudocolorAtts.headStyle = PseudocolorAtts.None # None, Spheres, Cones

PseudocolorAtts.endPointRadiusSizeType = PseudocolorAtts.FractionOfBBox #
Absolute, FractionOfBBox

PseudocolorAtts.endPointRadiusAbsolute = 0.125

PseudocolorAtts.endPointRadiusBBox = 0.05

PseudocolorAtts.endPointResolution = 10

PseudocolorAtts.endPointRatio = 5

PseudocolorAtts.endPointRadiusVarEnabled = 0

PseudocolorAtts.endPointRadiusVar = ""

PseudocolorAtts.endPointRadiusVarRatio = 10

PseudocolorAtts.renderSurfaces = 1

PseudocolorAtts.renderWireframe = 0

PseudocolorAtts.renderPoints = 0

PseudocolorAtts.smoothingLevel = 0

PseudocolorAtts.legendFlag = 1

PseudocolorAtts.lightingFlag = 1

PseudocolorAtts.wireframeColor = (0, 0, 0, 0)

PseudocolorAtts.pointColor = (0, 0, 0, 0)

SetPlotOptions(PseudocolorAtts)

DrawPlots()


Next, I launch the CLI by:

/path/to/visit -cli


Then I tried to open my database with:

OpenDatabase("localhost:/home/shiqi/Documents/thesis/DG_wave_c/outputs/output*.dat
database", 0)


Just as the first line in my python script. However, visit threw me errors:

VisIt: Error - VisIt could not read from the file
"/home/shiqi/Documents/thesis/DG_wave_c/outputs/output*.dat database".

The generated error message was:

There was an error opening
/home/shiqi/Documents/thesis/DG_wave_c/outputs/output*.dat database. It may
be an invalid file.
VisIt tried using the following file format readers to open the file:
OVERFLOW, TFT, VASP, paraDIS, paraDIS_tecplot, Silo

If you know the specific format reader VisIt should use to
read this data, you can use Open As... (GUI) or
'-o <file>,<plugin> (CL arg.) and identify that specific reader
for VisIt to try. This will possibly give more information on
the exact error.


I think visit does not read it in the right format. I am using Tecplot
format. How can I specify that in the command line? Thank you!


All the best,

Shiqi He

**Comment by biagas** [comment]
You can add the plugin name as the third argument to the OpenDatabase call.  Note that the plugin name also includes the plugin version number, for Tecplot (and most plugins) the verison is "1.0".

```
OpenDatabase("localhost:/home/shiqi/Documents/thesis/DG_wave_c/outputs/output*.dat database", 0, "Tecplot_1.0")
```

Apologies that the command-recording didn't provide this information.

There is also a way to change the default read options.  Did you need to change the read options when opening your data via the GUI?

**Comment by markcmiller86-visit** [comment]
Yes. That would be nice. What would be the command to change the default
read format?

And also, because I am rendering a time-dependent dataset, I need to set
the following option:
Options - Preferences - treat all databases as time-varying

This option does not being recorded. Would you tell me the command line to
do so?

Thank you,
Shiqi He

**Comment by biagas** [comment]
For time-varying, simply call
```
SetTreatAllDBsAsTimeVarying(1)
```
To set default read options, you first need to open the mdserver, then retrieve the read options, change as necessary, set the changes as the new default, then call open database. Unfortunately, the options are very verbose, and need to be spelled correctly to work. So you may want to print them first so you can see what they are:

Here are the results of printing the options:
```
{'Z axis variable index (or -1 for none)': -1, 'Method to determine coordinate axes': 'Guess from variable names # Options are: Guess from variable names, Specify explicitly (below)', 'X axis variable index (or -1 for none)': -1, 'Y axis variable index (or -1 for none)': -1}
```

Here's the code to change a couple of options:
```
OpenMDServer()
tecplotOptions = GetDefaultFileOpenOptions("Tecplot")
tecplotOptions['Method to determine coordinate axes'] = 'Specify explicitly (below)'
tecplotOptions['X axis variable index (or -1 for none)'] = 5
SetDefaultFileOpenOptions("Tecplot", tecplotOptions)
OpenDatabase("/path/to/data", 0, "Tecplot_1.0")
```

**Comment by biagas** [comment]
Shiqi, anything new to report for this?
If VisIt is still crashing when you step through time, would you be willing to provide a minimal set of data that reproduces the problem?
