### ISSUE TITLE
The .visit file with "!TIME" marker appears to not work for .vtk binary files

### ISSUE THREAD

**Issue by flow-phys** [visit-dav/live-customer-response#128]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
### Description
I've been successfully visualizing collections of .vtk binary files over time using the "!NBLOCKS".  Visit plots show the CYCLE and TIME values as the same integer value that corresponds with the base file name; the cycle number.  I'd like the physical time to be accurately displayed.  When I use the "!TIME {value}"  in the .visit file, the behavior is not changed, and I still see integer cycle numbers at the "time" rather than the actual time.

**Helpful additional information**
Visit did not crash
I see unexpected values for the displayed "Time" in the visit plot window.

### To Reproduce
Steps to reproduce the behavior. For example:
1. Open the attached .tgz file
2. Open the "pyranda.visit" file (Note, this file DOES include the "!TIME {value}"
3. AddPseudocolor->rho
4. Note the cycle and time are both integer values.  Time is not capturing the simulation value.

### Expected behavior
As per the [documentation here](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/WorkingWithFiles/Supported_File_Types.html?highlight=.visit#creating-visit-files), I would expect the value for Time to be displayed. 

### Attachments
* KelvinHelmholtz.tgz - Dataset
* Screenshot.png - Sample unexpected output.

### Desktop
 - LC- rzgenie
 - VisIt Version: 3.1.2

### Additional context

[KelvinHelmholtz.zip](https://github.com/visit-dav/visit/files/5113349/KelvinHelmholtz.zip)
![Screenshot](https://user-images.githubusercontent.com/7298711/90968793-64cb4000-e4a5-11ea-934f-d38eff3795ed.png)

**Comment by biagas** [comment]
Thank you for reporting your problem. I've verified that the problem exists for ascii vtk files as well. I will enter a ticket into our bug tracker.

In the meantime, if you can control how your vtk files get written out, you could utilize a convention that VisIt uses, involving Field data in vtk files for CYCLE and TIME.

For an ascii vtk file, the beginning of the file would look something like this:

```
# vtk DataFile Version 4.2
vtk output
ASCII
DATASET STRUCTURED_GRID
FIELD FieldData 2
CYCLE 1 1 int
229 
TIME 1 1 double
0.7012092338664179 
DIMENSIONS 128 128 1
POINTS 16384 float
....
```

If you are using vtkDataSet (eg not just writing out information to vtk file formats), CYCLE and TIME can be added like so (where ds is an instance of a vtkDataSet):

```
        vtkIntArray *cycleArray = vtkIntArray::New();
        cycleArray->SetNumberOfValues(1);
        cycleArray->SetValue(0, 229);
        cycleArray->SetName("CYCLE");
        ds->GetFieldData()->AddArray(cycleArray);
        cycleArray->Delete();
 
        vtkDoubleArray *timeArray = vtkDoubleArray::New();
        timeArray->SetNumberOfValues(1);
        timeArray->SetValue(0, 0.7012092338664179);
        timeArray->SetName("TIME");
        ds->GetFieldData()->AddArray(timeArray);
        timeArray->Delete();
```

**Comment by flow-phys** [comment]
Thanks, @biagas!  I tried the fix above which appears to not work for binary VTK files but only ASCII vtk files.  Is that expected?  Thanks.

**Comment by biagas** [comment]
Yes, it should work for binary data as well. Did you just hand modify the vtk files or change how they are written?

**Comment by flow-phys** [comment]
Thanks, @biagas, I changed how the files are written.

**Comment by biagas** [comment]
@flow-phys Thanks for following up.  Hopefully we can get the .visit !TIME issue fixed soon, there's a ticket in our bug tracker.
