### ISSUE TITLE
Slice operator settings

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#129]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
I am looking at the defaults for the Slice operator, and I see that the default `up` in Visit for slices orthogonal to the X, Y, and Z axes is Y, Z, and Y, respectively. The axis values are also -x, -y, and +z. Is there a reason for why the up isn't the opposite axis, and why the z is the only axis that isn't negative? I did read the man page for Slice. Thanks.

- Walt

**Comment by biagas** [comment]
I interacted with Walt on Teams.
