### ISSUE TITLE
ADIOS reader, large file, INT_MAX problem.

### ISSUE THREAD

**Issue by brugger1** [visit-dav/live-customer-response#13]
Dear all,

I have a large file .bp file containing 1 concentration field associated to a rectilinear mesh. The total amount of mesh points is above single integer limit (4.2 billion)

I can't open the file with visit 2.13.3 (I can open a smaller file of 2 billion cells below, single integer limit)

The error message is the following :

The compute engine running on host n4368.occigen issued the following warning: Mesh and/or variable size exceeds INT_MAX for domain 0. This domain is being set to empty. Your only recourse to correct this issue is to decompose your input database into smaller domains. If you continue to process this data, this and likely other warnings will periodically re-appear.

Changelogs of version 2.13.1 indicates that:

Corrected a bug where VisIt would crash when the number of nodes or zones or tuples times the number of components exceeds INT_MAX in a single block.

So I am wondering if there still a problem with version 2.13.3. I may also miss some points about very large data files but .bp file seems OK to me (see bpls output below)

Thanks for your answer, best regards

Stéphane Glockner

File info:
  of groups:     1
  of variables:  20
  of attributes: 19
  of meshes:     1
  time steps:    0 - 0
  file size:     32 GB
  bp version:    3
  endianness:    Little Endian
  statistics:    Min / Max / Avg / Std_dev

  integer  nxg001                                            scalar = 3500
  integer  nyg001                                            scalar = 1104
  integer  nzg001                                            scalar = 1104
  integer  nxug001                                           scalar = 3501
  integer  nyvg001                                           scalar = 1105
  integer  nzwg001                                           scalar = 1105
  integer  nproc001                                          scalar = 8192
  integer  offs_x001                                         scalar = 0
  integer  offs_y001                                         scalar = 0
  integer  offs_z001                                         scalar = 0
  integer  nx001                                             scalar = 110
  integer  ny001                                             scalar = 69
  integer  nz001                                             scalar = 69
  integer  nxu001                                            scalar = 111
  integer  nyv001                                            scalar = 70
  integer  nzw001                                            scalar = 70
  double   X001                                              {3501} = 0 / 0.0035 / null  / null 
  double   Y001                                              {1105} = -0.00055275 / 0.00055275 / null  / null 
  double   Z001                                              {1105} = -0.00055275 / 0.00055275 / null  / null 
  double   concentration_EtOH                                {1104, 1104, 3500} = -4.74853e-17 / 1 / null  / null 
  string   /adios_schema/version_major                       attr   = "1"
  string   /adios_schema/version_minor                       attr   = "1"
  string   /adios_schema/mesh/type                           attr   = "rectilinear"
  string   /adios_schema/mesh/dimensions0                    attr   = "nzwg001"
  string   /adios_schema/mesh/dimensions1                    attr   = "nyvg001"
  string   /adios_schema/mesh/dimensions2                    attr   = "nxug001"
  integer  /adios_schema/mesh/dimensions-num                 attr   = 3
  string   /adios_schema/mesh/coords-multi-var0              attr   = "Z001"
  string   /adios_schema/mesh/coords-multi-var1              attr   = "Y001"
  string   /adios_schema/mesh/coords-multi-var2              attr   = "X001"
  integer  /adios_schema/mesh/coords-multi-var-num           attr   = 3
  string   /adios_schema/mesh/nspace                         attr   = "3"
  string   /adios_schema/mesh/time-varying                   attr   = "yes"
  double   /adios_schema/mesh/time-steps-count               attr   = 43400
  double   /adios_schema/mesh/time-scale-count               attr   = 0.00543711
  string   concentration_EtOH/adios_schema                   attr   = "mesh"
  string   concentration_EtOH/adios_schema/centering         attr   = "cell"
  double   concentration_EtOH/adios_schema/time-steps-count  attr   = 43400
  double   concentration_EtOH/adios_schema

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by brugger1** [comment]
Hi Stéphane,

VisIt had a lot of code that used int for sizes instead of size_t. I suspect a lot of that code has been fixed, but there may still be instances where it is an issue. That change comment probably refers to a specific case where that was fixed. Judging from the error message you are seeing the ADIOS reader has been coded to be conservative in this regard.

I believe at this point we should remove the check and then if something breaks fix it. I will mention that if you try to visualize a file with a single block of 4 billion cells that the performance will be rather slow. We could add logic to automatically break up the single block into multiple blocks as we have done with other readers when running in parallel. Would you be able to run in parallel to take advantage of such a solution? If so, I can look into making that change as well.

Eric

**Comment by brugger1** [comment]
Hi Eric,

Thanks for you answer. Yes I can run it in parallel.

Best regards
Stéphane

**Comment by brugger1** [comment]
Hi Stéphane,

I got some feedback from other VisIt developers that there are spots in VisIt that would need changing to handle more than 4 billion cells in a single block, soremoving that test in the ADIOS reader wouldn't be helpful and would lead to crashes. I have submitted a ticket to enhance the ADIOS reader to automatically break up large blocks in parallel. I will look into the effort to do that this week.

Eric

**Comment by brugger1** [comment]
Hi Eric,
OK, thanks for your help !
Stéphane

**Comment by markcmiller86** [comment]
@brugger1 any guidance regarding effort involved in implementing automatic decomposition in ADIOS plugin.

**Comment by brugger1** [comment]
I haven’t looked at it yet. I believe it is an hdf5 file under the hood and logic from the pixie reader could be used as a starting point. I also found another reader that used a different splitting method, but I can’t recall the name of the plugin. One did the splitting using a method in one of the base classes and the other had its own splitting logic.

**Comment by cyrush** [comment]
the also have their own file format, auto-decomp would probably have to been done at the ADIOS level

**Comment by markcmiller86-visit** [comment]
Please remove me from this list.

**Comment by brugger1** [comment]
Hello,
Instead of ADIOS bp file, is xdmf+hdf5 VisIT reader OK above 2 billion cells ?
Thanks for your answer, regards
Stéphane

**Comment by brugger1** [comment]
While any particular file format *may* support over 2 billion cells, the problem is that VisIt internals as well as the VTK classes/APIs VisIt is using presently do not.

Out of curiosity...are GPUs involved in any way with creating the >2b cell datasets you have?

Mark

**Comment by brugger1** [comment]
Hi Stéphane,

The Pixie reader is a basic HDF5 reader that will automatically split structured grids when run in parallel. For example, if you have a grid with 16 billion cells and run VisIt with 16 processors, VisIt will split the data into 16 1 billion cell grids, which will work with VisIt. You could take your HDF5 file and specify the Pixie reader when opening the file, using enough processors to get the data per processor below the 2 billion cell limit.
Eric

**Comment by markcmiller86-visit** [comment]
OK thanks, I will try a basic HDF5 file since I have a rectilinear grid.
Regards
Stéphane

Le 14/04/2020 à 18:53, Eric Brugger via visit-users a écrit :

**Comment by markcmiller86-visit** [comment]
Hi,

I have done a small .h5 file test that contains the mesh coordinates of 
a rectilinear grid and a scalar associated (temperature).
The file is read with pixie reader, temperature field is ok, but the 
domain appears as a cube, with cubic cells, coordinates are not OK 
(instead I have the number of cells in each direction)

So the grid is not properly read. I did not find any documentation on 
the structure of the expected HDF5 files, or on the naming convention of 
the coordinates.

Is there a way with visit to associate coordinates to a given data of 
the h5 file ?

I can also try to guess how to write the .h5 file thanks to h5dump of 
some pixie database files, but I can't find them
(src/test/tests/databases/pixie.py script tests 
pixie_test_data/pixie3d3.h5 and pixie_test_data/pixie3d4.h5 files)
They do not seem to be there 
https://wci.llnl.gov/simulation/computer-codes/visit/datafiles

I have also tried to had an xmdf xml file associated to the h5 file and 
everything works fine, the grid is correct.
But Mark did not mention that the xdmf plugin has an automatic block 
decomposition with the number of processor used, so I am not sure it is 
pertinent to go on
with xdmf ?

Finally, Vs reader does the same, no documentation.

Thanks for your help
Stéphane




Below the code to write the h5 file adapted from 
http://www.visitusers.org/index.php?title=Using_XDMF_to_read_HDF5

   call h5open_f(error)
   call h5fcreate_f("test.h5", H5F_ACC_TRUNC_F, file_id, error)

   dims1 = (/ ie-is+1 /)
   call H5Screate_simple_f(1, dims1, dataspace, error)
*call H5Dcreate_f(file_id, "/xcoords", H5T_NATIVE_DOUBLE, dataspace, 
dataset, error)*
   call H5Dwrite_f(dataset, H5T_NATIVE_DOUBLE, coord_x(is:ie), dims1, error)
   call H5Dclose_f(dataset, error);
   call H5Sclose_f(dataspace, error);

   dims1 = (/ je-js+1 /)
   call H5Screate_simple_f(1, dims1, dataspace, error)
*call H5Dcreate_f(file_id, "/ycoords", H5T_NATIVE_DOUBLE, dataspace, 
dataset, error)*
   call H5Dwrite_f(dataset, H5T_NATIVE_DOUBLE, coord_y(js:je), dims1, error)
   call H5Dclose_f(dataset, error);
   call H5Sclose_f(dataspace, error);

   dims1 = (/ ke-ks+1 /)
   call H5Screate_simple_f(1, dims1, dataspace, error)
*call H5Dcreate_f(file_id, "/zcoords", H5T_NATIVE_DOUBLE, dataspace, 
dataset, error)*
   call H5Dwrite_f(dataset, H5T_NATIVE_DOUBLE, coord_z(ks:ke), dims1, error)
   call H5Dclose_f(dataset, error);
   call H5Sclose_f(dataspace, error);

   dims3 = (/ ie-is+1,je-js+1,ke-ks+1 /)
   call H5Screate_simple_f(3, dims3, dataspace, error)
   call H5Dcreate_f(file_id, "/temperature", H5T_NATIVE_DOUBLE, 
dataspace, dataset, error)
   call H5Dwrite_f(dataset, H5T_NATIVE_DOUBLE, 
temperature(is:ie,js:je,ks:ke), dims3, error)
   call H5Dclose_f(dataset, error);
   call H5Sclose_f(dataspace, error);

   call H5Fclose_f(file_id, error);

*and the xmdf file*

<?xml version="1.0" ?>
<!DOCTYPE Xdmf SYSTEM "Xdmf.dtd" []>
<Xdmf xmlns:xi="http://www.w3.org/2003/XInclude" Version="2.2">
   <Domain>
     <Grid Name="rectilinear_scalar" GridType="Uniform">
       <Topology TopologyType="3DRECTMesh" NumberOfElements="8 8 8" />
       <Geometry GeometryType="VXVYVZ">
         <DataItem Name="*xcoords*" Dimensions="8" NumberType="Float" 
Precision="4" Format="HDF">
             test.h5:/xcoords
         </DataItem>
         <DataItem Name="*ycoords*" Dimensions="8" NumberType="Float" 
Precision="4" Format="HDF">
             test.h5:/ycoords
         </DataItem>
         <DataItem Name="*zcoords*" Dimensions="8" NumberType="Float" 
Precision="4" Format="HDF">
             test.h5:/zcoords
         </DataItem>
       </Geometry>
       <Attribute Name="temperature" AttributeType="Scalar" Center="Node">
         <DataItem Dimensions="8 8 8" NumberType="Float" Precision="4" 
Format="HDF">
           test.h5:/temperature
         </DataItem>
       </Attribute>
     </Grid>
   </Domain>
</Xdmf>



Le 14/04/2020 à 18:53, Eric Brugger via visit-users a écrit :

**Comment by brugger1** [comment]
Hi Stéphane,

I'll have to take a look at the Pixie reader to see if there is anyway to associate arrays with in the HDF5 file with the coordinates. I suspect that the XDMF reader doesn't automatically decompose arrays in parallel like the Pixie reader, but I'll need to check the code for that as well.

One thought is that if the coordinates have constant spacing in each of the three coordinate directions, you could apply the transform operator to scale and translate the coordinates that the reader generates.

Eric

**Comment by markcmiller86-visit** [comment]
Hi,
OK thanks (mesh can be stretched)
Regards
Stéphane

Le 17/04/2020 à 17:11, Eric Brugger via visit-users a écrit :

**Comment by markcmiller86-visit** [comment]
Hi,
So I have written a Pixie hdf5 file output. It works fine with our 
parallel code.

VisIt 3.1.1 can open pixie files on 1 processor but, on several 
processors, only one sub domain is plotted, whatever the partitioning 
X,Y or Z Slab choice.
Enclosed the outputs with  4 processors, with Z Slab and Y slab. One 
fourth of the domain is plotted, coordinates are not good
(domain should be rectangular as shown in the last enclosed image)

I have built visit on my local system with the following options (I have 
same same problem on a remote supercomputing center)

  ./build_visit3_1_1 --makeflags -j16 --parallel --tbb --adios --ospray 
--embree  --mxml  --hdf5 --xdmf --icet --silo
Visit is launched with "-np" option.

So I am wondering if I miss something ? May I share a small .h5 file ?

Thanks, regards
Stéphane


Le 14/04/2020 à 18:53, Eric Brugger via visit-users a écrit :

**Comment by markcmiller86-visit** [comment]
Hi,
To complete previous mail, I have switched to "Regular" pixie file and 
VisIt works fine on several processors (using coordinate scaling to get 
the correct ones).

So display problem is only relative to "Curvilinear" pixie file (that is 
necessary for a non-uniform rectilinear mesh).

Thanks, regards
Stéphane



Le 16/05/2020 à 17:11, Stéphane Glockner a écrit :

**Comment by brugger1** [comment]
Yes, a small file would be useful.

**Comment by markcmiller86-visit** [comment]
Enclosed a small file (8x8x8 cells).
Thanks
Stéphane

Le 18/05/2020 à 16:09, Eric Brugger via visit-users a écrit :

**Comment by biagas** [comment]
I grabbed the sample data file off the users list archive, zipped it and added it here.

[dirichlet_3D_000001-0001.h5.zip](https://github.com/visit-dav/live-customer-response/files/4647194/dirichlet_3D_000001-0001.h5.zip)

**Comment by biagas** [comment]
Thank you very much for the data, I created a bug [ticket](https://github.com/visit-dav/visit/issues/4749).

**Comment by brugger1** [comment]
I have found and fixed the bug causing the incorrect behavior with curvilinear meshes. I will probably have a pull request in on Tuesday (Monday is Memorial Day).

**Comment by markcmiller86-visit** [comment]
Thanks for all.
Stéphane

Le 22/05/2020 à 22:31, Eric Brugger via visit-users a écrit :

**Comment by brugger1** [comment]
I merged the fix in. It is targeted for visit 3.1.3. You can either grab the source code from the 3.1RC and build it or I can build you a version for your platform of interest. Let me know what you would like.

**Comment by markcmiller86-visit** [comment]
I will do it. Thanks.
Stéphane

Le 28/05/2020 à 22:33, Eric Brugger via visit-users a écrit :
