### ISSUE TITLE
How to generate movie with changing of displacement multiplier

### ISSUE THREAD

**Issue by griffin28** [visit-dav/live-customer-response#130]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

Sir:
I want to generate movie using visit.
What I want to draw is a mesh with the displace operator. That is, the deformation of the mesh.
I already have a mesh and a vector field.
I want generate the movie using follow frames.
(1) the deformation of the mesh with displacement multiplier 0.
(2) the deformation of the mesh with displacement multiplier 10.
(3) the deformation of the mesh with displacement multiplier 20.
(4) the deformation of the mesh with displacement multiplier 30.
(.) the deformation of the mesh with displacement multiplier ....
(11) the deformation of the mesh with displacement multiplier 100.
 
The moive is always be used during structure modal analysis.
There is an example that what I want to draw:
https://github.com/mkraska/CalculiX-Examples/tree/master/Test/Supports
 
A vtk file with a grid and  vector field is attached.
 
How can I implement that using Visit GUI?
I apologize if it is a stupid problem. Thanks for your time.
 

 
 
徐辉，Xu Hui
清华大学航天航空学院博士研究生
PhD Candidate, School of Aerospace Engineering
Tsinghua University
Tel： 188-1152-7137
Mail：459543524@qq.com

**Comment by griffin28** [comment]
Xu...encoding the movie with a Python script from VisIt's **Commands** window is probably the best option. See this [reference](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/tutorials/MakingMovies.html#encoding-the-movie-with-a-python-script). You can record the initial Python code to get started (See [Recording a macro](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/CommandWindow/Macros.html)).

Your script would look something like this:

```
from visit_utils import * 

OpenDatabase("noise.silo")
AddPlot("Vector", "grad")
AddOperator("Displace")
DisplaceAtts = DisplaceAttributes()

for factor in range(0,100,10):
    DisplaceAtts.factor = factor
    DisplaceAtts.variable = "default"
    SetOperatorOptions(DisplaceAtts)
    DrawPlots()
    SaveWindow()
    DeleteActivePlots()

encoding.encode("Desktop/visit%04d.png", "Desktop/movie.mpg", fdup=3) 
```

**Comment by qzxuhui** [comment]
Wow, thanks sir, the solution is wonderful. I now can use the script to generate the movie!

**Comment by markcmiller86** [comment]
@qzxuhui thanks for letting us know. Good luck.
