### ISSUE TITLE
Plot a 1d extract from a 2d mesh versus time

### ISSUE THREAD

**Issue by brugger1** [visit-dav/live-customer-response#131]
I have a user that has 2d MFEM data and would like to extract a 1d slice over time (I assume from a structured grid) to create a 2d mesh.

Do we have any way of doing this built in, or do we have to resort to scripting and processing with Python?

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by markcmiller86** [comment]
Hmmm...MFEM is only *unstructured*. So, am not really sure what your paranthetical (*I assume from structured grid*) means. 

A 1d slice is a lineout, right?. We can definiately update a single lineout as we move through time. However, taking a series of 1D lineouts and assembling a 2D mesh...I don't think you can do that without scripting (and effectively exporting and re-importing).

Does that help?

**Comment by brugger1** [comment]
Yes. I was hoping for a solution that was better than exporting and re-importing, but figured it might not exist. People have added weird features over time and I thought I’d ask before going down that route.

**Comment by markcmiller86** [comment]
Its always felt to me like we can create variables easily, but I think we fundamentally lack an ability to arbitrarily create new *meshes* from existing meshes (or extracts thereof) *without* an export/import iteration.

We have many operators that do a specific thing to a mesh, creating a new mesh (slice, lineout, reflect, project, external surface, extrude, resample) that is in some sense *reduced* (in topological or geometrical dimensionality (e.g. project) or in somehow using a subset of the original mesh). **But, the meshes so "created" do not exist as independent objects we can use to re-input to other things like we can variable expressions for example.**

However, building *up* a mesh from smaller bits and pieces isn't something we easily handle. That said, now that I write this, the imgvol plugin does effectively assemble a 3D volumetric mesh from a set of 2D "slices").

**Comment by brugger1** [comment]
I don't think there is anyway to combine the individual slices using operators in VisIt, so I think I will need to create it with Python. Here is what I am thinking of doing:

Write out all the slices as VTK files.
Loop over the VTK files reading them and building up a 2D dataset
Write out the 2D dataset as a VTK file

Does this sound reasonable or does anyone else have a better solution.

I will use the VTK python interface for reading/writing the VTK files, as well as building the 2D dataset.

**Comment by brugger1** [comment]
After some iteration I determined the user wanted to stack a bunch of 2d plots vertically from a time series. I sent her the following script that does just that with one of our sample data sets. It does it a plot from each time step, appropriately translated.

OpenDatabase("/usr/gapps/visit/data/dbA00.pdb")
nStates = TimeSliderGetNStates()
for state in range(0, nStates):
    TimeSliderSetState(state)
    AddPlot("FilledBoundary", "material")
    atts = FilledBoundaryAttributes()
    atts.legendFlag = 0
    SetPlotOptions(atts)
    AddOperator("Transform")
    atts = TransformAttributes()
    atts.doTranslate = 1
    atts.translateY = state * 5.
    SetOperatorOptions(atts)
    DrawPlots()
    SetPlotFollowsTime(0)

She replied that she got it to work and it did what she wanted.
