### ISSUE TITLE
Problems Searching the Visit-Users Mailing List?

### ISSUE THREAD

**Issue by biagas** [visit-dav/live-customer-response#132]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
I have been searching this mailing list for the past few weeks to find hints on issues I've been having with Python expressions and the like and, up until a week ago, the search function has been working fine.

The link is the same as usual (https://elist.ornl.gov/mailman/private/visit-users/) but at the top of the page, the search box is missing. Now there is text that looks like broken HTML (see below):

Other than downloading all the gzipped text and making a script to search it, how else would I be able to search the user archives? I have also tried searching the visit forum but that interface is terrible and does not contain much compared to this mailing list. Likewise, the github page contains a lot but is mainly about bugs and feature requests.

Thank you,
Anna

**Comment by biagas** [comment]
Sorry for the delayed response.
There is something definitely wrong, thank you for the report. I have sent a request to the site maintainers about getting it working again.

Kathleen

**Comment by biagas** [comment]
@brugger1 do you know who to contact at ORNL about this?

**Comment by brugger1** [comment]
Possibly Dave Pugmire or just their general computer help line.

**Comment by biagas** [comment]
Opened bug ticket.
