### ISSUE TITLE
can Visit read ASCII VTK files

### ISSUE THREAD

**Issue by brugger1** [visit-dav/live-customer-response#134]
From walton@grainflow.com:

Eric, 
Please forward this to whoever handles VisIt help questions.  
I would like to use VisIt to visualize particles from some new DEM simulations I am beginning work on.  I generated a set of particles in a Python script (to act as boundaries for the DEM simulation) and wanted to 'look' at the configuration (using VisIt).  I wrote out what I thought was a VTK format (ASCII) file with the particle coordinates but could not read it with VisIt (VisIt expected a 'VTK Silo', file not an ASCII file) . The head of the file generated by the Python script is: 
  
head -20 coords_vels.vtk 
vtk DataFile Version 3.0 
SCD model w/ points for auger blade version 01 
ASCII 
DATASET coords velocities 
POINT_DATA 12420 coords, Velocity vectors 
0.053562 -0.000000 0.000000 0.0000000 0.000 0.000 
0.053543 -0.001463 0.000167 0.0000000 0.000 0.000 
0.053483 -0.002925 0.000334 0.0000000 0.000 0.000 
0.053383 -0.004385 0.000500 0.0000000 0.000 0.000 
0.053243 -0.005841 0.000667 0.0000000 0.000 0.000 
0.053064 -0.007293 0.000834 0.0000000 0.000 0.000 
  
but when I clicked on the file to have VisIt read it I obtained: 
"VisIt could not read from the file "/home/otis/JSC_Simulations-2020/coords_vels.vtk". 
The generated error message was: 
There was an error opening /home/otis/JSC_Simulations-2020/coords_vels.vtk. It may be an invalid file. 
VisIt tried using the following file format readers to open the file: VTK, Silo 
If you know the specific format reader VisIt should use to 
read this data, you can use Open As... (GUI) or 
'-o <file>,<plugin> (CL arg.) and identify that specific reader 
for VisIt to try. This will possibly give more information on 
the exact error." 
  
Can I use an ASCII file to provide input data to VisIt? 
  
Thanks 
Otis Walton 
(925) 784-4501 

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by markcmiller86** [comment]
Its concievable the VTK file your Python script created is subtley wrong. I will post here an example that I know does work and maybe you can use that to tease out the differences in what your Python script is producing. Look for another email on this in a bit.

Also, this message from VisIt...

> VisIt tried using the following file format readers to open the file: VTK, Silo

doesn't mean ... *"VisIt expected a 'VTK Silo', file not an ASCII file"*.

This message is indicating it tried `VTK` format and next tried `Silo` format and neither succeeded. It tried `VTK` because of the file extension. It tries `Silo` because VisIt's default behavior is to fall back to Silo before giving up entirely.

**Comment by markcmiller86** [comment]
I just now noticed that the line...

> `vtk DataFile Version 3.0`

In your output from `head` appears to be missing the comment designator. To ensure it is created as a comment it should look like...

> `# vtk DataFile Version 3.0`

Below I have pasted the contents of an example vtk ascii file that plots correctly which includes two scalar variables, `var1`, and `var2` and one vector variable, `vel`. Try adjustijng your script to conform to this format.

```
# vtk DataFile Version 4.2
my example data file
ASCII
DATASET UNSTRUCTURED_GRID

POINTS 30 float
0 0 0 1 0 0 2 0 0 
0 0 1 1 0 1 2 0 1 
0 1 0 1 1 0 2 1 0 
0 1 1 1 1 1 2 1 1 
0 2 0 1 2 0 2 2 0 
0 2 1 1 2 1 2 2 1 
1 3 1 2.75 0 1 3 0 0.75 
3 0.25 1 3 1 1 3 1 0 
2.75 2 1 3 1.75 1 3 1.75 0.75 
3 0 0 2.575 0.425 0.575 2.59375 1.4375 0.71875 

POINT_DATA 30
VECTORS vel float
3 3 3 3 3 3 3 3 3 
3.3 3.3 3.3 3.3 3.3 3.3 3.3 3.3 3.3 
10.5 10.5 10.5 10.5 10.5 10.5 10.5 10.5 10.5 
10.8 10.8 10.8 10.8 10.8 10.8 10.8 10.8 10.8 
27 27 27 27 27 27 27 27 27 
27.3 27.3 27.3 27.3 27.3 27.3 27.3 27.3 27.3 
81 81 81 3.3 3.3 3.3 3.15 3.15 3.15 
4.5 4.5 4.5 10.8 10.8 10.8 10.5 10.5 10.5 
27.3 27.3 27.3 25.5 25.5 25.5 25.35 25.35 25.35 
1.37749e-40 1.37749e-40 1.37749e-40 5.985 0 5.985 18.5062 0 18.5062 

FIELD FieldData 2
var1 2 30 int
0 0 0 1 0 2 0 3 0 
4 0 5 0 6 0 7 0 8 
0 9 0 10 0 11 0 12 0 
13 0 14 0 15 0 16 0 17 
0 18 0 19 0 20 0 21 0 
22 0 23 0 24 0 25 0 26 
0 27 0 -1 0 -1 
var2 1 30 float
1 1 1 1.1 1.1 1.1 3.5 3.5 3.5 
3.6 3.6 3.6 9 9 9 9.1 9.1 9.1 
27 1.1 1.05 1.5 3.6 3.5 9.1 8.5 8.45 
4.59163e-41 1.995 6.16875 
```

**Comment by markcmiller86** [comment]
In the interim of reporting this issue and getting a response, the user had success with a different format.
