### ISSUE TITLE
Batch job errors on zin pvis

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#135]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Something has changed with Visit when launching the engine on zin's pvis partition. I now get a license error: "Batch job submission failed: invalid license specification." It doesn't happen on zin's debug partition or pvis partitions on other machines.

**Comment by brugger1** [comment]
That looks like a batch system issue. I would contact LC.

**Comment by rusu24edward** [comment]
It is resolved now. LC made a TOSS update last week that broke it and an admin just fixed it.
