### ISSUE TITLE
CLI window does not appear on Catalina 10.15.6

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#136]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Currently I'm using VisIt 3.0.2 (for compatibility with a remote server).  I'm running the client on a MacBook Pro running masOS Catalina version 10.15.6.  When I try to launch a CLI window the "Launch in progress" window appears but the CLI window never comes up.  When I "Cancel" the "Launch in progress" window, I get the error message:
VisIt could not connect to the new client /Applications/VisIt.app/Contents/Resources/bin/visit.
This was working with the previous version of Catalina I was running. I suspect there is a permission issue of some type.
Does anyone know how to fix this problem? Thank you for your time and help!

**Comment by rusu24edward** [comment]
Hi Terry,

Can you try launching Visit from the command line using this command:

```
/Applications/VisIt.app/Contents/Resources/bin/visit
```
and repeat the same steps. Do you get the same error?

**Comment by markcmiller86-visit** [comment]
Thanks for the suggestion/diagnostic!  Running VisIt from the command 
line allowed the CLI to launch successfully.  The window it's using is 
my normal xterm format while the one that wouldn't launch, when it used 
to launch, was different (e.g., black on white vs. white on black 
foreground/background, size).

Better yet, I can now make movies again (which depend on the CLI 
launching)!  There's still a problem when I launch VisIt from its icon 
BUT at least I can continue with my current work.

Many thanks!

                                 Terry J. (Ligocki, tjligocki@lbl.gov)

On 9/8/20 9:41 AM, Edward Rusu via visit-users wrote:
>
> Hi Terry,
>
> Can you try launching Visit from the command line using this command:
>
> |/Applications/VisIt.app/Contents/Resources/bin/visit |
>
> and repeat the same steps. Do you get the same error?
>
------------------------------------------------------------------------
*[Winds of] Change
*
/When the winds of change blow hard enough,
the most trivial of things can become deadly projectiles.
/
(Despair, Inc.)

**Comment by rusu24edward** [comment]
Hi Terry,

Glad to hear that this works as a path forward and allows you to make movies again!

Regarding using the icon, this may indeed be an issue with permissions. This has come up before as a previous inquiry, and a solution was suggested. Would you mind checking out [this issue](https://github.com/visit-dav/live-customer-response/issues/111) and seeing if resolving the permissions allows you to use the icon?

Eddie

**Comment by tjligocki-lbl** [comment]
I added "Full Disk Access" for "Terminal" under "System Preferences" -> "Security & Privacy" -> "Privacy" -> "Full Disk Access" and now the CLI launches without a problem if run from the icon!  Many thanks...

**Comment by rusu24edward** [comment]
That's great! Thanks for following up on this Terry! We're starting to get a clearer picture of all the necessary steps to smoothly run on Catalina.
