### ISSUE TITLE
Connecting to LLNL systems from ORNL via VPN

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#137]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hello,
 
I am trying to use VisIt to connect to remote clusters (borax & quartz) at LLNL from ORNL, so that I can visualize results generated from ALE3D.
 
If I am not directly connected to the ORNL network or on VPN (e.g. at home, no VPN), then I can view my results remotely.  If I am on VPN or directly connected at ORNL, then the connection will not go through…. it just stalls out. 
 
For Putty and Filezilla connections to LLNL, I must use an ORNL proxy server.  Is there a way to specify a proxy server in VisIt?
 
Thanks for any help.
 
Best,
 
Justin

**Comment by rusu24edward** [comment]
Hi Justin,

I'm not aware of a way to specify proxy servers in VisIt. We do have a feature in our host profiles to [use a gateway](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/ClientServer/Host_Profiles.html?highlight=host%20profiles#gateway), which you may be able to use as a proxy. If you set the gateway host to the ORNL machine and setup [passwordless ssh](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/ClientServer/Client_server_mode.html#settinguppasswordlessssh) between ORNL and LLNLmachines, then this might work.

Can you give it a try and let me know what happens?

**Comment by rusu24edward** [comment]
Another thought: can you double check that you have port-forwarding through ssh selected?

**Comment by machjc** [comment]
Thanks for the advice!  I have tried various ssh options to specify the proxy server, but did not have any luck.  I am reaching out to ORNL IT folks again to see if they have any further advice.  Thank you!

**Comment by machjc** [comment]
This is the ssh command that I must use to connect to borax:  ssh  -o ProxyCommand="nc -X connect -x snowman.ornl.gov:3128 %h %p" mach1@borax.llnl.gov.  This works in Windows via Cygwin.  It also works in Linux CentOS by replacing the -X connect -x with --proxy.

But, I can't seem to get VisIt to use it.  How can I override the use of qtssh.exe in VisIt?  I found an old thread about editing the registry, but I couldn't find the registry keys for VisIt.

**Comment by machjc** [comment]
It seems like no matter what I put in the "ssh Command" box in the VisIt profile, I get the same behavior:
![image](https://user-images.githubusercontent.com/71343347/93257272-96fd5400-f76a-11ea-8479-7be4d25a0ac6.png)

**Comment by rusu24edward** [comment]
Hmm... that would have been my suggestion. Tagging @visit-dav/visit-developers to see if anyone has experience with this.

**Comment by biagas** [comment]
If you want to override qtssh while running VisIt on a Windows machines, set a couple of environment variables:
**VISITSSH** to point to your desired ssh executable
**VISITSSHARGS** containing any arguments needed for your ssh

If you are running Windows 10, from the startmenu type 'environment' then choose 'Edit environment variables for your account'. User variables should be shown at the top. Click 'New' and add _VISITSSH_ as the _Variable name_, and the full path as the _Variable value_ , then repeat for _VISITSSHARGS_.

VisIt should pick up this new ssh next time you launch.

**Comment by machjc** [comment]
Thank you!  That did redirect the ssh command; unfortunately, I still get stuck at the metadata server launch phase and it just hangs:
![image](https://user-images.githubusercontent.com/71343347/93262135-b64baf80-f771-11ea-9f26-3e0f661ccefb.png)
