### ISSUE TITLE
Legend and triad stretching with window aspect ratio...

### ISSUE THREAD

**Issue by tjligocki** [visit-dav/live-customer-response#140]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

I've noticed that when the viewing/render window is stretched, i.e. the aspect ratio isn't 1:1, the legends and triad get distorted by the amount of stretching.  In the case of the legends, I can try to correct this by changing the width of the legend but it seems like this legend aspect ratio should be independent of the display window aspect ratio.  In the case of the triad, there isn't way I know of to correct this distortion and relative length of the triad axes independent of the display window aspect ratio.

When I don't correct the legends when the display window doesn't have a 1:1 aspect ratio, they don't look nearly as good as when the ratio is 1:1.  The triads simply look wrong.

Thanks for any thoughts, comments, etc.

                    Terry J. (Ligocki, tjligocki@lbl.gov)

**Comment by rusu24edward** [comment]
Hi Terry,

I cannot immediately duplicate this issue. Can you provide more details?
* What kind of plot are you doing (e.g. Pseudocolor)?
* Are you seeing this using client-server?
* What is your os (I assume from your previous inquiries that Catalina is your os)?
* Can you provide some snapshots that demonstrate this distortion?

Thanks,
Eddie

**Comment by tjligocki-lbl** [comment]
This has been an on going issue (for me) even since I can remember using VisIt, on all OS's, with or without client-server, etc.  That said, I will provide some example images as soon as I can generate some...

**Comment by tjligocki-lbl** [comment]
Below are three images.  The first image has a 1:1 aspect ratio and the legend and triad look reasonable (to me).  In the second image, I reduced the height considerably.  This caused the legend and triad to shrink in the same direction.  In my opinion, ideally, both would retain the same proportions they had in the first image.  To do this they may need to shrink in both directions (as the object in the image did).  The third image , I reduced the width considerably.  Again, I think the legend and triad shouldn't change aspect ratio.

I hope this makes some sense and clarifies the issue...

![visit_normal](https://user-images.githubusercontent.com/2855958/92648094-c9580e80-f29d-11ea-9020-6a9256a79a90.png)
![visit_long](https://user-images.githubusercontent.com/2855958/92648202-ef7dae80-f29d-11ea-9182-62d8e0a5f96a.png)
![visit_narrow](https://user-images.githubusercontent.com/2855958/92648232-fad0da00-f29d-11ea-8858-5f2859e04375.png)

**Comment by brugger1** [comment]
Wow, I'm able to reproduce the triad issue trivially. I've never noticed it before, probably because I normally have a window with close to a 1:1 aspect ratio.

The legend behavior actually make sense to me, since the width of the legend is a fraction of the width of the window. For the annotations the positioning is done in a 0 to 1 space of the window, so as the aspect ratio changes the positions change. The sizing is done either as a fraction of the width or height of the window, so again things may change as the aspect ratio changes. I don't know of a better solution than that.

**Comment by rusu24edward** [comment]
Thanks for the images, Terry, and for the comments, Eric. I was paying attention to the axis and not the legend and triad. I can reproduce this as well. I've added this as an [issue in our main issue tracker](https://github.com/visit-dav/visit/issues/5037)
