### ISSUE TITLE
Using already allocated resources on LC

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#142]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hello everyone,
 
Is there a way to launch a custom build of VisIt in parallel using the currently allocated resources? For launching in parallel, I usually do something like this
./bin/visit -np 4 -nn 1 -l "msub/srun" -p pvis
 
But this allocates new resources. If I already have an allocated node, I’d like to just launch using those processors. I’ve tried other variations of this command without much luck.
 
Thanks,
Alister

**Comment by rusu24edward** [comment]
Hi Alister,
 
I’m assuming you used an mxterm to get your allocation. In this case you can use “srun” and drop the “-p pvis”.
 
Eric

**Comment by rusu24edward** [comment]
Just adding this info here because it's nice to know.

**Comment by markcmiller86** [comment]
We've probably titled this wrong [here](http://www.visitusers.org/index.php?title=Visit-tutorial-time-savers#Using_mxterms_to_grab_and_hold_onto_compute_resources) and it needs to be migrated to our RTD docs.

**Comment by aowen87** [comment]
Hey Eric,

Thanks for the info. I actually was using an interactive node (no mxterm). I’m guessing the process is the same? I’ll try it out today.

Thanks,
Alister

**Comment by cyrush** [comment]
yes, if you are already in an allocation you can use:

visit -np 2 -l srun

**Comment by cyrush** [comment]
if you are in python, are on a slurm system, and already have an allocation you can also use:

```
import visit_utils
visit_utils.engine.open(method="slurm")
```

This will look at the slurm env vars and launch the engine with the number of MPI tasks in your allocation.

**Comment by aowen87** [comment]
Great! Thanks, Cyrus!

Alister

**Comment by markcmiller86-visit** [comment]
Worked perfectly!
Alister


From: Alister via visit-users <visit-users@elist.ornl.gov>
Reply-To: visit-dav/live-customer-response <reply@reply.github.com>, VisIt software users community <visit-users@elist.ornl.gov>
Date: Thursday, September 10, 2020 at 8:26 AM
To: visit-dav/live-customer-response <live-customer-response@noreply.github.com>
Cc: Alister <notifications@github.com>, Subscribed <subscribed@noreply.github.com>
Subject: [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] Using already allocated resources on LC (#142)

Hey Eric,

Thanks for the info. I actually was using an interactive node (no mxterm). I’m guessing the process is the same? I’ll try it out today.

Thanks,
Alister
