### ISSUE TITLE
Get xy values from Query over time

### ISSUE THREAD

**Issue by biagas** [visit-dav/live-customer-response#144]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

Hi Mark,

I’m making progress, but have reached another impasse, where I’m trying to export the curve created by a Query over time operation to an alpha numeric data file with (x,y) values to use for post-processing in another application.

As you can see from the attached screenshot, the Query-over-time produced a nice plot of the surface integral value.  But the QUERY GUI doesn’t show the alpha-numeric information, as it does when we query just one instant in time, and I can’t figure out how to export the curve data with readable (x,y) data values.

I couldn’t find anything in the Manual on this issue.

Thanks for looking at this.
Greg

**Comment by biagas** [comment]
@rusu24edward 
I didn't put the screenshot here, as I wasn't sure if the customer would want it displayed publicly.

**Comment by markcmiller86** [comment]
Thanks @biagas for posting here. I should have done that. Instead, I had already responsed to the user via direct email (contrary to the policy I've advocated for :confused:). @rusu24edward I think its probably fine to close this. Have asked user for his GitHub handle though and will post here when/if available.
