### ISSUE TITLE
Re: VisIt cannot access local directories, mac catalina

### ISSUE THREAD

**Issue by brugger1** [visit-dav/live-customer-response#145]
I know there has been a lot of discussion of running VisIt on Mac and hanging on startup lately, but I seem to have an unusually stubborn problem.

I'm running 10.15.6 Catalina and every time I execute visit, it hangs.  I've given Terminal full disk access, and executed VisIt via the command line as mentioned below, yet VisIt still hangs for me.

Is there any way to diagnose what's happening?

Thanks,
Tom Gardiner

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by brugger1** [comment]
When you run from the command line can you add "-debug 5" to the command line and then send the resulting "*.vlog" files. That may provide a clue.

**Comment by markcmiller86-visit** [comment]
________________________________
From: Eric Brugger via visit-users <visit-users@elist.ornl.gov>
Sent: Monday, September 14, 2020 11:30 AM
To: visit-dav/live-customer-response
Cc: Eric Brugger; Subscribed
Subject: [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] Re: VisIt cannot access local directories, mac catalina (#145)


When you run from the command line can you add "-debug 5" to the command line and then send the resulting "*.vlog" files. That may provide a clue.

-

**Comment by markcmiller86-visit** [comment]
Hi Eric,


I've done some additional testing and believe it or not, both of my (work) mac computers have this same problem.  To be clear, I work at Sandia NM and I have the same problem with my laptop as with my desktop Mac.  Both are running 10.15.6.

That being said, I have coworkers that have no problems with visit...


I also installed VisIt on my personal mac at home and of course there it works fine when running it via the command line.


I've tested my environment as well.  On all 3 machines I'm using bash and using the same shell scripts (bashrc, bash_profile, etc.), but just to be sure, I moved these shell scripts out of the way, changed my shell to zsh and tried running VisIt, just in case something in my environment was interfering with the initialization.  Unfortunately, this did not help.


Might you have a suggestion for something else I might try to identify the problem?


Thanks,

Tom Gardiner


________________________________
From: Eric Brugger via visit-users <visit-users@elist.ornl.gov>
Sent: Monday, September 14, 2020 11:30 AM
To: visit-dav/live-customer-response
Cc: Eric Brugger; Subscribed
Subject: [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] Re: VisIt cannot access local directories, mac catalina (#145)


When you run from the command line can you add "-debug 5" to the command line and then send the resulting "*.vlog" files. That may provide a clue.

-

**Comment by markcmiller86** [comment]
If you are launching VisIt by clikcing an icon, does [this guidance](https://github.com/visit-dav/visit/issues/4069), which recommends launch from `Terminal` app command-line, help?
