### ISSUE TITLE
Simple surface integral Query using "weighted variable sum" not working

### ISSUE THREAD

**Issue by burton29-LLNL** [visit-dav/live-customer-response#146]
Trying to calculate: \int x-coord*pressure*dA.  

See attached screenshot.  Surface field quantity is positive-definite as are the x-coordinate values, yet Query outputs a value of exactly 0.0 for each time dump.

<img width="1440" alt="Screen Shot 2020-09-14 at 1 05 29 PM" src="https://user-images.githubusercontent.com/71102332/93133433-123c0880-f68c-11ea-82c9-654e734ea46c.png">

**Comment by brugger1** [comment]
Hi Greg,

I have seen instances in the past where the query over time doesn't work properly, whereas doing the same query at a single time state works fine. Can you try doing the same query at a single time. If that ends up working for you, then I can provide you a simple script that will generate the same result.

Eric

**Comment by burton29-LLNL** [comment]
Eric,

So I’ve got a workaround that seems to produce the proper result.  Since the “weighted variable sum” is weighted by the mesh element area dA, I just created a variable “MeshArea’ that has the same value.  I was then able to use the simpler “variable sum” and got what appears to be the correct result.   That said, I think there may be a bug in VisIT which maybe should be investigated by the developer team.

Greg

============================================
Gregory C. Burton, Ph.D.
Turbulence Analysis & Simulation Center (TASC), Head
Thermal Fluids Group, Group Leader
Computational Engineering Division
Lawrence Livermore National Laboratory
7000 East Avenue, L-140
Livermore, California 94550
(925) 422-3515
burton29@llnl.gov
https://tasc.llnl.gov
============================================

**Comment by brugger1** [comment]
Hi Greg,

Glad you found a workaround.

Can you give me one or two timesteps on one of the open LC systems so that we can investigate.

Eric

**Comment by burton29-LLNL** [comment]
What’s your name on QUARTZ for me to do a give of the tar files?

============================================
Gregory C. Burton, Ph.D.
Turbulence Analysis & Simulation Center (TASC), Head
Thermal Fluids Group, Group Leader
Computational Engineering Division
Lawrence Livermore National Laboratory
7000 East Avenue, L-140
Livermore, California 94550
(925) 422-3515
burton29@llnl.gov
https://tasc.llnl.gov
============================================

**Comment by brugger1** [comment]
brugger

**Comment by burton29-LLNL** [comment]
Just gave you one timestep Aeroshell349.tgz on QUARTZ.  Untar with tar -xvzf Aeroshell349.tgz.

============================================
Gregory C. Burton, Ph.D.
Turbulence Analysis & Simulation Center (TASC), Head
Thermal Fluids Group, Group Leader
Computational Engineering Division
Lawrence Livermore National Laboratory
7000 East Avenue, L-140
Livermore, California 94550
(925) 422-3515
burton29@llnl.gov
https://tasc.llnl.gov
============================================

**Comment by brugger1** [comment]
Hi Greg,

I got you data.

Can you define xPdA for me?  "\int x-coordpressuredA" isn't quite making sense to me.

Eric

**Comment by brugger1** [comment]
Hi Greg,

It looks like doing a weighted variable sum on any variable is giving zero, even though the variable sum is not.

Are all the elements quadrilaterals? If so, I believe that may be the issue. I suspect that quad don't have a volume and the weighted variable sum is weighting by volume, not area.

Eric

**Comment by markcmiller86** [comment]
> I suspect that quad don't have a volume and the weighted variable sum is weighting by volume, not area.

This is one reason I thought it could make sense to adjust this query slightly as described [here](https://github.com/visit-dav/visit/issues/4359#issuecomment-588605515).

**Comment by brugger1** [comment]
I wonder if if makes sense to replace "Weighted variable sum" with "Volume weighted sum" and "Area weighted sum". This might be easier than the solution proposed in the issue you linked to.

**Comment by markcmiller86** [comment]
Just my thinking but...

- That adds 4 queries to already long list where one would work
- User can wind up mis-matching query with their data and be confused with result
- What query is used for mixed-element mesh case

**Comment by markcmiller86-visit** [comment]
The mixed element case seems like it would always be open to interpretation. I would say that if you have a mixed element case and you want both, you do 2 queries or the one that you are interested in. The area one would only do elements with topo dimension 2 and the volume one would only do elements with topo dimension 3. We could also go with 1 query and have them provide an argument indicating which one, although this seems more clumsy (don’t know why, but just does). Also maybe naming them “variable sum weighted by area” and “variable sum weighted by volume” would have them next to each other in the interface and may make it more obvious that they need to think about this issue. Of course having an easy, obvious way to get a precise definition would be good in general, since a lot of our queries aren’t necessarily obvious.

**Comment by burton29-LLNL** [comment]
Hi Eric & Mark,

I’m seeing your chain of e-mails now.  I think that the volume/area issue is important, because the dataset I gave you was a surface of quadrilateral cells, but VisIT didn’t warn that there was no volume defined in the dataset.  That might be a simpler way to look at it.

However, don’t forget that the weighting apparently does work when there is only a single query.  I tried it and it gave me a correct value every time.  It was only when the “query-over-time” was selected did it spit out a series of zeros.

Also, Eric, the math expression is a surface integral of the “x coordinate value” multiplied by the Pressure, multiplied by the differential area of the surface associated with those values for x, and Pressure.  Summing them all up was the point of the operation.  Hence, \integral x*P*dA.   Note that if I change the kernel to unity and calculate the integral I get exactly the surface area of the object, which checked out perfectly when I tried it.

Lastly, a possible bug in version 2.13 I’m seeing on the SCF with this same data set:  when I ask for a query-over-time the first and last lines of the curve are numbers completely unrelated to what I was querying.  It seems VisIT is just adding some numbers to the header and footer lines.

Thanks,
Greg

============================================
Gregory C. Burton, Ph.D.
Turbulence Analysis & Simulation Center (TASC), Head
Thermal Fluids Group, Group Leader
Computational Engineering Division
Lawrence Livermore National Laboratory
7000 East Avenue, L-140
Livermore, California 94550
(925) 422-3515
burton29@llnl.gov
https://tasc.llnl.gov
============================================

**Comment by markcmiller86-visit** [comment]
This is similar to an issue that I had reported a while ago.

I don’t think that adding multiple calls is the right way. Instead you could do any of the following, when querying a weighted variable sum over a combination of sets of different dimensionality (say if you have a domain consisting of a volume A and a surface B and do a weighted average of a field f over A\cup B)
- throw an error because the result is not going to be dimensionally consistent
- ignore the sets of lower dimensionality because a “nice” two dimensional set has 0 volume, so that \int_B f\, dV = 0
- integrate on each set separately and sum, i.e. return \int_A f\, dV + \int_B f\, dS.

I believe that the current behavior is the third one and is the one that makes the least sense from a mathematical standpoint.


Regards,
Blaise


> On Sep 15, 2020, at 3:04 PM, Brugger, Eric via visit-users <visit-users@elist.ornl.gov> wrote:
> 
> The mixed element case seems like it would always be open to interpretation. I would say that if you have a mixed element case and you want both, you do 2 queries or the one that you are interested in. The area one would only do elements with topo dimension 2 and the volume one would only do elements with topo dimension 3. We could also go with 1 query and have them provide an argument indicating which one, although this seems more clumsy (don’t know why, but just does). Also maybe naming them “variable sum weighted by area” and “variable sum weighted by volume” would have them next to each other in the interface and may make it more obvious that they need to think about this issue. Of course having an easy, obvious way to get a precise definition would be good in general, since a lot of our queries aren’t necessarily obvious.
> --
> VisIt Users Wiki: https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fvisitusers.org%2F&amp;data=02%7C01%7Cbourdin%40lsu.edu%7Cc3a73d12f16549199dc508d859b28e95%7C2d4dad3f50ae47d983a09ae2b1f466f8%7C0%7C0%7C637357970722926907&amp;sdata=wpHw6j%2BKDRTu%2FQm4%2BA1KcfafFGyMLPgHQHTRA%2FetXQw%3D&amp;reserved=0
> Frequently Asked Questions for VisIt: https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwci.llnl.gov%2Fsimulation%2Fcomputer-codes%2Fvisit%2FFAQ.html&amp;data=02%7C01%7Cbourdin%40lsu.edu%7Cc3a73d12f16549199dc508d859b28e95%7C2d4dad3f50ae47d983a09ae2b1f466f8%7C0%7C0%7C637357970722926907&amp;sdata=KlE21%2FgV2K5%2Fc2meL%2F8a0CyYIcxTS8dcj%2FSQcCFq7p0%3D&amp;reserved=0
> To Unsubscribe: send a blank email to visit-users-unsubscribe@elist.ornl.gov
> More Options: https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Felist.ornl.gov%2Fmailman%2Flistinfo%2Fvisit-users&amp;data=02%7C01%7Cbourdin%40lsu.edu%7Cc3a73d12f16549199dc508d859b28e95%7C2d4dad3f50ae47d983a09ae2b1f466f8%7C0%7C0%7C637357970722926907&amp;sdata=auk8z85vScW8b4Pdj7%2Bbmi2Zcz77OwGNaSYx30Q8q9E%3D&amp;reserved=0

-- 
A.K. & Shirley Barton Professor of  Mathematics
Adjunct Professor of Mechanical Engineering
Adjunct of the Center for Computation & Technology
Louisiana State University, Lockett Hall Room 344, Baton Rouge, LA 70803, USA
Tel. +1 (225) 578 1612, Fax  +1 (225) 578 4276 Web http://www.math.lsu.edu/~bourdin

**Comment by markcmiller86** [comment]
> - integrate on each set separately and sum, i.e. return \int_A f\, dV + \int_B f\, dS.

What about integrating on each set separately and then returning the separately computed values for each set?

**Comment by markcmiller86-visit** [comment]
> On Sep 16, 2020, at 3:51 PM, Mark C. Miller via visit-users <visit-users@elist.ornl.gov> wrote:
> 
> 
> 	• integrate on each set separately and sum, i.e. return \int_A f, dV + \int_B f, dS.
> What about integrating on each set separately and then returning the separately computed values for each set?

That could work too. IMHO, as long as the result is clearly documented, all is well. That said, is there an easy way to check the dimensionality of a set? 
Blaise


> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> --
> VisIt Users Wiki: https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fvisitusers.org%2F&amp;data=02%7C01%7Cbourdin%40lsu.edu%7Ce78aa63efae64a2d622708d85a824b9e%7C2d4dad3f50ae47d983a09ae2b1f466f8%7C0%7C0%7C637358862942560692&amp;sdata=xXmopI1qHP1jeePDABU2icdNI7%2F6HcNczhUPTh8kjjQ%3D&amp;reserved=0
> Frequently Asked Questions for VisIt: https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwci.llnl.gov%2Fsimulation%2Fcomputer-codes%2Fvisit%2FFAQ.html&amp;data=02%7C01%7Cbourdin%40lsu.edu%7Ce78aa63efae64a2d622708d85a824b9e%7C2d4dad3f50ae47d983a09ae2b1f466f8%7C0%7C0%7C637358862942560692&amp;sdata=HIu6%2BJzoenmPgbVARAABr3QZ%2BPI1ri36bATg%2F9dhQXU%3D&amp;reserved=0
> To Unsubscribe: send a blank email to visit-users-unsubscribe@elist.ornl.gov
> More Options: https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Felist.ornl.gov%2Fmailman%2Flistinfo%2Fvisit-users&amp;data=02%7C01%7Cbourdin%40lsu.edu%7Ce78aa63efae64a2d622708d85a824b9e%7C2d4dad3f50ae47d983a09ae2b1f466f8%7C0%7C0%7C637358862942560692&amp;sdata=uqNM4HZSWEISmSrhUbqV1YyhJu5o4fftGsRhuwDjl7M%3D&amp;reserved=0

-- 
A.K. & Shirley Barton Professor of  Mathematics
Adjunct Professor of Mechanical Engineering
Adjunct of the Center for Computation & Technology
Louisiana State University, Lockett Hall Room 344, Baton Rouge, LA 70803, USA
Tel. +1 (225) 578 1612, Fax  +1 (225) 578 4276 Web http://www.math.lsu.edu/~bourdin

**Comment by markcmiller86** [comment]
> That said, is there an easy way to check the dimensionality of a set?

For users working from CLI or GUI...not really. VisIt assumes user's know their data. For developers from from C++ code, yes, they *filter* things out based on dimensionality. Reason I like solution of returning `N` answers where `N` is the number of different dimensionalities in the input mesh is that for non-mixed case, you get the one and only answer you need and for mixed case, the coding is identical and you get `N` answers, labeled by dimensionality for example like so...

```
Weighted sum of 0d (points) elements = A
Weighted sum of 1d (linear) elements = B
Weighted sum of 2d (areal) elements = C
Weighted sum of 3d (volume) elements = D
```

**Comment by burton29-LLNL** [comment]
Hi,

It appears that my link to submit new questions/items to the Visit Help Desk on GitHub is busted.  Can you give me the new link to submit a new ticket?

Greg

============================================
Gregory C. Burton, Ph.D.
Turbulence Analysis & Simulation Center (TASC), Head
Thermal Fluids Group, Group Leader
Computational Engineering Division
Lawrence Livermore National Laboratory
7000 East Avenue, L-140
Livermore, California 94550
(925) 422-3515
burton29@llnl.gov
https://tasc.llnl.gov
============================================

**Comment by brugger1** [comment]
Here it is.

https://github.com/visit-dav/live-customer-response

Eric

**Comment by burton29-LLNL** [comment]
Eric, All,

There appears to be a bug  in November 2020 Visit release:  When outputting frames for a movie, and the debug partition session expires, Visit just hangs.  Whereas in older versions, it prompts the user to submit another job, and once new job starts, the outputting of frames continues without pause.  Now I just get the  spinning ball.

Greg

============================================
Gregory C. Burton, Ph.D.
Turbulence Analysis & Simulation Center (TASC), Head
Thermal Fluids Group, Group Leader
Computational Engineering Division
Lawrence Livermore National Laboratory
7000 East Avenue, L-140
Livermore, California 94550
(925) 422-3515
burton29@llnl.gov<mailto:burton29@llnl.gov>
https://tasc.llnl.gov
============================================

**Comment by burton29-LLNL** [comment]
Hi,

New question: I’m using Version 3.1.3 (August 2020), and got a question about examining nodes and zones through “Pick”, on derived new expressions on a boundary surface.    I’ve got a velocity field defined on a surface, and I want to extract that part of the velocity field that is perpendicular to the surface.  So generating an “external surface” and then using the DeferExpression workflow that I’ve developed previously,  I generate a pseudo-color plot of this derived field I’m calling “V_perp_mag” which looks reasonable.  However, when I try using “Pick” on one of the surface zones or nodes,  Visit gives me a message “No Information Found”.

How can I inspect individual nodes and zones on the surface to see what the values are for this new variable V_perp_mag?

Thanks,
Greg

============================================
Gregory C. Burton, Ph.D.
Turbulence Analysis & Simulation Center (TASC), Head
Thermal Fluids Group, Group Leader
Computational Engineering Division
Lawrence Livermore National Laboratory
7000 East Avenue, L-140
Livermore, California 94550
(925) 422-3515
***@***.***
https://tasc.llnl.gov
============================================


From: Eric Brugger ***@***.***>
Reply-To: visit-dav/live-customer-response ***@***.***>
Date: Tuesday, September 15, 2020 at 12:48 PM
To: visit-dav/live-customer-response ***@***.***>
Cc: "Burton, Greg" ***@***.***>, Author ***@***.***>
Subject: Re: [visit-dav/live-customer-response] Simple surface integral Query using "weighted variable sum" not working (#146)


I wonder if if makes sense to replace "Weighted variable sum" with "Volume weighted sum" and "Area weighted sum". This might be easier than the solution proposed in the issue you linked to.

**Comment by biagas** [comment]
@burton29-LLNL Moved this new question to it's own issue visit-dav/live-customer-response#238
