### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by brugger1** [visit-dav/live-customer-response#147]
Hello, 

I am trying to install parallel VisIt on my system running Ubuntu 20.04. 
My mpi library is Open MPI 4.0.3.

What I did:

1. downloaded build_visit3_1_2
2. Exported environment variables 
   export PAR_COMPILER=//usr/bin/mpicc
   export  PAR_COMPILER_CXX=/usr/bin/mpicxx
   export PAR_INCLUDE=-I/usr/lib/x86_64-linux-gnu/openmpi/include/
   export PAR_LIBS=-lmpl \
3. execute the stript:
   /build_visit3_1_2 --parallel --makeflags -j10 4. It fails with 
   ModuleNotFoundError: No module named '_ctypes'
   Could not install pyparsing

The log-files of my two tries with gcc 9 and 7 are attached.
 
I hope somebody can help me.

Yours Dennis Grieger
Department Visualization
High Performance Computing Center Stuttgart (HLRS) Nobelstr. 19, 70569, Stuttgart, Germany
Tel.: +49 (0) 711 / 685-61503
Email: grieger@hlrs.de

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by brugger1** [comment]
Hi Greg,

"_ctypes" comes from libffi. The solution is to install "libffi-dev" on your system.

apt-get update && apt-get install -y libffi-dev && rm -rf /var/lib/apt/lists/*

Eric

**Comment by markcmiller86-visit** [comment]
Hello,

Tanks for the quit answer. Unfortunately I now get a different error when building qt:
~/visit3.1.2/qt-everywhere-src-5.10.1/qtbase/src/corelib/io/qfilesystemengine_unix.cpp:101:12: error: ‘int renameat2(int, const char*, int, const char*, unsigned int)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static int renameat2(int oldfd, const char *oldpath, int newfd, const char *newpath, unsigned flags)

Regards Dennis

----- Original Message -----

**Comment by brugger1** [comment]
The build_visit script isn't properly recognizing the ubuntu 20 operating system and as a result not applying a required patch. The fix is in the 3.1.3 release, which we're currently building on the various operating systems. It should be released any day now. If you want to try and patch your version of the script, you can look for the function "apply_qt_patch" and look for some lines of code that call "apply_qt_5101_centos8_patch", you can move that function call out of the if block it's in.
