### ISSUE TITLE
Problems Running parallel engine on localhost (ubuntu 20)

### ISSUE THREAD

**Issue by biagas** [visit-dav/live-customer-response#149]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hi,

Can I run a parallel compute engine using the pre-built version of VisIt? I tried the following, but I'm greeted by a network error:

$ visit -hw-accel -nn 1 -np 6 -n-gpus-per-node 1 -display :1
Running: gui3.1.2 -hw-accel -n-gpus-per-node 1 -display :1 -engineargs -l;mpirun;-np;6;-nn;1 -launchengine localhost
Running: viewer3.1.2 -hw-accel -n-gpus-per-node 1 -display :1 -engineargs -l;mpirun;-np;6;-nn;1 -geometry 722x970+510+27 -borders 26,4,4,4 -shift 0,0 -preshift 4,26 -defer -host 127.0.0.1 -port 5600 -launchengine localhost
Running: mdserver3.1.2 -hw-accel -n-gpus-per-node 1 -display :1 -host 127.0.0.1 -port 5601
Running: mpirun -np 6 -npernode 6 /opt/visit/visit3_1_2.linux-x86_64-ubuntu20/3.1.2/linux-x86_64/bin/engine_par -plugindir /home/wyp/.visit/3.1.2/linux-x86_64/plugins:/opt/visit/visit3_1_2.linux-x86_64-ubuntu20/3.1.2/linux-x86_64/plugins -visithome /opt/visit/visit3_1_2.linux-x86_64-ubuntu20/3.1.2 -visitarchhome /opt/visit/visit3_1_2.linux-x86_64-ubuntu20/3.1.2/linux-x86_64 -hw-accel -n-gpus-per-node 1 -display :1 -host basecamp -port 5600 The engine could not connect to the viewer due to a networking problem.  The engine is exiting The engine could not connect to the viewer due to a networking problem.  The engine is exiting The engine could not connect to the viewer due to a networking problem.  The engine is exiting The engine could not connect to the viewer due to a networking problem.  The engine is exiting The engine could not connect to the viewer due to a networking problem.  The engine is exiting

VisIt still runs, but when I click on "Compute Engine", it reports only using 1 CPU core (see attached screenshot).

For reference, I'm using pre-built VisIt 3.1.2 on Ubuntu 20.04.1 LTS x86_64. I compiled OpenMPI 4.0.4 from source using the default GCC 9.3.0. Attached is the output from ompi_info, in case it's needed.

$ uname -a
Linux basecamp 5.4.0-45-generic #49-Ubuntu SMP Wed Aug 26 13:38:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/issue
Ubuntu 20.04.1 LTS \n \l

Any help would be appreciated.

Thanks,
Wileam Y. Phan

**Comment by biagas** [comment]
Hello Wileam,

Visit's comes packaged with the mpich libraries and executables that VisIt was built against, and should be able to run in parallel on your system.  You may need to verify that the mpirun being used is from VisIt. ('which mpirun' should tell you).  If it doesn't point to VisIt's version, edit your PATH environment variable, or create an mpirun alias to point to VisIt's version.
should be /opt/visit/visit3_1_2.linux-x86_64-ubuntu20/3.1.2/linux-x86_64/bin/mpirun (based on the info you provided)
Also, when first testing VisIt works in parallel, use the simplest command line, something like ('visit -np 2').

If VisIt doesn't work in parallel for a simple test using it's packaged mpich, then you may need to build VisIt from scratch.

Kathleen

**Comment by markcmiller86-visit** [comment]
Hi Kathleen,

Ah, I see. I happen to also have MPICH 3.3.2 compiled from source in my
machine. Once I `module load mpich` and run VisIt, everything works
smoothly, despite not using the packaged MPICH.

You can close the ticket.

Thanks,
Wileam Y. Phan

**Comment by biagas** [comment]
Thank you for the follow-up.
