### ISSUE TITLE
Lineout / Pick on a 2D surface where a surface normal needs to be generated first

### ISSUE THREAD

**Issue by burton29-LLNL** [visit-dav/live-customer-response#150]
So I have a surface in a 3D CFD simulation that gets dumped in a separate file.  I generate an external surface to define a normal vector and then define a secondary expression like Pressure*Normal_x, P*Normal_y, P*Normal_z.  VisIT then graphs out a pseudcolor plot without trouble.  Now I want to generate a lineout plot on that surface.  So I use Query -->> Lineout, and add 3D endpoints.  However the lineout plot doesn't contain any data.  How can I get a lineout of those derived expression values.  I'm using VisIT 2.13.
---

**Comment by biagas** [comment]
Hi Greg,

Would you be willing to share data and steps to reproduce (or sessionfile) on CZ or RZ?

Kathleen

**Comment by burton29-LLNL** [comment]
I will need to create this unfortunately.  It is on another network.  I can give you a similar file on Quartz, which you could use.  Would that work.  The steps were basically what I describe above.

**Comment by biagas** [comment]
Yes, that will work. Thank you.

**Comment by burton29-LLNL** [comment]
Tarring up a dump file now on quartz.  The geometry is different however, but I don't believe that is a problem.

**Comment by burton29-LLNL** [comment]
Gave you one file on Quartz.  Probably just create a surface normal on it and then try to graph out the value of one coordinate of the normal like normal_x as a pseudo color plot.  If you try to interrogate it by putting a lineout on the surface, it will claim there are no values!

**Comment by biagas** [comment]
Thanks for the data.
I should have read your original question more clearly.
There is a known bug with [Pick and DeferExpression](https://github.com/visit-dav/visit/issues/4571)
I can see that same bug affecting lineout too.

A workaround would be to save out the surface as vtk file(s), then open it with Visit to perform your queries.
A poor workaround, I know, but: with the Pseudocolor plot active, open the 'File->Set save options' window. Change file type to vtk, choose a filename, and save.  It may create a .visit file, which you should use to open the data.  Pick and Lineout should work on that surface.

**Comment by burton29-LLNL** [comment]
Ok. Thanks, Kathleen!

============================================
Gregory C. Burton, Ph.D.
Turbulence Analysis & Simulation Center (TASC), Head
Thermal Fluids Group, Group Leader
Computational Engineering Division
Lawrence Livermore National Laboratory
7000 East Avenue, L-140
Livermore, California 94550
(925) 422-3515
burton29@llnl.gov
https://tasc.llnl.gov
============================================

**Comment by burton29-LLNL** [comment]
Thank you, Kathleen.  I will try this and let you know.

Greg

============================================
Gregory C. Burton, Ph.D.
Turbulence Analysis & Simulation Center (TASC), Head
Thermal Fluids Group, Group Leader
Computational Engineering Division
Lawrence Livermore National Laboratory
7000 East Avenue, L-140
Livermore, California 94550
(925) 422-3515
burton29@llnl.gov
https://tasc.llnl.gov
============================================
