### ISSUE TITLE
serial or parallel decision with python script instead of choosing manually

### ISSUE THREAD

**Issue by biagas** [visit-dav/live-customer-response#151]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hello Dear members and experts, 
Recently I discovered VisIt as a very good and programmable tool for visualisation. Integration works fine so far with a python script integrated in the command-line-interface and now the only thing being not so practical is, that each time I open visit and then add a plot window, a new mask appears and asks if I want to work with serial or parallel data exchange on my 'localhost' (i.e. my Home-PC). Is there any possibility to write a python-script instead of this mask, because I only want to work with serial data flow? I have tried for several days now to find a solution in one of the manuals (functions, attributes...) and on the net, but  couldn't find anything yet. So, please, could you help me, I would be very happy for any advice. Thank you!
Wolfgang S. from Bavaria, Germany.

**Comment by biagas** [comment]
Hello Wolfgang,

You can script opening of the compute engine (either serial or parallel) so that the engine-chooser window doesn't pop up.
For a serial engine opening on your local machine:
 OpenComputeEngine("localhost") 

Take a look at this [quick recipe](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/cli_manual/quickrecipes.html#opening-a-compute-engine) for help with opening parallel engines.

Kathleen

**Comment by markcmiller86-visit** [comment]
Hello Kathleen,
thank you so much for your help, it works fine with:
<OpenComputeEngine("localhost", ("-l", "srun","-np", "4", "-nn", "1"))> on
my Home-PC.
In the quick recipe, detailed help is given by typing: visit --fullhelp.
Maybe that's a quite silly question, but where do you type visit
--fullhelp? I've tried on windows execute and also as a command in the
script, but it wouldn't work? Thank you again in advance and have a nice
day.
Wolfgang

Am Fr., 25. Sept. 2020 um 18:14 Uhr schrieb Kathleen Biagas via visit-users
<visit-users@elist.ornl.gov>:

**Comment by biagas** [comment]
Hi Wolfgang,
Thanks for pointing out this bug with VisIt on Windows. I have entered a [ticket](https://github.com/visit-dav/visit/issues/5088).

The only args needed for launching parallel engines on Windows would be '-np' with the number of procs specified, unless you are working with an HPC cluster.

Kathleen
