### ISSUE TITLE
Leading character in saved .curve file

### ISSUE THREAD

**Issue by burton29-LLNL** [visit-dav/live-customer-response#152]
I want to change the leading non-alphanumeric character in a .curve file from "#" to "%".  I note that version 3.1 allows for changing that preference.  What about 2.13?  I don't see any way to switch the character.
---

**Comment by biagas** [comment]
Sorry Greg, that preference was added in 3.0.0. Is there any particular reason you need to use 2.13?

**Comment by biagas** [comment]
2.13 wasn't the default on the system he wanted to use.
I suggested use '-v 3.1' when running VisIt.
