### ISSUE TITLE
Operating at cell level

### ISSUE THREAD

**Issue by griffin28** [visit-dav/live-customer-response#155]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hi all!
I'm working with a 2D cartesian mesh (a normal and simple one) using the python CLI interface. All variables are scalars zone-centred.

I would like to be able to operate at cell level, e.g. do a looping over all cells in the mesh, maybe a double one of the kind (a typical C/FORTRAN one):
```
for j in range(ny):
   for i in range(nx): 

      statements --> pres(i,j) = A(i,j)
      ....

   # endfor i
# endfor j
```
Or maybe something like this: 
```
for j in range(zoneid):

      statements --> pres(j) = A(j)
      ....

# endfor j
```
How could I do that? Where can I start from? Any idea or example will be appreciated!

Best regards!

**Comment by griffin28** [comment]
Ernesto you can use **ZonePick** and do something like:

```
for j in range(ny):
   for i in range(nx):
           ZonePick(x=i, y=j, vars=("varName1", "varName2"))  # can use coord = (i,j,0)
           pickOutput = GetPickOutputObject()
           zoneFloat = float(pickOutput['zone_id'])
           var1Value= float(pickOutput['varName1'])
           var2Value = float(pickOutput['varName2'])
```

Here's documentation of the [Zone Pick Function](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/cli_manual/functions.html?highlight=zonepick#zonepick)

Here's a reference to [VisIt scripting in general](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/tutorials/Scripting.html)

**Comment by markcmiller86-visit** [comment]
Thanks a lot Kevin for your fast response!

I have now an additional question.
>>for j in range(ny):

>>   for i in range(nx):
>>           ZonePick(x=i, y=j, vars=("varName1", "varName2"))  # can use coord = (i,j,0)
>>           pickOutput = GetPickOutputObject()
>>           zoneFloat = float(pickOutput['zone_id'])
>>           var1Value= float(pickOutput['varName1'])
>>           var2Value = float(pickOutput['varName2'])

This is really nice to operate between cells. But, what about saving
results in a new or different scalar-expression.
E.g. I'm working with var1Value and var2Value, and want to save results in
a different var3Value to do then a pseudocolor plot.

Best!

**Comment by griffin28** [comment]
In that case you don't need to loop through each cell as VisIt will apply the new expression across the entire dataset. You will need to do something like:
```
DefineScalarExpression("varName3", "varName1 + varName2")
```
There are a number of math operators and functions you can use in expressions. [Look here](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/Quantitative/Expressions.html?highlight=Expressions#expressions) for more details.
