### ISSUE TITLE
Polyhedral mesh in Silo database

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#161]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hello,

Long time VisIt user, first time poster here.

I am trying to visualize a polyhedral mesh that I stored in a Silo database via the DBPutPHZonelist() call.
On the Silo side everything looks fine, both DBPutPHZonelist() and DBPutUcdmesh() return successfully.
On the VisIt side however, the only thing I see is the first element of the mesh. All the other elements are not displayed (with “first element” meaning the first element appearing in the zonelist).
Moreover, I have the impression that the parameter “origin” in the DBPutPHZonelist() call is not taken into account.

I attach a minimal example to reproduce the problem (it is almost the same example found in the DBPutPHZonelist() section of the manual).
I am running VisIt 3.1.3 + libsiloh5-4.10.2.real-5+b1 on Debian 10.

Thank you for your help,
Matteo

**Comment by rusu24edward** [comment]
[polytest.c.zip](https://github.com/visit-dav/live-customer-response/files/5379291/polytest.c.zip)

**Comment by markcmiller86** [comment]
> Moreover, I have the impression that the parameter “origin” in the DBPutPHZonelist() call is not taken into account

Typically, the value for `origin` will be `0` (C indexing) or `1` (Fortran indexing). It can be arbitrary. However, I don't honestly know if all consumers are expecting anything other than 0 or 1. What value are you specifying?

**Comment by markcmiller86** [comment]
Oh, I see the code is attached here now. Lemme take a quick look.

**Comment by datafl4sh** [comment]
Hello @markcmiller86,

Thanks for your reply.
I am using `0` for C indexing, but nothing changes if I specify `1`. Said otherwise, point indexes must be 0-based.

**Comment by datafl4sh** [comment]
Thank you @markcmiller86.

Clearly I did not read the manual carefully, with `nzones-1` works perfectly. Sorry for bothering you with an issue so trivial.

Thanks again,
Matteo

**Comment by markcmiller86** [comment]
Sure thing.
