### ISSUE TITLE
Running Visit from bsub allocation

### ISSUE THREAD

**Issue by flow-phys** [visit-dav/live-customer-response#169]
I'd like to run a visit post-processing script as a batch job on rzansel/lassen (blueOS) using the bsub command.

I request an allocation and then pass a python script to the visit command:

visit -cli -nowin -s [pythonFile] [args]

I use the OpenComputeEngine() in the visit script when I run without an allocation, which requests nodes/time on a machine.

Question:
How do I attach to the allocated nodes on the BlueOS systems?   Is the above command the correct command to issues from my bsub allocation?

Thanks

**Comment by griffin28** [comment]
Instead of using OpenComputeEngine() in the visit script try:

```
import visit_utils
visit_utils.engine.open(method="slurm") 
```

I believe this should look at the slurm env vars and launch the engine with the number of allocated nodes. Let me know if this works.

**Comment by flow-phys** [comment]
@griffin28 , thanks for the quick reply!  The above appears to work on the TOSS machines but I get the following error on BlueOS:

raise VisItException("engine.open(method='slurm') requires "
visit_utils.common.VisItException: <VisIt Error> engine.open(method='slurm') requires SLURM_JOB_NUM_NODES and SLURM_CPUS_ON_NODE env vars

Any thoughts?

Thanks

**Comment by griffin28** [comment]
Hmmm..@brugger1 or @cyrush...is `slurm` the correct workload manager for BlueOS?

**Comment by flow-phys** [comment]
Not sure this is the blessed solution, but if i set my environment variables:
SLURM_JOB_NUM_NODES
SLURM_CPUS_ON_NODE
to their appropriate values for the blueos nodes, the script appears to run.  Its a bit of a hack, but when I inspect the Compute Engines through the GUI, it appears to be using what I've requested.  
Solved?

**Comment by griffin28** [comment]
Ok. I'm not familiar with BlueOS, once Cyrus or Eric get some free cycles they may be able to shed some light on why these env vars aren't being set.

**Comment by cyrush** [comment]
`slurm `won't work out of the box -- but @flow-phys  clever to emulate those vars. 

We would need to understand the magic env vars for LSF to provide a similar setup. 

@flow-phys  Do you know which ones we should pull off hand?

**Comment by brugger1** [comment]
I think you should be able to get OpenComputeEngine to work. I'll see if I can get you the correct set of flags to run with.

**Comment by brugger1** [comment]
The following encantation of OpenComputeEngine launched a batch job for me on lassen.

OpenComputeEngine("localhost", ("-np", "80", "-nn", "2", "-l", "bsub/mpirun", "-b", "wbronze", "-p", "pbatch"))

**Comment by griffin28** [comment]
@brugger1 will this use pre-allocated nodes?

**Comment by brugger1** [comment]
This will allocate nodes. I missed that part of the original submission.

**Comment by flow-phys** [comment]
> `slurm `won't work out of the box -- but @flow-phys clever to emulate those vars.
> 
> We would need to understand the magic env vars for LSF to provide a similar setup.
> 
> @flow-phys Do you know which ones we should pull off hand?


@cyrush , there is an environment variable that get created when you have an allocation that may work.  Here's what I see:
"LSB_MCPU_HOSTS=rzansel62 1 rzansel47 40"
The "1" is the number of nodes and the "40" is the number of CPUs.

I didn't see anything else from printenv.
