### ISSUE TITLE
Build fails on rzgenie

### ISSUE THREAD

**Issue by aowen87** [visit-dav/live-customer-response#171]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

I'm trying to build VisIt on rzgenie, which I've done without issue in the past, but I'm now running into this error during the make proces:
```
../../lib/libavtpipeline_ser.so: undefined reference to `vtkm::cont::CellSetExplicit<vtkm::cont::StorageTagBasic, vtkm::cont::StorageTagBasic, vtkm::cont::StorageTagBasic, vtkm::cont::StorageTagBasic>::CellSetExplicit(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../../lib/libavtpipeline_ser.so: undefined reference to `vtkm::cont::CoordinateSystem::CoordinateSystem<vtkm::Vec<float, 3>, vtkm::cont::StorageTagBasic>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, vtkm::cont::ArrayHandle<vtkm::Vec<float, 3>, vtkm::cont::StorageTagBasic> const&)'
../../lib/libavtpipeline_ser.so: undefined reference to `vtkm::cont::CoordinateSystem::CoordinateSystem<vtkm::Vec<double, 3>, vtkm::cont::StorageTagBasic>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, vtkm::cont::ArrayHandle<vtkm::Vec<double, 3>, vtkm::cont::StorageTagBasic> const&)'
../../lib/libavtpipeline_ser.so: undefined reference to `vtkm::cont::CoordinateSystem::CoordinateSystem(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, vtkm::Vec<int, 3>, vtkm::Vec<double, 3>, vtkm::Vec<double, 3>)'
../../lib/libavtpipeline_ser.so: undefined reference to 
`vtkm::cont::CellSetExplicit<vtkm::cont::StorageTagImplicit<vtkm::cont::detail::ArrayPortalImplicit<vtkm::cont::detail::ConstantFunctor<unsigned char> > >, vtkm::cont::StorageTagImplicit<vtkm::cont::detail::ArrayPortalImplicit<vtkm::cont::detail::ConstantFunctor<int> > >, vtkm::cont::StorageTagBasic, vtkm::cont::StorageTagImplicit<vtkm::cont::internal::ArrayPortalCounting<int> > >::CellSetExplicit(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
```

Is there maybe something wrong with the library installations here?

**Comment by aowen87** [comment]
I've commented out the vtkm option in rzgenie.cmake to see if that resolves the issue for now.

**Comment by aowen87** [comment]
Commenting out vtkh and vtkm in rzgenie.cmake lets me get past that failure.

**Comment by brugger1** [comment]
Is this with develop or the 3.1RC?

**Comment by aowen87** [comment]
This is develop.

**Comment by brugger1** [comment]
I used the rztrona5 config site file and ran into the PIDX failure you mentioned. I commented out PIDX and things built fine after that.

**Comment by aowen87** [comment]
Hmm.. That's kind of strange. I wonder why I was having trouble with VTK libs. I can try building again today.

**Comment by aowen87** [comment]
I just realized that I had copied the rztrona config file to an "rzgenie" config file a long time ago, and I just forgot that there wasn't an actual rzgenie config file in VisIt's repo. So, my configuration was just really old. This is an Alister issue, not a VisIt issue.

**Comment by aowen87** [comment]
I re-cloned VisIt, updated my config file to rztrona5, and I'm still running into that failure from VTKM/H.

**Comment by rusu24edward** [comment]
@aowen87 is this still failing?

**Comment by aowen87** [comment]
It was the last time I checked a few weeks ago. I've just started commenting out those VTKH/M links to build there.

**Comment by rusu24edward** [comment]
I was able to build rzgenie just now without any issues. I used `rztopaz194.cmake` as the config file. For what it's worth, I had to blow out my build directory and create one from scratch because of the upgrades to qt a few weeks ago.

**Comment by aowen87** [comment]
Thanks, Eddie. I'll try again when I'm back on VisIt.

**Comment by aowen87** [comment]
I think it's safe to close this now.
