### ISSUE TITLE
Draw arbitrary shapes in plots

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#172]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Is there a way that I can get visit to draw arbitrary simple shapes on my plots?  For example, add a sphere or a cylinder of arbitrary radius & length?

Michael Hohensee

**Comment by rusu24edward** [comment]
I don't think there is a straightforward way to accomplish this. You may be able to hack something using [Interactive Tools](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/InteractiveTools/index.html) at the top of the window (e.g. Sphere tool will draw a sphere). [Annotations](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/MakingItPretty/Annotations.html?highlight=Annotations) could also be used . This is a good idea, I'll add this as a feature request.

**Comment by aowen87** [comment]
I think @biagas recently came up with a strategy to accomplish drawing arbitrary boxes in VisIt by writing simple vtk files. I'm not sure how well this would work for more complicated shapes, but this may be a good workaround for simpler ones.
