### ISSUE TITLE
everything is dark when draw a big mesh

### ISSUE THREAD

**Issue by biagas** [visit-dav/live-customer-response#177]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Sir:

I want draw mesh using visit. I found that if the mesh is too large(too fine) and do not zoom in at detail, every thing in the view is dark.

I can not resolve geometric shapes from the view at that time.

I wonder is there any way can draw a large mesh and not let every thing in view is dark?

Why I want this:
Usually for demonstrate a big mesh, we needs to give a overview of mesh and zoom in, zoom in, zoom in.
But at the overview stage, everything is dark.

I apologize if it is a stupid problem. Thanks for your time.

**Comment by biagas** [comment]
Basically, you need to reduce the amount of data until you zoom in on your area of intereset.

If your Mesh is an AMR Mesh, you can try using the MultiRes Control operator to remove the finer-grain portions of the mesh until you zoom in. Or you can turn off levels via the [Subset controls](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/Subsetting/Using_the_Subset_Window.html).

Otherwise, you might want to try the Subset plot, using your Mesh as the variable. Turn on the Wireframe option of the Subset plot, set the color as you would like.  This should give you just the external boundary edges of the mesh, then switch to to the Mesh plot when you zoom in close enough to see the finer details.

For rectilinear data, you have the option to use the [Resample operator](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/Operators/OperatorTypes/Resample_operator.html) to resample onto a coarser mesh.

**Comment by qzxuhui** [comment]
Sir, my application is a big one level unstructured grid (not AMR), seems there is no way like resample.

**Comment by markcmiller86-visit** [comment]
This is definitely not a fix for the resampling issue that you mention, but
you may be able to get a better view by turning the opacity down. How
effective this will be is very dependent on your specific mesh and what you
may wish to plot behind or inside of it.

Best,
Alex

**Comment by markcmiller86** [comment]
> Sir, my application is a big one level unstructured grid (not AMR), seems there is no way like resample.

When you have a situation where each mesh element is about the same size as (or smaller than) a single pixel, plotting the *mesh lines* as a **Mesh Plot** means that every pixel will get whatever the mesh line color is.

To *fix* this, you have a few options...
* Zoom the view in far enough that your mesh elements are much bigger than a single pixel. The price you pay is that you may not be able to see *all* of the mesh in one view.
* *Reduce* the data using one of a variety of approaches
  * [Subsetting](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/Subsetting/Using_the_Subset_Window.html#using-the-subset-window)
  * [Clipping](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/Operators/OperatorTypes/Clip_operator.html?highlight=clip%20operator#clip-operator)
  * [Logical down sampling](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/Operators/OperatorTypes/Index_Select_operator.html#index-select-operator) (works only for structured grids)
  * [Geometric Down Sampling](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/Operators/OperatorTypes/Resample_operator.html#resample-operator)
  * [Slicing](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/Operators/OperatorTypes/Slice_operator.html#slice-operator) (there are several different kinds of slice operators but they do also reduce dimensionality too)
* Use a rendering technique designed to *integrate* contributions from all elements that map to an image pixel such as [Volume](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/Plots/PlotTypes/VolumePlot.html#volume-plot) rendering.

If your goal is a plot of the *mesh lines* that captures the *whole* of the shape but is not a blob of single color, then likely only one of the sampling approaches will work.

We used to have the ability to display only the *feature* edges of a mesh plot. I don't know how reliable that was. But, maybe we should enter an enhancement request to enable such a feature in the mesh plot. A *feature* edge is an edge where the adjoining faces meet at an acute angle (typically 90 degrees of less though that could be a knob in the GUI).
