### ISSUE TITLE
Issue opening silo file

### ISSUE THREAD

**Issue by aowen87** [visit-dav/live-customer-response#18]
A user reached out through Jabber is was having issues opening a silo file from within a python script. The generated error is that the input file "does not exist".

Looking more closely at the path of her input file, it contains some odd characters. It mostly looks like "var_a\=val_a/var_b\=val_b/var_c\=val_c.silo". This is on a linux system, and her directory names and files have backslashes and equal signs in them. I originally thought this might be an issue, but VisIt seems to handle these types of file names correctly on my mac. 

I've asked her to see if she can open the file from within it's directory using VisIt. 

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by markcmiller86** [comment]
I wonder if she was using python 3 or 2? Silo's python interface won't work with python 3.

**Comment by markcmiller86** [comment]
Ok, so I just tested something similar on my Mac...

```
[scratlantis:~/silo/4.10.3RC/tests] miller86% mkdir -p var_a=val_a/var_b=val_b/
[scratlantis:~/silo/4.10.3RC/tests] miller86% cp onehex.silo var_a=val_a/var_b=val_b/var_c=val_c.silo
[scratlantis:~/silo/4.10.3RC/tests] miller86% env PYTHONPATH=../build/my_install/lib python
Python 2.7.16 (default, Dec  3 2019, 02:03:47) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import Silo
>>> db = Silo.Open("var_a=val_a/var_b=val_b/var_c=val_c.silo")
>>> db.GetToc()
nvar = 22
var_names = (_fileinfo, _meshtvinfo, _silolibinfo, cycle, facelist_nodelist, facelist_shapecnt, facelist_shapesize, facelist_zoneno, hex_align_nodal, hex_align_zonal, hex_coord0, hex_coord1, hex_coord2, hex_max_extents, hex_min_extents, mat_dims, mat_matlist, mat_matnos, v_data, zonelist_nodelist, zonelist_shapecnt, zonelist_shapesize)
nucdmesh = 1
ucdmesh_names = (hex)
nucdvar = 1
ucdvar_names = (v)
nmat = 1
mat_names = (mat)

**Comment by aowen87** [comment]
Renaming her files solved this issue. I still think it's odd that it worked for us but not her, which might be due to the fact that she was using an older version of VisIt. I've suggested she try 3.1. For now, though, her problem is resolved.
