### ISSUE TITLE
dependencies for build_visit to run

### ISSUE THREAD

**Issue by biagas** [visit-dav/live-customer-response#182]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
i have a fresh laptop with a new linux mint install.

i am trying to build visit but it crashes immediately with the following in the bash_log:
**********************************
Processing bsd license.
**********************************

i recall that i needed to install some command line applications to get the build_visit script to run but do not recall what they are.

please help
thanks

**Comment by biagas** [comment]
This [wiki](https://visitusers.org/index.php?title=Building_on_Ubuntu_12.04) on packages needed for ubuntu in order to build visit might be helpful.

**Comment by charlsonkim** [comment]
yes, that wiki is exactly what i am looking for
thanks

**Comment by charlsonkim** [comment]
still missing something, build_visit crashes with same output

**Comment by markcmiller86** [comment]
Any chance you can run `build_visit` with debugging enabled?

Please do the following...

```
% script
Script started, output file is typescript
./build_visit <same-args-as-before> --bv-debug
exit

Script done, output file is typescript
% mv typescript typescript.txt
```

Then attach `typescript.txt` to a comment in this issue.

**Comment by charlsonkim** [comment]
it looks like the "script" function unlocked whatever was crashing the build script.  the build is now chugging along.

**Comment by charlsonkim** [comment]
it looks like the "script" function unlocked whatever was crashing the build script.  the build is now chugging along.

**Comment by charlsonkim** [comment]
spoke too soon, crashes on qt build (from bash_log) : 
Building Qt (~60 minutes)
prepare_build_dir: qt-everywhere-src-5.10.1 qt-everywhere-src-5.10.1.tar.xz
Found qt-everywhere-src-5.10.1 . . .
Patching qt . . .
patching file qtbase/src/corelib/global/qrandom.cpp
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file qtbase/src/corelib/global/qrandom.cpp.rej
+ cd qtbase
+ /home/charlson/bin/VisIt/qt-everywhere-src-5.10.1/qtbase/configure -top-level -prefix /home/charlson/bin/VisIt/third_party/qt/5.10.1/linux-x86_64_gcc-9.3 -platform linux-g++-64 -make libs -make tools -no-separate-debug-info -no-dbus -no-sql-db2 -no-sql-ibase -no-sql-mysql -no-sql-oci -no-sql-odbc -no-sql-psql -no-sql-sqlite -no-sql-sqlite2 -no-sql-tds -no-libjpeg -opensource -confirm-license -skip 3d -skip canvas3d -skip charts -skip connectivity -skip datavis3d -skip doc -skip gamepad -skip graphicaleffects -skip location -skip multimedia -skip networkauth -skip purchasing -skip quickcontrols -skip quickcontrols2 -skip remoteobjects -skip scxml -skip sensors -skip serialport -skip speech -skip wayland -nomake examples -nomake tests -no-qml-debug -qt-zlib -qt-libpng -qt-xcb -qt-xkbcommon
Creating qmake...
/home/charlson/bin/VisIt/qt-everywhere-src-5.10.1/qtbase/src/corelib/io/qfilesystemengine_unix.cpp:101:12: error: ‘int renameat2(int, const char*, int, const char*, unsigned int)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
  101 | static int renameat2(int oldfd, const char *oldpath, int newfd, const char *newpath, unsigned flags)
      |            ^~~~~~~~~
In file included from /usr/include/c++/9/cstdio:42,
                 from /usr/include/c++/9/ext/string_conversions.h:43,
                 from /usr/include/c++/9/bits/basic_string.h:6493,
                 from /usr/include/c++/9/string:55,
                 from /home/charlson/bin/VisIt/qt-everywhere-src-5.10.1/qtbase/include/QtCore/../../src/corelib/tools/qbytearray.h:52,
                 from /home/charlson/bin/VisIt/qt-everywhere-src-5.10.1/qtbase/include/QtCore/qbytearray.h:1,
                 from /home/charlson/bin/VisIt/qt-everywhere-src-5.10.1/qtbase/include/QtCore/../../src/corelib/tools/qstring.h:49,
                 from /home/charlson/bin/VisIt/qt-everywhere-src-5.10.1/qtbase/include/QtCore/qstring.h:1,
                 from /home/charlson/bin/VisIt/qt-everywhere-src-5.10.1/qtbase/include/QtCore/../../src/corelib/io/qiodevice.h:50,
                 from /home/charlson/bin/VisIt/qt-everywhere-src-5.10.1/qtbase/include/QtCore/qiodevice.h:1,
                 from /home/charlson/bin/VisIt/qt-everywhere-src-5.10.1/qtbase/include/QtCore/../../src/corelib/io/qfiledevice.h:43,
                 from /home/charlson/bin/VisIt/qt-everywhere-src-5.10.1/qtbase/include/QtCore/qfiledevice.h:1,
                 from /home/charlson/bin/VisIt/qt-everywhere-src-5.10.1/qtbase/src/corelib/io/qfile.h:44,
                 from /home/charlson/bin/VisIt/qt-everywhere-src-5.10.1/qtbase/src/corelib/io/qfilesystemengine_p.h:54,
                 from /home/charlson/bin/VisIt/qt-everywhere-src-5.10.1/qtbase/src/corelib/io/qfilesystemengine_unix.cpp:43:
/usr/include/stdio.h:164:12: note: previous declaration of ‘int renameat2(int, const char*, int, const char*, unsigned int)’
  164 | extern int renameat2 (int __oldfd, const char *__old, int __newfd,
      |            ^~~~~~~~~
/home/charlson/bin/VisIt/qt-everywhere-src-5.10.1/qtbase/src/corelib/io/qfilesystemengine_unix.cpp:107:12: error: ‘int statx(int, const char*, int, unsigned int, statx*)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
  107 | static int statx(int dirfd, const char *pathname, int flag, unsigned mask, struct statx *statxbuf)
      |            ^~~~~
In file included from /usr/include/x86_64-linux-gnu/bits/statx.h:39,
                 from /usr/include/x86_64-linux-gnu/sys/stat.h:446,
                 from /home/charlson/bin/VisIt/qt-everywhere-src-5.10.1/qtbase/mkspecs/linux-g++-64/../linux-g++/qplatformdefs.h:75,
                 from /home/charlson/bin/VisIt/qt-everywhere-src-5.10.1/qtbase/mkspecs/linux-g++-64/qplatformdefs.h:40,
                 from /home/charlson/bin/VisIt/qt-everywhere-src-5.10.1/qtbase/src/corelib/io/qfilesystemengine_unix.cpp:42:
/usr/include/x86_64-linux-gnu/bits/statx-generic.h:56:5: note: previous declaration of ‘int statx(int, const char*, int, unsigned int, statx*)’
   56 | int statx (int __dirfd, const char *__restrict __path, int __flags,
      |     ^~~~~
make: *** [Makefile:429: qfilesystemengine_unix.o] Error 1
make: *** No targets specified and no makefile found.  Stop.

**Comment by brugger1** [comment]
The build_visit script if failing to apply a patch required to build Qt on your system. It is a pretty simple fix to the script to fix the issue.

Search for the function "apply_qt_patch" and add the line

    apply_qt_5101_centos8_patch

as the first line in the function. You need to make sure that there are exactly 4 spaces at the beginning of the line.

You should remove the directory "qt-everywhere-src-5.10.1" before running build_visit again.

**Comment by charlsonkim** [comment]
made it past the patch, but looks like it is crashing on the Python 3 install (tail of bash_log):

Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-19.2.3 setuptools-41.2.0
Done with Python3
Done building python3.
Extracting six ...
Extracting pyparsing ...
Extracting sphinx ...
running install
running build
running build_py
creating build
creating build/lib
copying six.py -> build/lib
running install_lib
copying build/lib/six.py -> /home/charlson/bin/VisIt/third_party/python/3.7.7/linux-x86_64_gcc-9.3/lib/python3.7/site-packages
byte-compiling /home/charlson/bin/VisIt/third_party/python/3.7.7/linux-x86_64_gcc-9.3/lib/python3.7/site-packages/six.py to six.cpython-37.pyc
running install_egg_info
Writing /home/charlson/bin/VisIt/third_party/python/3.7.7/linux-x86_64_gcc-9.3/lib/python3.7/site-packages/six-1.13.0-py3.7.egg-info
/home/charlson/bin/VisIt/third_party/python/3.7.7/linux-x86_64_gcc-9.3/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
/home/charlson/bin/VisIt/third_party/python/3.7.7/linux-x86_64_gcc-9.3/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
Traceback (most recent call last):
  File "./setup.py", line 5, in <module>
    from setuptools import setup
  File "/home/charlson/bin/VisIt/third_party/python/3.7.7/linux-x86_64_gcc-9.3/lib/python3.7/site-packages/setuptools/__init__.py", line 20, in <module>
    from setuptools.dist import Distribution, Feature
  File "/home/charlson/bin/VisIt/third_party/python/3.7.7/linux-x86_64_gcc-9.3/lib/python3.7/site-packages/setuptools/dist.py", line 35, in <module>
    from setuptools import windows_support
  File "/home/charlson/bin/VisIt/third_party/python/3.7.7/linux-x86_64_gcc-9.3/lib/python3.7/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/home/charlson/bin/VisIt/third_party/python/3.7.7/linux-x86_64_gcc-9.3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
Could not install pyparsing
sphinx python module build failed. Bailing out.
Error in build process.  See bash_log for more information. If the error is unclear, please include bash_log in a  message to the visit-users@ornl.gov list.  You will probably  need to compress the bash_log using a program like gzip  so it will fit within the size limits for email attachments.

**Comment by charlsonkim** [comment]
previously building with --parallel-build but that looks like it caused the qt build to get ahead of the Python installs.
build line:
>. ./build_visit3_1_4 --console --makeflags "-j 4" --parallel --vtk --h5part --silo --git --hdf5 --icet

**Comment by brugger1** [comment]
You need to install "libffi-dev" on your system. If you use apt-get to install on your system, the command would be:

apt-get update && apt-get install -y libffi-dev && rm -rf /var/lib/apt/lists/* 

The other solution is to add "--no-sphynx" to build_visit, which will cause the Python 3 build to be skipped. We only use Python 3 for generating documentation for the help system, so this isn't critical.

**Comment by brugger1** [comment]
Also, you should blow away the Python 2 and 3 directories in the directory you are running build_visit and also in the installation directory.

**Comment by charlsonkim** [comment]
a little further but crashes at Qt5:
erator=(const QList<QApplicationArgument>::iterator&)’ is deprecated [-Wdeprecated-copy]
  387 |     start = low + 1;
      |     ~~~~~~^~~~~~~~~
In file included from /home/charlson/bin/VisIt/qt-everywhere-src-5.10.1/qtbase/include/QtCore/qlist.h:1,
                 from /home/charlson/bin/VisIt/qt-everywhere-src-5.10.1/qtbase/include/QtCore/../../src/corelib/tools/qhash.h:46,
                 from /home/charlson/bin/VisIt/qt-everywhere-src-5.10.1/qtbase/include/QtCore/qhash.h:1,
                 from /home/charlson/bin/VisIt/qt-everywhere-src-5.10.1/qtbase/include/QtCore/../../src/corelib/io/qdebug.h:45,
                 from /home/charlson/bin/VisIt/qt-everywhere-src-5.10.1/qtbase/include/QtCore/qdebug.h:1,
                 from /home/charlson/bin/VisIt/qt-everywhere-src-5.10.1/qtbase/include/QtCore/QtDebug:1,
                 from qapplicationargumentparser.cpp:29:
/home/charlson/bin/VisIt/qt-everywhere-src-5.10.1/qtbase/include/QtCore/../../src/corelib/tools/qlist.h:239:16: note: because ‘QList<QApplicationArgument>::iterator’ has user-provided ‘QList<T>::iterator::iterator(const QList<T>::iterator&) [with T = QApplicationArgument]’
  239 |         inline iterator(const iterator &o) Q_DECL_NOTHROW : i(o.i){}
      |                ^~~~~~~~
Info: creating cache file /home/charlson/bin/VisIt/qt-everywhere-src-5.10.1/qtdeclarative/.qmake.cache
sh: 1: python: not found
Project ERROR: Building QtQml requires Python.
make: *** [Makefile:264: module-qtdeclarative-make_first] Error 3

**Comment by brugger1** [comment]
It looks like you are missing python. The command with apt-get is:

apt-get update && apt-get install -y python  && rm -rf /var/lib/apt/lists/*

**Comment by charlsonkim** [comment]
but i am building python in visit

**Comment by brugger1** [comment]
Yes, you're correct. My guess is that our Qt build isn't set up to use the python we build. We should fix that. I do see that all our containers used for building VisIt on different operating systems all install python, so I assume it's necessary.

**Comment by charlsonkim** [comment]
???!!!*$*$*$???!!!

ok

**Comment by brugger1** [comment]
Sorry!

**Comment by cyrush** [comment]
In the past some 3rd party libs have required python as part of their build system or build process -- even if they have nothing else to do with python.  These cases were also not advertised well and pretty elusive ( I think one case was old mesa build when trying to parse xml). So system python is a good hedge.  Regardless, life is complicated :-(
