### ISSUE TITLE
Problems making movies on macOS Catalina

### ISSUE THREAD

**Issue by markcmiller86** [visit-dav/live-customer-response#184]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

Dear VisIt developers,

I am having the following error when trying to export a movie from VisIt
(Visit versions 3.1.3/4, binary for macOS):

Qt: Warning: Window position outside any known screen, using primary screen
WARNING:
VisIt does not recognize your terminal application so it will ignore the
-newconsole argument.

I am running on macOS Catalina 10.15.7. First, I need to run the
application as sudo user otherwise getting the error1.png attached
message, you can also see the log from the terminal in the error-1b.png
file. When I run as sudo user everything seems to be working properly
but when I try to export a movie: nothing happens but the error2.png
attached message. In all cases when I try to open a file I receive the
Warning.png message which I have been normally ignoring.

Possibly you can kindly help, especially if I could export movies and
work as a regular macOS user would be perfect. I am a VisIt user since
many years and I am encountering those troubles only since I upgraded
the macOS to Catalina, and consequently installed the latest versions of
VisIt.

Kind Regards,

Ivan

### Warning
<img width="504" alt="Warning" src="https://user-images.githubusercontent.com/5720676/100136691-35c7c000-2e40-11eb-9cd4-cef553ba7479.png">

### error1
<img width="499" alt="error1" src="https://user-images.githubusercontent.com/5720676/100136697-3b250a80-2e40-11eb-9d68-d971da48afc5.png">

### Error 1b
![error-1b](https://user-images.githubusercontent.com/5720676/100136710-3f512800-2e40-11eb-91ea-8de73f0d0617.png)

### Error 2
![error2](https://user-images.githubusercontent.com/5720676/100136726-437d4580-2e40-11eb-88db-4825d3495f89.png)

**Comment by markcmiller86** [comment]
> Qt: Warning: Window position outside any known screen, using primary screen
> WARNING:
> VisIt does not recognize your terminal application so it will ignore the
> -newconsole argument.

Hmmm....are you using macOS `Terminal` app there or something else?

> 
> I am running on macOS Catalina 10.15.7. First, I need to run the
> application as sudo user otherwise getting the error1.png attached
> message, you can also see the log from the terminal in the error-1b.png
> file. 

I suspect error1 and error-1b are both a manifstation of the same issue...It would appear you are trying to run `/Applications/VisIt.app/MacOS/visit` and it seems to find and run the `viewer` and `mdserver` processes ok. However, when it tries to launch the `engine` process, it seems to be trying to run `/Users/igriotto/ICTP_TMP/Visit_temp/bin/visit`. This suggest to me that there is something wrong with your [host profile](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/ClientServer/Host_Profiles.html?highlight=profile#host-profiles) for either host `127.0.0.1` or host `pb-griotto.local`

I think if we can debug why the above is happening, we can fix your problems.


> When I run as sudo user everything seems to be working properly
> but when I try to export a movie: nothing happens but the error2.png
> attached message. In all cases when I try to open a file I receive the
> Warning.png message which I have been normally ignoring.
> 
> Possibly you can kindly help, especially if I could export movies and
> work as a regular macOS user would be perfect. I am a VisIt user since
> many years and I am encountering those troubles only since I upgraded
> the macOS to Catalina, and consequently installed the latest versions of
> VisIt.

**Comment by igirotto** [comment]
Thanks, I didn't spot this "/Users/igriotto/ICTP_TMP/Visit_temp/bin/visit". There is definitely still some link with older versions of VisIt I had installed. The "host profile" should be clean as the one I am trying to run is a new version. Maybe some ".config" file related to VisIt I do not recall I edited?

**Comment by igirotto** [comment]
I reckon I am using macOS terminal: 

pb-girotto:~ igirotto$ echo $TERM 
xterm-256color

**Comment by igirotto** [comment]
Hi Mark, I fixed it. I removed the folder $HOME/.visit on which I had nothing important and lunched visit again. Now everything works also with my user, including the option of making videos. Therefore, thanks to your help all is now working as expected. You can kindly close this issue. Thanks again for your valuable help.

**Comment by markcmiller86** [comment]
@igirotto glad you fixed it. Thanks for letting us know.
