### ISSUE TITLE
Connecting to LC CZ

### ISSUE THREAD

**Issue by brugger1** [visit-dav/live-customer-response#185]
Hi Visit folks,

I'm having trouble connecting to the CZ, Quartz in particular. Even with the pre-set configuration settings I cannot get a metadata server to launch.

With "Tunnel through SSH" unchecked I can get it to request a password but no metadata server. With tunneling checked I don't even get a password prompt.

I can connect to Quartz with Putty and run Visit through X11 but it's crazy slow

Any suggestions on things to try? I cannot currently modify environment variables on this computer (e.g. VISITSSH or whatever)...that's supposed to be fixed but it's moving at the speed of government. 

Thanks!
Dave

US Army
Picatinny Arsenal

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by brugger1** [comment]
Hi Dave,

You most likely want "Tunnel through SSH" checked. You should get a password prompt in both cases, but with "Tunnel through SSH" unchecked most firewalls will block the connection from the remote system (Quartz in this case).

I assume you are running on Windows. What version of VisIt are you running?

Eric

**Comment by markcmiller86-visit** [comment]
I’ve tried with 2.8.0, 2.10.2 (a portable version made by DAAC) and 3.1.2

2.8 was what I used to use on Cab and then later Quartz but it’s been a while and something has probably changed.

Yes, Windows 10, 1909

**Comment by brugger1** [comment]
The oldest version currently installed on Quartz is 2.12.3, so of those versions the only one that has a chance of working is 3.1.2. Can you run "VisIt with Debug logging"?

![VisIt_Start_Menu](https://user-images.githubusercontent.com/1102718/101187577-63afc000-3609-11eb-89bd-1858a4854d64.png)

It will create some "vlog" files in you "visit" folder, most likely under your "Documents" folder.

**Comment by markcmiller86-visit** [comment]
I was shown how to run visit through VNC Viewer which seems like a better way, unless you still want to figure out what’s going on with this method?

**Comment by brugger1** [comment]
Thanks for letting us know you found a work around to the problem.

If the VNC viewer works better for you, then I don't see any reason to pursue this issue. I'll go ahead and close the issue.
