### ISSUE TITLE
Visit crash in client-server with pseudocolor

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#186]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Barbara Kornblum has been having an issue for several days where Visit crashes when running client-server on SCF systems. She is running a full 3d visualization. Filled boundary plot. Mesh plot. Selection clipping to look inside the object. As soon as she does Pseudocolor plot, Visit crashes.

**Comment by markcmiller86** [comment]
Some thoughts. 
* Is she truly certain which version she is running?
* Can she think of anything thats recently *changed* on the system(s) she is running on?
   * Are the data files she is now using *new* (or from a new version of the data producer) or has she looked at these specific files before?
* Does falling back to an earlier version fix this?
* If she can run with `-debug 5`, its concievable we could ask her to grep for some tell-tale signs of cause?

**Comment by rusu24edward** [comment]
Turns out the user was running with scalable rendering set to Never, so it's likely that Visit crashed from out of memory issue. I had her turn on scalable rendering, and the problem went away. I also emailed her the [advanced scalable rendering docs](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/Preferences/Rendering_Options_Window.html?highlight=scalable%20rendering#advanced-rendering-options)
