### ISSUE TITLE
Memory leak in engine_ser when creating animations via script

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#189]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
I am using Visit 3.1.3 on Mac OS X, installed from binary.

I use a simple python script derived from visit tutorials that loops over 200 exodus files and generates images for animation.
For each exodus database:
   open exodus database
   add plot
   set plot attributes
   draw plots
   save window
   delete plots
   close database

For about 100 exodus files, everything works fine. For 140+ exodus files, the images start having artifacts, white polygons, and computer slows down.

I have noticed in Activity Monitor that process
   engine_ser
grows in memory to several GB, and process
   Visit Viewer 3.1.3.
shows in red as (Non Responding)

I go around the problem by processing files in batches, but would prefer to process the files in one sitting.
Any suggestions will be appreciated.

Srdjan Simunovic
Oak Ridge National Laboratory
+1-865-771-9919

**Comment by rusu24edward** [comment]
Hi Srdjan,

Since the strange behavior manifests itself over time and not at the beginning, and since the engine_ser blows up to use a ton of resources, I would guess you're experiencing a memory leak bug in VisIt. In addition to the work around you have described, you can try clearing the engine cache at each iteration in your loop. You can try [ClearCache](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/cli_manual/functions.html?highlight=cache#clearcache) or [ClearCacheForAllEngines](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/cli_manual/functions.html?highlight=cache#clearcacheforallengines) cli functions. You can also try changing the pipeline caching mode with [SetPipelineCachineMode](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/cli_manual/functions.html?highlight=cache#setpipelinecachingmode).

Can you try this and let me know if helps resolve your issue?

Thanks,
Eddie

**Comment by aowen87** [comment]
I've also encountered this issue while saving out png images from silo files. I used the same workaround as Srdjan.

**Comment by simunovics** [comment]
I first tried ClearCacheForAllEngines, at the end of each loop
`foreach`
`     ...`
`    CloseDatabase(db)`
`    ClearCacheForAllEngines()
`

Then added:
`    CloseDatabase(db)`
`    ClearCache("localhost")`
`    ClearCacheForAllEngines()
`

And finally put
`SetPipelineCachingMode(0)`
at the beginning of the script.

Still engine_ser memory grows and crashes the computer.
I also tried 3.1.4 version with the same outcome.

**Comment by rusu24edward** [comment]
@simunovics Thanks for trying those steps! What you are describing is documented in an active issue [here](https://github.com/visit-dav/visit/issues/1923). Can you try one more thing for me? Can you try using the [CloseComputEngine](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/cli_manual/functions.html#closecomputeengine) and [OpenComputeEngine](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/cli_manual/functions.html#opencomputeengine) cli functions periodically in your script (probably doesn't need to be at every iteration, but say every 10 iterations)? This should kill the compute engine and release the memory resources, and then relaunches it.

You're going to be experiencing some overhead from opening and closing, but since you're already using batching I'm hoping that this can slightly improve your workflow until we resolve the memory leak.

Please let me know if this helps mitigate the issue.

Thanks,
Eddie

**Comment by simunovics** [comment]
@rusu24edward I used the script below (main parts shown only) and still had the same memory growing for engine_ser. Am I using a correct sequence?

```
SetPipelineCachingMode(0) # Disable caching
# ...
for i in range(0, nframes+1, 1):
    OpenComputeEngine("localhost")
    db="localhost:./base.e-s.%04d" % i
    db=db+".exo"
    OpenDatabase(db)
    AddPlot("Molecule", "Particle Diameter", 1, 1)
    # ...
    AddPlot("Mesh","Mesh")
    # ...
    AddPlot("Pseudocolor", "Damage/Burn")
    # ...
    DrawPlots()
    SaveWindow()
    DeleteAllPlots()
    CloseDatabase(db)
    ClearCache("localhost")
    ClearCacheForAllEngines()
    CloseComputeEngine("localhost")
```

**Comment by rusu24edward** [comment]
@simunovics That's not what I expected, but there is nothing in your script that I would do differently. Thanks again for trying out these efforts--more data points for us to fix the underlying issue. Sorry I couldn't help mitigate the workflow. I've prioritized this issue for the developers team, and I hope we can get a fix in soon!
