### ISSUE TITLE
Lineout operator always greyed out

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#19]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

Hello,

I am having an issue in Visit where the Lineout operator is always grayed out. I’ve tried a few different types of plots, but the Lineout operator is still grayed out. Are there certain plots that the Lineout operator works with? Or specific parameters that need to be set?

Thanks,
Hardeep

**Comment by rusu24edward** [comment]
@griffin28 replied: 

Hello Hardeep…are your plots 2D? The lineout operator from the GUI only works on 2D plots.
-- Kevin

**Comment by rusu24edward** [comment]
@biagas replied:

Hello Hardeen,
        
To Clarify Kevin's statement: Lineout Mode in the viewer window toolbar is restricted to 2D plots. Lineouts for 3D plots can be achieved by other means. Please see these docs:
https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/Quantitative/Lineout.html#lineout
        
Kathleen

**Comment by sullan2** [comment]
Thanks! I was working with a 3D plot, the Query Function worked for me.
