### ISSUE TITLE
build_visit failure with packaging VisIt

### ISSUE THREAD

**Issue by biagas** [visit-dav/live-customer-response#192]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hello,

Could someone take a look at the attached failing build script/logs? I think it is close to work. The final message is:

Building VisIt . . . (~50 minutes)
All indications are that VisIt was successfully built.
Packaging VisIt ... (~10 minutes)
VisIt package failed.  Giving up
Unable to build or install VisIt.  Bailing out.
Error in build process.  See build_visit_log for more information. If the error is unclear, please include build_visit_log in a message to the visit-users@ornl.gov list.  You will probably  need to compress the build_visit_log using a program like gzip  so it will fit within the size limits for email attachments.

Thanks.

--

Valmor

[build_visit.gz](https://github.com/visit-dav/live-customer-response/files/5690197/build_visit.gz)
[build_visit_log.gz](https://github.com/visit-dav/live-customer-response/files/5690198/build_visit_log.gz)

**Comment by biagas** [comment]
Another email from Valmor:
------------------------------------
Hello,

The build process is failing towards the end:

[snip]

[100%] Built target visit_testing_py_setup Run CPack packaging tool...
CPack: Create package using TGZ
CPack: Install projects
CPack: - Run preinstall target for: VISIT
CPack: - Install project: VISIT
Symlinking current to 3.1.4
CMake Error at
/usr/local/packages/visit-3.1.4_gcc-9.3.0/visit/build/cmake_install.cmake:1800
(file):
   file INSTALL cannot find
"/usr/local/packages/visit-3.1.4_gcc-9.3.0/third_party/qt/5.14.2/linux-x86_64_gcc-9.3/plugins/xcbglintegrations".


The files that do exist with similar names are:


->  find . -name *xcbglintegratio* -print
./qt-everywhere-src-5.14.2/qtbase/src/plugins/platforms/xcb/.moc/moc_qxcbglintegrationplugin.cpp
./qt-everywhere-src-5.14.2/qtbase/src/plugins/platforms/xcb/gl_integrations/qxcbglintegrationfactory.h
./qt-everywhere-src-5.14.2/qtbase/src/plugins/platforms/xcb/gl_integrations/qxcbglintegrationplugin.h
./qt-everywhere-src-5.14.2/qtbase/src/plugins/platforms/xcb/gl_integrations/qxcbglintegration.h
./qt-everywhere-src-5.14.2/qtbase/src/plugins/platforms/xcb/gl_integrations/qxcbglintegrationfactory.cpp
./qt-everywhere-src-5.14.2/qtbase/src/plugins/platforms/xcb/gl_integrations/qxcbglintegration.cpp
./qt-everywhere-src-5.14.2/qtbase/src/plugins/platforms/xcb/.obj/moc_qxcbglintegrationplugin.o
./qt-everywhere-src-5.14.2/qtbase/src/plugins/platforms/xcb/.obj/qxcbglintegration.o
./qt-everywhere-src-5.14.2/qtbase/src/plugins/platforms/xcb/.obj/qxcbglintegrationfactory.o

Thanks for inputs.

--

Valmor

--

**Comment by biagas** [comment]
Hello Valmor,

I looked into the build_visit log you provided (thanks for that). 

Based on this section of the Qt build summary, your system may be missing the X11 development package (libx11-dev).


```
  X11 specific:
    XLib ................................. no
    XCB Xlib ............................. no
    EGL on X11 ........................... no
```
and this section shows that Qt isn't building the glx plugin
```
  XCB:
    Using system-provided XCB libraries .. no
    XCB XKB .............................. yes
    XCB XInput ........................... yes
    Native painting (experimental) ....... no
    GL integrations:
      GLX Plugin ......................... no
      EGL-X11 Plugin ..................... no
```

**Comment by markcmiller86-visit** [comment]
Hi Kathleen,

Thanks for the help.

No luck in installing additional X11 libraries. I have installed just 
about everything I can. There is no libx11-dev in my linux distro.


I have tried this option

./build_visit --system-qt --system-cmake --no-sphinx

I would like to use my system's libraries as much as possible. Is there 
a way to to use the build_visit script to only build vtk and python2.7 
and use my system packages for the remaining dependencies? The above 
command fails in compiling qwt but I already have qwt installed on my 
system and I would like to use it.

Thank you.

--

Valmor

**Comment by biagas** [comment]
To build only required libraries, using system locations for some:
```
--no-third-party
--system-cmake
--system-qt
--alt-qwt-dir /path/to/system/qwt
--system-cmake
--openssl
--zlib
--vtk
--python --no-sphinx
```

For other IO libraries, you would have to know which Database readers you wanted built.
You can see the full list of options by running
```
./build_visit --help
```

**Comment by markcmiller86-visit** [comment]
No matter what build_script and option I use I end up getting back to 
this X11 issue. I believe what is happening is that my system had 32 bit 
and 64 bit libX11:

->  file /usr/lib64/libX11.so.6.4.0
/usr/lib64/libX11.so.6.4.0: ELF 64-bit LSB shared object, x86-64, 
version 1 (SYSV), dynamically linked, stripped

->  file /usr/lib/libX11.so.6.4.0
/usr/lib/libX11.so.6.4.0: ELF 32-bit LSB shared object, Intel 80386, 
version 1 (SYSV), dynamically linked, stripped

and the Qt script is configuring with /usr/lib/libX11 which is 
incompatible and dismissing it. It should be configuring with 
/usr/lib64/libX11 instead.

I saw a message from another package I happen to be building where the 
incompatible 32bit library was skipped and the 64bit library used instead.

I will look at PATH issues, etc. but in the meantime I wanted to send 
this update for any inputs if you have.

Thanks,

--

Valmor
