### ISSUE TITLE
VR

### ISSUE THREAD

**Issue by biagas** [visit-dav/live-customer-response#193]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
From Charlson C Kim:

are there any plans for VR for visit?

**Comment by biagas** [comment]
When you say 'VR', do you have anything specific in mind?

**Comment by charlsonkim** [comment]
https://drive.google.com/file/d/1xwC3rqw8ezmunYj2Buwla9VT0hnLU5IM/view?usp=sharing

something a collaborator is working on, using paraview

**Comment by griffin28** [comment]
@charlsonkim From the NVIDIA side, one the goals in the next year or two is to make this capability available through Omniverse (https://developer.nvidia.com/nvidia-omniverse-platform). I will be working on a VisIt-Omniverse bridge that will allow VisIt data to be rendered in Omniverse. From there you will be able to use Omniverse's VR capabilities. One of the cool things is that you will also be able to pull in objects from other applications connected to the Omniverse platform.

**Comment by charlsonkim** [comment]
looking forward to your progress
