### ISSUE TITLE
Visit hangs outputting frames for a movie

### ISSUE THREAD

**Issue by biagas** [visit-dav/live-customer-response#194]
Eric, All,

There appears to be a bug  in November 2020 Visit release:  When outputting frames for a movie, and the debug partition session expires, Visit just hangs.  Whereas in older versions, it prompts the user to submit another job, and once new job starts, the outputting of frames continues without pause.  Now I just get the  spinning ball.

Greg

**Comment by biagas** [comment]
@burton29-LLNL I created a new issue for this.

Which previous version of VisIt did  you get a prompt to submit another job?

**Comment by burton29-LLNL** [comment]
Hi Kathleen,

It worked fine on the December 2019  release (2.13?).  It also may have worked fine on an earlier variant of release 3, for example one from April 2020, but I’ve lost complete recollection of when I uploaded the new releases in 2020.  Today is the first time I’m seeing this behavior, and I just uploaded the newest release this morning.

Greg

============================================
Gregory C. Burton, Ph.D.
Turbulence Analysis & Simulation Center (TASC), Head
Thermal Fluids Group, Group Leader
Computational Engineering Division
Lawrence Livermore National Laboratory
7000 East Avenue, L-140
Livermore, California 94550
(925) 422-3515
burton29@llnl.gov<mailto:burton29@llnl.gov>
https://tasc.llnl.gov
============================================

**Comment by biagas** [comment]
Thanks for the info. I want to try to reproduce ... are you generating a time-series movie? How many timesteps? Types of plots?
Sounds like you are running on LC is that correct?

**Comment by biagas** [comment]
@burton29-LLNL Are you still experiencing this?

**Comment by burton29-LLNL** [comment]
Must’ve been resolved, as I use VisIt a lot but haven’t had this problem recently.

============================================
Gregory C. Burton, Ph.D.
Turbulence Analysis & Simulation Center (TASC), Head
Thermal Fluids Group, Group Leader
Computational Engineering Division
Lawrence Livermore National Laboratory
7000 East Avenue, L-140
Livermore, California 94550
(925) 422-3515
burton29@llnl.gov
https://tasc.llnl.gov
============================================
