### ISSUE TITLE
Automate ability to set min max based on expression of maximum.

### ISSUE THREAD

**Issue by brugger1** [visit-dav/live-customer-response#197]
I got the following question from a user.

As I am visualizing a variable intensity and go through the different times, it would be useful, as I change the time, to keep a range fixed, not by numbers but by functions, like I would like to display   from  0.001*max(var) to max(var)  for example.   How do I do this,  everytime I change the time, max intensity changes and I have to redo the max/min.  It is a bit annoying.  Is there a way I can do this?

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by markcmiller86** [comment]
Wouldn't this be possible using the `IF` conditional expression and creating a new variable that is clamped to the desired range.

**Comment by brugger1** [comment]
I believe it's actually simpler than that. I think setting the min and max for the pseudocolor plot is all that is needed.

**Comment by markcmiller86** [comment]
Hmm...those are specific numerical values that don't change with time. This user seems to want to set the *min* to 0.1% of the maximum value. Can we do that?

**Comment by biagas** [comment]
Probably would have to create a python script to query the max and set the Pseudocolor plot's min/max at each time state.

**Comment by cyrush** [comment]
If we had a max expression that takes the max of all values, and then paints it back onto the mesh as a fully populated field value, then I think user could construct an expression that accomplishes this w/o scripting or changing the plot atts. 

Max in this way is not the most efficient, but it would be straight forward to add and use.

**Comment by cyrush** [comment]
the thing that makes this hard now (and pushes towards python scripting) is the fact that the max is a query and can't be easily interwoven in an expression.

**Comment by biagas** [comment]
Could even make it use the callback feature so it is called at every time state change.
Something along the lines of:
```
def set_pc_plot_minmax():
    SetQueryOutputToValue()
    max = Query("Max")
    pc = PseudocolorAttributes(1)
    pc.minFlag =1
    pc.min = 0.001*max
    pc.maxFlag = 1
    pc.max = max
    SetPlotOptions(pc)
 
RegisterCallback("SetTimeSliderStateRPC", set_pc_plot_minmax)
```

**Comment by markcmiller86** [comment]
I thought we indeed *did* have a `max()` expression. We don't. We do have a `max_over_time()` expression and that doesn't help here.

**Comment by markcmiller86** [comment]
Well, we do have a `max(var1, var2)` expression but that is computing the max between two values at every point in the mesh, not the max over all values.

**Comment by brugger1** [comment]
I believe Kathleen's coding is what the user is after. I believe that the user wants to use the max from the current time state, not over all time.

**Comment by cyrush** [comment]
@markcmiller86 yeah, max is a pairwise thing, not a reduction.  If we added a new max, it would have to have a clear (somehow :-) ) name to differentiate

**Comment by rusu24edward** [comment]
To map one range of values to another, you can use the following equation:
```
output = output_start + ((output_end - output_start) / (input_end - input_start)) * (input - input_start)
```
where
`output_start = 0.001*max(input)`,
`output_end = max(input)`,
`input_end = max(input)`,
`input_start = min(input)`
I believe we can generate the `min` and `max` of the variable using expressions with the second variable something higher/lower than any value in the user's time-series (do we expose DBL_MIN and DBL_max to expressions?). Then this can all be done with expressions.

**Comment by rusu24edward** [comment]
Something I missed: does the user want to use the max over all time?

**Comment by rusu24edward** [comment]
Forget what I said. Min and max don't work the way I thought they did. Sorry for the noise :)

**Comment by markcmiller86** [comment]
> @markcmiller86 yeah, max is a pairwise thing, not a reduction. If we added a new max, it would have to have a clear (somehow :-) ) name to differentiate

Just off the top of my head, how 'bout `no_the_real_max_of_just_this_variable_over_the_whole_mesh(<var>)`

**Comment by brugger1** [comment]
Kathleen's solution was close. SetTimeSliderStateRPC only applies when the time slider is dragged to a new state. If you use the previous and next frame buttons it doesn't apply. There are different callbacks for those events. The following captures those additional events. Note also that SetTimeSliderStateRPC takes 1 argument and the others take 0 arguments, hence 2 functions.

def set_pc_plot_minmax():
    SetQueryOutputToValue()
    max = Query("Max")
    pc = PseudocolorAttributes(1)
    pc.minFlag =1
    pc.min = 0.001*max
    pc.maxFlag = 1
    pc.max = max
    SetPlotOptions(pc)

def set_pc_plot_minmax1(state):
    set_pc_plot_minmax()

RegisterCallback("SetTimeSliderStateRPC", set_pc_plot_minmax1)
RegisterCallback("TimeSliderNextStateRPC", set_pc_plot_minmax)
RegisterCallback("TimeSliderPreviousStateRPC", set_pc_plot_minmax)
