### ISSUE TITLE
python version in VisIt

### ISSUE THREAD

**Issue by biagas** [visit-dav/live-customer-response#198]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

Hello,

Just to double check. Is python2.7.14 the only version used by VisIt? 
This is what is downloaded by the build_visit script. Is there a plan to upgrade to python 3.8?

Thanks,

--

Valmor

**Comment by biagas** [comment]
Python 3 support is in the works and is currently available in our develop branch (using Python 3.7.7), experimentally.
It is tentatively scheduled to be fully operational for our 3.2 release.
Kathleen

**Comment by markcmiller86-visit** [comment]
Thanks.

Is there a build_script I can use with the dev branch?

--

Valmor

**Comment by biagas** [comment]
If you checkout our develop branch, you can run the build_visit script there, with --write-unified-file <script file name> to create the latest build script for develop, eg:

visit/src/tools/dev/scripts/build_visit --write-unified-file build_visit_dev

Then run 'build_visit_dev' with whatever options you need. (--help to see all the options).

**Comment by markcmiller86-visit** [comment]
Got it.

Thanks for the prompt response.

--

Valmor
