### ISSUE TITLE
Need Mesalib-based version on LC

### ISSUE THREAD

**Issue by doutriaux1** [visit-dav/live-customer-response#20]
I'm generating Visit movies on LC as part of a workflow. Since these will be run from cli I would like to avoid having to X forward or ask my users to set their DISPLAY and X forward, etc...

I cannot find such a version on LC (rztopaz)

**Comment by rusu24edward** [comment]
Hi @doutriaux1,

Can you explain what you mean by, "cannot find such a version on LC"? A *version* of what, exactly?

Thanks,
Eddie

**Comment by rusu24edward** [comment]
Ah I see. Sorry, I did not look at the title of the post. I will look into this and get back to you shortly.

**Comment by cyrush** [comment]
@doutriaux1 all lc versions are built with support for offscreen rendering.

You can avoid popping up any windows by running your script using:

`visit -nowin -cli -s {script.py}`

**Comment by doutriaux1** [comment]
@cyrush w/o Xwin32 on and running:

```
/usr/gapps/visit/bin/visit  -nowin -no-launch-x -s my_script.py
```

I get:

```
connect localhost port 6000: Connection refused
QXcbConnection: Could not connect to display 192.168.128.188:101.0
```

But you're right it might be because I had XForward enabled and my X server off on my windows laptop.

Let me explore this.

**Comment by doutriaux1** [comment]
@cyrush my mistake, I had not pasted the -cli from my original script when testing... Totally fine with the `-cli` sorry for the noise.

**Comment by cyrush** [comment]
@doutriaux1 no worries, glad its working for you now!
