### ISSUE TITLE
python 3 on build_script_dev

### ISSUE THREAD

**Issue by dealmeidavf** [visit-dav/live-customer-response#201]
This section

```bash
function python_set_vars_helper
{
    VISIT_PYTHON_DIR=`"$PYTHON_CONFIG_COMMAND" --prefix`
    PYTHON_BUILD_DIR=`"$PYTHON_CONFIG_COMMAND" --prefix`
    PYTHON_VER=`"$PYTHON_COMMAND" --version 2>&1`
    PYTHON_VERSION=${PYTHON_VER#"Python "}
    PYTHON_COMPATIBILITY_VERSION=${PYTHON_VERSION%.*}
    ########################
    PYTHON_INCLUDE_PATH=`"$PYTHON_CONFIG_COMMAND" --includes`
    #remove -I from first include
    PYTHON_INCLUDE_PATH="${PYTHON_INCLUDE_PATH:2}"
    #remove any extra includes
    PYTHON_INCLUDE_PATH="${PYTHON_INCLUDE_PATH%%-I*}"
    PYTHON_INCLUDE_DIR="$PYTHON_INCLUDE_PATH"
    PYTHON_LIBRARY=`"$PYTHON_CONFIG_COMMAND" --libs`
    #remove all other libraries except for python..
    PYTHON_LIBRARY=`echo $PYTHON_LIBRARY | sed "s/.*\(python[^ ]*\).*/\1/g"`

    if [[ "$DO_STATIC_BUILD" == "yes" ]]; then
        PYTHON_LIBRARY="lib${PYTHON_LIBRARY}.a"
    else
          if [[ "$OPSYS" == "Darwin" ]]; then
              PYTHON_LIBRARY="lib${PYTHON_LIBRARY}.dylib"
          else
              PYTHON_LIBRARY="lib${PYTHON_LIBRARY}.so"
          fi
    fi

    # vfda
    echo " "
    echo "visit_python_dir: $VISIT_PYTHON_DIR"
    echo "python_command: $PYTHON_COMMAND"
    echo "python_config_command: $PYTHON_CONFIG_COMMAND"
    echo "python_build_dir: $PYTHON_BUILD_DIR"
    echo "python_version: $PYTHON_VERSION"
    echo "python_include_path: $PYTHON_INCLUDE_PATH"
    echo "python_include_dir: $PYTHON_INCLUDE_DIR"
    echo "python_library_dir: $PYTHON_LIBRARY_DIR"
    echo "python_library: $PYTHON_LIBRARY"
    echo "python_library_dir/python_library: "${PYTHON_LIBRARY_DIR}/${PYTHON_LIBRARY}
    echo " "

    #
    # use python's distutils info to get the proper library directory.
    #
    PYTHON_LIBRARY_DIR=`"$PYTHON_COMMAND" -c "import sys;from distutils.sysconfig import get_config_var; sys.stdout.write(get_config_var('LIBDIR'))"`

    # vfda
    echo "python_library_dir: $PYTHON_LIBRARY_DIR"

    if [ ! -e "${PYTHON_LIBRARY_DIR}/${PYTHON_LIBRARY}" ]
    then
        # some systems eg fedora use lib64...
        PYTHON_LIBRARY_DIR="${VISIT_PYTHON_DIR}/lib64"
        if [ ! -e "${PYTHON_LIBRARY_DIR}/${PYTHON_LIBRARY}" ]
        then
            # some systems eg debian use x86_64-linux-gnu...
            PYTHON_LIBRARY_DIR="${VISIT_PYTHON_DIR}/lib/x86_64-linux-gnu"
            if [ ! -e "${PYTHON_LIBRARY_DIR}/${PYTHON_LIBRARY}" ]
            then
                error "python library was not found, cannot configure python"
            fi
        fi
    fi
    PYTHON_LIBRARY="${PYTHON_LIBRARY_DIR}/${PYTHON_LIBRARY}"
```

does not identify the `python` system on my machine. The output results are:

>->  ./build_visit_dev  --system-cmake --system-python --no-sphinx
>Processing bsd license.
>using system cmake
>version: 3.17.4
>
>CMake suite maintained and supported by Kitware (kitware.com/cmake). build: /usr bin: /usr/bin root: /usr/share/cmake
>Using system python
>
>visit_python_dir: /usr
>python_command: python
>python_config_command: python-config
>python_build_dir: /usr
>python_version: 3.8.6
>python_include_path: /usr/include/python3.8 
>python_include_dir: /usr/include/python3.8 
>python_library_dir: 
>python_library: lib-lcrypt -lpthread -ldl -lutil -lm -lm.so
>python_library_dir/python_library: /lib-lcrypt -lpthread -ldl -lutil -lm -lm.so
>
>python_library_dir: /usr/lib64
>python library was not found, cannot configure python

It seems to get passed if I set:

````bash
PYTHON_LIBRARY="/usr/lib/python3.8/site-packages"
````

Just some feedback on using the future `python 3` build.
Thanks.

 --
 Valmor

**Comment by markcmiller86** [comment]
@cyrush, @biagas or @brugger1 is this a known issue?

**Comment by biagas** [comment]
It may have been fixed by recent changes I made to bv_python.sh. PYTHON_COMMAND and PYTHON_CONFIG_COMMAND weren't being set properly for system python 3. PR #5363 and #5371

**Comment by biagas** [comment]
Hi Valmor,

I'm looking into this issue a bit more. The bv_python.sh module uses 'python3-config' (or python-config for python2) to find things like python's include and lib dirs, etc.

If you do a 'which python3-config' on your system, does it return the correct location for the system python you wished to use?

If not, we also have an --alt-python-dir option to build_visit which will allow you to specify a location for python that isn't the usual system location.  This option expects a full-path to the python location, up-to-but-not-including 'bin'.  This option will also expect that 'python3-config' or 'python-config' exists in the alt-dir/bin location.

BTW, there is still a problem with bv_python preferring python2 over python3 when --system-python is chosen. I am working on that fix.
