### ISSUE TITLE
Getting Variables Names out of silo files

### ISSUE THREAD

**Issue by doutriaux1** [visit-dav/live-customer-response#203]
I am writing a script to plot variables from a silo database. My issue is that dependending on the simulation, the same variable might have a slightly different name. Is there a way to Query a visit opened database to access the variables available?

This would allow me to make sure the script requested variable is matched to the correct name in the file.

**Comment by brugger1** [comment]
You can get the list of variables with the GetMetaData() function. To print the list of scalars from /usr/gapps/visit/data/rect2d.silo:

md = GetMetaData("/usr/gapps/visit/data/rect2d.silo")
for i in range(0, md.GetNumScalars()):
    md.GetScalars(i).name

Similarly, you can do the same with:

Meshes
Vectors
Tensors
SymmTensors
Arrays
Materials
Species
Curves
Labels

by substituting the above name for "Scalars".
