### ISSUE TITLE
build_visit3_1_4 script failing on adding tools/DataManualExamples/Simulaitons directory

### ISSUE THREAD

**Issue by shots47s** [visit-dav/live-customer-response#205]
I am trying to use the build_visit3_1_4 script and am seeing an error. 

I am using the following build command:

 `./build_visit3_1_4 --server-components-only --parallel --static --skip-opengl-context-check --thirdparty-path /opt/packages/Visit --makeflags -j16`

The code works fine until building the actual visit package until I get to the following error:
`CMake Error at CMakeLists.txt:2126 (ADD_SUBDIRECTORY):
  ADD_SUBDIRECTORY given source "tools/DataManualExamples/Simulations" which
  is not an existing directory.`

It would appear that I am to download or the script is to download something that is not in the visit tarball, but when I go to the website, anything that looks like this is missing. Any advice?

**Comment by brugger1** [comment]
Looking at the build_visit command line, my guess is that the "--static" is causing the issue. This is not a configuration we use very frequently. Would it be possible to remove the "--static" option or could you describe the use case you have for building static? Also, it would be useful to know what OS you are encountering this problem on.

**Comment by shots47s** [comment]
Sure, I will try that, it was a legacy from a previous build, I am not sure it is needed. 

This is on Centos8.

**Comment by shots47s** [comment]
That worked, thank you. 

Details:
OS: CentOS8
Kernel:  4.18.0-193.28.1.el8_2.x86_64
Compiler: intel 20.4
Build command:
`build_visit3_1_4 --server-components-only --parallel --skip-opengl-context-check --thirdparty-path /opt/packages/Visit --no-sphinx --makeflags -j16`

Thanks for your help.

**Comment by brugger1** [comment]
You're welcome. Thanks for the update.

I submitted ticket #5387 for the CMakeLists.txt error.
