### ISSUE TITLE
Repurpose Boxlib plugin code for Nyx/AMReX ML Workflow

### ISSUE THREAD

**Issue by markcmiller86** [visit-dav/live-customer-response#212]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

@prashplus writes...

> I am working on a project related to Big data analysis. I am wokring on Visit's code from last few days and tring to extract the part that reads the AMRex/Boxlib plt files from Nyx(https://github.com/AMReX-Astro/Nyx). But, I am having some difficulty. Just able to get how to read the Header file from the plt dir by looking at this file avtBoxlibFileFormat.C (https://github.com/visit-dav/visit/blob/develop/src/databases/Boxlib3D/avtBoxlibFileFormat.C).

Apologies but...Are you trying to repurpose VisIt's boxlib plugin to read boxlib data in your ML workflow?

> Can you tell me the part of code that I should look and some guidance like what should I do if I want to make my own reader for plt files from Nyx/AMReX.

If you want to write your own plugin, a big first question is whether you need it to operate in parallel or not? Developing a *scalable* parallel plugin is more involved than something that either doesn't scale well or is not intended to work in parallel at all. A second question is whether the input data is always a monolithic single block or is decomposed into multiple blocks (domains, chunks, pieces) and/or in possibly separate files.

You can start from *scratch* or by copying an existing simple plugin and modifying it. I would recommend the latter.

A basic database plugin needs to implement just a few methods...

- `MyPlugin::GetType(...)` /* returns a string for the name of the plugin */
- `MyPlugin::PopulateDatabaseMetaData(...)` /* returns avtDatabaseMetadata about the contents of a database */
- ⏸️ `MyPlugin::GetMesh(...)` /* returns a vtkXXXGrid object (coordinates and topology) for a given block/piece/domain */
- ⏸️ `MyPlugin::GetVar(...)` /* returns a vtkXXXDataArray object for a variable on the mesh */
- ⏸️ `MyPlugin::GetVectorVar(...)` /* for variables with more than a single component */
- `MyPlugin::FreeUpResources(...)`

The methods with ⏸️ are parallel and called independently, with different args on different MPI ranks. The others are called collectively in parallel with identical args on all ranks.

Typically, one first tries to get `PopulateDatabaseMetaData(...)` to do basically the correct thing. You can have a plugin that does *just* that but returns `NULL` for the other calls. That way, you can test if GUI is getting populated with variables you expect as you test opening various database examples you have and you don't have to worry about making any plots. Next, make a `GetMesh()` call work correctly and that a MeshPlot in the GUI does what you expect with it and then finally the `GetVar` calls.

If you are working with AMReX, my impression is that the old *BoxLib-like* format it outputs for plotting has potentially been made obsolete by a newer HDF5-based file format that AMReX produces. If that is so, I would really recommend starting from that format rather than continuing with the BoxLib format. If you do go the route of AMReX/HDF5 files, then you probably want to have a look at various HDF5 plugins we have in VisIt to see if any are close to your needs (those in bold may be particularly useful in your quest)

ALS AMR BATL Blueprint CaleHDF5
CarpetHDF5 **Chombo** CosmosPP Denovo Enzo
FLASH GTC H5Nimrod H5Part M3D
M3DC1 MOAB OpenPMD PFLOTRAN PVLD
**Pixie** **SAMRAI** SXRIS Tetrad UNIC
Velodyne Vs XGC **Xdmf**
Xolotl

**Comment by cyrush** [comment]
One option may be to use VisIt to read the boxlib data and export it to a simpler format that can be digested by an ML pipeline.

**Comment by prashplus** [comment]
Yes, I need it to operate in parallel, since I am going to run it in on a HPC system. I think the input data is actually divided into multiple plt files.

Ok sure. I will start with an existing simple plugin and modifying it.
Yes, I will go step by step as you specified, starting from `PopulateDatabaseMetaData(...)`.

You are right, HDF5 seems an easy way to go for my quest. Sure,I will also try HDF5 plugins from Visit you suggested.

I will keep you posted as I go ahead.

**Comment by markcmiller86** [comment]
@prashplus as a preliminary part of your work, please consider what @cyrush suggested...you can use VisIt maybe as an intermediary to read BoxLib data and then write out a format that puts the data in a form you can more easily digest in your ML workflow. Some possible output (export database operation) formats are...

**BOV** Curve2D
H5Part Image **PLY**
**RAW** **STL** Silo
Tecplot VTK WavefrontOBJ **XYZ**
Xmdv lata

Plus various image fomats (save as operation) if those are appropriate (jpg, bmp, png, tiff, ppm)

**Comment by prashplus** [comment]
Ya sure, I will consider that.

**Comment by markcmiller86** [comment]
BTW...as part of these [hadoop](https://github.com/markcmiller86/silo-issues/wiki/Silo_Hadoop_and_VisIt) and [spark](https://github.com/markcmiller86/silo-issues/wiki/Apache_Spark_and_VisIt) projects, years ago we wrote a [python-query based exporter](https://github.com/visit-dav/visit/tree/develop/src/tools/data/hdfs_export) and we have a [reader](https://github.com/visit-dav/visit/tree/develop/src/databases/HDFS) that reads from the resulting ascii files. It hasn't been exercised in a while but may be useful.

**Comment by prashplus** [comment]
Oh this is interesting. Thanks

**Comment by cyrush** [comment]
The blueprint plugin will also allow you to create hdf5 files that you could consume in python using h5py.

**Comment by markcmiller86** [comment]
And, I forgot about [these slides](https://visit-dav.github.io/visit-website/pdfs/Tutorial_FileFormatReader.pdf)
