### ISSUE TITLE
Changing the number of decimals in the Y axis.

### ISSUE THREAD

**Issue by biagas** [visit-dav/live-customer-response#213]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hello,

I have a 2D plot that on the Y axis is showing the ticks values: 0.20, 0.40, ... 1.00. The tick values are OK, but I want to have only one
decimal: 0.2, 0.4, etc. but I couldn't find any way to do it. Am I out of luck, or did I miss some setting in the Annotations window?

Thanks,
--
Ángel de Vicente

**Comment by biagas** [comment]
Hello Angel,

Sorry, but there isn't really a way to control that. 
We have multiple tickets in the system to address this in some fashion or another.
I will see about elevating the most appropriate one for immediate re-consideration.

Kathleen

**Comment by biagas** [comment]
Elevated ticket 226, closing.

**Comment by markcmiller86-visit** [comment]
Hi,

How do I unsubscribe this email list?  The unsubscribe link does not work (after it directed me to log in to GitHub).

Thanks.

Wei
On Jan 28, 2021, 9:40 AM -0800, Kathleen Biagas via visit-users <visit-users@elist.ornl.gov>, wrote:

Closed visit-dav/live-customer-response#213<https://github.com/visit-dav/live-customer-response/issues/213>.

**Comment by markcmiller86** [comment]
Wei,

Send a message to visit-users-leave@ornl.gov<mailto:visit-users-leave@ornl.gov>. It will send a confirmation and if you reply to that confirmation, you will be unsubscribed. But, you must do this from whatever email account is receiving these messages.

I tried to do it for you but there are 10+ users with “wei” somewhere in their names and I had no other way to identify you.

Apologies for everyone for spam.

Mark


"markcmiller86-visit" wrote:

Hi,

How do I unsubscribe this email list? The unsubscribe link does not work (after it directed me to log in to GitHub).

Thanks.

Wei
On Jan 28, 2021, 9:40 AM -0800, Kathleen Biagas via visit-users <visit-users@elist.ornl.gov>, wrote:

Closed visit-dav/live-customer-response#213<https://github.com/visit-dav/live-customer-response/issues/213>.
