### ISSUE TITLE
Picking a built-in expression

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#218]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.
---
Genesis Rosado wants to pick our built-in expression `shape_and_size`. She records the actions in the GUI and gets the following command (condensed):
```
pa = GetPickAttributes()
pa.variables= ("mesh_quality/mesh_3d/shape_and_size")
SetPickAttributes(pa)
```
She added this to her script and then tried to do a zone pick:
```
PickByZone(element=100)
```
The shape and size variable was not included in the output. She tried
```
PickByZone(element=100, vars=("mesh_quality/mesh_3d/shape_and_size"))
```
Still nothing. Doing this in the CLI return the following 
```
curv3d.silo
curvmesh3d 
Point: <-1.02575, 2.01314, 0.5>
Zone:  100
Incident Nodes:  103  104  135  134  1374  1375  1406  1405  
mesh_quality/mesh_3d/shape_and_size:  
    No Information Found
```

### Work-around:
She was able to accomplish what she wanted by first defining an expression `DefineScalarExpression('my_var', 'shape_and_size(Mesh)')` and picking that expression.

**Comment by biagas** [comment]
Does surrounding the var with <> work?
eg:
```
PickByZone(element=100, vars=("<mesh_quality/mesh_3d/shape_and_size>"))
```

**Comment by rusu24edward** [comment]
> Does surrounding the var with <> work?

I just tried this on curv3d.silo, where the expression is `mesh_equality/shape_and_size`, and it did not work even when I included the angle brackets.

**Comment by biagas** [comment]
Does it work if that expression is the plotted variable (eg you don't have to specify a variable for Pick to work report on?)

**Comment by rusu24edward** [comment]
I plotted the shape and size and performed the pick through the CLI. This is the output I got in the CLI window:
```
>>> PickByZone(element=100)
{'pick_letter': 'B', 'point': (-1.0257458090782166, 2.0131395161151886, 0.5), 'zone_id': 100, 'incident_nodes': (103, 104, 135, 134, 1374, 1375, 1406, 1405), 'filename': 'curv3d.silo'}
```
and here is what shows in the Pick GUI window
```
curv3d.silo
curvmesh3d 
Point: <-1.02575, 2.01314, 0.5>
Zone:  100
Incident Nodes:  103  104  135  134  1374  1375  1406  1405  
mesh_quality/shape_and_size:  
    No Information Found
```

**Comment by rusu24edward** [comment]
This is what I see when I do a pick through the GUI zonal pick:
```
curv3d.silo
curvmesh3d 
Point: <-3.54059, 3.2752, 30>
Zone:  35917
Incident Nodes:  38013  38014  38045  38044  39284  39285  39316  39315  
mesh_quality/shape_and_size:  <zonal> = 0.141439
```

**Comment by biagas** [comment]
Thanks. This should be a bug ticket.

**Comment by rusu24edward** [comment]
Thanks for looking at it! I'll add the bug ticket.

**Comment by rusu24edward** [comment]
Tracked in [5421](https://github.com/visit-dav/visit/issues/5421)
