### ISSUE TITLE
How to use VisIt to get a mean value of variables?

### ISSUE THREAD

**Issue by markcmiller86** [visit-dav/live-customer-response#219]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

I am a beginner of Vislt, and I use Vislt to visualize the flow field. 

For present work, I have got some time-dependent variables (such as flow velocity U), and I want to obtain the mean values of those variables (I mean the time-mean velocity). How can I achieve that?

With best regards

Li-Ming

**Comment by markcmiller86** [comment]
You probably want to do a **Variable Sum Query** which you can read about [here](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/Quantitative/Query.html?highlight=variable%20sum%20query#query). You can divide the sum/total by whatever weight factor you need to get the average. If you want an average by count of nodes or zones, then also do a **NumZones** or **NumNodes** query to get that number.

**Comment by markcmiller86-visit** [comment]
Dear Mr. Miller,

Thanks so much for your suggestions!

I think that I have misled you about my question. I have read the
introduction about Variable Sum Query, I think that this function is
related to the discrete data point. Actually, I wanna get the average of a
series of pesudcolor figures obtained from the flow field. I attached one
figure example. Would you mind giving me some additional suggestions?

With best regards

Li-Ming

clink link to see image....
https://user-images.githubusercontent.com/5720676/106505785-a3661d00-647d-11eb-9a4f-ad4cf120e451.png

Mark C. Miller via visit-users <visit-users@elist.ornl.gov> 于2021年1月31日周日
上午5:01写道：

**Comment by markcmiller86-visit** [comment]
Moreover, I wanna get a pseudocolor figure of the averaged variables, how
can I do for that?

Li-Ming Chao <clm004886@gmail.com> 于2021年1月31日周日 上午11:50写道：

**Comment by aowen87** [comment]
Hi Li-Ming,

Do you want the averaging to take place for every element (zone or node) across time? If so, we have an expression called "average_over_time" that allows you to do this. Documentation can be found [here](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/Quantitative/Expressions.html?highlight=average_over_time#time-iteration-expressions).

**Comment by markcmiller86-visit** [comment]
Dear Alister,

Thanks so much for you reply. I think the expression "average_over_time"
can solved my problem. However, when I used this expression, some errors
occurred. I have attched the figure, please kindly give me some suggestions.

With best regards!

Li-Ming

[image: 338.jpg]

Alister via visit-users <visit-users@elist.ornl.gov> 于2021年2月2日周二 上午12:44写道：

**Comment by aowen87** [comment]
Hi Li-Ming,

For some reason, I haven't been able to access your attachments... I'm not quite sure why that's happening, but I'll go ahead and make a guess that the issue your encountering is an error that reads something along the lines of `The expression was invalid: The expression parser encountered an unexpected token` or maybe `viewer: engine_ser: The expression variable "AOT" was declared to be of type scalar, but is actually of type vector`. Is that right?

If so, maybe the following will help. If not, could you paste the text from the error in your response?

I think the template we provide for this expression is a little odd/confusing, and it's easy to make mistakes when constructing it. The template in the GUI will look like this:

`average_over_time(<var> [, "pos_cmfe", <fillvar-for-uncovered-regions>] [, start-time-index, stop-time-index, stride])`

I believe the lists in this template are different routes you can take for constructing this expression. If your using a single, time-varying mesh, then what you'll want to use is actually this:

`average_over_time(<var>, start-time-index, stop-time-index, stride)`

So, if I have a vector field named "direction" in a mesh with 71 time steps, I could create a new variable that represents the average over all time steps with the following:

`average_over_time(direction, 0, 70, 1)`

I'd also need to change the expression type to "Vector mesh variable" since my variable is a vector.

Does that help?

**Comment by markcmiller86-visit** [comment]
Dear Alister，

Thanks so much for your kind reply！

I have used the expression as your suggestion. However, there are some
problems. The error like this:

The compute engine running on host DESKTOP-STQ3IUC issued the following
warning: avtAverageOverTimeExpression:  Clamping end time to number of
available timesteps.

Shortly thereafter, the following occured...

The compute engine running on DESKTOP-STQ3IUC has exited abnormally.

Shortly thereafter, the following occured...

The Pseudocolor plot of "ux" for the file "E:\10\viz_2d\dumps.visit" could
not be generated by the compute engine on host "localhost".

Would you mind give me some suggestions？

With best wishes！

Li-Ming

Alister via visit-users <visit-users@elist.ornl.gov> 于2021年2月3日周三 上午12:08写道：

**Comment by aowen87** [comment]
Hi Li-Ming,

The first warning, "avtAverageOverTimeExpression:  Clamping end time to number of available timesteps." is nothing to worry about. This one is just saying you requested X time steps when only X-A (s.t. A > 0) time steps exist. VisIt will automatically clamp to your last time step for you.

The second message seems to be an actual issue... Can you post the exact expression definition you're using? Also, what type of dataset is this, and which version of VisIt are you using?

**Comment by markcmiller86-visit** [comment]
Dear Alister,

The version of VisIt is 2.13.3 which has been installed in Win 10
plateform.  The expression I used is average_over_time(U_x, 19000, 20000,
125), where U_x is the name of variables, 19000 is the start time in VisIt,
20000 is the end time, and 125 is the time step of the data. Actually, I
have tried other values of start time, end time and time step, the problem
also occurs. For the dataset, I got the dataset from a opening
computational fluid dynamics source IBAMR. The format of the dataset is
*.visit which is related to a series of *.samrai files.

With best regards!

Li-Ming



Alister via visit-users <visit-users@elist.ornl.gov> 于2021年2月4日周四 上午12:19写道：

**Comment by aowen87** [comment]
Hi Li-Ming, 

I think this might be the problem: `average_over_time(U_x, 19000, 20000,
125)`

It sounds like the first time in your dataset is 19000, the last is 20000, and the time increment between each step is 125. Did I get that right? 
What `average_over_time` expects is the _indices_ of these times. So, it sounds like your total number of time steps is something around (20000 - 19000) / 125 = 8. You time _steps_ here are then 0, 1, 2, 3, 4, 5, 6, 7. To create an average over all time steps, I would use `average_over_time(U_x, 0, 7, 1)`. Does that make sense?

**Comment by markcmiller86-visit** [comment]
Dear Alister,

I have tried your suggestions. However, the error still persists. I
uploaded the dataset into the attachment
 viz_2d.zip
<https://drive.google.com/file/d/1p8TcgqTwWULPKEevX85zg6VWxGBXVhQA/view?usp=drive_web>
and OneDrive (https://1drv.ms/u/s!Amm5z6-izNhkbBDsd-12c8W75Ik?e=wIe5bw),
may I beg you for testing my dataset ?

With best regards!

Li-Ming

Alister via visit-users <visit-users@elist.ornl.gov> 于2021年2月4日周四 下午11:39写道：

**Comment by aowen87** [comment]
Hi Li-Ming, 

Sorry for the delayed response. I finally had a chance to open up your dataset, but I didn't see any variables defined other than the mesh. Where is the variabe U_x coming from?
