### ISSUE TITLE
Trouble reading CGNS files

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#22]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

Hi,

I'm a new CGNS user and I've been basing myself on the example scripts included in the library's source code. However, VisIt fails to read all the CGNS files produced by those scripts. I've opened VisIt through the terminal with the following command:
$ visit -debug 5

The following error occurs:
```
VisIt could not read from the file "/Users/my_user/Documents/cgns/grid_structured.cgns".
```

The generated error message was:
```
There was an error opening /Users/my_user/Documents/cgns/grid_structured.cgns. It may be an invalid file. VisIt tried using the following file format readers to open the file: CGNS, Silo

If you know the specific format reader VisIt should use to read this data, you can use Open As... (GUI) or '-o <file>,<plugin> (CL arg.) and identify that specific reader for VisIt to try. This will possibly give more information on the exact error.
```

The example CGNS script and the output file are both attached, as well as the level 5 log files. Not that using old CGNS files located in the link above works with no errors. Also the current CGNS file was read successfully with Paraview.

Thank you for your help,
Solal

**Comment by rusu24edward** [comment]
Hi Solal,

Thanks for making us aware of this issue. Since other CGNS files are being read correctly, it seems to me that the issue is not in reading the CGNS files but in the example script that is creating the grid_unstructured.cgns file. I will take a look at this script today and try to come up with a fix.

Thanks,
Eddie

**Comment by markcmiller86-visit** [comment]
On Mar 25, 2020, 9:16 AM -0700, Edward Rusu via visit-users <visit-users@elist.ornl.gov>, wrote:

Hi Solal,

Thanks for making us aware of this issue. Since other CGNS files are being read correctly, it seems to me that the issue is not in reading the CGNS files but in the example script that is creating the grid_unstructured.cgns file. I will take a look at this script today and try to come up with a fix.

Thanks,
Eddie

**Comment by rusu24edward** [comment]
> example scripts included in the library's source code.

Solal,
Can you provide me with the version of the cgns library you are using?

**Comment by rusu24edward** [comment]
[CGNS_trouble.zip](https://github.com/visit-dav/live-customer-response/files/4403709/CGNS_trouble.zip)

**Comment by markcmiller86** [comment]
If Solal is using CGNS v4, VisIt won't read it correctly. I am pretty sure this is now captured in [this product development issue](https://github.com/visit-dav/visit/issues/4560)
