### ISSUE TITLE
Python 3 status

### ISSUE THREAD

**Issue by brugger1** [visit-dav/live-customer-response#220]
Sorry if this is covered somewhere, but I've been unable to determine the level of integration/support of Python 3 within VisIt.  Specifically, it does not appear that VisIt can be built without Python 2 and it appears that some components link to the Python 2 libraries creating a runtime dependency as well.  Is this accurate?  Is it possible to build and/or run VisIt on a system without Python 2?

-Patrick

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by brugger1** [comment]
Hi Patrick,

We will have Python 3 in our upcoming release VisIt 3.2. We are in the process of fixing that last few critical bugs and then we will create the release. Assuming nothing unforeseen comes up, we should have it out by mid to late of February. If you would like to try it out sooner, you could clone our development branch and build it yourself, although there may be some build issues, since we only built on a handful of our development systems.

Eric

**Comment by brugger1** [comment]
Thank you very much for the quick response.  I've grabbed the development branch and will try to get it built on my system.  It appears you are targeting Python 3.7 and still using VTK 8.1.  We are using Python 3.8 which requires VTK 9 so there might be some patches necessary but hopefully I can get it to work.

-Patrick

**Comment by brugger1** [comment]
Yes on both counts. Python 3.7 and VTK 8.1. We started on the Python 3 port a little over a year ago, so my guess is those were the most current at the time.

**Comment by brugger1** [comment]
My recommendation is to avoid directly linking against a specific version of Python 3.x.

For example defining:
-DPy_LIMITED_API=0x03030000

will make sure that your application is ABI compatible with Python 3.3 and newer.

Linux is fine not linking against a python dll.

macOS would require adding linker options like:

"-undefined dynamic_lookup -flat_namespace"

and windows provides a helper lib to link against a generic python dll:

python3.lib

instead of a .lib file with a specific version number.

Than users can use any Python 3 installation on their system.  Of course, there would be an issue if you directly call the C API for a module like numpy.

Please see:

https://docs.python.org/3/c-api/stable.html


Regards,

Juan

**Comment by markcmiller86-visit** [comment]
The number of patches I started racking up to move VisIt to VTK 9.0.1 got
out of hand so I rolled back to Python 3.7.9 and VTK 8.1.0.  Things seem to
be mostly working but I'm getting segfaults when attempting to use the
FieldViewXDB writer to generate extracts through the Python interface,
though VTK appears to work fine.  I'm digging down through the layers* to
try and pinpoint the failure but it seems likely I'll eventually get to the
FieldViewXDB prebuilt shared libraries.  It looks like they have not been
updated in quite some time.  Should those work or will I need to wait until
newer prebuilt libraries are available?

* I know it at least gets as far as viewer/core/actions/IOActions.C around
line 237 where it calls:
GetViewerEngineManager()->ExportDatabases(key, networkIds, exportAtts, "")

-Patrick

**Comment by brugger1** [comment]
Sorry about not closing the loop on this. I believe those should work, but we are very close (a week or two) to releasing 3.2, which will have Python 3 support and the FieldViewXDB prebuilt shared libraries, so I suggest waiting.

**Comment by markcmiller86-visit** [comment]
I have built the official 3.2 release and am still encountering segfaults
when attempting to use the FieldViewXDB extract format.  It has come to my
attention that the way we are interfacing with VisIt (simV2) appears
somewhat deprecated and I'm wondering if that could have something to do
with my issues.  Any help would be greatly appreciated.

Thanks,
Patrick

**Comment by markcmiller86** [comment]
Mentioning @BradWhitlock in hopes he might have some insigts.

**Comment by brugger1** [comment]
The simV2 interface is still supported. If we have missed something we should fix it. I believe the libraries related to the FieldViewXDB are pretty old at this point, perhaps we need new ones from IL. @BradWhitlock should be able to provide information on that as well.

**Comment by markcmiller86-visit** [comment]
It is very possible I am missing something, though I don't appear to be
able to set options for the VTK export format.  Our code was attempting to
use the VTK XML Binary format for exports:

opts = VisIt_OptionList_alloc()
# ... other options and hvars NameList being set
VisIt_OptionList_setValueB(opts,'Binary format',1)
VisIt_OptionList_setValueB(opts,'XML format',1)
rv = VisItExportDatabaseWithOptions(filename, 'VTK', hvars, opts)

Those options are no longer used so we always end up with Legacy ASCII.  I
can see by looking in avtVTKOptions.C that the new way to accomplish this
would be to specify a 'FileFormat' of 'XML Binary' but any attempt to set
that value through the existing VisIt_OptionList_setValueX() routines ends
up with segfaults during the export.  Do you know how that option should be
set through the simV2 interface?

I'll try to dig further into the VTK export segfault but I'm currently on
travel and unable to work on this issue.  Could be totally unrelated to the
FieldViewXDB issue.  I was going to try switching over to using visitpy,
but we use this in our CFD simulation code on DSRCs where we use the
server-only VisIt build and it appears that visitpy is not included for
that configuration.  Using a full build is problematic because of the QT
dependencies.

-Patrick

**Comment by brugger1** [comment]
Hi,

I'm not familiar with the functions you were calling above, but using the commands I found that test exporting in the VisIt regression suite I was able to come up with the following code that successfully exports a binary VTK file.

Eric

OpenDatabase("/usr/gapps/visit/data/rect2d.silo")
AddPlot("Pseudocolor", "d")
DrawPlots()
e = ExportDBAttributes()
e.db_type = "VTK"
e.filename = "binary_VTK"
opts = GetExportOptions("VTK")
opts['FileFormat'] = 1
ExportDatabase(e, opts)
quit()

**Comment by markcmiller86-visit** [comment]
Thank you for the follow up.  I had seen those as well in the export_db.py
test, but I believe those are using the 'visit' package (which I think is
visitpy in src) that is not included in server-only builds.  The functions
we use are in libsim imported as 'simV2' and are still available in VisIt
3.2 though I'm not sure how well supported they are.  They don't appear to
have similar tests anywhere in the source tree.

Switching to a more full-featured build and swapping to the 'visit' package
is a potential long-term solution, but I cannot make that happen before our
next release so I need to either find a way to accomplish this with the
simV2 package or I need to remove this capability from our release.  I
tried both of the following calls but both ended up segfaulting during the
export call.

VisIt_OptionList_setValueI(opts, 'FileFormat', 3)
VisIt_OptionList_setValueS(opts, 'FileFormat', 'XML Binary')

This is from memory so I apologize if there are any typos.

-Patrick

**Comment by brugger1** [comment]
Thanks for the clarification. I was unaware those functions existed. I will do some investigation.

**Comment by markcmiller86-visit** [comment]
Thank you very much for taking a look.  If there are alternatives in simV2
we could/should be using, please let me know.

-Patrick

**Comment by biagas** [comment]
Thank you for the report on the crash with VisItExportDatabaseWithOptions from LibSim. I have entered a ticket in our bug tracker and will be looking into fixing the problem.
