### ISSUE TITLE
VisIt in batch mode on HPC

### ISSUE THREAD

**Issue by brugger1** [visit-dav/live-customer-response#228]
Hi,

I am trying to set up VisIt to run batch jobs on our HPC cluster. I am starting it with the CLI and feeding it a session file. Within the session file, I am starting and stopping a compute engine using SRUN to process across multiple nodes.

I keep getting the following error:

The engine could not connect to the viewer due to a networking problem.  The engine is exiting

Is there something I should be doing differently. 

Thanks,

Erin

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by brugger1** [comment]
Hi Erin,

Launching a parallel engine is not done through a session file, but rather by setting up a host profile for your system that tells VisIt how to start a parallel job on your system.

I don't know how far you've gotten yet with VisIt, but the first thing I would try out is just starting VisIt and making sure you can run a serial compute engine and generate an image. Then I would move on to parallel.

You can actually specify a lot of the parallel options on the command line. Based on the limited information you have specified, you could try:

visit -np 4 -l srun

There are additional flags for setting things such a the queue or bank to charge, but without additional information, I don't know if those are needed or not.

Here is the section of the manual on setting up host profiles.

https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/ClientServer/Host_Profiles.html

Here is some information about starting a compute engine through the command line interface.

https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/cli_manual/quickrecipes.html#opening-a-compute-engine

Eric

**Comment by markcmiller86-visit** [comment]
Hi Eric,

The response was helpful – so what I am specifically doing is starting visit using the following command:

visit -cli -nowin -verbose  -s visit_driver.py

Then inside my visit_driver script I set up the compute engine:

OpenComputeEngine("localhost",("-nn",str(nodes),"-np",str(totalCores),"-l","srun","-machinefile",machineFile))

Do I need a nowin in the OpenComputeEngine line (is a batch mode even possible)?

We have some HPC resources that we want to render images on which are air-gapped form the loggin node.

Thanks,

Erin

**Comment by markcmiller86-visit** [comment]
Hi Erin,

You do not need “-nowin” for starting the compute engine. The compute engine never has any windows. Yes, you can run VisIt in a totally batch mode just saving images in the file system. Once you have the engine started you would create and draw plots and then save the images.

Eric

From: ERIN BOLAND via visit-users <visit-users@elist.ornl.gov>
Sent: Thursday, February 25, 2021 12:50 PM
To: visit-dav/live-customer-response <reply@reply.github.com>; VisIt software users community <visit-users@elist.ornl.gov>
Cc: ERIN BOLAND <erin.k.boland@raytheon.com>
Subject: [visit-users] [EXTERNAL] RE: [Bulk] Re: [visit-dav/live-customer-response] VisIt in batch mode on HPC (#228)

Hi Eric,

The response was helpful – so what I am specifically doing is starting visit using the following command:

visit -cli -nowin -verbose  -s visit_driver.py

Then inside my visit_driver script I set up the compute engine:

OpenComputeEngine("localhost",("-nn",str(nodes),"-np",str(totalCores),"-l","srun","-machinefile",machineFile))

Do I need a nowin in the OpenComputeEngine line (is a batch mode even possible)?

We have some HPC resources that we want to render images on which are air-gapped form the loggin node.

Thanks,

Erin
