### ISSUE TITLE
Access control points of continuous color table within CLI

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#23]
I’ve got a quick VisIt question (that may or may not have a quick answer).  Is there a way to access the control points of a continuous color table within VisIt’s CLI?  In other words, given an arbitrary color table, I would like to be able to get (or construct) a list of the (r,g,b,alpha) tuples that are used as control points.

**Comment by markcmiller86** [comment]
I am pretty sure there is even from CLI. I don't have a good example handy though.  I grep'd tests and see that maybe color control points are manipulated in volumePlot.py test.

Alternatively, manipulate an ascii-xml color table file and then load that. See [this ref](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/MakingItPretty/Color_tables.html#editing-color-control-point-positions-numerically)

**Comment by biagas** [comment]
Here's a quick example:
http://visitusers.org/index.php?title=Creating_a_color_table

**Comment by biagas** [comment]
sorry, misread the question.
You can call 'GetColorTable("colortablename")' eg:
```
 >>> ccp = GetColorTable("hot")
>>> ccp
GetControlPoints(0).colors = (0, 0, 255, 255)
GetControlPoints(0).position = 0
GetControlPoints(1).colors = (0, 255, 255, 255)
GetControlPoints(1).position = 0.25
GetControlPoints(2).colors = (0, 255, 0, 255)
GetControlPoints(2).position = 0.5
GetControlPoints(3).colors = (255, 255, 0, 255)
GetControlPoints(3).position = 0.75
GetControlPoints(4).colors = (255, 0, 0, 255)
GetControlPoints(4).position = 1
smoothing = Linear  # None, Linear, CubicSpline
equalSpacingFlag = 0
discreteFlag = 0
categoryName = "Standard"
>>>
```

**Comment by rusu24edward** [comment]
It seems that you can also modify the control points of a color table for a specific plot:

```
OpenDatabase("/.../noise.silo")

AddPlot("Volume", "hardyglobal")

# Modify colors. The default color table has 5 control points. Delete
# all but 2 of them and then change their colors.
v = VolumeAttributes()
v.colorControlPoints.RemoveControlPoints(4)
v.colorControlPoints.RemoveControlPoints(3)
v.colorControlPoints.RemoveControlPoints(2)
v.colorControlPoints.GetControlPoints(0).colors = (255,0,0,255)
v.colorControlPoints.GetControlPoints(0).position = 0.
v.colorControlPoints.GetControlPoints(1).colors = (0,0,255,255)
v.colorControlPoints.GetControlPoints(1).position = 1.
SetPlotOptions(v)
DrawPlots()
```
