### ISSUE TITLE
Specifying --alt-python-dir to build_visit

### ISSUE THREAD

**Issue by biagas** [visit-dav/live-customer-response#234]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hello,
What shall I specify for --alt-python-dir in build_visit3_1_4? I've tried the directory that contains bin, lib, include subdirectories and bin subdirectory. None of them worked. Thank you.

Regards,
Weiguang

**Comment by biagas** [comment]
Which version of python were you attempting to use with build_visit3_1_4?  We don't support python3 for that version.
The path to pass should be the parent of python's 'bin', python-config should be present in the bin dir.
Our next version of VisIt, 3.2, due out in another week or two will support python3.

**Comment by markcmiller86-visit** [comment]
Hi Kathleen,

If one doesn't give any python-related options for "build_visit3_1_4", it
will download/build both 2.7.14 and 3.7.7. Why is that?

Look forward to version 3.2.

Regards,
Weiguang

**Comment by markcmiller86-visit** [comment]
Thanks for the prompt reply.

My own build of python doesn't contain a file "python-config". So I can't
use --alt-python-dir, can I?

Weiguang

**Comment by biagas** [comment]
You *might* bet able to get around the need for python-config by making modifications to the build_visit3_1_4 script, adding full-paths to some of the things determined programatically via python-config.  I cannot guarantee this would work, however.

First thing would be to modify  bv_python_alt_python_dir to look like this:
```
function bv_python_alt_python_dir
{
    echo "Using alternate python directory"

    bv_python_enable
    USE_SYSTEM_PYTHON="yes"
    PYTHON_ALT_DIR="$1"
    PYTHON_COMMAND="$PYTHON_ALT_DIR/bin/python"
    PYTHON_FILE=""
    python_set_vars_helper #set vars..
}
```
Then modify python_set_vars_helper to look like this:
```
function python_set_vars_helper
{
    VISIT_PYTHON_DIR=$PYTHON_ALT_DIR
    PYTHON_BUILD_DIR=$PYTHON_ALT_DIR
    PYTHON_VER=`"$PYTHON_COMMAND" --version 2>&1`
    PYTHON_VERSION=${PYTHON_VER#"Python "}
    PYTHON_COMPATIBILITY_VERSION=${PYTHON_VERSION%.*}
    ########################
    PYTHON_INCLUDE_DIR=$PYTHON_ALT_DIR/include/python$PYTHON_COMPATIBILITY_VERSION
    PYTHON_LIBRARY=python$PYTHON_COMPATIBILITY_VERSION
     if [[ "$DO_STATIC_BUILD" == "yes" ]]; then
        PYTHON_LIBRARY="lib${PYTHON_LIBRARY}.a"
    else
          if [[ "$OPSYS" == "Darwin" ]]; then
              PYTHON_LIBRARY="lib${PYTHON_LIBRARY}.dylib"
          else
              PYTHON_LIBRARY="lib${PYTHON_LIBRARY}.so"
          fi
    fi
    #
    # use python's distutils info to get the proper library directory.
    #
    PYTHON_LIBRARY_DIR=`"$PYTHON_COMMAND" -c "import sys;from distutils.sysconfig import get_config_var; sys.stdout.write(get_config_var('LIBDIR'))"`
    if [ ! -e "${PYTHON_LIBRARY_DIR}/${PYTHON_LIBRARY}" ]
    then
        # some systems eg fedora use lib64...
        PYTHON_LIBRARY_DIR="${VISIT_PYTHON_DIR}/lib64"
        if [ ! -e "${PYTHON_LIBRARY_DIR}/${PYTHON_LIBRARY}" ]
        then
            # some systems eg debian use x86_64-linux-gnu...
            PYTHON_LIBRARY_DIR="${VISIT_PYTHON_DIR}/lib/x86_64-linux-gnu"
            if [ ! -e "${PYTHON_LIBRARY_DIR}/${PYTHON_LIBRARY}" ]
            then
                error "python library was not found, cannot configure python"
            fi
        fi
    fi
    PYTHON_LIBRARY="${PYTHON_LIBRARY_DIR}/${PYTHON_LIBRARY}"
    echo $PYTHON_BUILD_DIR $PYTHON_VERSION $VISIT_PYTHON_DIR

}
```

**Comment by markcmiller86-visit** [comment]
Thank you very much for the help.

Weiguang

**Comment by markcmiller86-visit** [comment]
Hi Kathleen,

Another problem occurred --- It tried to make /bin/moc instead of using the
moc under path specified with  --alt-qt-dir.
[ 27%] Built target viewerproxy
make[2]: *** No rule to make target '/bin/moc', needed by
'winutil/moc_QvisVariablePopupMenu.cxx'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:4466:
winutil/CMakeFiles/winutil.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

The command I issued is
./build_visit3_1_4 --skip-opengl-context-check --parallel --alt-python-dir
/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14
--llvm --mesagl --alt-qt-dir /cvmfs/
soft.computecanada.ca/easybuild/software/2017/Core/qt/5.10.1

Weiguang

**Comment by markcmiller86-visit** [comment]
Here I attach the build log to this email as recommended in the output
message of the build script.

Weiguang

**Comment by biagas** [comment]
Thank you for the log file.
In the host .cmake file generated by build_visit: build-node.computecanada.ca.cmake , what QT entries are present?

It looks like our Find module for Qt is expecting VISIT_QT_DIR to be set, and to point to an installation of Qt (eg with bin, include, lib underneath).

You may need to add an entry (or modify the entry) VISIT_QT_DIR to point to your Qt location.

**Comment by markcmiller86-visit** [comment]
The QT entries in build-node.computecanada.ca.cmake are
##
## Qt
##
SETUP_APP_VERSION(QT 5.10.1)
VISIT_OPTION_DEFAULT(QT_QTUITOOLS_INCLUDE_DIR /cvmfs/
soft.computecanada.ca/easybuild/software/2017/Core/qt/5.10.1/include/QtUiTools
)
VISIT_OPTION_DEFAULT(VISIT_QT_BIN /cvmfs/
soft.computecanada.ca/easybuild/software/2017/Core/qt/5.10.1/bin)
SET(VISIT_QT_SKIP_INSTALL ON)

Do you imply that option "--alt-qt-dir" would do the trick as expected?

Thank you for the suggestion which I will try later today. However, I'm
looking for an automatic build recipe without any hacks.

Regards,
Weiguang

**Comment by biagas** [comment]
Sorry, but no,  --alt-qt-dir doesn't seem to be working correctly out-of-the box.
See the [bug ticket](https://github.com/visit-dav/visit/issues/5547) I just entered.
I tried a simple test of running build_visit3_1_4 and came across some issues. Slightly different than yours, but I believe what I discovered highlights some fundamental flaws in our handling of --alt-qt-dir.
I am sorry for the inconvenience.  Is there any reason you can't have build_visit build Qt for you?

**Comment by markcmiller86-visit** [comment]
I'm glad that I can follow up with you and get helpful feedback.

I've tried building Qt and it failed. But I forget what's the error
message. I will let build_visit build Qt and get back to you with the error
message.

Thank you very much.

Weiguang

**Comment by markcmiller86-visit** [comment]
Just want to report two new problems:

   1. Compiling Qt 5.10 failed with gcc version 8.4 or higher. I've tested
   gcc 7.3 and it works.
   2.

**Comment by markcmiller86-visit** [comment]
Just want to report two new problems:

   1. Compiling Qt 5.10 failed with gcc version 8.4 or higher. I've tested
   gcc 7.3 and it works. The error message is ....... Creating qmake...
   /home/guanw/visit-stdenv2020-final/qt-everywhere-src-5.10.1/qtbase/src/corelib/io/qfilesystemengine_unix.cpp:101:12:
   e
   rror: ‘int renameat2(int, const char*, int, const char*, unsigned int)’
   was declared ‘extern’ and later ‘static’ [-fpe
   rmissive]
    static int renameat2(int oldfd, const char *oldpath, int newfd, const
   char *newpath, unsigned flags)
               ^~~~~~~~~
   In file included from /cvmfs/
   soft.computecanada.ca/easybuild/software/2020/Core/gcccore/8.4.0/include/c++/8.4.0/cstdio
   :42,
                    from /cvmfs/
   soft.computecanada.ca/easybuild/software/2020/Core/gcccore/8.4.0/include/c++/8.4.0/ext/st
   ring_conversions.h:43,
                    from /cvmfs/
   soft.computecanada.ca/easybuild/software/2020/Core/gcccore/8.4.0/include/c++/8.4.0/bits/b
   asic_string.h:6400,
                    from /cvmfs/
   soft.computecanada.ca/easybuild/software/2020/Core/gcccore/8.4.0/include/c++/8.4.0/string
   :52,
                    from
   /home/guanw/visit-stdenv2020-final/qt-everywhere-src-5.10.1/qtbase/include/QtCore/../../src/core
   lib/tools/qbytearray.h:52,
                    from
   /home/guanw/visit-stdenv2020-final/qt-everywhere-src-5.10.1/qtbase/include/QtCore/qbytearray.h:1
   ,
                    from
   /home/guanw/visit-stdenv2020-final/qt-everywhere-src-5.10.1/qtbase/include/QtCore/../../src/core
   lib/tools/qstring.h:49,
                    from
   /home/guanw/visit-stdenv2020-final/qt-everywhere-src-5.10.1/qtbase/include/QtCore/qstring.h:1,
                    from
   /home/guanw/visit-stdenv2020-final/qt-everywhere-src-5.10.1/qtbase/include/QtCore/../../src/core
   lib/io/qiodevice.h:50,
                    from
   /home/guanw/visit-stdenv2020-final/qt-everywhere-src-5.10.1/qtbase/include/QtCore/qiodevice.h:1,
                    from
   /home/guanw/visit-stdenv2020-final/qt-everywhere-src-5.10.1/qtbase/include/QtCore/../../src/core
   lib/io/qfiledevice.h:43,
                    from
   /home/guanw/visit-stdenv2020-final/qt-everywhere-src-5.10.1/qtbase/include/QtCore/qfiledevice.h:
   1,
                    from
   /home/guanw/visit-stdenv2020-final/qt-everywhere-src-5.10.1/qtbase/src/corelib/io/qfile.h:44,
                    from
   /home/guanw/visit-stdenv2020-final/qt-everywhere-src-5.10.1/qtbase/src/corelib/io/qfilesystemengine_unix.cpp:43:
   /cvmfs/soft.computecanada.ca/gentoo/2020/usr/include/stdio.h:164:12:
   note: previous declaration of ‘int renameat2(int, const char*, int, const
   char*, unsigned int)’
    extern int renameat2 (int __oldfd, const char *__old, int __newfd,

   2. FindX11 doesn't work in my case. I have to add
   /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/include
   and
   /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/lib
   in
   /home/guanw/visit-stdenv2018-final/third_party/cmake/3.9.3/linux-x86_64_gcc-7.3/share/cmake-3.9/Modules/FindX11.cmake

**Comment by biagas** [comment]
Thanks for the report.

Using gcc-7.3 did you get everything compiled that you need?

Just so you know, with VisIt 3.2, we increased the minimum gcc required to 6.0 and above, and are using newer versions of several of our third party libraries  such as python: 3.7.7 and qt: 5.14.2.  If you build with Mesa, that version changed to 17.3.9.

**Comment by markcmiller86-visit** [comment]
Yes, I've built Visit-3.1.4 successfully with gcc-7.3 with one little
problem "Building the VisIt manuals failed.  Continuing". Also, I need to
fix the "Could not find X11" problem by editing FindX11.cmake file.

Weiguang

**Comment by surak** [comment]
I noticed that the function python_set_vars_helper will never work on Python 3.x compiled from source. Not the version here, this one works - but the one present in VisIT 3.1.4. It has this: 


```
    PYTHON_LIBRARY=`"$PYTHON_CONFIG_COMMAND" --libs`
    #remove all other libraries except for python..                                                                                                                                          
    PYTHON_LIBRARY=`echo $PYTHON_LIBRARY | sed "s/.*\(python[^ ]*\).*/\1/g"`
```

but this is the output of python3-config:
```
python-config --libs | sed "s/.*\(python[^ ]*\).*/\1/g"
 -lcrypt -ldl -lm -lpthread -lutil -lm -lm 
```

**Comment by biagas** [comment]
Using python3-config from python compiled from source (using build_visit) on a rhel7 system I get:
python3-config --libs
-lpython3.7m -lcrypt -ldl  -lutil -lm 

python3-config --libs | sed "s/.*\(python[^ ]*\).*/\1/g"
python3.7m

What system are you running on where this command didn't work?
