### ISSUE TITLE
Query Function

### ISSUE THREAD

**Issue by sullan2** [visit-dav/live-customer-response#239]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
When running a lineout using the query window, does this automatically query over time if the entire database is open?
If so, is it possible to bound the timeframe that the query is run over?

Thanks,
Hardeep

**Comment by biagas** [comment]
Lineout is performed at a single time state (the time state that exists for the plot being queried).
