### ISSUE TITLE
TurnMaterialOn/Off() crashing engine

### ISSUE THREAD

**Issue by brugger1** [visit-dav/live-customer-response#240]
To whom it may concern:

In my VisIt python scripts I’ve used TurnMaterialsOn/Off() for years with a tuple argument of materials to be selectively turned on or off.  I’ve encountered problems with this functionality recently, where I can call these methods without arguments, turning on/off all materials, but if I attempt to turn on/off a single material the engine will unexpectedly quit.  I’m using v 3.1.4, but it appears to happen with older visit builds as well.  I’m not sure if there is something about certain problems that chokes visit or what.  Please advise.

Thank you,
Jay

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by brugger1** [comment]
Hi Jay,

Nothing has changed with TurnMaterialsOn/Off(). If it fails with 3.1.4 and older versions as well, I suspect that the issue is related to the data. If the data isn't too large you could send the data or you could run visit with "-debug 5" and send the "A.engine_ser.5.vlog" or "A.engine_par.000.5.vlog" file depending on whether you are running in serial or parallel.

Eric

**Comment by markcmiller86** [comment]
I just looked at `globe.silo` (test data in `/usr/gapps/visit/data` on RZ/CZ), did a **FilledBoundary** plot of `mat1` variable there and then...

```
>>> help(TurnMaterialsOff)

>>> TurnMaterialsOff()
VisIt: Warning - The Filled Boundary plot of variable "mat1" yielded no data.
1L
>>> TurnMaterialsOn()
1L
>>> TurnMaterialsOff("1")
1L
>>> TurnMaterialsOff("4")
1L
>>> TurnMaterialsOn()
1L
>>> TurnMaterialsOff(("1","4"))
1L
>>> 
>>> TurnMaterialsOff((1,4))
invalid is an invalid set name.
invalid is an invalid set name.
0L
>>> TurnMaterialsOn()
1L
>>> TurnMaterialsOn("5")
5 is an invalid set name.
0L
>>> TurnMaterialsOff("5")
5 is an invalid set name.
0L
```

All of these worked fine (in that the engine didn't crash) so I think @brugger1 is on the right track here...its likely the input data file.

**Comment by brugger1** [comment]
Thanks for the rapid response Eric and Mark!

I ‘give’d you both a tarball on RZ with a quick test visit script and a dump file that should reproduce the issue:

-> take jay
-> tar xvf visTest.tar
-> visit -cli -nowin -s visTest.py

If you can give me a clue as to what could be wrong with my dataset wrt turning materials on/off in visit, that would be much appreciated.

Thanks!
Jay

**Comment by brugger1** [comment]
Hi Jay,

I got your data and getting close to figuring out this issue.

Eric

**Comment by brugger1** [comment]
Hi Jay,

VisIt is crashing creating ghost zones, which are necessary for doing material interface reconstruction. When you plot the entire mesh, it skips doing the material interface reconstruction, but when you turn off a material, it does the material interface reconstruction, which then triggers the ghost zone creation.

Looking at the ghost zone creation, it uses the domain boundary information from your file. It looks like the domain boundary information is incomplete. For every domain there is a list of neighbors and it looks like if domain X has neighbor Y, VisIt expects domain Y to list X as a neighbor. In your file, domain Y doesn't list domain X as a neighbor. Since this used to work, is it possible that your simulation code changed its output?

Eric

**Comment by brugger1** [comment]
My assessment was close but not completely correct. For every domain X that has a neighbor Y, domain Y has domain X as a neighbor. The problem is that the neighbor information has a bad value. The domain information is coming from a Silo file and has the following structure:

/Decomposition/gmapXX contains the neighbor information for domain XX.

In that directory are the following variables:

NumNeighbors, gmap, neighbor0, neighbor1, ... , neighborXX

Where neighborXX is an array of 12 values which contains information about a neighbor. The 12 value should be zero, if it isn't then the Silo reader ignores that neighbor information. So the problem is that all the neighbor information is present, its just that some of the neighbor information has a non-zero 12th value.
Here is the relevent code in Silo.

                int n_all_neighbors = nneighbors[j];
                for (int k = 0 ; k < n_all_neighbors; k++)
                {
                    char neighborname[256];
                    sprintf(neighborname, "gmap%d/neighbor%d",j,k);
                    int neighbor_info[512];  // We only want 11, but it can
                                             // be as big as 400.
                    // clear the 12th entry
                    // for some codes, non-zero @ neighbor_info[11]
                    // indicates a periodic boundary condition that we should
                    // not include as a neighbor
                    neighbor_info[11] = 0;
                    DBReadVar(dbfile, neighborname, neighbor_info);
                    if(neighbor_info[11] == 0)
                    {
                        memcpy(&neighbors[index],neighbor_info,11*sizeof(int));
                        index += 11;
                        nactual_neighbors+=1;
                    }
                    else
                    {
                        // remove periodic boundary conditions
                        // from neighbor count
                        nneighbors[j] += -1;
                    }
                }
            }

It would be great if VisIt output an error message that made some indication of the problem rather than just crashing.

**Comment by brugger1** [comment]
Closing since the Jay has been notified of the issue with his data and I entered a ticket to have the compute engine crash when the structured domain boundary information is correct.
