### ISSUE TITLE
Can't save image with multiple databases open and graphed

### ISSUE THREAD

**Issue by burton29-LLNL** [visit-dav/live-customer-response#242]
See screenshot where I am trying to save a Visit window as a .png image.  I have multiple sub databases open and graphed as you can see, but I get an error message that the "pipeline is being used incorrectly"
 I'm attaching the screenshot here:
<img width="1562" alt="Screen Shot 2021-04-08 at 9 12 32 AM" src="https://user-images.githubusercontent.com/71102332/114061630-810cc900-984b-11eb-89f8-8820a7afcbfe.png">

**Comment by brugger1** [comment]
Hi,

Those error messages are pretty generic and don't provide a lot of insight as to what might be going wrong. Can you run again with "-debug 5" on the command line and sending the resulting "A.engine_ser.5.vlog" and "A.viewer.5.vlog" files.

Eric
