### ISSUE TITLE
Compiling 3.1.4 on HPC cluster

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#243]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hello,

Trying to compile VisIt 3.1.4 on our HPC cluster:

module load python/2.7.18 cmake/3.18.4 gcc/9.3.0 vtk/9.0.1
export PAR_COMPILER=mpicc
export PAR_INCLUDE="-I${EBROOTOPENMPI}/include"
export PAR_LIBS="-L${EBROOTOPENMPI}/lib -lmpi"
export CC=$EBROOTGCC/bin/gcc
export CXX=$EBROOTGCC/bin/g++
./build_visit3_1_4 --parallel --prefix $HOME/3.1.4 --system-cmake --system-python --mesagl --server-components-only --llvm --thirdparty-path $HOME/3rdparty --cflags "-pthread" --alt-vtk-dir $EBROOTVTK

with

$ which mpicc
/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/gcc9/openmpi/4.0.3/bin/mpicc
$ echo $EBROOTOPENMPI
/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/gcc9/openmpi/4.0.3

I receive an error in build_visit3_1_4_log while compiling IceT:

-- Could NOT find MPI_C (missing: MPI_C_WORKS)
CMake Error at /cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/cmake/3.18.4/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
 Could NOT find MPI (missing: MPI_C_FOUND)
 Reason given by package: MPI component 'CXX' was requested, but language CXX is not enabled. MPI component 'Fortran' was requested, but language Fortran is not enabled.

In the related icet-master-*/CMakeFiles/CMakeError.log I see:

make[1]: Entering directory '/tmp/razoumov/icet-master-77c708f9090236b576669b74c53e9f105eedbd7e/CMakeFiles/CMakeTmp' 
Building C object CMakeFiles/cmTC_38e51.dir/test_mpi.c.o 
/cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/gcccore/9.3.0/bin/gcc -isystem /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler\
/gcc9/openmpi/4.0.3/include -fPIC -m64 -fPIC -pthread -o CMakeFiles/cmTC_38e51.dir/test_mpi.c.o -c /cvmfs/soft.computecanada.ca/easybuild/software/2020/Co\
re/cmake/3.18.4/share/cmake-3.18/Modules/FindMPI/test_mpi.c 
Linking C executable cmTC_38e51 
/cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/cmake/3.18.4/bin/cmake -E cmake_link_script CMakeFiles/cmTC_38e51.dir/link.txt --verbose=1 
/cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/gcccore/9.3.0/bin/gcc -fPIC -m64 -fPIC -pthread -rdynamic CMakeFiles/cmTC_38e51.dir/test_mpi.c.o\
 -o cmTC_38e51 -L/tmp/razoumov/icet-master-77c708f9090236b576669b74c53e9f105eedbd7e -Wl,-rpath,/tmp/razoumov/icet-master-77c708f9090236b576669b74c53e9f10\
5eedbd7e /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/gcc9/openmpi/4.0.3/lib/libmpi.so -lfakempi 
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/x86_64-pc-linux-gnu/binutils-bin/2.33.1/ld.gold: error: cannot find -lfakempi 
collect2: error: ld returned 1 exit status

Clearly, it is looking for MPI, but I explicitly set all the necessary variables above. Is my syntax wrong somewhere?

Thank you,

--
Alex Razoumov
WestGrid Training & Visualization Coordinator, Compute Canada

**Comment by rusu24edward** [comment]
Hi Alex,

Sorry for your trouble building visit. I believe the bug you are experiencing was captured in [5318](https://github.com/visit-dav/visit/issues/5318), for which we have already [merged a fix](https://github.com/visit-dav/visit/pull/5413) for our development branch. This fix does not appear in 3.1.4 since that was released in November 2020 and the fix was applied in January 2021. However, the fix is very simple, just a couple of changes to bv_icet.sh. Can you copy [these changes](https://github.com/visit-dav/visit/pull/5413/files#diff-9809ab91080cb4909e54d55f35bba43e0a8abe73afe2d985530fe3ae4e394aa4) to your build script and let me know if it works for you?

Thanks,
Eddie

**Comment by biagas** [comment]
Hi Alex,

You should know as well that VisIt 3.1.4 is not compatible with VTK-9. You need VTK-8.1.0. We recommend using build_visit to build VTK since we apply necessary patches during the build.

Kathleen
