### ISSUE TITLE
Error installing Visit

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#245]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hello,
I am new to this software, installed it according to the website instructions, the installation took place without an error, but when I run /bin/visit, I get the following error:

Running: gui3.1.4
/home/rohan/visit/3.1.4/linux-x86_64/bin/gui: error while loading shared libraries: libicui18n.so.55: cannot open shared object file: No such file or directory

Couldn't find such a lib anywhere in the system, what might have gone wrong?
Any suggestion would be great!
Thank you in advance,

Rohan Srikanth,

**Comment by rusu24edward** [comment]
Hi Rohan,

Can you provide me the website link that contained the installation instructions?

Eddie

**Comment by markcmiller86-visit** [comment]
Dear Eddie,

https://visit-sphinx-github-user-manual.readthedocs.io/en/latest/Intro/Installing_VisIt.html
- This was the site,

Thank you for the reply,

*Rohan Srikanth*

**Comment by rusu24edward** [comment]
Hi Rohan,

When you arrived [here](https://wci.llnl.gov/simulation/computer-codes/visit/executables), exactly which platform link did you select?

Eddie

**Comment by markcmiller86-visit** [comment]
Dear Eddie,

Thank you for that, I just checked and had made a silly error in the
installation, downloaded the Ubuntu-16 executable instead of 20, it works
now,

*Rohan Srikanth*,
