### ISSUE TITLE
Issue plotting data from DDCMD.

### ISSUE THREAD

**Issue by brugger1** [visit-dav/live-customer-response#248]
I had a user report a problem displaying data from DDCMD. He provided a sample data file and Liam was able to create a correct image using VisIt 3.1.3 on Fedora33.

Here is the e-mail chain.

Hi Tomorr,

I was able to plot the particle Ids when I changed the glyph type to "Sphere". I still had an issue with the data range for the Id being 0 - 65495 and some of the particles being outside the rectangle of the data. I tried this on Windows with 3.1.2, 3.1.4 and a beta of 3.2.0. I'll file a ticket and have someone investigate.

Eric

----------------------------------------------------------------------------------------

Hi Tomorr.

Your example snapshot loaded without error and I was able to plot data (see attached).

I'm running Visit3.1.3 on my Fedora Core 33 laptop.

Cheers.

-Liam

----------------------------------------------------------------------------------------

HI Eric and Liam,

I have attached a small bxyz dataset to this email.
Also, I am using visit in LC so it is version 3.1.4.
With the same version of visit I could open simulations done before with previous version of ddcMD.

Best,

Tomorr

----------------------------------------------------------------------------------------

Hi Eric.  Query below regarding VisIt ddcMD reader.

Thanks

-Liam

----------------------------------------------------------------------------------------

Similarly, it's been years since I've attempted to look at any ddcMD data.

Which version of VisIt are you trying to use with new data?

Which version do you use to successfully view old simulation data?

I'd be willing to try to look at a representative (small if possible) bxyz dataset, but I honestly don't think I'll be able to help - the visit team is the best bet.  I'll forward your issue to them...

-Liam

----------------------------------------------------------------------------------------

I’m afraid that I can’t help at all.  It has been years since I touched any  ddcMD code.

Dave

-------------------

David Richards

Center for Applied Scientific Computing
Lawrence Livermore National Laboratory

----------------------------------------------------------------------------------------

I have attached the error message that I get from Visit when trying to open  the ddcMD  files.

Just to be clear I use:
            ddcMD FILEHEADER { files=bxyz; }

Also, I am able to open with visit simulations that I did more than three  years ago.

Best,

Tomorr

----------------------------------------------------------------------------------------

Tomorr,

I don’t know of any specific development of Visit for ddcMD files.   
That  said there has  been no significant  change in ddcMD file 
formats for a long time.   I have  included  Liam in this reply to get 
his input.   Liam any thoughts?

Jim

----------------------------------------------------------------------------------------

Hi Jim and Dave,

Do you know if Visit has been updated to keep up with the recent changes in  ddcMD?

The visit section is crashing when I tried to open recent runs with ddcMD.
 
Best,

Tomorr

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by biagas** [comment]
I don't think I'm understanding the issue. 
What are the steps to reproduce?
I successfully created Psuedocolor plot of 'Id' using 3.1.4 and 3.2.0 on Windows, and 3.1.3, 3.1.4 and 3.2.0 on pascal (running through VNC on my windows machine). I used 'point' and 'sphere' glyphs.

**Comment by brugger1** [comment]
The data range was incorrect for me. I saw 0 - 65495 and it was different in Liam's image. Also, I got some particles outside the bounding box (rotate the image to see them, they are behind most of the spheres in the default view). I assume there shouldn't be any outside the bounding box. When I did it on Windows I got a blank image with point. I had to switch to sphere to see them.

**Comment by biagas** [comment]
For any type of glyphing (non-Point), they may appear outside the bounding box.
I am not able to duplicate, I've attached snapshot from Windows (which is the same thing I get on Pascal).
![Capture](https://user-images.githubusercontent.com/17075318/115443583-4b130180-a1c8-11eb-9eb0-c4a558d3a14e.PNG)

**Comment by biagas** [comment]
Makes me wonder if there is something amiss in a config file ?

**Comment by brugger1** [comment]
Here is what I see with points and a point size of 20. Just a single point. If I rotate the image the point may disappear and another point may show up.

![ddcmd1](https://user-images.githubusercontent.com/1102718/115446147-9f6bb080-a1cb-11eb-9824-a2c417294e93.png)

Here is what I see with spheres. There are definitely spheres outside the box and the data range is wrong in both images.

![ddcmd2](https://user-images.githubusercontent.com/1102718/115446173-a72b5500-a1cb-11eb-89c2-a6303c6024e3.png)

**Comment by brugger1** [comment]
Maybe memory corruption?

**Comment by biagas** [comment]
Can you try a run with -noconfig?

**Comment by brugger1** [comment]
Same behavior.

**Comment by brugger1** [comment]
I moved the file to quartz and was able to plot it fine. I then turned on debug 5 on Windows and quartz and compared the information in the log file about the DDCMD file.

On Linux it is:

```
DDCMDHeader {
    cgridFile = false
    isLegacy = true

    headerLength = 846
    dataType = FIXRECORDBINARY
    lRec = 39
    nRecord= 19433
    nFiles = 16
    nFields = 11
    swap = 0
    hMatrix = {112.96, 0, 0, 0, 112.96, 0, 0, 0, 21.18, }
    loop = 5000
    time = 50
    fieldNames=checksum,id,pinfo,rx,ry,rz,vx,vy,vz,energy,virial}
    fieldTypes = {u4,b2,b1,f4,f4,f4,f4,f4,f4,f4,f4}
    fieldUnits = {}
    fieldSizes = {4,2,1,4,4,4,4,4,4,4,4}
    nXFile = 0
    nYFile = 0
    nZFile = 0
    speciesNames = {Ni,Ti}
    groupNames = {Ni,Ti}
    typeNames = {ATOM}
    exeVersion = NONE
}
varName=id,offset=4,size=2,type=b,units=1
varName=vx,offset=19,size=4,type=f,units=1
varName=vy,offset=23,size=4,type=f,units=1
varName=vz,offset=27,size=4,type=f,units=1
varName=energy,offset=31,size=4,type=f,units=1
varName=virial,offset=35,size=4,type=f,units=1
fileSizes=61062,44421,35373,50700,60255,42822,35373,50700,59514,42354,35373,50700,60957,42783,35217,51129,
nRecords=19433,fileNumber=0,fileOffset=846
```

On Windows it is:

```
DDCMDHeader { 
    cgridFile = false
    isLegacy = true

    headerLength = 846
    dataType = FIXRECORDBINARY
    lRec = 39
    nRecord= 19433
    nFiles = 16
    nFields = 11
    swap = 0
    hMatrix = {112.96, 0, 0, 0, 112.96, 0, 0, 0, 21.18, }
    loop = 5000
    time = 50
    fieldNames=checksum,id,pinfo,rx,ry,rz,vx,vy,vz,energy,virial}
    fieldTypes = {u4,b2,b1,f4,f4,f4,f4,f4,f4,f4,f4}
    fieldUnits = {}
    fieldSizes = {4,2,1,4,4,4,4,4,4,4,4}
    nXFile = 0
    nYFile = 0
    nZFile = 0
    speciesNames = {Ni,Ti}
    groupNames = {Ni,Ti}
    typeNames = {ATOM}
    exeVersion = NONE
}
varName=id,offset=4,size=2,type=b,units=1
varName=vx,offset=19,size=4,type=f,units=1
varName=vy,offset=23,size=4,type=f,units=1
varName=vz,offset=27,size=4,type=f,units=1
varName=energy,offset=31,size=4,type=f,units=1
varName=virial,offset=35,size=4,type=f,units=1
fileSizes=61540,44421,35373,50700,60255,42822,35373,50700,59514,42354,35373,50700,60957,42783,35217,51129,
nRecords=19445,fileNumber=0,fileOffset=846
```

If you look closely you will notice that the file size on Windows of the first file is larger than the first file on quartz (61540 bytes vs 61062 bytes) causing Windows to think there are more points.
I checked the file size in properties on Windows and with ls on quartz and they are in fact different in size. Looking at the file in WinZip on Windows it is 61062 also, but when it is unpacked into a directory the size changes. When I copy the quartz file to Windows everything works, so the problem I am seeing on Windows is with my version of WinZip.

**Comment by brugger1** [comment]
I contacted the user and the only issue is the one I described above, which isn't a VisIt issue. He is fine visualizing his data on LC. I'm closing this ticket.
