### ISSUE TITLE
build_visit --server-components-only does not build CLI

### ISSUE THREAD

**Issue by biagas** [visit-dav/live-customer-response#249]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hello,

I finally managed to compile VisIt 3.1.4 on our HPC cluster with

$ ./build_visit3_1_4 --parallel --prefix /path/to/installation --cmake --mesagl \
     --llvm --thirdparty-path /path/to/3rdparty --vtk --python \
     --netcdf --hdf5 --silo --server-components-only

The client-server mode works well. Contrary to my naive expectations, this did not build the CLI tools:

$ /path/to/installation/visit -nowin -cli -s test.py
Version 3.1.4 of cli does not exist for the architecture linux-x86_64.

I would like to avoid having to build the full Qt version with the GUI, as we need only (1) the server for client-server workflows and (2) the engine to run off-screen rendering scripts from the command line without opening any windows. Is there a way to do that without compiling the full GUI?

Thank you,

--
Alex Razoumov
WestGrid Training & Visualization Coordinator, Compute Canada

**Comment by biagas** [comment]
Hello Alex,

The --server-components-only option is designed for building only those components necessary for processing data on a remote machine, while the gui and cli run on a local machine and connect to the remote server. 

I can enter a ticket to provide the sort of build you need, I'm not sure there are any other options at this point.

Kathleen

**Comment by biagas** [comment]
I created a [ticket](https://github.com/visit-dav/visit/issues/5648).

**Comment by markcmiller86-visit** [comment]
Thank you very much, Kathleen! I’ll be monitoring the ticket.

Best regards,

--
Alex Razoumov
WestGrid Training & Visualization Coordinator, Compute Canada
