### ISSUE TITLE
PointPick on multiple points

### ISSUE THREAD

**Issue by biagas** [visit-dav/live-customer-response#251]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
I’m looking for an automated way to sample a set of points on a plot using the python interface. One approach is to call PointPick() on each point, but I’m finding that this is extremely slow (I want to sample many thousands of points). An alternative is to use a sequence of Lineout() calls and then save those plots to ultra files and read them back. That is faster, but is an unpleasant hack. There does not seem to be a way to pass a list of points to VisIt to perform a vectorized query on them.

Any thoughts?

Thanks,

Joe.

**Comment by markcmiller86** [comment]
What about doing a [CMFE expression](https://visit-sphinx-github-user-manual.readthedocs.io/en/latest/Quantitative/Expressions.html#comparison-expressions) onto a point mesh? Create a database with a point mesh in it with all the points in the mesh being your sample points. The do a CMFE of the plot's variable *from* its original database *onto* that point mesh. Once there, you can export to some ascii file formats or whatever. I wonder if that would work? I think it should.

**Comment by joepmorris** [comment]
Excellent suggestion! I tried it out and it appears to work well. One gotcha I notice is that the interpolation appears to be onto the target point mesh cell centers. The easy fix is to shift the points so the interpolation is onto the points you originally wanted. The performance is pretty good (orders of magnitude faster than point-based queries!). Thanks for your help,
Joe.

**Comment by markcmiller86** [comment]
Hmm....if you have a CMFE *target* mesh of *just points*, the *cell centers* should be one in the same with the *points*. However, if the variable on the *donor* mesh is a cell-centered variable, that could potentially cause issues. I would ensure the donor variable is node-centered first by creating an expression using the [`recenter`](https://visit-sphinx-github-user-manual.readthedocs.io/en/latest/Quantitative/Expressions.html#recenter-expression-function) expression function that recenters the donor variable onto the nodes of the donor mesh. Then CMFE that expression onto the nodes of the point mesh.
