### ISSUE TITLE
Status github visit development

### ISSUE THREAD

**Issue by CHMBroeders** [visit-dav/live-customer-response#257]
Obviously visit development is in a moving process to github support.
I encountered several empty links in the github repo.
My incentive is to repeat a vistt source installation after system crash on OpenSUSE Tumbleweed.
My main actual problem is the documentation support on github.
After several trials my Tumbleweed system seems to contain all required software.
Installation is stopped at end of qt5 processing.
Search for further installation support on github points to file docs/GettingStarted/GettingStarted.book
After half day search in internet I can not read the .book file on my system.
My running trial is a Framemaker MS-Windows solution to read the .book file.
My specific recommendation for this issue is to replace old non-Linux documentation parts by modern options.

**Comment by markcmiller86** [comment]
Have you tried our RTD manuals, https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/building_visit/index.html

**Comment by CHMBroeders** [comment]
These document areas also contain not-resolved links.Is it possible to install visit3.2 from a github repo?Thanks,CBGesendet mit der WEB.DE iPad AppOn 03.05.21 at 01:46, Mark C. Miller wrote:
                
            
            
                
                    From: "Mark C. Miller" ***@***.***>Date: 3. May 2021To: "visit-dav/live-customer-response" ***@***.***>Cc: "C.H.M. Broeders" ***@***.***>,"Author" ***@***.***>Subject: Re: [visit-dav/live-customer-response] Status github visit development (#257)
                
                
Have you tried our RTD manuals, https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/building_visit/index.html

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/visit-dav/live-customer-response/issues/257#issuecomment-830927783",
"url": "https://github.com/visit-dav/live-customer-response/issues/257#issuecomment-830927783",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by brugger1** [comment]
Hi,

It looks like our main GitHub page has some links to some outdated material. We are trying to standardize our documentation on read-the-docs, which can be reached via the "GUI and CLI Users Manuals" link under documentation. The link to the "Users Wiki" points to older, but still valuable content, some of which may be outdated.

The "GitHub Development Info" unfortunately also contains outdated information from the "Users Wiki" from when we were transitioning to GitHub. The transition has been completed a while ago and current information can be found in the read-the-docs documentation.

I submitted the following issue to update the documentation.

https://github.com/visit-dav/visit/issues/5672

Eric

**Comment by brugger1** [comment]
I added the section https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/dev_manual/GitHub.html to the VisIt Users manual. I also changed the link on the main GitHub VisIt page to point to it instead of the outdated page on visitusers.org.
