### ISSUE TITLE
cannot build parallel VisIt 3.2 on cluster with GUI enabled

### ISSUE THREAD

**Issue by biagas** [visit-dav/live-customer-response#261]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

Hi,

I am trying to build a parallel build of VisIt 3.2 with the GUI enabled. Without the GUI (--server-components-only), it builds correctly. However, without this flag, the build of VisIt itself fails with a compile error:

/g/data/jh2/bw0729/visit_build/visit/src/vtkqt/vtkQtRenderWindow.C:9:10: fatal error: QVTKOpenGLWidget.h: No such file or directory

I use the build_visit script:

$ env MPI_HOME=/home/120/bw0729/openmpi4.1.1 PAR_COMPILER=mpicxx PAR_COMPILER_CXX=mpicxx PAR_INCLUDE=-I/home/120/bw0729/openmpi4.1.1/include PAR_LIBS="-lmpi -lmpi_cxx" THIRD_PARTY_PATH=/g/data/jh2/bw0729/visit_build/third_party ./build_visit.sh --parallel --mesagl --icet --llvm --szip --boxlib --hdf5  --makeflags -j4 --alt-hdf5-dir /apps/hdf5/1.10.5

VisIt build failed. Giving up 
Unable to build or install VisIt. Bailing out.
Error in build process. See build_visit.sh_log for more information. If the error is unclear, please include build_visit.sh_log in a message to the visit-users@ornl.gov list. You will probably need to compress the build_visit.sh_log using a program like gzip so it will fit within the size limits for email attachments.
Log file full path:  /g/data/jh2/bw0729/visit_build/visit/build/build_visit.sh_log

I have attached my build_visit.sh_log

Thanks,
Ben

[build_visit_log.gz](https://github.com/visit-dav/live-customer-response/files/6442389/build_visit_log.gz)

**Comment by biagas** [comment]
Hi Ben,

Thank you for providing the log file.  It looks like all the third party libraries were previously built. Was this when you ran with --server-components-only?

At any rate this error in the log file:

```
-- Checking for VTK in /g/data/jh2/bw0729/visit_build/third_party/vtk/8.1.0/linux-x86_64_gcc-8.3/lib/cmake/vtk-8.1
ERRORVisIt requires vtkGUISupportQtOpenGL
```
indicates that VTK was not built with Qt support (which would be the case for a server-only build).  You may need to blow away the VTK dirs and re-run build_visit so that VTK can be built properly with Qt.

**Comment by BenWibking** [comment]
That fixed it! Thanks.
