### ISSUE TITLE
shouldn't python3 be chosen as a default when specifying --system-python

### ISSUE THREAD

**Issue by jfavre** [visit-dav/live-customer-response#262]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
I have both python2 and pythoon3 in /usr/bin.
When building I see python2 being picked up by the build script. Can we not force python3? :

./src/tools/dev/scripts/build_visit --console --no-visit --parallel --llvm --mesagl --vtk --makeflags -j32 --system-python --alt-python-dir /usr --openssl --qwt --qt --silo --hdf5  --icet --ospray --ispc --embree --tbb  --system-cmake
Processing bsd license.
Using system python
/usr 2.7.17 /usr
Using alternate python directory
/usr 2.7.17 /usr

**Comment by biagas** [comment]
Yes, you are correct. Thanks for pointing this out. I will create a ticket to address the problem.

Try modifying this function in build_visit so that it looks for python3-config, as below:
```
function bv_python_system_python
{
    echo "Using system python"
    TEST=`which python3-config`
    [ $? != 0 ] && error "System python3-config not found, cannot configure python"

    bv_python_enable
    USE_SYSTEM_PYTHON="yes"
    PYTHON_COMMAND="python3"
    PYTHON_CONFIG_COMMAND="python3-config"
    PYTHON_FILE=""
    python_set_vars_helper #set vars..
}
```

**Comment by jfavre** [comment]
we're making progress but step2 still needs tuning. Here is the output:

Using system python
/usr 3.6.10 /usr
Using alternate python directory
/usr 2.7.17 /usr

**Comment by biagas** [comment]
This function has python2 logic before python3, you can remove the python2 logic.

function bv_python_alt_python_dir

**Comment by jfavre** [comment]
that works fine. Thanks.
