### ISSUE TITLE
visit 3.2 over x11 hangs at splash screen while "Calculating wir"

### ISSUE THREAD

**Issue by BenWibking** [visit-dav/live-customer-response#265]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hi,

I am trying to use VisIt 3.2 on a remote cluster over X11. I connect to the cluster using `ssh -Y`, I start visit using the wrapper script `visit` inside bin/, and I get a splash screen.  Then it appears to hang while displaying the splash screen with the status message "Calculating wir".  I've attached a screenshot below.

![Visit_Capture](https://user-images.githubusercontent.com/1781919/117527783-e6520680-b011-11eb-94d7-52e6ca091cf1.PNG)

The terminal just displays:
```

$ ./visit_install/bin/visit
Running: gui3.2.0

```

Any advice on how to get it working would be appreciated.

Thanks,
Ben

**Comment by brugger1** [comment]
Hi Ben,

Did you build VisIt from source code or did you use one of the pre-built versions of VisIt. What OS are you running VisIt on and if you used one of the pre-built versions, which version of those are you using.

Another thing that would be helpful would be to run:

```
./visit_install/bin/visit -debug 5
```

and then send the "A.*.5.vlog" files.

**Comment by BenWibking** [comment]
Hi,

I built it from source with the flags: ` PAR_COMPILER=mpicxx PAR_COMPILER_CXX=mpicxx PAR_LIBS="-lmpi -lmpi_cxx"  ./build_visit.sh --parallel --mesagl --icet --llvm --szip --boxlib --hdf5  --makeflags -j4 --alt-hdf5-dir /apps/hdf5/1.10.5`

This cluster is running CentOS Linux release 8.3.2011.

Strangely, from my Linux machine it starts and runs just fine. But connecting from Windows 10 using WSL, it hangs as shown above.

I've attached the *.vlog files:
[vlogs.tar.gz](https://github.com/visit-dav/live-customer-response/files/6481638/vlogs.tar.gz)

**Comment by brugger1** [comment]
Hi,

We have a know issue with VisIt hangs on startup on WSL (https://github.com/visit-dav/visit/issues/5485). The log file doesn't match exactly, but it may be a similar issue. I'm not sure when I'll have time to look into it further. It will realistically be at least a month.

Eric

**Comment by BenWibking** [comment]
Ok, thanks for taking a look. However, I don't have this problem when starting VisIt locally on WSL, so I'm not sure if it's the same issue. But I should add that I'm using [WSLg](https://github.com/microsoft/wslg) rather than running an X server on the Windows side, unlike the user who reported visit-dav/visit#5485

**Comment by brugger1** [comment]
Ok, I think I misunderstood your situation. Did you ssh from WSL to your remote system and then launch VisIt on that system with X forwarding back to WSL?

**Comment by BenWibking** [comment]
Yes, that's right.

**Comment by brugger1** [comment]
@cyrush has access to a system with WSLg and will try it out next week.

**Comment by brugger1** [comment]
You might try adding -nowindowmetrics to the command line.

**Comment by BenWibking** [comment]
That fixed it! Thanks.
