### ISSUE TITLE
linking errors when compiling VisIt on Cray systems

### ISSUE THREAD

**Issue by jfavre** [visit-dav/live-customer-response#266]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

I have no idea how to fix these errors; There are a few. I have configured VisIt with -DMPI_C_COMPILER=cc -DMPI_CXX_COMPILER=CC -DCMAKE_CXX_COMPILER=CC -DCMAKE_BUILD_TYPE=RelWithDebInfo -DVISIT_ENABLE_MANUALS=FALSE -DVISIT_DATA_MANUAL_EXAMPLES:BOOL=ON  -DVISIT_INSTALL_THIRD_PARTY:BOOL=ON  -DVISIT_SLIVR:BOOL=OFF -DVISIT_ENABLE_XDB:BOOL=OFF

after having built the third party stuff with my system's python (3.6.10)
---
cd /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/build/engine/main && /apps/daint/UES/jenkins/7.0.UP02-20.11/mc/easybuild/software/CMake/3.14.5/bin/cmake -E cmake_link_script CMakeFiles/engine_par_exe.dir/link.txt --verbose=1
/opt/cray/pe/craype/2.7.3/bin/CC  -O2 -fno-math-errno -O2 -fno-math-errno -m64 -fPIC -fvisibility=hidden -O2 -g -DNDEBUG  -L/opt/cray/pe/libsci/20.09.1/GNU/8.1/x86_64/lib  CMakeFiles/engine_par_exe.dir/main.C.o  -o ../../exe/engine_par  -L/run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/icet/77c708f9090236b576669b74c53e9f105eedbd7e/linux-x86_64_gcc-9.3/lib -Wl,-rpath,/run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/icet/77c708f9090236b576669b74c53e9f105eedbd7e/linux-x86_64_gcc-9.3/lib:/run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/build/lib:/run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/zlib/1.2.11/linux-x86_64_gcc-9.3/lib:/run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib:/run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/ospray/1.6.1/linux-x86_64_gcc-9.3/lib64:/run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/mesagl/17.3.9/linux-x86_64_gcc-9.3/lib:/run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/tbb/tbb2018_20171205oss/linux-x86_64_gcc-9.3/lib/intel64/gcc4.7:/run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/embree/3.2.0/linux-x86_64_gcc-9.3/lib:/run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/llvm/6.0.1/linux-x86_64_gcc-9.3/lib: ../../lib/libengine_par.so /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/zlib/1.2.11/linux-x86_64_gcc-9.3/lib/libz.so ../../lib/libenginerpc.so ../../lib/libavtwriter_par.so /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkIOPLY-8.1.so.1 ../../lib/libavtquery_par.so ../../lib/libavtshapelets.so ../../lib/libavtexpressions_par.so ../../lib/libavtdbin_par.so ../../lib/libavtpythonfilters_par.so /usr/lib64/libpython2.7.so ../../lib/libavtviswindow_par.so ../../lib/libavtplotter_par.so ../../lib/libavtfilters_par.so ../../lib/libavtview.so /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkRenderingFreeType-8.1.so.1 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkfreetype-8.1.so.1 ../../lib/libavtdatabase_par.so ../../lib/libavtmir_par.so ../../lib/libvisit_verdict.so ../../lib/libtess2.so /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/ospray/1.6.1/linux-x86_64_gcc-9.3/lib64/libospray_module_visit.so /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/ospray/1.6.1/linux-x86_64_gcc-9.3/lib64/libospray_module_visit_common.so /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/icet/77c708f9090236b576669b74c53e9f105eedbd7e/linux-x86_64_gcc-9.3/lib/libIceTCore.a /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/icet/77c708f9090236b576669b74c53e9f105eedbd7e/linux-x86_64_gcc-9.3/lib/libIceTGL.a /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/icet/77c708f9090236b576669b74c53e9f105eedbd7e/linux-x86_64_gcc-9.3/lib/libIceTMPI.a /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkFiltersHybrid-8.1.so.1 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/mesagl/17.3.9/linux-x86_64_gcc-9.3/lib/libGL.so.1 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkInteractionStyle-8.1.so.1 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkRenderingOSPRay-8.1.so.1 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/tbb/tbb2018_20171205oss/linux-x86_64_gcc-9.3/lib/intel64/gcc4.7/libtbb.so.2 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/tbb/tbb2018_20171205oss/linux-x86_64_gcc-9.3/lib/intel64/gcc4.7/libtbbmalloc.so.2 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/embree/3.2.0/linux-x86_64_gcc-9.3/lib/libembree3.so.3 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/ospray/1.6.1/linux-x86_64_gcc-9.3/lib64/libospray.so /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/ospray/1.6.1/linux-x86_64_gcc-9.3/lib64/libospray_module_ispc.so /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/ospray/1.6.1/linux-x86_64_gcc-9.3/lib64/libospray_common.so /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkRenderingSceneGraph-8.1.so.1 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkRenderingOpenGL2-8.1.so.1 /usr/lib64/libSM.so /usr/lib64/libICE.so /usr/lib64/libX11.so /usr/lib64/libXext.so /usr/lib64/libXt.so /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkRenderingVolume-8.1.so.1 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkRenderingCore-8.1.so.1 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkFiltersModeling-8.1.so.1 ../../lib/libavtpipeline_par.so ../../lib/libavtdbatts.so ../../lib/libvisit_vtk.so /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkFiltersExtraction-8.1.so.1 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkFiltersFlowPaths-8.1.so.1 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkFiltersSources-8.1.so.1 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkFiltersGeneral-8.1.so.1 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkImagingHybrid-8.1.so.1 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkImagingCore-8.1.so.1 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkIOImage-8.1.so.1 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkpng-8.1.so.1 -lm /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtktiff-8.1.so.1 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkjpeg-8.1.so.1 -lm ../../lib/libavtmath.so ../../lib/liblightweight_visit_vtk.so ../../lib/libvisitcommon.so /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/zlib/1.2.11/linux-x86_64_gcc-9.3/lib/libz.so /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkIOLegacy-8.1.so.1 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkIOCore-8.1.so.1 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkFiltersGeometry-8.1.so.1 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkFiltersCore-8.1.so.1 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkCommonExecutionModel-8.1.so.1 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkCommonDataModel-8.1.so.1 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkCommonTransforms-8.1.so.1 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkCommonMisc-8.1.so.1 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkCommonMath-8.1.so.1 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib/libvtkCommonCore-8.1.so.1 -ldl ../../lib/libcognomen.so -Wl,-Bstatic -lIceTCore -lIceTGL -lIceTMPI -Wl,-Bdynamic ../../lib/libvisit_vtk_offscreen.so /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/mesagl/17.3.9/linux-x86_64_gcc-9.3/lib/libOSMesa.so.8 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/mesagl/17.3.9/linux-x86_64_gcc-9.3/lib/libglapi.so.0 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/mesagl/17.3.9/linux-x86_64_gcc-9.3/lib/libGLU.so.1 /run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/llvm/6.0.1/linux-x86_64_gcc-9.3/lib/libLLVM-6.0.so -Wl,-rpath-link,/run/user/1100/easybuild/build/Visit/3.2.0/CrayGNU-20.11/visit3.2.0/third_party/vtk/8.1.0/linux-x86_64_gcc-9.3/lib 
/usr/bin/ld: ../../lib/libavtpythonfilters_par.so: undefined reference to `PyMem_RawFree'
/usr/bin/ld: ../../lib/libavtquery_par.so: undefined reference to `PyUnicode_FromString'
/usr/bin/ld: ../../lib/libavtpythonfilters_par.so: undefined reference to `PyUnicode_AsEncodedString'
/usr/bin/ld: ../../lib/libavtpythonfilters_par.so: undefined reference to `PyBytes_FromStringAndSize'
/usr/bin/ld: ../../lib/libavtexpressions_par.so: undefined reference to `_Py_FalseStruct'
/usr/bin/ld: ../../lib/libavtpythonfilters_par.so: undefined reference to `Py_DecodeLocale'

**Comment by markcmiller86-visit** [comment]
I have been trying to unsubscribe from this list for a year now - can someone okease remove my address.

**Comment by brugger1** [comment]
It looks like it is linking against /usr/lib64/python2.7.0.so, so it is picking up of Python 2. What does the config-site file have for the location of python?

**Comment by cyrush** [comment]
Linking error does seem like it could be due to crossing python's (python 2.x and python 3x)

I also wanted to mention:  when porting, we targeted Python 3.7 or newer.
It's possible that 3.6 could cause an issue.

**Comment by jfavre** [comment]
Eric was right! he found the libpython2.7 in my very long link line. I had missed it. So, there is still confusion in the setup because my config-site file has the correct python3 stuff, which I also see after configuring the final build, but I also see FIND_PACKAGE_MESSAGE_DETAILS_PYTHONLIBS:INTERNAL=[/usr/lib64/libpython2.7.so][/usr/include/python2.7][v()]

for completeness, here is is the whole output of greping for PYTHON

grep PYTHON CMakeCache.txt

PYTHON_ENABLE_MODULE_mpicom:BOOL=ON
PYTHON_ENABLE_MODULE_pysimV2:BOOL=ON
PYTHON_ENABLE_MODULE_visit_writer:BOOL=ON
PYTHON_ENABLE_MODULE_visitmodule:BOOL=ON
//PYTHON_INCLUDE_PATH value
PYTHON_INCLUDE_PATH:PATH=/usr/include/python3.6m
//PYTHON_LIBRARY value
PYTHON_LIBRARY:PATH=/usr/lib64/libpython3.6m.so
PYTHON_LIBRARY_DEBUG:FILEPATH=PYTHON_LIBRARY_DEBUG-NOTFOUND
//PYTHON_LIBRARY_DIR value
PYTHON_LIBRARY_DIR:PATH=/usr/lib64
PYTHON_MODULE_mpicom_BUILD_SHARED:BOOL=ON
PYTHON_MODULE_pysimV2_BUILD_SHARED:BOOL=ON
PYTHON_MODULE_visit_writer_BUILD_SHARED:BOOL=ON
PYTHON_MODULE_visitmodule_BUILD_SHARED:BOOL=ON
//PYTHON_VERSION value
PYTHON_VERSION:PATH=3.6
//VISIT_PYTHON_DIR value
VISIT_PYTHON_DIR:PATH=/usr
VISIT_PYTHON_FILTERS:BOOL=ON
VISIT_PYTHON_SCRIPTING:BOOL=ON
//Details about finding PYTHONLIBS
FIND_PACKAGE_MESSAGE_DETAILS_PYTHONLIBS:INTERNAL=[/usr/lib64/libpython2.7.so][/usr/include/python2.7][v()]
//PYTHON_INCLUDE_PATH default value
PYTHON_INCLUDE_PATH_DEFAULT:INTERNAL=/usr/include/python3.6m
//ADVANCED property for variable: PYTHON_LIBRARY
PYTHON_LIBRARY-ADVANCED:INTERNAL=1
//ADVANCED property for variable: PYTHON_LIBRARY_DEBUG
PYTHON_LIBRARY_DEBUG-ADVANCED:INTERNAL=1
//PYTHON_LIBRARY default value
PYTHON_LIBRARY_DEFAULT:INTERNAL=/usr/lib64/libpython3.6m.so
//PYTHON_LIBRARY_DIR default value
PYTHON_LIBRARY_DIR_DEFAULT:INTERNAL=/usr/lib64
//PYTHON_VERSION default value
PYTHON_VERSION_DEFAULT:INTERNAL=3.6
//VISIT_PYTHON_DIR default value
VISIT_PYTHON_DIR_DEFAULT:INTERNAL=/usr

I am searching for another PYTHON keyword to bootstrap cmake (in addition to the variables already in the config-site file) to avoid that...Any tips?

**Comment by jfavre** [comment]
GIven my system:

ls /usr/lib64/libpython*
/usr/lib64/libpython2.7.so  /usr/lib64/libpython2.7.so.1.0  /usr/lib64/libpython3.6m.so  /usr/lib64/libpython3.6m.so.1.0  /usr/lib64/libpython3.so

The problem is in FindVisItPython.cmake where the following is found:

PYTHON_GLOB_RESULT=/usr/lib64/libpython2.7.so;/usr/lib64/libpython3.6m.so;/usr/lib64/libpython3.so

Selecting the 0-th entry in the list if its length is greater than 1 results in the 2.7 lib being wrongly picked up.

list(GET PYTHON_GLOB_RESULT 0 PYTHON_GLOB_RESULT)

I hacked the line above to pick the second entry in the list and got a clean compile and link.

**Comment by brugger1** [comment]
Thanks for tracking down the cause of the problem! I submitted issue https://github.com/visit-dav/visit/issues/5704.
