### ISSUE TITLE
Whitespace Issue

### ISSUE THREAD

**Issue by cara52** [visit-dav/live-customer-response#270]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

Hello,
I have a question regarding how to change the amount of whitespace that appears in windows. I have a plot that doesn't fill the whole window so there is a lot of white space on the right side of the window. Is there a way to change the size of the window without the plot automatically resizing with it or any other way to reduce the white space?

Thanks!

**Comment by aowen87** [comment]
Hello, 
One way to accomplish this is to use full frame mode (Windows->Full frame mode), which "stretches" the plot out to fill the window space. The downside to this is that you lose the original aspect ratio of your data, and you may need to adjust the window to find an aspect ratio that looks appropriate. Does this work for your case?

**Comment by cara52** [comment]
Unfortunately it does not. I need to keep the original aspect ratio.

**Comment by biagas** [comment]
You can also adjust the viewport. Open Controls->View
the viewport controls are described in our [manual](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/MakingItPretty/View.html#setting-the-2d-view)

**Comment by aowen87** [comment]
Also, if the legend is ending up in an undesirable position when you resize the window or adjust the viewport, you can manually set its position under Controls->Annotations->Objects-Legend.

**Comment by brugger1** [comment]
If you need to maintain a 1:1 aspect ratio, you can adjust the window size and VisIt will automatically remove the extra white space. When you save the image you should specify that the aspect ratio of the saved image matches the aspect ratio of the window (this is the default).

If you have an image of 2D data, you can shrink the window in the direction of the excess white space to eliminate the extra white space.

Here is an example with an image of 2D data with excess white space on the side.

![crop_2d_1](https://user-images.githubusercontent.com/1102718/119177187-d0d0d980-ba20-11eb-8271-449a4c733b8e.png)

Here is the image after shrinking the width.

![crop_2d_2](https://user-images.githubusercontent.com/1102718/119177229-e47c4000-ba20-11eb-8156-262331f0d74c.png)

Unfortunately, this now contains overlap of the legend and the data. You can widen the window a bit and adjust the viewport on the "2D view" tab of the view window to fix this (The 4 values in the viewport represent the xmin, xmax, ymin, ymax in a 0 -> 1 space of the window to plot the data).

![crop_2d_3](https://user-images.githubusercontent.com/1102718/119177493-3e7d0580-ba21-11eb-9616-0255afa04a46.png)

If you have an image of 3D data, you can adjust the width of the image and the size of the object will not change. That will allow you to reduce white space on the sides.

Here is an image from 3D data with excess white space on the side.

![crop_2d_4](https://user-images.githubusercontent.com/1102718/119178202-3e313a00-ba22-11eb-80d9-f2151c7eba71.png)

Here is the image after shrinking the width.

![crop_2d_5](https://user-images.githubusercontent.com/1102718/119178224-44bfb180-ba22-11eb-9b16-d1dbd759ae44.png)

As before, the legend now overlaps the object. You can merely widen the window slightly and pan the object.

![crop_2d_6](https://user-images.githubusercontent.com/1102718/119178246-4a1cfc00-ba22-11eb-9063-9b17c561a6ec.png)

**Comment by aowen87** [comment]
@cara52 were you able to find a solution using these methods?

**Comment by cara52** [comment]
@ aowen87 yes, thank you!
