### ISSUE TITLE
Visit graphics card compatibility

### ISSUE THREAD

**Issue by mgagne0** [visit-dav/live-customer-response#271]
I'm purchasing a new high-end Linux workstation that needs to run parallel visit. If I understand correctly Visit uses OpenGL for rendering. It appears that OpenGL 4.6 supports the NVIDIA Volta architecture, specifically the NVIDIA GV100 graphics card. Will the latest release of Visit run well on the GV100 card? Thanks.
Marc Gagné

**Comment by rusu24edward** [comment]
Hi @mgagne0, Visit requires [at least OpenGL 3.2](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/dev_manual/OpenGL.html?highlight=opengl#opengl-in-visit) to work properly, so it's likely that you'll be able to use the NVIDIA GV100 with Visit. Where are you getting your OpenGL library?

**Comment by mgagne0** [comment]
Well, it'll depend whether I build visit from source, or use one of the pre-built binaries.

Marc Gagné
Department of Earth and Space Sciences
West Chester University
Merion 201

________________________________

**Comment by rusu24edward** [comment]
Gotcha. Just wanted to check if you had the GL libraries already.

**Comment by rusu24edward** [comment]
We have a prebuilt binary that ships with [Mesa 17.3.9](https://docs.mesa3d.org/relnotes/17.3.9.html#mesa-17-3-9-release-notes-april-18-2018), which implements OpenGL 4.5, but only if requested at context creation. I'm not sure if our prebuilt binary has this since we only need 3.2 to run.

**Comment by markcmiller86** [comment]
@mgagne0 ... I think your best bet is to build VisIt from sources using the `build_visit.sh` [most recent](https://github.com/visit-dav/visit/releases/download/v3.2.0/build_visit3_2_0) script.

The mesa stuff is to support *software* rendering. I don't think the Mesa builds we provide have the ability to auto-switch between software (Mesa) GL and the local system's *native* GL.

**Comment by mgagne0** [comment]
Ok. Thank you.

Marc Gagné
Department of Earth and Space Sciences
West Chester University
Merion 201

________________________________
