### ISSUE TITLE
Question about accessing number of materials

### ISSUE THREAD

**Issue by cara52** [visit-dav/live-customer-response#274]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hello,

I am running VisIt via a python script. I am having an issue with a boundary plot when there is only one material. However, there are only a few time states where there is only one material. Is there a way to access the number of materials in a specific state? Thanks.

**Comment by rusu24edward** [comment]
Hi @cara52,

Sorry for your difficulty. Can you provide some more information about your setup? What kind of data are you using? What error do you see with the boundary plot? Can you share the data and script here?

**Comment by cara52** [comment]
I unfortunately cannot share the data or the script here. When the boundary plot is reflected and there is only one material, the underlying pseudocolor plot disappears. This only happens in that specific case (reflected boundary plot with one material). I am using a for loop to go through all of the states. Is there a way to see how many materials a specific state contains?

**Comment by rusu24edward** [comment]
[ListMaterials](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/cli_manual/functions.html#listmaterials) and [GetMaterials](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/cli_manual/functions.html#getmaterials) are a good place to start. Can you try this and let me know if it works?

**Comment by cara52** [comment]
Unfortunately, both of those contain all materials, not just the materials at a specific state.
