### ISSUE TITLE
scatterplot data extraction for comparison

### ISSUE THREAD

**Issue by biagas** [visit-dav/live-customer-response#279]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hello,

I need to extract a surface from time=n and subtract the ‘z’ values from the same surface at time=0 to generate a resultant displacement (delta_z) as a function of (x,y).

I am having no success at this, seemingly simple, task.

I am able to flatten the data with binning and projections to get the 2D scatterplot in x and y, with the third (z) value being the color. However, it is only an image in the window.

I cannot inspect or export the data through any means. I’ve tried to view the scatterplot with a spreadsheet (no good), and I’ve tried to export the window (I get the entire database). 

Can you please help me solve this simple problem?

Thanks,

Warren Jones
Idaho National Laboratory

**Comment by biagas** [comment]
If you export to VTK file format, it creates polydata of the scatter plot (x,y,z=0 coordinates), with the color/z variable as a scalar field.
Is this what you were looking for?

**Comment by markcmiller86-visit** [comment]
I might be able to work with that, if there isn't any way to get to the data that is being displayed in the scatterplot directly within VisIt. Can I turn my scatterplot into a query of the y coord over x &z? Note that my mesh is eularian, so I can't just grab deflection of a node. I'd need to perform a threshold on my material of interest and get the min & max y coordinate from the mesh query.



Thanks,



Warren



From: Kathleen Biagas via visit-users ***@***.***
Sent: Monday, June 7, 2021 3:36 PM
To: visit-dav/live-customer-response ***@***.***>
Cc: Kathleen Biagas ***@***.***>; Subscribed ***@***.***>
Subject: [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] scatterplot data extraction for comparison (#279)



If you export to VTK file format, it creates polydata of the scatter plot (x,y,z=0 coordinates), with the color/z variable as a scalar field.
Is this what you were looking for?

-

**Comment by biagas** [comment]
Hi Warren,

You might want to give [CMFE's](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/Quantitative/Expressions.html#comparison-expressions) a try.  A CMFE expression will allow you to take a variable from timestep 0 and map into the same mesh at a different timestep.  Then you can use it in a difference expression.

Something along these lines:

Create an expression returning the z-coord of mesh with name 'meshname' (substitute correct mesh name here)
```
zcoord= coord(meshname)[2]
```

Create a connectivity based cmfe mapping zcoord at timestep 0 onto the current mesh:
```
zcmfe= conn_cmfe(<[0]i:zcoord>, <meshname>)
```
The '[0]i:' part is the time index specification.

Create an expression that diffs the current zcoord with the one at timestep 0:
```
zdiff = (zcoord - zcmfe)
```

You will want to use the Defer Expression operator to differ evaluation of zdiff until after your data binning, etc.

Also, you can combine all the above expressions into one, I just separated them out to make it easier to explain.

Kathleen

**Comment by markcmiller86-visit** [comment]
Hi Kathleen,



I was able to use the vtk file format. Not elegant, but it'll work for now. You can close my ticket if there's one open.



Thanks for your help,



Warren



From: Kathleen Biagas via visit-users ***@***.***
Sent: Monday, June 7, 2021 3:36 PM
To: visit-dav/live-customer-response ***@***.***>
Cc: Kathleen Biagas ***@***.***>; Subscribed ***@***.***>
Subject: [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] scatterplot data extraction for comparison (#279)



If you export to VTK file format, it creates polydata of the scatter plot (x,y,z=0 coordinates), with the color/z variable as a scalar field.
Is this what you were looking for?

-
