### ISSUE TITLE
issue with missing domains

### ISSUE THREAD

**Issue by cyrush** [visit-dav/live-customer-response#28]
LLNL user reached out, not able to plot all domains for time steps beyond 0.

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by cyrush** [comment]
Using:  "Treat All Databases as Time Varying" resolved the issue

```
File Menu->Preferences:
Database Tab
Check: Treat all databases as time-varying
Dismiss
 
Options Menu->Save Settings

Restart VisIt.
```

This was a silo database, I expected the equiv TreatAllDbs flag to be set the output files, but that didn't appear to be the case.

**Comment by markcmiller86-visit** [comment]
I would like to be permanently unsubscribed from this email. I have three times attempted to do so via the link. Still receiving messages.
