### ISSUE TITLE
3_2_0 visit configure fails without sphinx

### ISSUE THREAD

**Issue by charlsonkim** [visit-dav/live-customer-response#281]
FYI:  --no-sphinx option does not work with latest release, configure fails without sphinx installed

--tcmalloc also had issues 

---

**Comment by biagas** [comment]
Just to be clear, building visit failed at configure time because sphinx wasn't installed? 

If that's the case, there is a flag that can be added to visit's CMake flags, to turn off building of manuals (VISIT_ENABLE_MANUALS=false)

What were the issues with --tcmalloc?

**Comment by charlsonkim** [comment]
tcmalloc looks like it builds but visit is unable to find it.  looks like
it doesn't get pushed to the third-party/ directory

**Comment by biagas** [comment]
Do you have a particular need for tcmalloc?

**Comment by charlsonkim** [comment]
no, not a big deal, just carrying over from older build line.
