### ISSUE TITLE
VisIt package failed. Giving up

### ISSUE THREAD

**Issue by charlsonkim** [visit-dav/live-customer-response#282]
Building VisIt (~50 minutes)
Building VisIt in visit/build . . .
Configuring VisIt . . .
Building VisIt . . . (~50 minutes)
All indications are that VisIt was successfully built.
Packaging VisIt ... (~10 minutes)
VisIt package failed. Giving up
Unable to build or install VisIt. Bailing out.

*************************************************************
tail of build_log
*************************************************************
running install_egg_info
Writing /home/charlson/bin/VisIt/visit/build/_CPack_Packages/Linux/TGZ/visit3_2_0.linux-x86_64/3.2.0/linux-x86_64/lib/site-packages/visit_testing-0.1-py3.7.egg-info
modules installed to '/home/charlson/bin/VisIt/visit/build/_CPack_Packages/Linux/TGZ/visit3_2_0.linux-x86_64/3.2.0/linux-x86_64/lib/site-packages/', which is not in Python's module search path (sys.path) -- you'll have to change the search path yourself

CPack Error: Error when generating package: visit
make: *** [Makefile:141: package] Error 1

---

**Comment by cyrush** [comment]
@charlsonkim  These search path warning shouldn't be a problem -- I suspect the real issue happened earlier in the process, are their any more error like signals in the log?

**Comment by biagas** [comment]
Here's a link to Qt's X11 requirements: https://doc.qt.io/qt-5/linux-requirements.html

**Comment by brugger1** [comment]
Looking at my Docker files for Ubuntu 18 and 20, I running the following command will install the packages you need.

```
apt-get update && apt-get install -y \
libxkbcommon-dev \
libegl1 \
libegl1-mesa-dev
```

**Comment by charlsonkim** [comment]
installed all missing dependencies and recompiled but still needed to remove -xbc-native-painting in build_visit and xcbglintegrations in FindVisItQt.cmake to get a complete compile. however when i try running :
***********************************************************************************************
charlson@R2-XPS-15-9560:~/bin/VisIt320/bin$ ./visit -np 4
./visit: 120: [[: not found
Running: gui3.2.0 -engineargs -l;mpirun;-np;4 -launchengine localhost
charlson@R2-XPS-15-9560:~/bin/VisIt320/bin$ ./visit
./visit: 120: [[: not found
Running: gui3.2.0
***********************************************************************************************
i've also tried the precompiled ubuntu 20 version .  gui mostly showed up but not cooperating well
![Screenshot at 2021-06-10 12-27-42](https://user-images.githubusercontent.com/11322613/121585605-a2269d00-c9e7-11eb-8dc7-13686162ebd3.png)

**Comment by biagas** [comment]
Could you post the contents of qt-everywhere-src-5.14.2/config.summary from your build?

**Comment by charlsonkim** [comment]
[config_summary.txt](https://github.com/visit-dav/live-customer-response/files/6639985/config_summary.txt)

**Comment by biagas** [comment]
Thanks for the config.summary.
I'm concerned about these entries:
```
  X11 specific:
    XLib ................................. no
    XCB Xlib ............................. no
    EGL on X11 ........................... no

```
and
```
   GL integrations:
      GLX Plugin ......................... no
```

Is X11 installed on your system? If so, is it found in  /usr/lib64 ?  We have a patch in our build_visit script that tells Qt to look there for X11 libs.  Qt's default location to search for X11 is /usr/X11R6/lib64. Perhaps our patch is incorrect for your system?

**Comment by charlsonkim** [comment]
i think Mint uses the same layout as Ubuntu.

/usr/lib/x86_64-linux-gnu/libX11.a

**Comment by biagas** [comment]
Would you mind trying a fresh rebuild of Qt, changing the following line (~19578 in [build_visit3_2_0_patched](https://github.com/visit-dav/visit/releases/download/v3.2.0/build_visit3_2_0_patched)):
```
 QMAKE_LIBDIR_X11        = /usr/lib64
```
to
```
 QMAKE_LIBDIR_X11        = /usr/lib/x86_64-linux-gnu
```

This will change our patch for X11 location to match where it is on your system. Probably would want a fresh build of VTK and then VisIt as well.

Actually, I'd be curious to see results of just configuring QT by hand (from a fresh untar of the source). Which mkspec does it use on your system? Does it find X11?

**Comment by charlsonkim** [comment]
qt build does better but not quite there.
resolved missing X11 and gl libraries but visit is not completing the
launch.  hangs at 98%

**Comment by charlsonkim** [comment]
trying a fresh build

**Comment by charlsonkim** [comment]
Excelsior!  things compile and work with a fresh build.

thanks for all your assistance.
![Screenshot at 2021-06-14 16-24-55](https://user-images.githubusercontent.com/11322613/121975479-906e2e00-cd36-11eb-9085-0799485dcd2c.png)

**Comment by biagas** [comment]
Whoo hoo!  Thanks for reporting on the issue and slogging through the rebuilds. Your efforts will help us improve our script for building Qt (hopefully for the next release).
