### ISSUE TITLE
 build_visit3_2_0 failed to build QT5

### ISSUE THREAD

**Issue by jodyxha** [visit-dav/live-customer-response#286]
[build_visit3_2_0_log.zip](https://github.com/visit-dav/live-customer-response/files/6702734/build_visit3_2_0_log.zip)

---
On my computer (gentoo) i tried to build VisIt 3.2.0.
I downloaded and unpacked the sources for VisIt 3.2.0, 
downloaded **build_visit3_2_0**, made it executable and copied it to the root off the visit directory, and then let it run.
After quite a while displaying "Building Qt5 . . . (~60 minutes)" it suddenly stops ("bailing out")
The logfile (attached) shows that at step [16451/18011] of buillding QT the error occurs:

make[4]: *** [Makefile.gn_run:741: run_ninja] Error 1
make[3]: *** [Makefile:82: sub-gn_run-pro-make_first] Error 2
make[2]: *** [Makefile:78: sub-core-make_first] Error 2
make[1]: *** [Makefile:49: sub-src-make_first] Error 2
make: *** [Makefile:453: module-qtwebengine-make_first] Error 2

Unfortunately the error message does not tell me what exactly went wrong.

Do you have any suggestions on how to track the error and fix this problem?

About my system:
output of 'uname -a':
`  Linux aim-frog 5.4.97-gentoo-x86_64 #1 SMP Tue Feb 16 11:12:44 CET 2021 x86_64 Intel(R) Xeon(R) W-2195 CPU @ 2.30GHz GenuineIntel GNU/Linux`

my gcc version:
`  gcc (Gentoo 9.3.0-r2 p4) 9.3.0`

I have python versions 3.7, 3.8, 3.9 installed

Thank You

**Comment by biagas** [comment]
@jodyxha, thanks for the report and providing  log files. I noticed an error message earlier on in the file regarding a failure with a part of webengine.  VisIt doesn't need webengine.  Perhaps if you  add `--skip webengine` to Qt's configure (approx line 25535 in build_visit3_2_0) like so:  ``` qt_flags="${qt_flags} -skip wayland --skip webengine"``` and rebuild?

Regarding Python, VisIt 3.2 will only work with 3.7.

Also, just so you know, we are transitioning  GitHub discussions. Any new  inquiries that you have can appropriately be handled there:

https://github.com/visit-dav/visit/discussions

**Comment by jodyxha** [comment]
Hi
Thank you for your suggestion.
After changing rhe line
    qt_flags="${qt_flags} -skip wayland"
to
    qt_flags="${qt_flags} -skip wayland -skip webengine"
visit was built without any more error messages.
I could also sucessfully compile a plugin.


However, something is not entirely right - the whole display window is 
black,
even after loading a file, selecting pseudocolor and clicking on "Draw".
But i think for this isuue i´ll have to do a ew pos.

Regards
   Jody

On 2021-07-03 0:35, Kathleen Biagas wrote

**Comment by biagas** [comment]
Did you resolve the black display yet? Are you going to open a new post? Don't forget you can do so on our Discussions page:
https://github.com/visit-dav/visit/discussions
