### ISSUE TITLE
Testing new issue behavior with visit-users

### ISSUE THREAD

**Issue by markcmiller86** [visit-dav/live-customer-response#3]

**Comment by markcmiller86** [comment]
Comment visit-dav/visit#12095

**Comment by markcmiller86-visit** [comment]
Comment visit-dav/visit#12094

**Comment by markcmiller86-visit** [comment]
comment 3

**Comment by markcmiller86** [comment]
email Reply to visit-dav/visit#12094

"markcmiller86-visit" wrote:


Comment visit-dav/visit#12094<https://github.com/visit-dav/live-customer-response/issues/2>

**Comment by markcmiller86** [comment]
mail-test
