### ISSUE TITLE
Reset view when playing cycles

### ISSUE THREAD

**Issue by aowen87** [visit-dav/live-customer-response#31]
Hello everyone,

Does anyone know of a way to have VisIt automatically reset the view for each cycle after pressing the "play" button? I have a mesh that shrinks over time, and it would be nice if the view was re-centered around the new bounds for each cycle. Otherwise, the details get pretty small pretty fast.

Alister

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by biagas** [comment]
Does changing "Controls->View->Advanced->View based on" to "Actual spatial extents" help?

**Comment by aowen87** [comment]
Doesn't seem to...

**Comment by markcmiller86** [comment]
@aowen87 did you find a resolution here?

**Comment by aowen87** [comment]
@markcmiller86 As a workaround, I created a python script that reset the view after each cycle update, and I saved out all of the frames to manually create a movie. It's a bit cumbersome, but it works.
