### ISSUE TITLE
Plot3D in VisIt

### ISSUE THREAD

**Issue by brugger1** [visit-dav/live-customer-response#32]
Hi

How do you read a plot3D file? As far as I know it is also required to read both grid file and solution file when reading a plot3D file and there are more parameters like if it binary or ascii, unformatted or formatted etc’ and I didn’t see all these options when I tried to read a plot3D file.

Also, can you read plot3D with iBlanks and address it in the visualisation?

One last question - since plot3D refers to structured mesh and structured mesh has also i,j,k coordinates of the mesh. Is there a possibility to display i,j or k surfaces of the solution  in VisIT?

Best regards,
Motti

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by brugger1** [comment]
Hi Motti,

In order to read a PLOT3D file, you can open either the grid file or the vp3d file. When you open the file you will need to specify the file type as "PLOT3D" at the bottom of the "File open" window.

![OpenPlot3D_1](https://user-images.githubusercontent.com/1102718/79477044-8b8cdd80-7fbe-11ea-91da-b7fcf936fb20.png)

You will then need to bring up the default open options for the PLOT3D reader and in there you can provide information about Binary vs. Ascii.

![OpenPlot3D_2](https://user-images.githubusercontent.com/1102718/79477074-97789f80-7fbe-11ea-87c1-8290d1504a7e.png)

In the options window you can specify reading the iblanks.

Eric

**Comment by markcmiller86-visit** [comment]
Thank you. This was very helpful.

How do I make sure that areas of the domain that are blanked out would not be displayed?

Best regards,
Motti

**Comment by brugger1** [comment]
I believe that VisIt will automatically remove the blanked out cells when you specify that the file has iblanking (or the vp3d file specifies iblanking is present).

**Comment by markcmiller86-visit** [comment]
It didn’t happen. The cells were not automatically removed. 
What is the vp3d file? 


‫ב-18 באפר׳ 2020, בשעה 0:31, ‏‏Eric Brugger via visit-users ‏<visit-users@elist.ornl.gov> כתב/ה:‬

**Comment by brugger1** [comment]
I'm not sure if its a standard plot3d meta file or something that the plot3d reader implementer developed. Here is a link to a description.

https://www.visitusers.org/index.php?title=Plot3D

I'll check the reader and see what should happen when iblanking is specified as a read option. Just to verify, you did specify iblanking in the reader options.

**Comment by brugger1** [comment]
I just looked through the plot3d reader and found the following piece of coding in vtkPLOT3DReader.C:

  // This is where we would read IBlanking information, but VisIt currently 
  //  doesn't do anything with it
  // 
#if 0
  if (this->Internal->IBlanking)
    {
    }
#endif

Based on this, I would say that our reader doesn't support eliminating zones based on iblank.

I will submit a ticket to enhance our reader.

**Comment by markcmiller86** [comment]
Not sure if *iblanking* in plot3d speak is quite the same as *missing value* functionality in VisIt but they might be close enough that we could implement this with VisIt's [missing value](https://github.com/visit-dav/visit/blob/b3d29a21c15c2e2a3d4d5ff5f0279800b2df2e16/src/databases/Silo/avtSiloFileFormat.C#L2659) functionality.

**Comment by brugger1** [comment]
I assumed iblanking was the same as missing value. Do you have any references on what iblanking means if it isn't.

I submitted issue [4632](https://github.com/visit-dav/visit/issues/4632) to add support for iblanking to the PLOT3D reader.

**Comment by markcmiller86** [comment]
Well...I guess I thought that *iblanking* is more about not showing/removing parts of a mesh without regard for reason/cause (for example, allowing finer resolution blocks to bleed through coarser resolution blocks in AMR) whereas VisIt's missing-value functionality is more about indicating a given mesh variable dof is not present (as can often be the case in experimental data) and so VisIt can decide how to visually indicate that in a plot too.

So, its maybe a subtle distinction that isn't worth quibbling about but now that I think about it, for sure VisIt's missing value functionality is attached to a mesh variable and not to the mesh. So, it can concievably change from one mesh variable to the next. That makes it maybe slightly more general than iblanking which I think is associated with the mesh and not any of its variables, right?

**Comment by markcmiller86-visit** [comment]
Sorry for the late response it was night in this part of the world.

So, iBlanking is not a missing value but is a “missing” mesh. It is areas in the mesh where the solver is not solving the equations. So, even if, for some reason, there are values in the solution file they are considered as non existing. I am not familiar with the VisIt’s missing-value functionality, being a new user, but it doesn’t sound like the right solution.
What VisIt should basically do is to simply not show the cells that have one or more nodes with iBlanked values.

**Comment by markcmiller86-visit** [comment]
Hi,

I am attaching 2 figures of the example I am using to check out the plot3D capabilities in VisIT.
The example has 3 meshs in the file. A far field mesh and 2 meshs for a wing.
One figure was created with a different visualisation code that support iBlanking and another one is created with VisIt.
You can see how the blanked out areas in the far field mesh looks like (this is on one plane of the domain but it explains the issue).
As I mentioned in my previous mail - the solver is not solving the equations in these areas. So there is no solution there and the information in the solution file given for these nodes is not relevant.

**Comment by markcmiller86-visit** [comment]
Hi,

I am attaching 2 figures of the example I am using to check out the plot3D capabilities in VisIT.
The example has 3 meshs in the file. A far field mesh and 2 meshs for a wing.
One figure was created with a different visualisation code that support iBlanking and another one is created with VisIt.
You can see how the blanked out areas in the far field mesh looks like (this is on one plane of the domain but it explains the issue).
As I mentioned in my previous mail - the solver is not solving the equations in these areas. So there is no solution there and the information in the solution file given for these nodes is not relevant.

**Comment by markcmiller86** [comment]
Copied images from email. It is a bit hard to see but I think the issue is the zones *inside* the wing. In the top image, they are *blanked* out. In the VisIt image, they are not. Also, there appears to be a region of the *rectangular* mesh that is also *blanked* out in the top image but not in the bottom image.

![image](https://user-images.githubusercontent.com/5720676/79677361-5393bf00-81a5-11ea-8eb4-db05e21f5fe4.png)

![image](https://user-images.githubusercontent.com/5720676/79677404-b8e7b000-81a5-11ea-8270-3630b8c0dae3.png)

**Comment by markcmiller86** [comment]
Actually, I took another look for instances of `iblank` in VisIt and found logic in `avtOVERFLOWFileFormat.C` and there this is handled using VisIt's *ghosting* logic and, in particular, the ghost value `NODE_NOT_APPLICABLE_TO_PROBLEM`. There is also an associated `ZONE_NOT_APPLICABLE_TO_PROBLEM` for zone centering. And, that sounds like the best way to handle this for Plot3D.

**Comment by markcmiller86-visit** [comment]
Thank you Mark. I don’t think I can use this because I am not sure if the plot3D file format is compatible with overflow format.
I understand that Eric Brugger submitted issue #4632 to add support for iblanking and I hope this finding will help.

I hope it can be updated easily and in the near future.

Thanks a lot.

Best regards,
Motti

**Comment by markcmiller86** [comment]
> I don’t think I can use this because I am not sure if the plot3D file format is compatible with overflow format.

Correct. Apologies for confusion. This was more or less a note to myself and our development team.

I was capturing my thoughts here about how to best we can proceed to *add* support for iblanking for Plot3D reader. Originally, I suggested VisIt's missing value functionality. But, the right way to go is with VisIt's *ghost* functionality and an example to follow is available to us in `avtOVERFLOWFileFormat.C`.

**Comment by markcmiller86-visit** [comment]
Ok. Great.
I hope to see an update soon.

Best regards,
Motti

**Comment by rusu24edward** [comment]
Pinged again in visit-dav/live-customer-response#78

**Comment by rusu24edward** [comment]
Resolved with [5204](https://github.com/visit-dav/visit/pull/5204). Should be released in 3.1.4.
