### ISSUE TITLE
VisIt (Python 3) fails to build with Intel compiler under CentOS 7.

### ISSUE THREAD

**Issue by andymwood** [visit-dav/live-customer-response#34]
I'm trying to build VisIt with the Intel compiler under CentOS 7.

It fails when it tries to build Python 3, reporting this error message in the log file:
```text
In file included from ./Include/Python.h(75),
                 from Parser/grammar1.c(4):
./Include/pyatomic.h(39): error: identifier "atomic_uintptr_t" is undefined
      atomic_uintptr_t _value;
      ^     

In file included from ./Include/Python.h(75),
                 from ./Programs/python.c(3):
./Include/pyatomic.h(39): error: identifier "atomic_uintptr_t" is undefined
      atomic_uintptr_t _value;
      ^     

In file included from ./Include/Python.h(75),
                 from Parser/node.c(3):
./Include/pyatomic.h(39): error: identifier "atomic_uintptr_t" is undefined
      atomic_uintptr_t _value;
      ^     

In file included from ./Include/Python.h(75),
                 from ./Include/pgenheaders.h(10),
                 from Parser/listnode.c(4):
./Include/pyatomic.h(39): error: identifier "atomic_uintptr_t" is undefined
      atomic_uintptr_t _value;
      ^     

compilation aborted for ./Programs/python.c (code 2)
make: *** [Programs/python.o] Error 2
make: *** Waiting for unfinished jobs....
compilation aborted for Parser/grammar1.c (code 2)
```

This appears to be an [resolved issue in Python](https://bugs.python.org/issue37415). The last comment on that bug report suggests that there's already a patch available that has been merged into the most recent version of Python.

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by andymwood** [comment]
I've now managed to build VisIt using Python 3.7.7 instead, setting the following environment variables prior to calling the build script:
```bash
export PYTHON3_URL=${PYTHON3_URL:-"https://www.python.org/ftp/python/3.7.7"}
export PYTHON3_FILE_SUFFIX="tgz"
export PYTHON3_VERSION=${PYTHON3_VERSION:-"3.7.7"}
export PYTHON3_COMPATIBILITY_VERSION=${PYTHON3_COMPATIBILITY_VERSION:-"3.7"}
export PYTHON3_FILE="Python-$PYTHON3_VERSION.$PYTHON3_FILE_SUFFIX"
export PYTHON3_BUILD_DIR="Python-$PYTHON3_VERSION"
export PYTHON3_MD5_CHECKSUM="d348d978a5387512fbc7d7d52dd3a5ef"
```

**Comment by griffin28** [comment]
Thanks @andymwood for updating us on what worked for you. What VisIt branch did you compile?

**Comment by andymwood** [comment]
I compiled from the source for 3.1.1 downloaded from [here](https://wci.llnl.gov/simulation/computer-codes/visit/source).

**Comment by griffin28** [comment]
This will be taken care of with https://github.com/visit-dav/visit/issues/4634.
