### ISSUE TITLE
Compilation Error when building visit with spack 

### ISSUE THREAD

**Issue by griffin28** [visit-dav/live-customer-response#35]
Hi,
 
I’m trying to build VisIt with spack as follows on an Ubuntu 16.04 with gcc 8.2.1:
 
`spack install visit~gui ^mesa~llvm`
 
This tries to install visit 3.0.1. All the dependencies build fine, but the visit build fails with the following errors:

```
In file included from /tmp/mdorier/spack-stage/spack-stage-visit-3.0.1-nvqekwfgxq5m5wvejt5ss6y6jtp3shcr/spack-src/src/visit_vtk/lightweight/vtkSkewLookupTable.C:43:
/tmp/mdorier/spack-stage/spack-stage-visit-3.0.1-nvqekwfgxq5m5wvejt5ss6y6jtp3shcr/spack-src/src/visit_vtk/lightweight/vtkSkewLookupTable.h:95:18: warning: invalid covariant return type for 'virtual unsigned char* vtkSkewLookupTable::MapValue(double)'
   unsigned char *MapValue(double v) override;
                  ^~~~~~~~
In file included from /tmp/mdorier/spack-stage/spack-stage-visit-3.0.1-nvqekwfgxq5m5wvejt5ss6y6jtp3shcr/spack-src/src/visit_vtk/lightweight/vtkSkewLookupTable.h:73,
                 from /tmp/mdorier/spack-stage/spack-stage-visit-3.0.1-nvqekwfgxq5m5wvejt5ss6y6jtp3shcr/spack-src/src/visit_vtk/lightweight/vtkSkewLookupTable.C:43:
/nfs2/mdorier/spack/opt/spack/linux-ubuntu16.04-skylake/gcc-8.2.1/vtk-8.2.0-bkc6q432axn3jsbwizbnz7zarhkeh3lr/include/vtk-8.2/vtkLookupTable.h:267:24: note: overridden function is 'virtual const unsigned char* vtkLookupTable::MapValue(double)'
   const unsigned char* MapValue(double v) override;
                        ^~~~~~~~
/tmp/mdorier/spack-stage/spack-stage-visit-3.0.1-nvqekwfgxq5m5wvejt5ss6y6jtp3shcr/spack-src/src/visit_vtk/lightweight/vtkSkewLookupTable.C: In member function 'virtual unsigned char* vtkSkewLookupTable::MapValue(double)':
/tmp/mdorier/spack-stage/spack-stage-visit-3.0.1-nvqekwfgxq5m5wvejt5ss6y6jtp3shcr/spack-src/src/visit_vtk/lightweight/vtkSkewLookupTable.C:69:36: error: invalid conversion from 'const unsigned char*' to 'unsigned char*' [-fpermissive]
   return this->Superclass::MapValue(temp);
```
 
Thanks,
 
Matthieu

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by griffin28** [comment]
Hello Matthieu…what version of VTK are you building?
 
We don’t currently support spack because our build_visit scripts do custom things during our builds, like apply patches, that resolves these types of build errors.
 
Have you tried using our build_visit script to build 3.0.1? It will download, patch, and build all of the needed dependencies.

**Comment by cyrush** [comment]
@griffin28 + Matthieu.

There are API breaking changes between VTK-8.1 and VTK 8.2.

I don't expect VisIt 3.0.1 to build without a patch.

This PR has a commit that outlines the const changes (and others) related to VTK 8.2:

https://github.com/visit-dav/visit/pull/4623/commits/4017bb7e44c5d523668fce0d8d7bb2610fbc3904

**Comment by griffin28** [comment]
I haven’t tried the build_visit script. I wanted to check if I could install visit with spack as part of the installation of Damaris.
Thanks,
 
Matthieu
