### ISSUE TITLE
Questions for plot issues in VisIt

### ISSUE THREAD

**Issue by griffin28** [visit-dav/live-customer-response#36]
Dear VisIT guys,

I am trying to use VisIT to plot large Flash files. I have no problems opening the files. I do have the following questions:

1. Why is the Controls/Annotations/Objects information needed in pseudocolor plots not saved as default?  After working to place and size the color bar in one plot, all info is lost for the next plot.

2. Why is the Control/View 2-D info not allowed to be saved as a default.

3. After quitting a session in VisIT, why are all of the default Annotations/2-D values lost? This forces my to redo all of the Annotations/2-D and Annotations/Object information.

4. How can you change the label positions in 2-D plots? In many cases, the position of the labels is not optimal for the particular plot?

5. In the Save Movie option, with mpg chosen, the last several frames of data are always lost. The number lost is variable but can be large. Can this be fixed? My workaround is to keep the sequential files for the movie by setting the number of frames used in Save Movie to be larger than the actual number. This causes a script error and happily leaves the sequential image files intact in its directory. Importing a sequence into ImageJ allows an .avi movie to be created and then converting in VLC allows an .m4v to be made. This is tedious but only one frame is lost in the last step. Finally, mpg is an old movie format. Could you actually use m4v or mp4 files?

I have just subscribed to the VisIT users list. FYI: the Flash center is moving to U. Rochester and Petros Tzeferacos has moved so we have massive Flash support.

Thanks in advance,

Rick

Dr. Rick B. Spielman
Senior Scientist
University of Rochester
Laboratory for Laser Energetics
250 East River Road
Rochester, NY 14623
Office: 585-275-2732
Cell: 505-715-0416
E-mail: spielman@lle.rochester.edu

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by griffin28** [comment]
Hello Rick...see my responses below.

> Why is the Controls/Annotations/Objects information needed in pseudocolor plots not saved as default? After working to place and size the color bar in one plot, all info is lost for the next plot.

To persist the annotation object between plots you'll need to press 'Make Default', 'Apply', and also do a 'Save Settings' (Options->Save Settings). If your questions is more along the line of why isn't this automatically done for you, then it's a matter of design choices that we need to make. There are users who would have the opposite request. Which one is right??

> Why is the Control/View 2-D info not allowed to be saved as a default.

I will add a ticket for this request. 

> After quitting a session in VisIT, why are all of the default Annotations/2-D values lost? This forces my to redo all of the Annotations/2-D and Annotations/Object information.

After selecting 'Make Default' and 'Apply' (may not need apply), also do a 'Save Settings' (Options->Save Settings).

> How can you change the label positions in 2-D plots? In many cases, the position of the labels is not optimal for the particular plot?

You can turn off 'Auto scale label values' and 'Auto set ticks' in the 'General' tab and then in the X- and Y-axis tabs adjust the 'Labels' and 'Tick marks' options. This may result in better label positioning

> In the Save Movie option, with mpg chosen, the last several frames of data are always lost. The number lost is variable but can be large. Can this be fixed? My workaround is to keep the sequential files for the movie by setting the number of frames used in Save Movie to be larger than the actual number. This causes a script error and happily leaves the sequential image files intact in its directory. Importing a sequence into ImageJ allows an .avi movie to be created and then converting in VLC allows an .m4v to be made. This is tedious but only one frame is lost in the last step. Finally, mpg is an old movie format. Could you actually use m4v or mp4 files?

I have experienced this myself and will file a ticket to get input from the other developers. As for m4v or mp4 you should have that option under 'Format'. If not it may be that you don't have a more robust encoder like ffmpeg installed on your system and in your path. VisIt doesn't ship with ffmpeg because of licensing issues, you'll need to install it yourself and make sure it's on your system path so VisIt can find it.

**Comment by markcmiller86** [comment]
Just wanted to also mention that some of the behavior in question here is described in [this](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/Preferences/index.html) section of the manual.

In particular...

> To persist the annotation object between plots you'll need to press 'Make Default', 

Is needed to ensure the *next* plot of that type in the *current* session has the same values.

> and also do a 'Save Settings' (Options->Save Settings).

Is needed to ensure that (all) defaults are saved for the *next time* you run VisIt.
