### ISSUE TITLE
Debian 10: VisIt 3.1.1

### ISSUE THREAD

**Issue by griffin28** [visit-dav/live-customer-response#37]
Greetings VisIt Developers,

I've downloaded and installed VisIt 3.1.1 using the installation script
from the LLNL web page. The OS is Debian 10, buster, stable. When I fire
up VisIt it returns:

```
/usr/..../3.1.1/linux-x86_64/bin/gui: error while loading shared
libraries: libicui18n.so.57: cannot open shared object file: No such
file or directory


Below are all of the *.so files pointing to an older library:

./libQt5XcbQpa.so
    libicui18n.so.57 => not found
--
./libQt5PrintSupport.so
    libicui18n.so.57 => not found
--
./libsimV2runtime_par.so
    libicui18n.so.57 => not found
--
./libQt5X11Extras.so
    libicui18n.so.57 => not found
--
./libQt5Widgets.so
    libicui18n.so.57 => not found
--
./libQt5Network.so
    libicui18n.so.57 => not found
--
./libQt5OpenGL.so
    libicui18n.so.57 => not found
--
./libQt5Xml.so
    libicui18n.so.57 => not found
--
./libQt5Concurrent.so
    libicui18n.so.57 => not found
--
./libQt5Qml.so
    libicui18n.so.57 => not found
--
./libQt5Gui.so
    libicui18n.so.57 => not found
--
./libQt5Svg.so
    libicui18n.so.57 => not found
--
./libQt5Core.so
    libicui18n.so.57 => not found

All of the other *.so files in 3.1.1/linux-x86_64/lib are linking against:

libicui18n.so.63 => /usr/lib/x86_64-linux-gnu/libicui18n.so.63
(0x00007f2de3e85000)
```

Thanks,

Todd

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by griffin28** [comment]
Hello Todd...try creating a soft link for `libicui18n.so.57` that points to `libicui18n.so.63`:

`ln -s /usr/lib/x86_64-linux-gnu/libicui18n.so.63 libicui18n.so.57`

**Comment by jmackey-astro** [comment]
I have the same issue, also with libraries: libicuuc.so.57 libicudata.so.57
If I add soft links to *.so.63 for these, then I get a QT error: 
/usr/local/visit/3.1.1/linux-x86_64/bin/gui: symbol lookup error: /usr/local/visit/3.1.1/linux-x86_64/lib/libQt5Core.so.5: undefined symbol: ucnv_getDefaultName_57
I have not managed to get VisIt 3.1.X working on debian 10 yet.

**Comment by markcmiller86-visit** [comment]
If I remember it correctly, I am able to run the centos8 binary on my Debian 10 system. None of the Debian binaries worked. You might try the centos8 binary from the Visit website.

Best
praveen

**Comment by jmackey-astro** [comment]
> My assumption is that you downloaded the executable built for `Debian 9 - Linux - x86_64 64 bit Debian 9, 4.9.184-linuxkit visit-dav/visit#12095 SMP, gcc 6.3 (Works on Debian 9 and 10.)`. If not, please do so and see if it works for your system.
> 
> If that's not the issue you may need to build from source on your system. @brugger1 handles the Debian builds so I'll file a ticket so he can look into this issue and potentially create a new Debian binary.

Yes that's right, I'm using the debian 9 binary.  I tried building from source but encountered errors that I was unable to work through.  I just downloaded the centos 8 version and it works!

**Comment by griffin28** [comment]
Created a ticket (https://github.com/visit-dav/visit/issues/4643) to hopefully resolve this and get Debian binaries to work on Debian systems.
