### ISSUE TITLE
Part of Set save options dialog off-screen

### ISSUE THREAD

**Issue by griffin28** [visit-dav/live-customer-response#39]
Hello,

I am running into an annoying problem with the "Set save options" dialog. When it pops-up, the bottom part of the dialog is off-screen, so I cannot click on "Save" "Apply", "Dismiss" etc. (see screenshot image below). I am aware that for some GUIs, shift-clicking on the side of the dialog and then dragging it solves the problem, but not on VisIt. Also, I can solve the problem by maximizing the dialog box but that takes up the whole screen and it is not ideal. 

I am using Visit 3.1.0 and Mac OS Mojave 10.14.6

I hope someone can help. 

Thank you,

David

<img width="1134" alt="david_ss" src="https://user-images.githubusercontent.com/26772741/79910782-1feaac00-83d4-11ea-95ee-4e65dbea9982.png">

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by markcmiller86-visit** [comment]
David…here’s a couple of suggestions:


  1.  Remove your ~/.visit directory and see if you still have that issue (you may want to make a copy of your ~/.visit directory first)
  2.  If possible, try using VisIt 3.1.1 that was built on macOS Mojave

If neither one of those work I will file a ticket.

-- Kevin


From: Kevin Griffin via visit-users <visit-users@elist.ornl.gov>
Reply-To: visit-dav/live-customer-response <reply@reply.github.com>, VisIt software users community <visit-users@elist.ornl.gov>
Date: Tuesday, April 21, 2020 at 1:31 PM
To: visit-dav/live-customer-response <live-customer-response@noreply.github.com>
Cc: Kevin Griffin <notifications@github.com>, Subscribed <subscribed@noreply.github.com>
Subject: [visit-users] [EXTERNAL] [visit-dav/live-customer-response] Part of Set save options dialog off-screen (#39)


Hello,

I am running into an annoying problem with the "Set save options" dialog. When it pops-up, the bottom part of the dialog is off-screen, so I cannot click on "Save" "Apply", "Dismiss" etc. (see screenshot image below). I am aware that for some GUIs, shift-clicking on the side of the dialog and then dragging it solves the problem, but not on VisIt. Also, I can solve the problem by maximizing the dialog box but that takes up the whole screen and it is not ideal.

I am using Visit 3.1.0 and Mac OS Mojave 10.14.6

I hope someone can help.

Thank you,

David

[david_ss]<https://user-images.githubusercontent.com/26772741/79910782-1feaac00-83d4-11ea-95ee-4e65dbea9982.png>

We're trying to combine visit-users email list with GitHub issues<https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works>.
When replying on visit-users, please reply only to emails with a Subject
line that includes [visit-dav/live-customer-response].

________________________________

**Comment by brugger1** [comment]
I notice that you are using VisIt on a low resolution screen. You might try setting "Post windows when shown" on the "General" tab of the "Preferences" window (under Options->Preferences...).

That will cause cause the window to get posted when you bring it up. When it's posted you should get scroll bars that allow you to scroll to the bottom of the window. I tried this on Windows and it worked. It didn't on Linux. I hope it will work on Mac.

**Comment by markcmiller86-visit** [comment]
Great!

Thank you for your help!

**Comment by markcmiller86** [comment]
@brugger1 are you sure this is a low-res screen? I checked the attached screen capture and it is ~3k x 2.5k and the *tray* at the bottom of the screen seems to show a *ton* of items. My impression is that its actually a high res screen that VisIt's GUI windows are for some reason taking up far more screen realestate than they should.

**Comment by brugger1** [comment]
Hmm! I was going on the fact that there was no notepad and there is a "Main" right below the title bar of the main window, which to me implies that VisIt has decided that it is a low resolution screen and is posting the main window. I agree, it does look high resolution now that you mention it. Perhaps it is some sort of Retina screen issue.

**Comment by markcmiller86** [comment]
Ok, well...now that you're talking about it...VisIt on my system does not appear to startup with a *notepad* area. Whether it is a build of my own or a released binary from VisIt's executable downloads, I get a main panel that looks like below. I never knew (or maybe just forgot) about that *notepad* area and I have to go with the mouse over that little dot at the bottom to grab a handle to drag the *notepad* out.

![Untitled 2](https://user-images.githubusercontent.com/5720676/79917305-19adfd00-83df-11ea-8c3e-4170c8a654f2.png)

**Comment by brugger1** [comment]
For whatever reason, when you start up the plot list has been increased to take up the entire bottom portion of the window. Maybe you did that once and then saved settings. What happens when you start with "-noconfig"?

**Comment by markcmiller86-visit** [comment]
Unfortunately, none of the options below worked.


   1. Remove your ~/.visit directory and see if you still have that issue
   (you may want to make a copy of your ~/.visit directory first)
   2. If possible, try using VisIt 3.1.1 that was built on macOS Mojave


I managed to fix the problem by scaling the resolution, although the bottom
end of the dialog is not visible.

By the way, I noticed that VisIt 3.1.1 has issues with dark mode in my OS.
Here's how it looks:

[image: Screen Shot 2020-04-21 at 5.51.42 PM.jpg]

**Comment by markcmiller86** [comment]
> @brugger1 wrote...
> What happens when you start with "-noconfig"?

Ok, tried that and indeed, I do see some space there now though it does look a bit funky. There is an empty **Tab** at the top and the **Output** button is sorta cut off too.

![Untitled 2](https://user-images.githubusercontent.com/5720676/79917830-20893f80-83e0-11ea-9807-3743db83ab7d.png)

**Comment by griffin28** [comment]
Are you using the retina display on a laptop or are you using an external monitor? Can you also provide a screen shot of your ‘About This Mac’ window with the ‘Overview’ tab selected?

The dark mode issue is known (https://github.com/visit-dav/visit/issues/4305) and we are working on it.

-Kevin

**Comment by markcmiller86-visit** [comment]
I am using my laptop retina display.

Here is the screenshot

[image: Screen Shot 2020-04-21 at 6.14.06 PM.jpg]

**Comment by markcmiller86-visit** [comment]
If I switch GUI style to "Windows" or "Fusion" and then back to macintosh
it fixes it but then if I save the settings and close and reopen visit. It
goes back to the wrong appearance.
