### ISSUE TITLE
Test issue from Eddie

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#4]
I do not have the email from gilcu about font config (not sure why I didn't get it...), so here is just a test issue with an image of some sand:

![Screen Shot 2020-01-27 at 8 59 14 AM](https://user-images.githubusercontent.com/18565891/73195870-7604c780-40e3-11ea-889d-70c1f4191e84.png)

**Comment by rusu24edward** [comment]
Here is a comment from Eddie

**Comment by rusu24edward** [comment]
replying to the email to see if it becomes a comment

**Comment by rusu24edward** [comment]
> Eddie

Wow, that's impressive!

**Comment by mclarsen** [comment]
What is impressive?

**Comment by cyrush** [comment]
are you sure that is sand? When I ask google to search using that image, it is pretty confident that it is actually Suede.

![suede](https://user-images.githubusercontent.com/1194526/73219652-7d42ca00-4111-11ea-9d03-c221aa394eb1.png)

**Comment by markcmiller86** [comment]
Ok, so things are not working as I expected. Neither @rusu24edward or @cyrush comments here came through on visit-users.

**Comment by markcmiller86** [comment]
I am trying something else to see if comments come through on visit-users

**Comment by markcmiller86** [comment]
Ok, yet another comment to test visit-users behavior
