### ISSUE TITLE
Azimuthal Velocity

### ISSUE THREAD

**Issue by griffin28** [visit-dav/live-customer-response#40]
> Dear all,
> 
> I am working with a problem which has a spherical symmetry. I post-process a .vtu file, which contains the fields u, v, w, p (u is the x-comp of the velocity, v the y-comp of the velocity, w the z-comp of the velocity and p pressure). So, I have the Cartesian components of the velocity. I would like to visualise the spherical components, in particular the azimuthal velocity, u_phi:
> 
> u_phi = - u * sin(arctan(y/x)) + v * cos (arctan (y/x)),
> 
> obtained from a change of coordinate system (assuming z is the axis of rotation). Clearly, I do not have x, y, z from my output file, hence my problem.
> I have seen there is an option in the Operators to Transform coordinates but I do not think it works in this case.
> 
> Could anybody help me out on this?
> 
> I am happy to share my .vtu file if it can be helpful.
> 
> Thank you in advance for your help.
> 
> Kind regards,
> Silvia

**From Mahesh Natarajan:
Go to this http://visitusers.org/index.php?title=VisIt-tutorial-data-analysis#Accessing_coordinates_.28of_a_mesh.29_in_Expressions

And see the section - Accessing coordinates (of a mesh) in Expressions, and follow those steps. It shows how to extract the x, y, z coordinates from the mesh data.**

Thank you Mahesh for your helpful responses!

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by brugger1** [comment]
![live-customer-response-40](https://user-images.githubusercontent.com/1102718/80010373-2e41d200-847f-11ea-8cd2-6b4a5bb21932.png)
