### ISSUE TITLE
Command line arguments for visit scripts

### ISSUE THREAD

**Issue by sullan2** [visit-dav/live-customer-response#42]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hello, 
Is it possible to specify arguments for visit scripts launched from command line. For example, if I am running:
visit -l srun -n visit -nn  32 -np 1024  -cli -nowin script.py
how can I specify command line arguments for script.py?

Thank You,
Hardeep

**Comment by sullan2** [comment]
Never mind, it works as expected.

**Comment by cyrush** [comment]
@sullan2  -- glad it worked for you, more context in case others land here:
Everything after "-s script.py" should exist are arguments. 
You can access via `sys.argv` or `Argv()`
