### ISSUE TITLE
Access to MPI in VisIt Scripts

### ISSUE THREAD

**Issue by sullan2** [visit-dav/live-customer-response#43]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hello,
I am running a script to capture lineout values of 512x512 lines, which is taking a long time.  Is it possible to parallelize the lineouts over MPI ranks in VisIt?  I’m thinking of allocating each rank an n x m patch, gathering on rank zero, and writing serially.

Thanks,
Hardeep

**Comment by griffin28** [comment]
If you have a spatially partitioned dataset and VisIt is running in parallel my assumption is that any call to the Lineout function should be executed in parallel without any additional work on your end.

@brugger1 is this a correct assumption?

**Comment by griffin28** [comment]
To clarify, If you have a dataset that is already spatially partitioned (has multiple domains) and you read it into VisIt that is running in parallel, the lineouts should execute in parallel and there's nothing you need to do programmatically.

**Comment by cyrush** [comment]
@sullan2  are you trying to get grids of data out? There might be a better way than line outs.

**Comment by sullan2** [comment]
Yes, essentially I am building a grid with information from the lineouts.

**Comment by cyrush** [comment]
@sullan2 are the meshes regular enough (like a uniform grid) that a resample operator can capture what you are looking for? If that is the case you can resample and save out a BOF (brick of floats) to easily process.

**Comment by cyrush** [comment]
you could also launch multiple versions of visit with your current setup -- more bookkeeping (to know what instance needs to do what lineoues) -- not sure what the speed ups would look like.
