### ISSUE TITLE
zeynep99_867@hotmail.com

### ISSUE THREAD

**Issue by teba103** [visit-dav/live-customer-response#46]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by teba103** [comment]
https://github.com/visit-dav/live-customer-response.wiki.git

**Comment by brugger1** [comment]
@teba103 there isn't any text associated with your submission. Can you add some?
