### ISSUE TITLE
SILO Multimeshadj in 2.13.3 and 3.0.2

### ISSUE THREAD

**Issue by brugger1** [visit-dav/live-customer-response#53]
Hi,

As I see, the issue I've reported some time ago has been fixed in 3.1.1 release. 
So, I've updated VisIt (visit3_1_1.linux-x86_64-centos8.tar.gz, desktop has also been updated from C7 to C8) and performed some experiments with the same data set.
The simple pseudocolor plot for UVelC variable looks correct for both Nodal and Original locations. Than, I've added new scalar variable "dUdy = gradient(UVelC)[1]". And the face x_max for dUdy disappeared again (see attach).

One more observation:
Pseudocolor plot for UVelC (Original) (all faces are in place) -> switch to dUdy (x_max dissapears)-> switch to UVelC (face x_max appears)
Pseudocolor plot for UVelC (Nodal) (all faces are in place) -> switch to dUdy (x_max dissapears)-> switch to UVelC (x_max missing)

However, a work-around with box operator still helps...

--
Best regards,
Boris Krasnopolsky

![visit0000](https://user-images.githubusercontent.com/1102718/80843176-774d0100-8bb8-11ea-83aa-2ae64be08f6c.png)

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by brugger1** [comment]
Hi Boris,

Our Silo expert off today and will be able to respond in a more meaningful manner than I can.

Eric

**Comment by rusu24edward** [comment]
Hi Boris,

Thanks for making us aware of this. I've created a [ticket](https://github.com/visit-dav/visit/issues/4680) in our system.

Eddie

**Comment by markcmiller86-visit** [comment]
Hi Eddie,

Ok, thank you. Will wait for the fix.


--
Boris
