### ISSUE TITLE
cli commands for serial/parallel prompt

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#57]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Good morning,
 
Is there any Python command to interact with (select and close) the serial/parallel prompt when VisIt launches?
 
Luis Costa

**Comment by rusu24edward** [comment]
Hi Luis,

I am not aware of a cli command to interact with the prompt. However, you can explicitly request engine resources in your workflow using the [OpenComputeEngine](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/cli_manual/functions.html#opencomputeengine) command. Alternately, you can use [host profiles](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/ClientServer/Host_Profiles.html?highlight=host%20profiles) to specify how you want to utilize compute engines if you are able to use client-server.

Will either of these options work for you?

**Comment by brugger1** [comment]
Hi Luis,

When you run the cli with a window present and host profiles defined for the machine you are running on, then VisIt will give you the standard prompt allowing you to choose the profile and if parallel, the number of nodes, processors and time limit. If you are running in "nowin" mode then it won't prompt you under the assumption that you don't have a display and can't respond to the prompt. If you use "OpenComputeEngine" and specify launch arguments, then it will use those and not prompt the user.

OpenComputeEngine is documented here:

https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/cli_manual/functions.html#opencomputeengine

Is that sufficient for your needs or do you need a way for the user to choose, even when running in "nowin" mode?

Eric

**Comment by markcmiller86-visit** [comment]
Eric, Edward,



Thanks for your suggestions. I got the behavior I wanted by adding:



    import socket

    hostname = socket.gethostname()

    args = ("-np", "1")

    OpenComputeEngine(hostname, args)



Thank you.



Regards,

Luis Costa

________________________________
From: Eric Brugger via visit-users [visit-users@elist.ornl.gov]
Sent: Tuesday, May 05, 2020 11:45 AM
To: visit-dav/live-customer-response
Cc: Eric Brugger; Subscribed
Subject: [Non-DoD Source] [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] cli commands for serial/parallel prompt (#57)

All active links contained in this email were disabled. Please verify the identity of the sender, and confirm the authenticity of all links contained within the message prior to copying and pasting the address to a Web browser.

________________________________



Hi Luis,

When you run the cli with a window present and host profiles defined for the machine you are running on, then VisIt will give you the standard prompt allowing you to choose the profile and if parallel, the number of nodes, processors and time limit. If you are running in "nowin" mode then it won't prompt you under the assumption that you don't have a display and can't respond to the prompt. If you use "OpenComputeEngine" and specify launch arguments, then it will use those and not prompt the user.

OpenComputeEngine is documented here:

Caution-https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/cli_manual/functions.html#opencomputeengine < Caution-https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/cli_manual/functions.html#opencomputeengine >

Is that sufficient for your needs or do you need a way for the user to choose, even when running in "nowin" mode?

Eric

**Comment by brugger1** [comment]
You can get the same behavior with OpenComputeEngine("localhost", ("-np", "1")) if you are running on local machine.

**Comment by cyrush** [comment]
You can also use:

```
from visit_utils import engine
engine.open(nprocs=1)
```

This will use the host profile that matches your host name (assuming it exists).
