### ISSUE TITLE
Artifact in visualization

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#59]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
I have encountered some issue with VisIt.
After I produced a VTU file, when I load this file into the program and draw the variables. 
I can see some color from the bottom mesh layer is showing on the top mesh layer and the location of this issue changed when I rotate.

![Unknown](https://user-images.githubusercontent.com/18565891/81314166-a5f62c00-903d-11ea-872c-ec046d458a5c.png)

I have attached the animation of this issue above.
Below are some details of the VTU file, also attached:

It is basically a nx*ny*nz mesh, but I prepared it using unstructured mesh.
Assume nx = 100, ny =100, nz = 2,
There are (nx+1)*(ny+1)*(nz+1) points.
I define (nx)(ny) polygon in top layer and another (nx)(ny) in middle layer as celltype quad, so these cells are faces instead of volume.
I assigned a variable to the top cells in one celldata, and another variable to the middle layer cells.

This vtk is generated by the PyeVTK package:
https://anaconda.org/conda-forge/pyevtk

Please take a look and let me know what you think.
Best Regards!

Chang Liao, PhD

**Comment by rusu24edward** [comment]
![Unknown](https://user-images.githubusercontent.com/18565891/81314252-bf977380-903d-11ea-9b31-6e44b0010b84.png)

**Comment by rusu24edward** [comment]
Hi Chang,

Can you please provide me with the .vtu files? I would like to get a better understanding of this issue by reproducing it with the rotations you mention.

Thanks,
Eddie

**Comment by changliao1025** [comment]
I have identified that this artifact was caused by the mesh distance being too close.
I increased the distance slightly and the artifact is gone.
Thanks.
