### ISSUE TITLE
Can't make scatter plot - as GitHub issue

### ISSUE THREAD

**Issue by markcmiller86** [visit-dav/live-customer-response#6]
We're trying a new approach to handling visit-users email issues as GitHub issues. See [New Approach](#new-approach)

---

I'm trying to make scatter plots in VisIt using this page http://visitusers.org/index.php?title=VisIt-tutorial-data-representations and I'm at this point:

![image](https://user-images.githubusercontent.com/5720676/73397946-63cc8a00-4299-11ea-9fc3-bd205687f913.png)

but I don't see any "Plots menu," and when I try to make a scatter plot in Plot Attributes > Scatter from the top menu bar, I get an error message saying 

"VisIt cannot set the Scatter plot attributes since no plots of that type are selected. This can either mean that you have no plots selected or you have more than one instance of the Scatter plot in your plot list. Please
 select a Scatter plot before trying to modify its plot attributes."  

Clearly I'm going about this the wrong way.  Is the visitusers guide for an older version of VisIt or am I missing something?

---
### New Approach
We've tried to integrate visit-users email list with a GitHub issues repository. You can easily view this issue on GitHub. If you have a GitHub account, you can add and edit comments there, add large attachments and easily search historical information there. There are many other advantages to using GitHub issues for such interactions and the VisIt team encourages you to do so.

**Comment by markcmiller86** [comment]
You need to have opened a databas first. 

You start by going to ``Plots:Add``->``Scatter``->``<some variable in your database>``. This will bring up the scatter plot *wizard*. From there you select additional variables for Y and (for 3D) Z axis.

If your database has only a single variable, I am not sure the scatter plot menu will even activate. You need at least two mesh variables to do a scatter plot. If that is your situation and you are maybe trying to do something with the mesh coordinates as one of the scatter plot variables, then you will have to use [expressions](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/Quantitative/Expressions.html#expression-window) to create some variables to plot.

**Comment by markcmiller86-visit** [comment]
Where is Plots:Add->Scatter?  And the file I am using is example.silo.  Is
that a database?

**Comment by markcmiller86-visit** [comment]
Wait... I see it now

**Comment by markcmiller86** [comment]
I am not familiar with `example.silo`. Can you mention where you found that?

**Comment by cyrush** [comment]
@markcmiller86 -- it's from our tutorial material (a renamed noise.silo)

**Comment by markcmiller86** [comment]
Kamron, were you able to resolve your issues here and create a scatter plot?

**Comment by markcmiller86-visit** [comment]
yes
