### ISSUE TITLE
Compiling 3.1.1 git request error

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#60]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hello,

1) On misc systems (Raspberry Pi Ubuntu Mate 18.04, CentOS 7.8, Ubuntu 18.04) I get the same error when attempting to build visit.
Typically I run
```
./build_visit3_1_1 --system-qt --mesagl --llvm --fortran --szip --zlib --silo --silex --netcdf --h5part --hdf5 --boxlib --cgns --java --python --openssl --console --parallel --makeflags -j 3
```
And get something like
```
Creating centos7.cmake
Done creating centos7.cmake
Building VisIt (~50 minutes)
Building VisIt in visit/build . . .
./build_visit3_1_1: ligne3952: ../src/GIT_VERSION: Aucun fichier ou dossier de ce type
fatal: Not a git repository (or any parent up to mount point /home2)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
cp: impossible de créer le fichier standard « ../src/config-site »: Aucun fichier ou dossier de ce type
/home2/cessenat/VISITCOMPIL/centos7/third_party/cmake/3.9.3/linux-x86_64_gcc-4.8/bin/cmake -DVISIT_CONFIG_SITE:FILEPATH=/home2/cessenat/VISITCOMPIL/centos7/centos7.cmake -DVISIT_INSTALL_THIRD_PARTY:BOOL=ON -DVISIT_PARALLEL:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release -DVISIT_C_COMPILER:FILEPATH=gcc -DVISIT_CXX_COMPILER:FILEPATH=g++ -DVISIT_C_FLAGS:STRING=" -m64 -fPIC -O2" -DVISIT_CXX_FLAGS:STRING=" -m64 -fPIC -O2" -DVISIT_JAVA:BOOL=ON ../src
CMake Error: The source directory "/home2/cessenat/VISITCOMPIL/centos7/visit/src" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
VisIt configure failed.  Giving up
```
Or
```
szip already installed, skipping
Creating host.conf
Creating ubuntu18.cmake
./build_visit3_1_1: ligne 2850 : pushd: trop d'arguments
./build_visit3_1_1: ligne 2850 : popd: 1,2 : argument non valable
popd : utilisation : popd [-n] [+N | -N]
Done creating ubuntu18.cmake
Building VisIt (~50 minutes)
Building VisIt in visit/build . . .
./build_visit3_1_1: ligne 3952: ../src/GIT_VERSION: Aucun fichier ou dossier de ce type
fatal: ni ceci ni aucun de ses répertoires parents (jusqu'au point de montage /) n'est un dépôt git
Arrêt à la limite du système de fichiers (GIT_DISCOVERY_ACROSS_FILESYSTEM n'est pas défini).
cp: impossible de créer le fichier standard '../src/config-site': Aucun fichier ou dossier de ce type
/usr/bin/cmake -DVISIT_CONFIG_SITE:FILEPATH=/home2/cessenat/VISITCOMPIL/ubuntu18/ubuntu18.cmake -DVISIT_INSTALL_THIRD_PARTY:BOOL=ON -DVISIT_PARALLEL:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release -DVISIT_C_COMPILER:FILEPATH=gcc -DVISIT_CXX_COMPILER:FILEPATH=g++ -DVISIT_C_FLAGS:STRING=" -m64 -fPIC -O2" -DVISIT_CXX_FLAGS:STRING=" -m64 -fPIC -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include -I/usr/lib/x86_64-linux-gnu/openmpi/include -O2" -DVISIT_JAVA:BOOL=ON ../src
CMake Error: The source directory "/home2/cessenat/VISITCOMPIL/ubuntu18/visit/src" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
VisIt configure failed.  Giving up
```
Do you have suggestions ?

2) For info:
Using your provided binary releases of VisIt with mpich works fine on Catalina and Mojave as well as Ubuntu 18.04 and CentOS 8.1. Making a plugin is easy and fine. Adding stripack to the FFP plugin is easy.
In French when LANG is fr_FR.UTF-8 there misses the menu « Set save options » Ctrl Shift O (or Apple Shift 0) - that is an old bug.
When making session files and re reading them there are some bugs - probably due to « , » for numbers in French instead of « . » for decimals.
In English all is fine.

3) Thank you.

Olivier

**Comment by rusu24edward** [comment]
(1) It looks like `git clone` failed in the build script. We have encountered this before in [this ticket](https://github.com/visit-dav/visit/issues/3991). Please try Eric's suggestion [here](https://github.com/visit-dav/visit/issues/3991#issuecomment-551241827) and let me know if that works for you.

**Comment by rusu24edward** [comment]
(2) Sorry to hear that you are still having issues with << Set Save Options >> missing in the menu. This was resolved [here](https://github.com/visit-dav/visit/issues/3317) and released with Visit 3.0.1. Can you confirm for me that you are still seeing this issue on a version of visit >= 3.0.1?

Regarding the session files, can you please provide me with an example file?

**Comment by markcmiller86-visit** [comment]
Hello Edward,

This happens on Mac when I run visit from a terminal (where I am in French), not from Menu/Apps/VisiT where I’m in English.
On Linux it does not happen, even in French.
All tests are in 3.1.1.

Included is the session file: load curve3d.silo, draw Pseudocolor, save session and quit.

[visitcurv3d.session.gz](https://github.com/visit-dav/live-customer-response/files/4603006/visitcurv3d.session.gz)

Cheers,

Olivier Cessenat

**Comment by markcmiller86-visit** [comment]
Hello Edward,

Yes indeed it worked fine : I completely restarted VisIt compilation and went through (at least on Linux Ubuntu 18,04 x86_64).

Cheers,

Olivier Cessenat.

**Comment by rusu24edward** [comment]
Hi Oliver,

Glad that the compilation has worked for you! I'm sorry to hear about the menu bug still not being fixed. I will make a note of this in our issue tracker so we can investigate a solution.
