### ISSUE TITLE
Example of diplaying vectors with reading in U and V vector data from ocean models

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#61]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Visit,
 
Looking for examples  of reading in and displaying vector data. We have u and v in netcdf files.
Visit can read the files but seems to just see individual variables and not as vector components.
How do I make the connection for displaying vectors in visit?
 
Thank you,
 
Peter.

```
File = localhost:D:\MODEL_DATA\hycom_glby_930_2020050600_t000_uv3z.nc
==============================================================================
Database: D:\MODEL_DATA\hycom_glby_930_2020050600_t000_uv3z.nc
Simulation: No
Database comment: Read as CCSM ST data
File format: NETCDF_1.0
Num Time States: 1
MetaData is NOT repopulated on state changes
useCatchAllMesh: 0
Format cannot do its own domain decomposition
The temporal extents are not set.
All Times are ***NOT*** Accurate
Times: Are identical to cycles
All Cycles are Accurate
Cycles:
0
Meshes:
Name = mesh4500x4251x40
Number of blocks = 1
Block origin = 1
Cell origin = 1 (origin within one block of the cells).
Node origin = 0 (origin within one block of the nodes).
Group origin = 0
Title for domain hierarchy is domains
Title for individual piece in domain hierarchy is domain
Number of groups = 0
Title for group hierarchy is groups
Title for individual piece in group hierarchy is group
Mesh type is Rectilinear Mesh.
Spatial Dimension = 3
The spatial extents are not set.
Topological Dimension = 3
The logical nodal bounds are not set.
The number of cells is not set.
There are no names set with the blocks.
Disjoint elements No
Contains ghost zones Maybe
Contains original cells No
Contains original nodes No
Units = x: "degrees_east", y: "degrees_north", z: "".
Labels = x: "lon", y: "lat", z: "depth".
Mesh coord type is XY
Mesh is primarily cell-based
Unit cell vector #0 is 1 0 0
Unit cell vector #1 is 0 1 0
Unit cell vector #2 is 0 0 1
Rectilinear grids do not have an implicit transform.

Name = global/mesh4500x4251x40
Number of blocks = 1
Block origin = 1
Cell origin = 1 (origin within one block of the cells).
Node origin = 0 (origin within one block of the nodes).
Group origin = 0
Title for domain hierarchy is domains
Title for individual piece in domain hierarchy is domain
Number of groups = 0
Title for group hierarchy is groups
Title for individual piece in group hierarchy is group
Mesh type is Unstructured Mesh.
Spatial Dimension = 3
The spatial extents are not set.
Topological Dimension = 3
The logical cell bound are not set.
The number of cells is not set.
There are no names set with the blocks.
Disjoint elements No
Contains ghost zones Maybe
Contains original cells No
Contains original nodes No
Units = x: "", y: "", z: "".
Labels = x: "X-Axis", y: "Y-Axis", z: "Z-Axis".
Mesh coord type is XY
Mesh is primarily cell-based
Unit cell vector #0 is 1 0 0
Unit cell vector #1 is 0 1 0
Unit cell vector #2 is 0 0 1
Rectilinear grids do not have an implicit transform.

Name = mesh4500x4251
Number of blocks = 1
Block origin = 1
Cell origin = 1 (origin within one block of the cells).
Node origin = 0 (origin within one block of the nodes).
Group origin = 0
Title for domain hierarchy is domains
Title for individual piece in domain hierarchy is domain
Number of groups = 0
Title for group hierarchy is groups
Title for individual piece in group hierarchy is group
Mesh type is Rectilinear Mesh.
Spatial Dimension = 2
The spatial extents are not set.
Topological Dimension = 2
The logical nodal bounds are not set.
The number of cells is not set.
There are no names set with the blocks.
Disjoint elements No
Contains ghost zones Maybe
Contains original cells No
Contains original nodes No
Units = x: "degrees_east", y: "degrees_north", z: "".
Labels = x: "lon", y: "lat", z: "Z-Axis".
Mesh coord type is XY
Mesh is primarily cell-based
Unit cell vector #0 is 1 0 0
Unit cell vector #1 is 0 1 0
Unit cell vector #2 is 0 0 1
Rectilinear grids do not have an implicit transform.

Name = global/mesh4500x4251
Number of blocks = 1
Block origin = 1
Cell origin = 1 (origin within one block of the cells).
Node origin = 0 (origin within one block of the nodes).
Group origin = 0
Title for domain hierarchy is domains
Title for individual piece in domain hierarchy is domain
Number of groups = 0
Title for group hierarchy is groups
Title for individual piece in group hierarchy is group
Mesh type is Unstructured Mesh.
Spatial Dimension = 3
The spatial extents are not set.
Topological Dimension = 2
The logical cell bound are not set.
The number of cells is not set.
There are no names set with the blocks.
Disjoint elements No
Contains ghost zones Maybe
Contains original cells No
Contains original nodes No
Units = x: "", y: "", z: "".
Labels = x: "X-Axis", y: "Y-Axis", z: "Z-Axis".
Mesh coord type is XY
Mesh is primarily cell-based
Unit cell vector #0 is 1 0 0
Unit cell vector #1 is 0 1 0
Unit cell vector #2 is 0 0 1
Rectilinear grids do not have an implicit transform.

Scalars:
Name = "water_u"
Mesh is = "mesh4500x4251x40"
Centering = node centered.
Units are: m/s
The extents are not set.
This variable does not contain enumerated values.
Missing value: -30

Name = "global/water_u"
Mesh is = "global/mesh4500x4251x40"
Centering = zone centered.
Units are: m/s
The extents are not set.
This variable does not contain enumerated values.
Missing value: -30

Name = "water_u_bottom"
Mesh is = "mesh4500x4251"
Centering = node centered.
Units are: m/s
The extents are not set.
This variable does not contain enumerated values.
Missing value: -30

Name = "global/water_u_bottom"
Mesh is = "global/mesh4500x4251"
Centering = zone centered.
Units are: m/s
The extents are not set.
This variable does not contain enumerated values.
Missing value: -30

Name = "water_v"
Mesh is = "mesh4500x4251x40"
Centering = node centered.
Units are: m/s
The extents are not set.
This variable does not contain enumerated values.
Missing value: -30

Name = "global/water_v"
Mesh is = "global/mesh4500x4251x40"
Centering = zone centered.
Units are: m/s
The extents are not set.
This variable does not contain enumerated values.
Missing value: -30

Name = "water_v_bottom"
Mesh is = "mesh4500x4251"
Centering = node centered.
Units are: m/s
The extents are not set.
This variable does not contain enumerated values.
Missing value: -30

Name = "global/water_v_bottom"
Mesh is = "global/mesh4500x4251"
Centering = zone centered.
Units are: m/s
The extents are not set.
This variable does not contain enumerated values.
Missing value: -30

Expressions:
mesh_quality/global/mesh4500x4251x40/aspect_gamma (scalar): aspect_gamma(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/aspect (scalar): aspect(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/condition (scalar): condition(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/diagonal_ratio (scalar): diagonal_ratio(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/min_diagonal (scalar): min_diagonal(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/max_diagonal (scalar): max_diagonal(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/dimension (scalar): dimension(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/jacobian (scalar): jacobian(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/max_edge_length (scalar): max_edge_length(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/max_side_volume (scalar): max_side_volume(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/min_edge_length (scalar): min_edge_length(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/min_side_volume (scalar): min_side_volume(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/oddy (scalar): oddy(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/relative_size (scalar): relative_size(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/scaled_jacobian (scalar): scaled_jacobian(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/shape (scalar): shape(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/shape_and_size (scalar): shape_and_size(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/shear (scalar): shear(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/skew (scalar): skew(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/stretch (scalar): stretch(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/taper (scalar): taper(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/volume (scalar): volume(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/face_planarity (scalar): face_planarity(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/relative_face_planarity (scalar): relative_face_planarity(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251/area (scalar): area(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/aspect (scalar): aspect(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/condition (scalar): condition(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/jacobian (scalar): jacobian(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/max_edge_length (scalar): max_edge_length(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/maximum_angle (scalar): maximum_angle(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/min_edge_length (scalar): min_edge_length(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/minimum_angle (scalar): minimum_angle(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/oddy (scalar): oddy(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/relative_size (scalar): relative_size(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/scaled_jacobian (scalar): scaled_jacobian(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/shape (scalar): shape(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/shape_and_size (scalar): shape_and_size(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/shear (scalar): shear(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/skew (scalar): skew(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/stretch (scalar): stretch(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/taper (scalar): taper(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/warpage (scalar): warpage(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/min_corner_area (scalar): min_corner_area(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/min_sin_corner (scalar): min_sin_corner(<global/mesh4500x4251>)
```

**Comment by rusu24edward** [comment]
Hi Peter,

Sorry for your trouble with reading vectors out of netcdf files. If possible can you share your data files with me so I can explore them in more detail?

For the time being, you can define a vector expression for the components being read as scalars. See image below for an example:
![Screen Shot 2020-05-07 at 2 43 28 PM](https://user-images.githubusercontent.com/18565891/81347552-3e59d400-9071-11ea-8706-bc5040f9e8d4.png)

Then my_vec will appear in the plot menus, and you should be able to plot a vector field with it.

**Comment by markcmiller86-visit** [comment]
Edward,







The link didn't work:

https://wci.llnl.gov/simulation/computer-codes/visit/FAQ.html



This one worked:



https://wci.llnl.gov/simulation/computer-codes/visit/faqs



I will work on reading the FAQs.



Thank you,



Peter.





Peter Flynn (N51) Regional Modeling Division
Fleet Numerical Meteorology and Oceanography Center (FNMOC)
1002 Balch Blvd., Stennis Space Center, MS 39522
(228) 688-6125 (DSN 828-) peter.m.flynn@navy.mil<https://b8b17ec8-ad06-44c8-b0d1-54f3ad2ef661/?REDIRECT=x-owacid2://0D4B0000/jmp:https://cas-chrl.nadsusea.nads.navy.mil/owa/redir.aspx?C=TwZscrWFbUufly3PG00Csw2Dx9xG0NAI3khFOaLbybyPXQ7f3dRDFYyxv2flqwzbuQWEXRmwDRg.&smime=14.2.247.1&URL=mailto:peter.m.flynn@navy.mil>

From: Edward Rusu via visit-users
Sent: Thursday, May 07, 2020 4:22:06 PM
To: visit-dav/live-customer-response
Cc: Edward Rusu; Subscribed
Subject: [Non-DoD Source] [visit-users] [EXTERNAL] [visit-dav/live-customer-response] Example of diplaying vectors with reading in U and V vector data from ocean models (#61)

We're trying to combine visit-users email list with GitHub issues<https://no-click.mil/?https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works>.
When replying on visit-users, please reply only to emails with a Subject
line that includes [visit-dav/live-customer-response].

________________________________

Visit,

Looking for examples of reading in and displaying vector data. We have u and v in netcdf files.
Visit can read the files but seems to just see individual variables and not as vector components.
How do I make the connection for displaying vectors in visit?

Thank you,

Peter.

File = localhost:D:\MODEL_DATA\hycom_glby_930_2020050600_t000_uv3z.nc
==============================================================================
Database: D:\MODEL_DATA\hycom_glby_930_2020050600_t000_uv3z.nc
Simulation: No
Database comment: Read as CCSM ST data
File format: NETCDF_1.0
Num Time States: 1
MetaData is NOT repopulated on state changes
useCatchAllMesh: 0
Format cannot do its own domain decomposition
The temporal extents are not set.
All Times are ***NOT*** Accurate
Times: Are identical to cycles
All Cycles are Accurate
Cycles:
0
Meshes:
Name = mesh4500x4251x40
Number of blocks = 1
Block origin = 1
Cell origin = 1 (origin within one block of the cells).
Node origin = 0 (origin within one block of the nodes).
Group origin = 0
Title for domain hierarchy is domains
Title for individual piece in domain hierarchy is domain
Number of groups = 0
Title for group hierarchy is groups
Title for individual piece in group hierarchy is group
Mesh type is Rectilinear Mesh.
Spatial Dimension = 3
The spatial extents are not set.
Topological Dimension = 3
The logical nodal bounds are not set.
The number of cells is not set.
There are no names set with the blocks.
Disjoint elements No
Contains ghost zones Maybe
Contains original cells No
Contains original nodes No
Units = x: "degrees_east", y: "degrees_north", z: "".
Labels = x: "lon", y: "lat", z: "depth".
Mesh coord type is XY
Mesh is primarily cell-based
Unit cell vector #0 is 1 0 0
Unit cell vector visit-dav/visit#12095 is 0 1 0
Unit cell vector visit-dav/visit#12094 is 0 0 1
Rectilinear grids do not have an implicit transform.

Name = global/mesh4500x4251x40
Number of blocks = 1
Block origin = 1
Cell origin = 1 (origin within one block of the cells).
Node origin = 0 (origin within one block of the nodes).
Group origin = 0
Title for domain hierarchy is domains
Title for individual piece in domain hierarchy is domain
Number of groups = 0
Title for group hierarchy is groups
Title for individual piece in group hierarchy is group
Mesh type is Unstructured Mesh.
Spatial Dimension = 3
The spatial extents are not set.
Topological Dimension = 3
The logical cell bound are not set.
The number of cells is not set.
There are no names set with the blocks.
Disjoint elements No
Contains ghost zones Maybe
Contains original cells No
Contains original nodes No
Units = x: "", y: "", z: "".
Labels = x: "X-Axis", y: "Y-Axis", z: "Z-Axis".
Mesh coord type is XY
Mesh is primarily cell-based
Unit cell vector #0 is 1 0 0
Unit cell vector visit-dav/visit#12095 is 0 1 0
Unit cell vector visit-dav/visit#12094 is 0 0 1
Rectilinear grids do not have an implicit transform.

Name = mesh4500x4251
Number of blocks = 1
Block origin = 1
Cell origin = 1 (origin within one block of the cells).
Node origin = 0 (origin within one block of the nodes).
Group origin = 0
Title for domain hierarchy is domains
Title for individual piece in domain hierarchy is domain
Number of groups = 0
Title for group hierarchy is groups
Title for individual piece in group hierarchy is group
Mesh type is Rectilinear Mesh.
Spatial Dimension = 2
The spatial extents are not set.
Topological Dimension = 2
The logical nodal bounds are not set.
The number of cells is not set.
There are no names set with the blocks.
Disjoint elements No
Contains ghost zones Maybe
Contains original cells No
Contains original nodes No
Units = x: "degrees_east", y: "degrees_north", z: "".
Labels = x: "lon", y: "lat", z: "Z-Axis".
Mesh coord type is XY
Mesh is primarily cell-based
Unit cell vector #0 is 1 0 0
Unit cell vector visit-dav/visit#12095 is 0 1 0
Unit cell vector visit-dav/visit#12094 is 0 0 1
Rectilinear grids do not have an implicit transform.

Name = global/mesh4500x4251
Number of blocks = 1
Block origin = 1
Cell origin = 1 (origin within one block of the cells).
Node origin = 0 (origin within one block of the nodes).
Group origin = 0
Title for domain hierarchy is domains
Title for individual piece in domain hierarchy is domain
Number of groups = 0
Title for group hierarchy is groups
Title for individual piece in group hierarchy is group
Mesh type is Unstructured Mesh.
Spatial Dimension = 3
The spatial extents are not set.
Topological Dimension = 2
The logical cell bound are not set.
The number of cells is not set.
There are no names set with the blocks.
Disjoint elements No
Contains ghost zones Maybe
Contains original cells No
Contains original nodes No
Units = x: "", y: "", z: "".
Labels = x: "X-Axis", y: "Y-Axis", z: "Z-Axis".
Mesh coord type is XY
Mesh is primarily cell-based
Unit cell vector #0 is 1 0 0
Unit cell vector visit-dav/visit#12095 is 0 1 0
Unit cell vector visit-dav/visit#12094 is 0 0 1
Rectilinear grids do not have an implicit transform.

Scalars:
Name = "water_u"
Mesh is = "mesh4500x4251x40"
Centering = node centered.
Units are: m/s
The extents are not set.
This variable does not contain enumerated values.
Missing value: -30

Name = "global/water_u"
Mesh is = "global/mesh4500x4251x40"
Centering = zone centered.
Units are: m/s
The extents are not set.
This variable does not contain enumerated values.
Missing value: -30

Name = "water_u_bottom"
Mesh is = "mesh4500x4251"
Centering = node centered.
Units are: m/s
The extents are not set.
This variable does not contain enumerated values.
Missing value: -30

Name = "global/water_u_bottom"
Mesh is = "global/mesh4500x4251"
Centering = zone centered.
Units are: m/s
The extents are not set.
This variable does not contain enumerated values.
Missing value: -30

Name = "water_v"
Mesh is = "mesh4500x4251x40"
Centering = node centered.
Units are: m/s
The extents are not set.
This variable does not contain enumerated values.
Missing value: -30

Name = "global/water_v"
Mesh is = "global/mesh4500x4251x40"
Centering = zone centered.
Units are: m/s
The extents are not set.
This variable does not contain enumerated values.
Missing value: -30

Name = "water_v_bottom"
Mesh is = "mesh4500x4251"
Centering = node centered.
Units are: m/s
The extents are not set.
This variable does not contain enumerated values.
Missing value: -30

Name = "global/water_v_bottom"
Mesh is = "global/mesh4500x4251"
Centering = zone centered.
Units are: m/s
The extents are not set.
This variable does not contain enumerated values.
Missing value: -30

Expressions:
mesh_quality/global/mesh4500x4251x40/aspect_gamma (scalar): aspect_gamma(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/aspect (scalar): aspect(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/condition (scalar): condition(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/diagonal_ratio (scalar): diagonal_ratio(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/min_diagonal (scalar): min_diagonal(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/max_diagonal (scalar): max_diagonal(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/dimension (scalar): dimension(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/jacobian (scalar): jacobian(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/max_edge_length (scalar): max_edge_length(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/max_side_volume (scalar): max_side_volume(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/min_edge_length (scalar): min_edge_length(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/min_side_volume (scalar): min_side_volume(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/oddy (scalar): oddy(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/relative_size (scalar): relative_size(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/scaled_jacobian (scalar): scaled_jacobian(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/shape (scalar): shape(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/shape_and_size (scalar): shape_and_size(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/shear (scalar): shear(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/skew (scalar): skew(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/stretch (scalar): stretch(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/taper (scalar): taper(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/volume (scalar): volume(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/face_planarity (scalar): face_planarity(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251x40/relative_face_planarity (scalar): relative_face_planarity(<global/mesh4500x4251x40>)
mesh_quality/global/mesh4500x4251/area (scalar): area(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/aspect (scalar): aspect(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/condition (scalar): condition(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/jacobian (scalar): jacobian(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/max_edge_length (scalar): max_edge_length(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/maximum_angle (scalar): maximum_angle(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/min_edge_length (scalar): min_edge_length(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/minimum_angle (scalar): minimum_angle(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/oddy (scalar): oddy(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/relative_size (scalar): relative_size(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/scaled_jacobian (scalar): scaled_jacobian(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/shape (scalar): shape(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/shape_and_size (scalar): shape_and_size(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/shear (scalar): shear(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/skew (scalar): skew(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/stretch (scalar): stretch(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/taper (scalar): taper(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/warpage (scalar): warpage(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/min_corner_area (scalar): min_corner_area(<global/mesh4500x4251>)
mesh_quality/global/mesh4500x4251/min_sin_corner (scalar): min_sin_corner(<global/mesh4500x4251>)

**Comment by markcmiller86-visit** [comment]
Edward,



I will try this today.



Thank you,



Peter.

Peter Flynn (N51) Regional Modeling Division
Fleet Numerical Meteorology and Oceanography Center (FNMOC)
1002 Balch Blvd., Stennis Space Center, MS 39522
(228) 688-6125 (DSN 828-) peter.m.flynn@navy.mil<https://b8b17ec8-ad06-44c8-b0d1-54f3ad2ef661/?REDIRECT=x-owacid2://0D4B0000/jmp:https://cas-chrl.nadsusea.nads.navy.mil/owa/redir.aspx?C=TwZscrWFbUufly3PG00Csw2Dx9xG0NAI3khFOaLbybyPXQ7f3dRDFYyxv2flqwzbuQWEXRmwDRg.&smime=14.2.247.1&URL=mailto:peter.m.flynn@navy.mil>

From: Edward Rusu via visit-users
Sent: Thursday, May 07, 2020 4:45:54 PM
To: visit-dav/live-customer-response
Cc: Edward Rusu; Subscribed
Subject: [Non-DoD Source] [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] Example of diplaying vectors with reading in U and V vector data from ocean models (#61)

Hi Peter,

Sorry for your trouble with reading vectors out of netcdf files. If possible can you share your data files with me so I can explore them in more detail?

For the time being, you can define a vector expression for the components being read as scalars. See image below for an example:
[Screen Shot 2020-05-07 at 2 43 28 PM]<https://no-click.mil/?https://user-images.githubusercontent.com/18565891/81347552-3e59d400-9071-11ea-8706-bc5040f9e8d4.png>

Then my_vec will appear in the plot menus, and you should be able to plot a vector field with it.

**Comment by markcmiller86-visit** [comment]
Edward,



The vectors are showing.



I am working on scalar for magnitude next.



You can close the ticket.



Thank you,



Peter.





Peter Flynn (N51) Regional Modeling Division
Fleet Numerical Meteorology and Oceanography Center (FNMOC)
1002 Balch Blvd., Stennis Space Center, MS 39522
(228) 688-6125 (DSN 828-) peter.m.flynn@navy.mil<https://b8b17ec8-ad06-44c8-b0d1-54f3ad2ef661/?REDIRECT=x-owacid2://0D4B0000/jmp:https://cas-chrl.nadsusea.nads.navy.mil/owa/redir.aspx?C=TwZscrWFbUufly3PG00Csw2Dx9xG0NAI3khFOaLbybyPXQ7f3dRDFYyxv2flqwzbuQWEXRmwDRg.&smime=14.2.247.1&URL=mailto:peter.m.flynn@navy.mil>

From: Edward Rusu via visit-users
Sent: Thursday, May 07, 2020 4:45:54 PM
To: visit-dav/live-customer-response
Cc: Edward Rusu; Subscribed
Subject: [Non-DoD Source] [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] Example of diplaying vectors with reading in U and V vector data from ocean models (#61)

Hi Peter,

Sorry for your trouble with reading vectors out of netcdf files. If possible can you share your data files with me so I can explore them in more detail?

For the time being, you can define a vector expression for the components being read as scalars. See image below for an example:
[Screen Shot 2020-05-07 at 2 43 28 PM]<https://no-click.mil/?https://user-images.githubusercontent.com/18565891/81347552-3e59d400-9071-11ea-8706-bc5040f9e8d4.png>

Then my_vec will appear in the plot menus, and you should be able to plot a vector field with it.
