### ISSUE TITLE
Extracting number of interconnected domains

### ISSUE THREAD

**Issue by brugger1** [visit-dav/live-customer-response#63]
Hello I have a scalar variable ("n") defined in an adaptive mesh (shown below). This variable varies between 0 and 1.

I would like to be able to use VisIt to count the number of interconnected regions where, n>0.5 via a query or some other method. For example, in the figure attached, that would be the number of red regions (3 in this case). 

I tried to do this by using a single-value contour plot at n=0.5 and then do a "Number of Connected Components" query, but that gives me the number of contour lines, which is not the same as the number of regions.

If I do a  "Number of Connected Components", "NumZones" or "NumNodes" query on the pseudocolor plot (or some selection of it) it gives me a really large number. 

Can anyone help with this? Any suggestions would be appreciated.

Thank you,

David

![github_issue_image](https://user-images.githubusercontent.com/1102718/81592652-22a54500-9373-11ea-92f6-2462b29c077f.jpg)

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by brugger1** [comment]
Hi David,

I notice that from the name of the file, that it is a vtu file. Assuming it's an collection of quads, then based on the image, my guess is that the cells are not connected and there are hanging nodes where there are changes in resolution. The connected components filter needs the cells to be connected. I don't have any good suggestions on how to proceed other than possibly to store the data as a regular mesh at some resolution sufficient to resolve the pieces. If this requires going down many levels in resolution, then this probably isn't feasible.

@cyrush do you have any thoughts?

Eric

**Comment by markcmiller86-visit** [comment]
Thank you, Eric

I think I understand. Could the resample operator help with connecting
between cells?

David

**Comment by brugger1** [comment]
Hi David,

Yes, resampling would definitely get things to work.

Eric

**Comment by cyrush** [comment]
yes, things have to be topologically connected with in a domain, but the do not need to be across domains.  @brugger1 do you think a merge operator could help? Never had much luck, but it seems like it would be helpful for this type of scenario .

**Comment by brugger1** [comment]
That’s an interesting idea. Do you know if it would handle the T junctions when there are changes in resolution?

**Comment by markcmiller86-visit** [comment]
Thank you, I will try some of your suggestions.

David

**Comment by cyrush** [comment]
@brugger1, hmm, hadn't thought of that. If duplicated points are removed and the topology is defined in terms of the new points,  it merging could still work.  You only need one shared point between cells in topology. 

We could also implement a more expensive local search that doesn't assume connected topology, but that wouldn't work out of the box (would need code changes)

**Comment by markcmiller86-visit** [comment]
It may not be the optimal solution but I managed to do what I wanted by
applying a resample operator and then an isovolume operator to a
pseudocolor plot.

Thank you all for your input.

David

**Comment by brugger1** [comment]
Glad you got it to work. Thanks for closing the loop.
