### ISSUE TITLE
Visualize AMR structured mesh in visit

### ISSUE THREAD

**Issue by biagas** [visit-dav/live-customer-response#67]
Hello Shiqi He,

Thank you for the detailed description and sample data files.
If you open Options->Preferences->Database, and select 'Treat all databases as time-varying' before opening your data and creating plots, you should see the desired outcome.

![Preferences-Database](https://user-images.githubusercontent.com/17075318/82233765-59d0a480-98e5-11ea-9894-7ca43a532611.png)

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hi Sir/Madam:

Hello! I am trying to use Visit to visualize my 2D non-conforming structured mesh (I attached an example: pic1.png ). The data is in Tecplot format. 
 
It's a series of AMR (adaptive mesh refinement) mesh. I do not have mesh blocks or different AMR hierarchy in my data. Each cell (or square) as I showed in pic1.png is defined as a "zone". 

The problem is that my visit-3.0.1 can open the data files by using Tecplot format, but the visualization is incomplete as I increase the time slab. I attached problem_example.pdf for more information. And to reproduce the error, you could use use my outputs data in the zip file. 

Thank you for your help, if you need more information, please contact me. 

All the best,

Shiqi He

![pic1](https://user-images.githubusercontent.com/17075318/82233093-512b9e80-98e4-11ea-9d8e-a9810cb5b28e.png)

[problem_example.pdf](https://github.com/visit-dav/live-customer-response/files/4645183/problem_example.pdf)

[outputs.zip](https://github.com/visit-dav/live-customer-response/files/4645184/outputs.zip)

**Comment by markcmiller86-visit** [comment]
Hi Kathleen:
Thank you so much! It all worked out!.

Have a nice day,
Shiqi He

**Comment by biagas** [comment]
You are welcome.
