### ISSUE TITLE
VisIt giving no errors but not rendering properly

### ISSUE THREAD

**Issue by biagas** [visit-dav/live-customer-response#69]
Hello Ivan,

Thank you for the detailed description and pictures of what's going wrong. There was a significant change in our rendering infrastructure with the 3.x versions of VisIt. Nothing in your script jumps out at me immediately.  I will pursue further investigations with your actual data, I will contact you shortly with instructions on how to send.

Kathleen

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Dear VisIt developers,

I have been using VisIt for last few years using the same configuration 
without any issue, now dumping into an unexpected problem that hopefully 
you can help with.

I use the VisIt command line tool, parsing the attached Python script 
for rendering HDF5 files of a multi-component fluid. But some of the 
renderings are now no longer working as expected. The script was also 
generated using VisIt and then hacked accordingly. In particular, I 
render files containing density data of a 2048x2048x2048 grid coarse 
grained to 1024x1024x1024, using the contour option. The coarse grain is 
obtained by simply averaging every two points from the original grid. In 
the past I have already used this technique of coarse gaining for 
smaller data-sets successfully. I have also successfully already 
rendered files at 1024x1024x1024 grid resolution without coarse gaining. 
So, the size should not be a problem.

However, now that I am rendering a 2048x2048x2048 grid coarse grained to 
1024x1024x1024 I am having troubles, I attached an examples of two time 
steps one rendered properly (t=150000) and now not (t=500000). For the 
rendering I am using the IBM MareNostrum at BSC, using fat memory nodes 
equipped with 300+GB of memory. I exclude it is a problem of the 
environment/code version as the rendering does not report any error and 
moreover, I have tried two different version of VisIt with the same 
results. Attached you also find two not wrong renderings made with two 
different version of VisIt.

I run the rendering as follows:

/apps/VISIT/3.0.2/bin/visit -cli -nowin -s plot-rho1-contours.py

Unfortunately I can't easily share the density files because of the size 
but I can find a way if you would be interested to investigate this further.

I hope you can kindly provide me some possible solution to this either 
because it is a problem in VisIt or it is something wrong in what I am 
doing. At the moment I have no clue how I can solve this problem.

The only concern is about the fact that at this resolution (and level of 
detail) the coarse grain technique might create some discontinuity that 
the contour doesn't digest properly. Maybe there is something to 
alleviate that effect if it is the case.

While thanking you in advance for any help you can provide, I remain 
available for anything else is needed.

Looking forward to receiving a feedback from you.

Kind regards,

Ivan

--

**Comment by brugger1** [comment]
rho-500000.png
![rho-500000](https://user-images.githubusercontent.com/1102718/82485942-01d6a100-9a91-11ea-8abd-2c71f2eac5fc.png)
rho-200000-visit-3.1.1.png
![rho-200000-visit-3 1 1](https://user-images.githubusercontent.com/1102718/82485950-0438fb00-9a91-11ea-827c-4b248b7e27fa.png)
rho-200000-visit-3.0.1.png
![rho-200000-visit-3 0 1](https://user-images.githubusercontent.com/1102718/82485953-04d19180-9a91-11ea-8a1f-9ce4b2d49646.png)
rho-150000.png
![rho-150000](https://user-images.githubusercontent.com/1102718/82485956-0602be80-9a91-11ea-9620-6ba0d8686e9e.png)

**Comment by biagas** [comment]
I iterated with Ivan privately. 
I was unable to duplicate his problem using his provided data. I tried various version of Visit 3.x.
Pixie reader was used, and there are > 1 billion cells.
He is going to try running in parallel.

**Comment by griffin28** [comment]
@biagas what method did you use to get the data from Ivan?

**Comment by biagas** [comment]
Our anonymous ftp server.

**Comment by biagas** [comment]
Ivan has reported success with using VisIt in parallel.

**Comment by markcmiller86** [comment]
It occurs to me we should also document this method (llnl anon ftp) of getting data to visit developers.

For some user *outside* LLNL, they would upload a file to `ftp://ftp.llnl.gov/incoming` and then email us to let us know it is there and the name of the file. Those files, including the list of filenames at that ftp server, are readable only by *anyone* inside the `.llnl.gov` domain. Finally, I believe files there are purged regularly. Don't know the specific time intervals though.

For developers to *send* data, they would upload a file to `ftp://ftp.llnl.gov/outgoing` and then send the link to whoever in email (e.g. `ftp://ftp.llnl.gov/outgoing/foo.tar.gz`) for someone to download (using anon ftp login). Files get purged there also. I think anyone logging in can see all filenames there.

Also, am not aware of an file size limits there.

**Comment by griffin28** [comment]
Thanks @markcmiller86 I was just crafting an email to ask for those details!
