### ISSUE TITLE
Problem in reading Lata format

### ISSUE THREAD

**Issue by griffin28** [visit-dav/live-customer-response#70]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

Dear Visit Assistance,
 
I am Mohammed Mehdi MOUMTAJI from the French atomic energy commission
I have a problem reading a format lata file in a parallel calculation.
The error message in visit is as follows:
![image001](https://user-images.githubusercontent.com/26772741/82922457-76e12500-9f2e-11ea-92cb-999ac885d903.jpg)

The error message in the terminal of visualization:
![image002](https://user-images.githubusercontent.com/26772741/82922460-78125200-9f2e-11ea-990c-0a7b5a4182c3.jpg)
 
In fact, it is a parallel CFD calculation using TrioCFD Software submitted to a supercalculator. Each day I stop the running to verify the sensors and the progress of the simulation and resume it.
The first three days, I was able to visualize but then the running progress without being able to read the Lata file.
Another thing is that when I stop the calculation, another lata file is created called data file_after restart.lata and also the same message from visit but the message in the terminal is a little bit different:
![image004](https://user-images.githubusercontent.com/26772741/82922461-78125200-9f2e-11ea-8188-6a1680efa1ea.jpg)
 
The operating system used is LINUX.
 
Kind Regards

**Comment by markcmiller86-visit** [comment]
Hello Mohammed…I have a few questions for you:

  1.  What type of Linux system and version?
  2.  What version of VisIt are you running?
  3.  What mode are you running in for VisIt (client/server?, in-situ?)
  4.  Are you able to share your data?

-- Kevin


From: Kevin Griffin via visit-users <visit-users@elist.ornl.gov>
Reply-To: visit-dav/live-customer-response <reply@reply.github.com>, VisIt software users community <visit-users@elist.ornl.gov>
Date: Tuesday, May 26, 2020 at 8:53 AM
To: visit-dav/live-customer-response <live-customer-response@noreply.github.com>
Cc: Kevin Griffin <notifications@github.com>, Subscribed <subscribed@noreply.github.com>
Subject: [visit-users] [EXTERNAL] [visit-dav/live-customer-response] Problem in reading Late format (#70)


We're trying to combine visit-users email list with GitHub issues<https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works>.
When replying on visit-users, please reply only to emails with a Subject
line that includes [visit-dav/live-customer-response].

________________________________

Dear Visit Assistance,

I am Mohammed Mehdi MOUMTAJI from the French atomic energy commission
I have a problem reading a format lata file in a parallel calculation.
The error message in visit is as follows:

The error message in the terminal of visualization:

In fact, it is a parallel CFD calculation using TrioCFD Software submitted to a supercalculator. Each day I stop the running to verify the sensors and the progress of the simulation and resume it.
The first three days, I was able to visualize but then the running progress without being able to read the Lata file.
Another thing is that when I stop the calculation, another lata file is created called data file_after restart.lata and also the same message from visit but the message in the terminal is a little bit different:

The operating system used is LINUX.

Kind Regards

**Comment by griffin28** [comment]
Thanks for your reply

LINUX version:
Scientific Linux
Release 6.10
Kernel Linux 2.6

VISIT Version :
visit/2_13_3

Mode: Running/Server

I am using the environment of the super calculator Occigen which allocate 1 node for me to use its visualization software Visit.
In fact, the CFD running is in 2 nodes (56 processors 28 each)  

I cannot share the data because it is in the supercalculator environment and I will send it to the local server after finishing the calculation.

**Comment by griffin28** [comment]
Mohammed...can you run VisIt in debug mode (-debug 5) and send me the log files? (https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/Preferences/File_Locations.html?highlight=debugging#files-in-other-locations). 

Also do you know Gauthier Fauchet or Benoit Mathieu? They worked on the LATA database and work for CEA. They may be in a better position to help you out.
