### ISSUE TITLE
Displaying time in hundredth of seconds in animations

### ISSUE THREAD

**Issue by griffin28** [visit-dav/live-customer-response#71]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

Dear all,

Is it possible to display time in animations in hundredth of seconds?

I need to post-process a simulation which has timestep=0.001, number of steps=10000 (so final time is 10 seconds) and a frame every 100 timesteps (so a total of 100 frames). 

Now Time in the video goes from 0 to 100 so I think it actually counts the frames. Is there a way to set it so it it displays the hundredth of second (to be very clear and specific: t=0.00 seconds, t=0.01 seconds, ... t=4.05 seconds, ... t=9.99seconds, t=10.00 seconds)?

Thank you.

Kind regards,
Silvia

**Comment by griffin28** [comment]
Hello Silvia,

I suggest you add a "Time Slider" in "Controls" / "Annotations" / "Objects" and then you can set your time format, by default it is "%g" but you can set "%8.2f" for instance.
The time your video viewer shows (the video actual time) is not related to VisIt by any mean.
Hope it helps.

Olivier Cessenat

**Comment by griffin28** [comment]
Hello Silva...you can also change how you display time (cycles, times, cycles and times) from VisIt preferences (under the File panel tab).

<img width="686" alt="Screen Shot 2020-05-27 at 8 38 15 AM" src="https://user-images.githubusercontent.com/26772741/83041739-aa3ab700-9ff5-11ea-8700-8412c70a9e54.png">

**Comment by markcmiller86-visit** [comment]
Thank you Oliver, that was useful.

Silvia

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
