### ISSUE TITLE
Getting range of a variable in pseudocolor plot

### ISSUE THREAD

**Issue by griffin28** [visit-dav/live-customer-response#73]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hi all,

We have embedded visIt windows in our application. I need to be able to get the actual Range(min, max) of a variable in pseudocolor plot. I know how to set min max by using minFlag,min, maxFlag,max in pseudocolor attributes, but I need to be able to get actual range of the variable i.e the values used when minFlag and maxFlag are set to false.
Is there any methods that return these values?

Your help will be much appreciated.

Thanks,
Jenisha

**Comment by markcmiller86-visit** [comment]
Hello Jenisha…I’m not sure how your embedded VisIt application is setup but if you have access to the Python CLI or Command window you can execute a MinMax query (https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/cli_manual/functions.html?highlight=min%20query#suppressqueryoutputoff)

--


From: Kevin Griffin via visit-users <visit-users@elist.ornl.gov>
Reply-To: visit-dav/live-customer-response <reply@reply.github.com>, VisIt software users community <visit-users@elist.ornl.gov>
Date: Wednesday, May 27, 2020 at 3:14 PM
To: visit-dav/live-customer-response <live-customer-response@noreply.github.com>
Cc: Kevin Griffin <notifications@github.com>, Subscribed <subscribed@noreply.github.com>
Subject: [visit-users] [EXTERNAL] [visit-dav/live-customer-response] Getting range of a variable in pseudocolor plot (#73)


We're trying to combine visit-users email list with GitHub issues<https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works>.
When replying on visit-users, please reply only to emails with a Subject
line that includes [visit-dav/live-customer-response].

________________________________

Hi all,

We have embedded visIt windows in our application. I need to be able to get the actual Range(min, max) of a variable in pseudocolor plot. I know how to set min max by using minFlag,min, maxFlag,max in pseudocolor attributes, but I need to be able to get actual range of the variable i.e the values used when minFlag and maxFlag are set to false.
Is there any methods that return these values?

Your help will be much appreciated.

Thanks,
Jenisha

**Comment by markcmiller86-visit** [comment]
This is how to do it if you have access to the Query window from your application: https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/tutorials/Data_Analysis.html?highlight=MinMax%20query#experiment-with-queries

-- Kevin


From: "Griffin, Kevin S. via visit-users" <visit-users@elist.ornl.gov>
Reply-To: VisIt software users community <visit-users@elist.ornl.gov>
Date: Wednesday, May 27, 2020 at 3:24 PM
To: visit-dav/live-customer-response <reply@reply.github.com>, VisIt software users community <visit-users@elist.ornl.gov>, visit-dav/live-customer-response <live-customer-response@noreply.github.com>
Cc: "Griffin, Kevin S." <griffin28@llnl.gov>, Subscribed <subscribed@noreply.github.com>, Kevin Griffin <notifications@github.com>
Subject: Re: [visit-users] [EXTERNAL] [visit-dav/live-customer-response] Getting range of a variable in pseudocolor plot (#73)

Hello Jenisha…I’m not sure how your embedded VisIt application is setup but if you have access to the Python CLI or Command window you can execute a MinMax query (https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/cli_manual/functions.html?highlight=min%20query#suppressqueryoutputoff)

--


From: Kevin Griffin via visit-users <visit-users@elist.ornl.gov>
Reply-To: visit-dav/live-customer-response <reply@reply.github.com>, VisIt software users community <visit-users@elist.ornl.gov>
Date: Wednesday, May 27, 2020 at 3:14 PM
To: visit-dav/live-customer-response <live-customer-response@noreply.github.com>
Cc: Kevin Griffin <notifications@github.com>, Subscribed <subscribed@noreply.github.com>
Subject: [visit-users] [EXTERNAL] [visit-dav/live-customer-response] Getting range of a variable in pseudocolor plot (#73)


We're trying to combine visit-users email list with GitHub issues<https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works>.
When replying on visit-users, please reply only to emails with a Subject
line that includes [visit-dav/live-customer-response].

________________________________

Hi all,

We have embedded visIt windows in our application. I need to be able to get the actual Range(min, max) of a variable in pseudocolor plot. I know how to set min max by using minFlag,min, maxFlag,max in pseudocolor attributes, but I need to be able to get actual range of the variable i.e the values used when minFlag and maxFlag are set to false.
Is there any methods that return these values?

Your help will be much appreciated.

Thanks,
Jenisha

**Comment by griffin28** [comment]
Hello Jenisha,

The easiest way to get the min max of a variable is to perform a query. 

SetQueryFloatFormat("%g")
Query("MinMax", use_actual_data=1)

If you want the min and max over all time steps you  can do those as well but as individual queries.

QueryOverTime("Min", end_time=6, start_time=0, stride=1, use_actual_data=1)

QueryOverTime("Max", end_time=6, start_time=0, stride=1, use_actual_data=1)

It will give the min/max for each time step which you can then use to determine the overall min/max.

Cheers,

Allen


Allen Sanderson
SCI Institute
University of Utah
