### ISSUE TITLE
Problem with Ospray Visit build

### ISSUE THREAD

**Issue by brugger1** [visit-dav/live-customer-response#75]
Hello,

I want to use Visit + Ospray. From my understanding of Visit documentation is that I have to build visit from source to get Ospray. 

I tried building it using the following command on macOS Catalina:
/.build_visit3_0_0  --ospray  --ispc --embree --tbb

But I get the following error:
Error: Cannot obtain source for embree.
Unable to build embree.  embree-3.2.0.x86_64.macosx.tar.gz not found.

This is the output related to the error from the log file:
+ warn 'Error: Cannot obtain source for embree.'
+ [[ yes == \y\e\s ]]
+ echo -e 'Error: Cannot obtain source for embree.'
+ [[ build_visit3_0_0_log != \/\d\e\v\/\t\t\y ]]
+ log 'Error: Cannot obtain source for embree.'
+ echo 'Error: Cannot obtain source for embree.'
Error: Cannot obtain source for embree.
+ return 1
+ [[ 1 != 0 ]]
+ ANY_ERRORS=yes
+ DO_EMBREE=no
+ error 'Unable to build embree.  embree-3.2.0.x86_64.macosx.tar.gz not found.'
+ warn 'Unable to build embree.  embree-3.2.0.x86_64.macosx.tar.gz not found.'
+ [[ yes == \y\e\s ]]
+ echo -e 'Unable to build embree.  embree-3.2.0.x86_64.macosx.tar.gz not found.'
+ [[ build_visit3_0_0_log != \/\d\e\v\/\t\t\y ]]
+ log 'Unable to build embree.  embree-3.2.0.x86_64.macosx.tar.gz not found.'
+ echo 'Unable to build embree.  embree-3.2.0.x86_64.macosx.tar.gz not found.'
Unable to build embree.  embree-3.2.0.x86_64.macosx.tar.gz not found.
+ test build_visit3_0_0_log '!=' /dev/tty

Any tips on what might be the problem? And please let me know if it is possible to get Ospray without having to build from source. 

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by brugger1** [comment]
Hi,

All the distributions post 3.0.0 should have ospray built in to all our download versions. It's possible some of the early 3.0.x versions for macOS didn't have it. I would try the latest version of VisIt (3.1.2) if the version you downloaded doesn't have OSPRay support. Also, the versions of build_visit after 3.1.0 download all the third party libraries from GitHub and I just checked and the embree library is there.

Eric

**Comment by markcmiller86-visit** [comment]
Thanks, the last version worked for me.

**Comment by brugger1** [comment]
Great! Thanks for closing the loop.

Eric
