### ISSUE TITLE
Visit build/install Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by brugger1** [visit-dav/live-customer-response#77]
Good day,

I have recently tried to install/build visit on Ubuntu 20.04 LTS. When building visit I do:

sudo ./build_visit3_1_2 --thirdparty-path /path/thirdparty --silo --required --mpich

but get stuck on the qt5 installation. I have also tried to build qt5 myself, without success. Is there anyone else who has this problem or with a solution to it, please? I attach the build log (compressed .gz).

I also tried installing visit using the executable packages with the install scripts. The install works smoothly, but when I run visit I get something like:

Running visit gui 3.1.2
error while loading shared libraries: libicui18n.so.*

I appreciate any assistance.

PS: I really enjoy Visit as a post-processing tool and visualiser and have cited it in papers as well. Thanks for the great package!

Best regards,

Leon MALAN, Ph.D | Senior Research Officer
Industrial CFD Research Group | Dept. Mechanical Engineering

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by brugger1** [comment]
Hi Leon,

The build_visit script for 3.1.2 didn't compile Qt properly on Ubuntu 20. We have added a fix for build_visit for the next release. Unfortunately, that is probably a month away. I can send you an updated build_visit script that has the fix.

Regarding the version you downloaded and installed. Was this the ubuntu20 version? After I made the fix to build_visit I added an ubuntu20 version to the 3.1.2 release on GitHub. If you downloaded right away or downloaded through a link on one of our web pages, you wouldn't have seen it. The link to the release on GitHub is:

https://github.com/visit-dav/visit/releases/tag/v3.1.2

Eric

**Comment by markcmiller86-visit** [comment]
Hi Eric,

Previously, ubuntu20 was not available and I tried 18 and 19 (both without success). I now installed the ubuntu20 version successfully. Thank you very much, I appreciate your assistance.

Best regards,

Leon MALAN, Ph.D | Senior Research Officer
Industrial CFD Research Group | Dept. Mechanical Engineering

[cid:de7f7de6-48a5-4432-a7b5-3e9b5061a7c8]      [cid:8f8facc0-3a4b-477d-a50e-9e69f23034aa]

________________________________

**Comment by brugger1** [comment]
Great! Glad to help.

Eric
