### ISSUE TITLE
iBlank support for Plot3D input file in the new VisIt3.1.2

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#78]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hi,

So I was hoping that the issue with reading a Plot3D that has iBlanks would be resolved in 3.1.2
If I understand correctly it is not resolved yet. Right?

Best regards,
Motti

**Comment by rusu24edward** [comment]
Hi Motti,

Sorry for your troubles with iBlanking. As you know, we've added this as an [issue in our issue-tracker](https://github.com/visit-dav/visit/issues/4632). I've added the priority label to it, and our team should review it this week and plan steps forward.

For the time being, do you have a workaround for what you need?

Eddie

**Comment by markcmiller86-visit** [comment]
Hi Eddie,

Thank you. 
Yes, for the time being we are using a different code that is much more limited with regard to its visualization capabilities. 

Best regards,
Motti

**Comment by rusu24edward** [comment]
Resolved with [5204](https://github.com/visit-dav/visit/pull/5204). Should be released in 3.1.4.
