### ISSUE TITLE
PLOT3D file problem

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#79]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
I have been using visit with plot3d x files that are of the default open options.  When I save a session, the session with restart correctly with the geometry displayed correctly using this saved session.  If I start from scratch and load a plot3d x file with other attributes, such as “multi grid”, and I select the “open file type” plot3d and then use the “set fault open options” button and select mutli grid.  The geometry will load and display correctly.  If I save this session and then start visit with this saved session,  the geometry is not displayed correctly.  I looked at the session file with and editor and could find no obvious saving of the x file options, although I did notice something about the settings for a plot3d q file.
 
Is there a fix for this problem?
 
Alan Egolf

**Comment by rusu24edward** [comment]
Hi Alan,

Sorry for your troubles with this. I have been trying to duplicate, but I have not been able to with the multi-grid PLOT 3D x data that I have access to. Can you share your data with me, including the plot3d x files and the session files? You can upload them to this page on github as a .zip file or you can send them via email.

Eddie

**Comment by markcmiller86-visit** [comment]
Eddie,

 

The attached file is asci , 3d, multi block. It is a simple representation of 4 helicopter rotor blades equally spaced around the z axis.

**Comment by rusu24edward** [comment]
Hi Alan,

I've been digging into this today, and here's what I know so far. I believe the session file is correctly storing the Multi Grid On option. The attached image shows a diff between one session file that uses it and other that doesn't; you can see a difference in the `optBools`.

![Screen Shot 2020-06-10 at 5 52 09 PM](https://user-images.githubusercontent.com/18565891/84333047-74dcb000-ab43-11ea-9b3a-d8e5d3e2731b.png)

Although this is in the sessionfile, it is not being read correctly. I've spent most of today digging through the code and haven't found a solution for this yet. I have created [an issue in our issue tracker](https://github.com/visit-dav/visit/issues/4804) to investigate this more thoroughly, but I do believe that this will require more effort than I can give this week.

Sorry for this inconvenience.
Eddie

**Comment by markcmiller86-visit** [comment]
Eddie,

I did say that I was using the defaults settings! That was a mistake on my part. Sorry for the confusion.  Never the less you can replicate are seeing my problem.  I am running on a Window 10 machine with version 3.1.1 of visit

**Comment by markcmiller86-visit** [comment]
Eddie,

 

Any chance of a resolution for this problem?

**Comment by rusu24edward** [comment]
Hi Alan,

We still need to dig into the codebase to see what is going on here. Do you have a workaround?

Eddie

**Comment by markcmiller86-visit** [comment]
No work around. Don't know enough about this tool.

**Comment by rusu24edward** [comment]
Thanks for the additional info, Alan. I will bring this up with the group and hopefully we can prioritize this.

**Comment by rusu24edward** [comment]
Alan,

As a workaround, you may be able to convert your data to a different file type and use that going forward. Is there a specific reason you are sticking with plot3d type?

Eddie

**Comment by markcmiller86-visit** [comment]
I used to use plot3d formatted data from government cfd codes and Fieldview
for graphical display of results when I was working. Also wrote company
codes to use this format. I will look at other possible formats.

Thanks
