### ISSUE TITLE
Would any left-handed users be willing to comment

### ISSUE THREAD

**Issue by markcmiller86** [visit-dav/live-customer-response#84]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

Hello VisIt Users...

I am writing to inquire if we have any left-handers who use VisIt routinely and, if so, whether you are aware of and would be willing to share any weaknesses w.r.t. to VisIt's operation (e.g. GUI) which make it harder to use as a left-handed operator?

This inquiry is wholly apart from any aspects of a typical computer workstation (mouse and keyboard layout) which already have known limitations in accommodating left-handed users.
 
I am looking for material to include in a paper regarding the importance of inclusion in software development and design.

**Comment by markcmiller86-visit** [comment]
I have switched the buttons on my mouse, which is kept to the left of my keyboard, and so I can use my left hand easily without any problems. This has the added benefit of frustrating right-handed users whenever they temporarily try to navigate with my mouse.

Don Frantz
