### ISSUE TITLE
Crash plotting from a Silo filo.

### ISSUE THREAD

**Issue by brugger1** [visit-dav/live-customer-response#9]
I got the following bug report from a user.

I have a certain material that contains more plot variables being output to a SILO file than other materials within the same simulation.  If I run the simulation on multiple processes and output to SILO, then it behaves fine and I am able to view those extra plot variables in Visit for only the material which has them (see screenshot below, only the colored element has the variable being plotted).  However, if I run the same simulation on only 1 process, then I get an error when trying to view this same variable in Visit and it crashes.
 
![visit_image](https://user-images.githubusercontent.com/1102718/76357528-1ea66980-62d5-11ea-9dcf-a9270920f854.png)

I have looked through our SILO write routines within Diablo and do not see anything obvious that would suggest why I would get different behavior when running with multiple processes vs. a single process. I’ve manually inspected the SILO hdf files using “hdfview” and don’t see any obvious differences other than the number of procs.  It may quite possibly still be something on our end, but was wondering if either of you had seen an issue like this before?  I can provide the relevant SILO files if that would help.

**Comment by brugger1** [comment]
There shouldn’t be any difference in behavior when running in serial or parallel. Can you give me the silo files? When you created the  pseudocolor plot, did you material select to only the materials that have the variable or did you do it over the entire mesh?

**Comment by brugger1** [comment]
I gave you an example of the SILO files created when I run with 2 procs vs 1 proc.  The variable I plotted below is pseudocolor “eeyy”.

Regarding the pseudocolor plot, I did not do any special selection of materials. It should be covering the whole mesh.  In our code it seems that we currently pass a NULL ptr into the SILO routines for element sets which do not contain the variable, though this should be the same regardless of num_procs.

**Comment by brugger1** [comment]
I have a fix that allows creating a pseudocolor plot of "eeeyy". The fix involved more changes than I thought, fortunately in just 3 files. There are 2 more spots that don't affect your data that I need to fix. I can make a version available now if you need it or in a little bit when I finish all the changes for you to test.

**Comment by aowen87** [comment]
@brugger1 should I move this to the main issue tracker?

**Comment by brugger1** [comment]
I'm waiting to hear back from the user.

**Comment by markcmiller86** [comment]
> @brugger1 should I move this to the main issue tracker?

Yes. But, did it turn out to be a Silo issue or a VisIt issue? If silo, I can move to the Silo issue tracker

**Comment by brugger1** [comment]
It’s a VisIt issue handling creating ghost zones from global ids and some of the blocks being NULL. I’ll have a pull request with the fix soon that you can look at.

**Comment by markcmiller86** [comment]
@brugger...is this now resolved?

**Comment by brugger1** [comment]
The fix is checked in, but I am waiting to hear back from the user. It turns out the e-mail came directly to you and me and I responded here, erroneously thinking he would get it from visit-users. I just now responded in the original e-mail chain, so I hope to hear back from the customer soon.

**Comment by brugger1** [comment]
The user tried 3.1.2 and it fixed his bug.
