### ISSUE TITLE
How to report bug in VisIt?

### ISSUE THREAD

**Issue by griffin28** [visit-dav/live-customer-response#90]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
I believe I might have found a bug in VisIt. How should I report it? I
want to attach some screen shots and scripts which are rejected by the
mailing list.

-erik

--
Erik Schnetter <eschnetter@perimeterinstitute.ca>
http://www.perimeterinstitute.ca/personal/eschnetter/

**Comment by griffin28** [comment]
Erik...you can create an issue ticket here: https://github.com/visit-dav/visit/issues

**Comment by griffin28** [comment]
Issue reported here: https://github.com/visit-dav/visit/issues/4845

**Comment by eschnett** [comment]
Thanks. Did that. I couldn't find a pointer to Github from the VisIt pages or VisIt wiki.
