### ISSUE TITLE
Question about time slider

### ISSUE THREAD

**Issue by griffin28** [visit-dav/live-customer-response#91]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

Hi,
I have a plot with two open databases and I would like the time to advance for both plots simultaneously. It seems like this isn’t possible though since the active time slider forces you to choose one database at a time. Is there a way to get around this?
Thanks!
Betsy

**Comment by griffin28** [comment]
Hello Betsy...yes it is possible to advance time for both plots simultaneously. You will need to do a time lock (https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/MultipleDatabaseAndWindows/Multiple_Window_Operations.html?highlight=Lock%20time#locking-time) 

It is the **lock** icon at the far right end of the tool bar. Once you've activated it the *Active time slider* will display **Correlation01**.

![Picture1](https://user-images.githubusercontent.com/26772741/85490685-0e19b680-b587-11ea-954b-33330c3359ba.png)
![Screen Shot 2020-06-23 at 7 20 20 PM](https://user-images.githubusercontent.com/26772741/85490695-11ad3d80-b587-11ea-98b8-e8130a8a71d0.png)

**Comment by markcmiller86-visit** [comment]
Hi Betsy,

The Database Correlation option under the "Controls" menu will do this for
you, I believe. In the menu click "new" then select the two sliders you
wish to attach to each other. This will create a third time slider that
moves both at once. If you have more than one window, you may also wish to
click the "lock time" to make all your windows change time simultaneously.
(Not a developer, just a Visit user, so if anyone else wants to weigh in,
please do.)

Best,
Alex
