### ISSUE TITLE
Building VisIt on SUSE

### ISSUE THREAD

**Issue by griffin28** [visit-dav/live-customer-response#92]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

Dear friends,

   I am building visit on suse with the following options
`./build_visit3_1_2 --parallel --llvm --mesagl`  (giving the paths to the
installed mpi version of the server).

  I got an error that I don't know how to sort out. Please, find
attached the log file. Thanks a lot in advance,

      Manel

--
Manel Perucho Pla
Departament d'Astronomia i Astrofísica / Observatori Astronòmic
Universitat de València
e-mail: manel.perucho <at> valencia.edu
web: http://www.uv.es/perucho
tel.: +34 96 354 33 63

**Comment by griffin28** [comment]
Hello Manel...your attachments were removed by our filters. Please upload your log files here: `ftp://ftp.llnl.gov/incoming` and then let me know it is there and the name of the file.

**Comment by markcmiller86** [comment]
> Please upload your log files here: `ftp://ftp.llnl.gov/incoming` and then let me know it is there and the name of the file.

Or, better yet, just attach the logs here as `.tar.gz` file if practical.

**Comment by griffin28** [comment]
Looking at the log files and if my translation is correct: `no s'ha trobat l'ordre => command not found` It looks like you need to install **patch** and **autoconf** on your SUSE system. 

VisIt build scripts use the patch command to patch third-party software and autoconf to build some third-party libraries.
