### ISSUE TITLE
troubles using XDMF to read HDF5 data

### ISSUE THREAD

**Issue by vsisl** [visit-dav/live-customer-response#96]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Dear VisIt community,

I would like to share my difficulties when using the XDMF reader to read HDF5 data. Hopefully, you will be able to help.

I have a large HDF5 database file with simulation data for various components at various timestamps. Component1 has a 3D cartesian mesh:

- /data/component1/mesh/x: (46)
- /data/component1/mesh/y: (46)
- /data/component1/mesh/z: (53)

The dataset I'm trying to plot (as pseudocolor) is called 27060:

- /data/component1/2024-01-01/fields/27060: (45, 45, 52)

My XMDF file **reader.xmf** looks as follows:

```xml
<?xml version="1.0" ?>
<!DOCTYPE Xdmf SYSTEM "Xdmf.dtd" []>
<Xdmf Version="2.0">
 <Domain>
   <Grid Name="mesh1" GridType="Uniform">

     <Topology TopologyType="3DRectMesh" Dimensions="53 46 46"/>

     <Geometry GeometryType="VXVYVZ">
       <DataItem Dimensions="46" NumberType="Float" Precision="4" Format="HDF">
        db_file.h5:/data/component1/mesh/x
       </DataItem>
       <DataItem Dimensions="46" NumberType="Float" Precision="4" Format="HDF">
        db_file.h5:/data/component1/mesh/y
       </DataItem>
       <DataItem Dimensions="53" NumberType="Float" Precision="4" Format="HDF">
        db_file.h5:/data/component1/mesh/z
       </DataItem>
     </Geometry>

     <Attribute Name="27060" AttributeType="Scalar" Center="Cell">
       <DataItem Dimensions="52 45 45" NumberType="Float" Precision="4" Format="HDF">
        db_file.h5:/data/component1/2024-01-01/fields/27060
       </DataItem>
     </Attribute>

   </Grid>
 </Domain>
</Xdmf>
```

It appears that VisIt is able to correctly read the mesh object - visualising the mesh using Add -> Mesh proves that:
![image](https://user-images.githubusercontent.com/28457179/85994734-81448200-b9f8-11ea-9925-c6bac85495a3.png)

However, when trying to visualise the dataset of interest (field 27060) it is apparent that the field is not read properly by VisIt. It seems like the mesh cells were loaded in a wrong order.

**Instead of something like this** (proper visualisation using the same data read from a SILO file):
![image](https://user-images.githubusercontent.com/28457179/85994858-a933e580-b9f8-11ea-8f7a-17e4c3107834.png)

**I get the following:** 
![image](https://user-images.githubusercontent.com/28457179/85276469-27850a80-b482-11ea-873d-048c491bba9a.png)

I would be grateful for any suggestions about what I might be doing wrong.

**Comment by vsisl** [comment]
My data and reader.xmf is here: 
[data_and_reader.tar.gz](https://github.com/visit-dav/live-customer-response/files/4845716/data_and_reader.tar.gz)

**Comment by biagas** [comment]
Thank you for providing the data. It looks like VisIt is reading NAN for most of the values for your field 27060.  I noticed your field dimensions are listed as (52 45 45) in the .xmf file, but it seems like it should be listed as 45 45 52 (according to the sizes of your coordinate arrays).  Simply changing the numbers in the .xmf file didn't help, so I'm still digging, and will get back with you.

**Comment by markcmiller86** [comment]
@vsisl it looks like the HDF5 file itself is bad...

```
% h5ls -vlrd db_file.h5 
Opened "db_file.h5" with sec2 driver.
/                        Group
    Location:  1:96
    Links:     1
/data                    Group
    Location:  1:800
    Links:     1
/data/component1         Group
    Location:  1:1832
    Links:     1
/data/component1/2024-01-01 Group
    Location:  1:2864
    Links:     1
/data/component1/2024-01-01/fields Group
    Location:  1:3896
    Links:     1
/data/component1/2024-01-01/fields/27060 Dataset {45/45, 45/45, 52/52}
    Location:  1:847328
    Links:     1
    Storage:   842400 logical bytes, 842400 allocated bytes, 100.00% utilization
    Type:      native double
    Data:
        (0,0,0) nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        (0,0,23) nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        (0,0,46) nan, nan, nan, nan, 459.853013759633, 624.870483415755, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        (0,1,12) nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        (0,1,35) nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 451.384961350865, 628.858975822851, nan,
        (0,2,1) nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        (0,2,24) nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        (0,2,47) nan, nan, nan, 485.17709533709, 6
```

**Comment by markcmiller86** [comment]
Alternatively, if you are using a `nan` value for the *missing value* functionality from Silo...that does not translate to XDMF, at least not that I am aware of. In which case, re-write the data using some value, like maybe -999, outside the desired range of the variable in place of all those nans and then when displaying with PC plot, add an threshold operator that removes all cells with value -999. Does that make sense?

**Comment by markcmiller86** [comment]
Also, can you attache the Silo version of you data too? That could help debug what is going on with the xmf data.

**Comment by vsisl** [comment]
Hello @biagas @markcmiller86 

Thank you so much for looking into this!

> I noticed your field dimensions are listed as (52 45 45) in the .xmf file, but it seems like it should be listed as 45 45 52 (according to the sizes of your coordinate arrays). 

I was following [an example from visitusers.org](https://visitusers.org/index.php?title=Using_XDMF_to_read_HDF5), but maybe I interpreted the instructions wrong...
_Note that the order of the coordinates when using HDF5 and the XML file is: Z, Y, X (with Z being optional)._

> Alternatively, if you are using a nan value for the missing value functionality from Silo...that does not translate to XDMF, at least not that I am aware of. In which case, re-write the data using some value, like maybe -999, outside the desired range of the variable in place of all those nans and then when displaying with PC plot, add an threshold operator that removes all cells with value -999. Does that make sense?

I didn't realize nan values might be causing this. I understand your idea with rewriting the data and using -999 instead of nan. I will try to do that to see if it fixes the issue.

However, eventually, I need to be able to keep nan values in my db file as I'm using the file also for other purposes than plotting with VisIt (and for those purposes, I need missing data to be represented by nans). I thought that VisIt was able to [handle missing data](https://visitusers.org/index.php?title=Missing_Data_Implementation).

**Comment by markcmiller86** [comment]
@biagas and @vsisl sorry to dribble this out. I just happened to notice that the `.xmf` file says that dataset `27060` has `NumberType="Float" Precision="4" ` but the actual hdf5 file shows it is a `double`. You might also try just manually changing precision to `8` in the `.xmf` file. Or, maybe the data producer told HDF5 the wrong thing and actually handed it `float` type data but told HDF5 the data was `double`.

**Comment by markcmiller86** [comment]
> I thought that VisIt was able to [handle missing data](https://visitusers.org/index.php?title=Missing_Data_Implementation).

Yes, right. VisIt can. However, not all database formats can. I honestly do not know if XDMF can. If it does, however, I see nothing in the `.xmf` file you provided that indicates it is *capturing* that information.

Finally, even *if* XDMF *does* support missing data (maybe it was a feature recently added), the existing reader(s) in VisIt do not appear to be processing  that so they would require some work to add the support.

Again, @biagas sorry for jumping in here. I just happened to take a quick look and saw these issues.

**Comment by biagas** [comment]
Thanks @markcmiller86, I appreciate you jumping in, you know more about our HDF5 readers than I.

**Comment by vsisl** [comment]
I tried the following:

- Changing `Precision="4"` to `Precision="8"`,
- changing `NumberType="Float" Precision="8"` to `NumberType="Double" Precision="8"`,
- generating a new h5 file with -999 replacing nan values (attaching here: [data_and_reader.tar.gz](https://github.com/visit-dav/live-customer-response/files/4847081/data_and_reader.tar.gz)
).

Unfortunately, none of these changes worked and I'm getting essentially the same result as before.

Thank you both for your inputs.

**Comment by markcmiller86** [comment]
Ok, thanks for attaching the data. Am thinking @biagas observation regarding the indexing is still an issue. Playing with things a bit.

**Comment by markcmiller86** [comment]
Ok, when I open the raw `db_file-no_nan.h5` file with our Pixie reader, I get what we expect...

### No-NaNs

![Untitled](https://user-images.githubusercontent.com/5720676/86040870-9bcb2b00-b9f9-11ea-9a96-4880db973361.png)

### NaNs

![Untitled 2](https://user-images.githubusercontent.com/5720676/86041566-ad610280-b9fa-11ea-911b-c46df0d0f1a6.png)

* Top-left: Pseudocolor plot of variable
* Top-right: Iso-volume operator applied to Pseudocolor plot
* Lower-left: Threshold operator applied to Pseudocolor plot

So, it looks like VisIt is *automatically* handling the NaN data as missing values (grayed out areas). However, it looks like Iso-volume operator is not hip to that behavior and continues to carry along those zones. The threshold operator appears to do the right thing even with missing-value'd (e.g. NaN) zones.

So, all this says that we don't understand the indexing order in the `.xdmf` metadata file. I took a look at [an example in our test suite](https://github.com/visit-dav/visit/blob/develop/data/xdmf_test_data.7z?raw=true) and found this one where raw data is embedded as ascii in the `.xmf` file itself. 

This confirms the dimension order is Z Y X in the `Dimensions=` attributes. However, look at the below example's cell-centered case. It appears to be the reverse of that. I would expect `2 2 3` but am seeing `3 2 2`. I dunno of that is a bug in this example or not.

```
<Xdmf xmlns:xi="http://www.w3.org/2003/XInclude" Version="2.1">
  <Domain>
    <Grid Name="3DRectMesh" GridType="Uniform">
      <Topology TopologyType="3DRectMesh" Dimensions="3 3 4"/>
      <Geometry Type="VXVYVZ">
        <!-- VX -->
        <DataItem Format="XML" Dimensions="4">
0 1 2 4
        </DataItem>
        <!-- VY -->
        <DataItem Format="XML" Dimensions="3">
0 1 3
        </DataItem>
        <!-- VZ -->
        <DataItem Format="XML" Dimensions="3">
3 1 0
        </DataItem>
      </Geometry>
      <Attribute Name="NodeScalars" AttributeType="Scalar" Center="Node">
        <DataItem Format="XML" Dimensions="3 3 4">
100 200 300 400
500 600 700 800
900 1000 1100 1200
1300 1400 1500 1600
1700 1800 1900 2000
2100 2200 2300 2400
2500 2600 2700 2800
2900 3000 3100 2900
3300 3400 3500 3600
        </DataItem>
      </Attribute>
      <Attribute Name="CellScalars" AttributeType="Scalar" Center="Cell">
        <DataItem Format="XML" Dimensions="3 2 2">
100 200 300 400
500 600 700 800
900 1000 1100 1200
        </DataItem>
      </Attribute>
      <Attribute Name="CellVectors2Components" AttributeType="Vector" Center="Cell">
        <DataItem Format="XML" Dimensions="3 2 2 2">
100 100 200 200 300 300 400 400
500 500 600 600 700 700 800 800
900 900 1000 1000 1100 1100 1200 1200
        </DataItem>
      </Attribute>
.
.
.
```

**Comment by markcmiller86-visit** [comment]
[Earlier on I sent this to the list only, but not sure if it is better
to send it to the github-issue address as well. Apologies for the
duplicated message, but just in case. I hope the github-issue address is
not only for developers?]

Hi,

I was just playing the other day with XDMF files, so I decided to give
it a try.

With the .xmf file changed as per the attached version and filtering out
the NaNs, I get the following (as in the image attached).

![image](https://user-images.githubusercontent.com/5720676/86047400-b60a0680-ba03-11ea-814b-5f52483a5099.png)

It looks like you got the precision and the coordinates order wrong when
writing the .xmf file...

```
<?xml version="1.0" ?>
<!DOCTYPE Xdmf SYSTEM "Xdmf.dtd" []>
<Xdmf Version="2.0">
 <Domain>
   <Grid Name="mesh1" GridType="Uniform">

     <Topology TopologyType="3DRectMesh" Dimensions="46 46 53"/>

     <Geometry GeometryType="VXVYVZ">
       <DataItem Dimensions="53" NumberType="Float" Precision="8" Format="HDF">
        db_file.h5:/data/component1/mesh/z
       </DataItem>
       <DataItem Dimensions="46" NumberType="Float" Precision="8" Format="HDF">
        db_file.h5:/data/component1/mesh/y
       </DataItem>
       <DataItem Dimensions="46" NumberType="Float" Precision="8" Format="HDF">
        db_file.h5:/data/component1/mesh/x
       </DataItem>
     </Geometry>

     <Attribute Name="27060" AttributeType="Scalar" Center="Cell">
       <DataItem Dimensions="45 45 52" NumberType="Float" Precision="8" Format="HDF">
        db_file.h5:/data/component1/2024-01-01/fields/27060
       </DataItem>
     </Attribute>

   </Grid>
 </Domain>
</Xdmf>
```

---------------------------------------------------------------------------------------------
AVISO LEGAL: Este mensaje puede contener información confidencial y/o privilegiada. Si usted no es el destinatario final del mismo o lo ha recibido por error, por favor notifíquelo al remitente inmediatamente. Cualquier uso no autorizadas del contenido de este mensaje está estrictamente prohibida. Más información en: https://www.iac.es/es/responsabilidad-legal
DISCLAIMER: This message may contain confidential and / or privileged information. If you are not the final recipient or have received it in error, please notify the sender immediately. Any unauthorized use of the content of this message is strictly prohibited. More information:  https://www.iac.es/en/disclaimer


-- 
Ángel de Vicente

Tel.: +34 922 605 747
Web.: http://research.iac.es/proyecto/polmag/

**Comment by markcmiller86** [comment]
Thank you Angel de Vicente!!

I've pasted your attachments here...

![image](https://user-images.githubusercontent.com/5720676/86047400-b60a0680-ba03-11ea-814b-5f52483a5099.png)

```
<?xml version="1.0" ?>
<!DOCTYPE Xdmf SYSTEM "Xdmf.dtd" []>
<Xdmf Version="2.0">
 <Domain>
   <Grid Name="mesh1" GridType="Uniform">

     <Topology TopologyType="3DRectMesh" Dimensions="46 46 53"/>

     <Geometry GeometryType="VXVYVZ">
       <DataItem Dimensions="53" NumberType="Float" Precision="8" Format="HDF">
        db_file.h5:/data/component1/mesh/z
       </DataItem>
       <DataItem Dimensions="46" NumberType="Float" Precision="8" Format="HDF">
        db_file.h5:/data/component1/mesh/y
       </DataItem>
       <DataItem Dimensions="46" NumberType="Float" Precision="8" Format="HDF">
        db_file.h5:/data/component1/mesh/x
       </DataItem>
     </Geometry>

     <Attribute Name="27060" AttributeType="Scalar" Center="Cell">
       <DataItem Dimensions="45 45 52" NumberType="Float" Precision="8" Format="HDF">
        db_file.h5:/data/component1/2024-01-01/fields/27060
       </DataItem>
     </Attribute>

   </Grid>
 </Domain>
</Xdmf>
```

**Comment by vsisl** [comment]
I confirm that this is the solution! Many thanks to all involved! @markcmiller86 @biagas Ángel de Vicente

**Comment by vsisl** [comment]
I'm sorry to reopen this issue, but I realized that there is another bug in the solution kindly provided by Ángel de Vicente.

@markcmiller86 looking at your latest screenshot, I noticed that the coordinate system is rotated. (I highlighted this in the picture attached below - **the correct coordinate directions are marked in red**.)
![image](https://user-images.githubusercontent.com/28457179/86488461-509a7a80-bd61-11ea-80e2-60edcd69acc4.png)

I tried to play around with the order of numbers in `Dimensions="46 46 53"` as well as with the order of `<DataItem>` definitions in `<Geometry>` but I wasn't able to find a working solution. :(

**Comment by markcmiller86-visit** [comment]
Hello,

vsisl via visit-users <visit-users@elist.ornl.gov> writes:

> I'm sorry to reopen this issue, but I realized that there is another
> bug in the provided solution.
>
> @markcmiller86 looking at your latest screenshot, I noticed that the
> coordinate system is rotated. (I highlighted this in the picture
> attached below.)

That's why I told you that you had somehow mixed the precision and the
coordinates order.

If you look at your file:

,----
| HDF5 "db_file.h5" {
| GROUP "/" {
|    GROUP "data" {
|       GROUP "component1" {
|          GROUP "2024-01-01" {
|             GROUP "fields" {
|                DATASET "27060" {
|                   DATATYPE  H5T_IEEE_F64LE
|                   DATASPACE  SIMPLE { ( 45, 45, 52 ) / ( 45, 45, 52 ) }
|                }
|             }
|          }
|          GROUP "mesh" {
|             DATASET "x" {
|                DATATYPE  H5T_IEEE_F64LE
|                DATASPACE  SIMPLE { ( 46 ) / ( 46 ) }
|             }
|             DATASET "y" {
|                DATATYPE  H5T_IEEE_F64LE
|                DATASPACE  SIMPLE { ( 46 ) / ( 46 ) }
|             }
|             DATASET "z" {
|                DATATYPE  H5T_IEEE_F64LE
|                DATASPACE  SIMPLE { ( 53 ) / ( 53 ) }
|             }
|          }
|       }
|    }
| }
| }
`----

The order in your dataset "27060" should be ( 52, 45, 45 ) to match the
mesh datasets description (i.e. the dataspace dimensions should be read
as (Z,Y,X).

As it is now, you have a 52x45x45 (XYZ) dataset, and so, when creating
the reader.xmf file I assumed that you got the mesh datasets just
wrongly named.

If you see the details of the reader.xmf
,----
|      <Topology TopologyType="3DRectMesh" Dimensions="46 46 53"/>
`----
This is specifying the same shape (plus one due to cell-centered values)
as for your dataset (53x46x46).


And this is specifying, in order, the coordinates for X,Y and Z. For X,
since we need 53 points, we are actually taking here the values from your
mess dataset named "z"
,---- 
|      <Geometry GeometryType="VXVYVZ">
|        <DataItem Dimensions="53" NumberType="Float" Precision="8" Format="HDF">
|         db_file.h5:/data/component1/mesh/z
|        </DataItem>
|        <DataItem Dimensions="46" NumberType="Float" Precision="8" Format="HDF">
|         db_file.h5:/data/component1/mesh/y
|        </DataItem>
|        <DataItem Dimensions="46" NumberType="Float" Precision="8" Format="HDF">
|         db_file.h5:/data/component1/mesh/x
|        </DataItem>
|      </Geometry>
`----

A bit confusing, but just because your .h5 files got the dimensions
order wrong.




Everything will make better sense if you re-create your .h5 file (you
would have to change the reader.xmf file as well, of course) to be
something like:

,----
| HDF5 "db_file.h5" {
| GROUP "/" {
|    GROUP "data" {
|       GROUP "component1" {
|          GROUP "2024-01-01" {
|             GROUP "fields" {
|                DATASET "27060" {
|                   DATATYPE  H5T_IEEE_F64LE
|                   DATASPACE  SIMPLE { ( 52, 45, 45 ) / ( 52, 45, 45 ) }
|                }
|             }
|          }
|          GROUP "mesh" {
|             DATASET "x" {
|                DATATYPE  H5T_IEEE_F64LE
|                DATASPACE  SIMPLE { ( 46 ) / ( 46 ) }
|             }
|             DATASET "y" {
|                DATATYPE  H5T_IEEE_F64LE
|                DATASPACE  SIMPLE { ( 46 ) / ( 46 ) }
|             }
|             DATASET "z" {
|                DATATYPE  H5T_IEEE_F64LE
|                DATASPACE  SIMPLE { ( 53 ) / ( 53 ) }
|             }
|          }
|       }
|    }
| }
| }
`----

-- 
Ángel de Vicente

Tel.: +34 922 605 747
Web.: http://research.iac.es/proyecto/polmag/
---------------------------------------------------------------------------------------------
AVISO LEGAL: Este mensaje puede contener información confidencial y/o privilegiada. Si usted no es el destinatario final del mismo o lo ha recibido por error, por favor notifíquelo al remitente inmediatamente. Cualquier uso no autorizadas del contenido de este mensaje está estrictamente prohibida. Más información en: https://www.iac.es/es/responsabilidad-legal
DISCLAIMER: This message may contain confidential and / or privileged information. If you are not the final recipient or have received it in error, please notify the sender immediately. Any unauthorized use of the content of this message is strictly prohibited. More information:  https://www.iac.es/en/disclaimer

**Comment by vsisl** [comment]
Thank you for your prompt reply Ángel de Vicente! I really appreciate your effort!

I was convinced, that my `db_file.h5` was correct. The mesh definition

- /data/component1/mesh/x: (46)
- /data/component1/mesh/y: (46)
- /data/component1/mesh/z: (53)

**is correct.** 

And I believed that also my dataset

- /data/component1/2024-01-01/fields/27060: (45, 45, 52)

was correctly defined...

I'm surprised by what you wrote: 

> The order in your dataset "27060" should be ( 52, 45, 45 ) to match the mesh datasets description (i.e. the dataspace dimensions should be read as (Z,Y,X).

Is that a convention for HDF5 files, that the shape of a cartesian 3D dataset should be in the order (Z, Y, X)? I believed that the general convention is (X, Y, Z) for cartesian coordinate system. And thus I believed that my definition of 27060: (X=45, Y=45, Z=52) was correct. Or is the (Z,Y,X) order a convention of VisIt or XDMF? I'm now quite confused.

**Comment by markcmiller86-visit** [comment]
Hi,

vsisl via visit-users <visit-users@elist.ornl.gov> writes:
> I was convinced, that my db_file.h5 was correct. The mesh definition
>
>   • /data/component1/mesh/x: (46)
>   • /data/component1/mesh/y: (46)
>   • /data/component1/mesh/z: (53)
>
> is correct.
>
> And I believed that also my dataset
>
>   • /data/component1/2024-01-01/fields/27060: (45, 45, 52)
>
> was correctly defined...

Nothing wrong with your file, as far as you stick with codes that follow
the "C" array convention for data storage. In a HDF5 file, by default,
the first dimension stored in the list of dimensions is the slowest
changing dimension and the last dimension stored is the fastest changing
dimension.

> Or is the (Z,Y,X) order a convention of VisIt or XDMF? I'm now quite
> confused.

This still gets me a bit confused, to be honest :-), but as far as I
understand, this is just a convention of VisIt, (or perhaps just of the
Pixie/XDMF reader, don't know that). So, if you work with
C/Python/etc. then you either work with the convention ZYX in the code,
or transpose the data when writing the files to be visualized with
VisIt, or just let VisIt do the transposing.

Not sure if there is a more portable way of doing it (i.e. just
specifying which convention was used when creating the file, so then a
reader could automatically transpose the data if needed...)

Cheers,
-- 
Ángel de Vicente

Tel.: +34 922 605 747
Web.: http://research.iac.es/proyecto/polmag/
---------------------------------------------------------------------------------------------
AVISO LEGAL: Este mensaje puede contener información confidencial y/o privilegiada. Si usted no es el destinatario final del mismo o lo ha recibido por error, por favor notifíquelo al remitente inmediatamente. Cualquier uso no autorizadas del contenido de este mensaje está estrictamente prohibida. Más información en: https://www.iac.es/es/responsabilidad-legal
DISCLAIMER: This message may contain confidential and / or privileged information. If you are not the final recipient or have received it in error, please notify the sender immediately. Any unauthorized use of the content of this message is strictly prohibited. More information:  https://www.iac.es/en/disclaimer

**Comment by markcmiller86** [comment]
@vsisl and Angel de Vicente...are you dealing with data coming from a Fortran code or a C code?

I am guessing its a Fortran code and VisIt is assuming a C array dimension ordering convention.

I've filed [this product development issue](https://github.com/visit-dav/visit/issues/4914) to have it addressed and so am closing this issue.

**Comment by vsisl** [comment]
Coming back to this thread with a workaround solution that fixed the coordinate system rotation for me...

> are you dealing with data coming from a Fortran code or a C code?

I create my HDF5 files with python's h5py package which, as far as I know, uses the HDF5 C library in the background.

**How I fixed the rotation of the coordinate system**

In VisIt, I added three transformations (Operators > Tranforms > Transform):

1) Rotation around the Y axis by -90 degrees
```python
AddOperator("Transform", 1)
TransformAtts = TransformAttributes()
TransformAtts.doRotate = 1
TransformAtts.rotateOrigin = (0, 0, 0)
TransformAtts.rotateAxis = (0, 1, 0)
TransformAtts.rotateAmount = -90
TransformAtts.rotateType = TransformAtts.Deg  # Deg, Rad
TransformAtts.doScale = 0
TransformAtts.doTranslate = 0
SetOperatorOptions(TransformAtts, 1, 1)
```

2) Rotation around the Z axis by 180 degrees
```python
AddOperator("Transform", 1)
TransformAtts = TransformAttributes()
TransformAtts.doRotate = 1
TransformAtts.rotateOrigin = (0, 0, 0)
TransformAtts.rotateAxis = (0, 0, 1)
TransformAtts.rotateAmount = 180
TransformAtts.rotateType = TransformAtts.Deg  # Deg, Rad
TransformAtts.doScale = 0
TransformAtts.doTranslate = 0
SetOperatorOptions(TransformAtts, 2, 1)
```

3) Swapping +- for the Y axis:
```python
AddOperator("Transform", 1)
TransformAtts = TransformAttributes()
TransformAtts.transformType = TransformAtts.Linear  # Similarity, Coordinate, Linear
TransformAtts.m00 = 1
TransformAtts.m01 = 0
TransformAtts.m02 = 0
TransformAtts.m03 = 0
TransformAtts.m10 = 0
TransformAtts.m11 = -1
TransformAtts.m12 = 0
TransformAtts.m13 = 0
TransformAtts.m20 = 0
TransformAtts.m21 = 0
TransformAtts.m22 = 1
TransformAtts.m23 = 0
TransformAtts.m30 = 0
TransformAtts.m31 = 0
TransformAtts.m32 = 0
TransformAtts.m33 = 1
SetOperatorOptions(TransformAtts, 3, 1)
```
Result:
![image](https://user-images.githubusercontent.com/28457179/89434426-d08e7880-d743-11ea-9d13-216a4207cdb4.png)

**Comment by brugger1** [comment]
Thanks for sharing your solution!
