### ISSUE TITLE
 Schlieren Post Processing of Hydrodynamics Simulations

### ISSUE THREAD

**Issue by biagas** [visit-dav/live-customer-response#97]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Does anyone know about a way to post process density results from hydrodynamics simulations in VisIT to get simulated Schlieren images? the manual is silent on this capability.

Thanks,

Rick

**Comment by biagas** [comment]
Response from Tomek Plewa
=========================
Use Controls -> Expression to create a mesh variable; in 2D,

constA*exp(constB*magnitude(ij_gradient(<var>))

Tomek
=====================

Rick indicated Tomek's solution worked.

**Comment by cyrush** [comment]
depending on the mesh type ,the ij gradient isn't a good choice -- it doesn't calc the right dx, dz, dy factor -- I would compare against the standard gradient.

**Comment by cyrush** [comment]
well not the mesh type, but the nature of the mesh. Depends on how dx,dy,dz compare to logical deltas.
